export const agentDeepDives = [
  {
    kind: "sequence",
    eyebrow: "RUN LIFECYCLE",
    title: "生产 Agent 的核心对象不是一段对话，而是可恢复的 Run",
    intro: "模型的一次输出、框架的一次运行和业务任务完成是三个层次。Run 必须有显式状态、转换条件、责任主体和不可变终态。",
    items: [
      { name: "创建运行实例", en: "Created", mechanism: "绑定任务目标、调用者身份、输入快照、预算、策略与版本，生成唯一 Run ID。", decision: "能否在数小时后准确恢复当时的权限、工具和模型配置？", boundary: "Conversation ID 只代表会话，不必然代表一次业务任务。" },
      { name: "执行与建立检查点", en: "Running / Checkpoint", mechanism: "模型提出决策，应用执行工具并在每次外部动作和结果验证后保存状态与调用账本。", decision: "崩溃后能否区分动作未执行、已执行或结果未知？", boundary: "模型输出 final_output 只结束运行器循环，不证明业务后置条件成立。" },
      { name: "等待输入或审批", en: "Waiting", mechanism: "缺少信息、等待外部事件或高风险动作审批时持久暂停，并记录恢复条件和超时策略。", decision: "暂停后是否释放计算资源，并在恢复时重新校验权限与参数？", boundary: "审批期间目标资源和授权都可能发生变化。" },
      { name: "重试或人工接管", en: "Retry / Handoff", mechanism: "按错误类别决定自动重试、补偿、人工修复或创建关联 Run，不让模型自由猜测。", decision: "哪些错误可安全重试，哪些必须先查询权威系统状态？", boundary: "跨第三方系统通常只能做到可去重、可检测和可补偿，不能轻率承诺 exactly-once。" },
      { name: "验证业务终态", en: "Verify Outcome", mechanism: "回读订单、工单、资源或测试等权威系统，以预定义后置条件确认真实结果。", decision: "谁定义成功，使用哪套系统作为 ground truth？", boundary: "“模型说完成”不能把 Run 置为业务成功。" },
      { name: "进入不可变终态", en: "Terminal State", mechanism: "Completed、Failed、Canceled、Expired 等终态不可原地改写；修订或重跑创建新 Run 并保留关联。", decision: "是否能解释每次终止的触发事件、责任主体和最终证据？", boundary: "内部状态机与 A2A Task 状态是不同层次，不能混为同一实现。" },
    ],
    sourceIds: ["openai-agents-run-loop", "a2a-task-lifecycle", "azure-durable-orchestration"],
  },
  {
    kind: "matrix",
    eyebrow: "ACTION CONTRACT",
    title: "工具 Schema 只描述形状，动作契约才决定能否安全执行",
    intro: "把 API 包成工具只是完成发现和参数生成。生产动作还要定义权限、副作用、幂等、错误和后置验证。",
    columnLabels: { name: "契约面", mechanism: "必须声明", decision: "售前验收", boundary: "常见误区" },
    items: [
      { name: "前置条件与身份", en: "Preconditions & Identity", mechanism: "声明 user subject、agent actor、应用身份、租户、scope、资源版本和必要审批。", decision: "真实执行前是否重新鉴权，而不是沿用规划阶段判断？", boundary: "工具目录里的能力声明不是权限，Prompt 更不能赋权。" },
      { name: "副作用与幂等", en: "Side Effects & Idempotency", mechanism: "区分只读、可逆写入和不可逆写入；为写操作定义幂等键、重复调用与并发冲突规则。", decision: "API 超时后，系统如何确认是否已经执行？", boundary: "HTTP 方法语义不等于跨队列、模型和业务系统的端到端仅执行一次。" },
      { name: "错误分类", en: "Error Taxonomy", mechanism: "区分可重试、需补充信息、需审批、永久失败、冲突、部分成功和结果未知。", decision: "错误能否驱动确定性恢复路径，而不是只返回一段自然语言？", boundary: "把所有失败都交给模型重试可能重复下单或扩大故障。" },
      { name: "后置条件", en: "Postconditions", mechanism: "声明预期业务状态、operation ID、验证接口和完成证据。", decision: "工具返回 200 后是否回读权威系统确认业务结果？", boundary: "结构合法的返回值不代表交易、权限或业务规则合法。" },
      { name: "补偿与审计", en: "Compensation & Audit", mechanism: "定义部分成功后的反向动作、人工恢复入口、版本和不可变审计凭证。", decision: "不可逆动作失败时，责任人能否看到完整调用账本并介入？", boundary: "补偿不是回滚时间，它本身也可能失败并需要审批。" },
    ],
    sourceIds: ["openapi-3-1-1", "openai-function-calling", "oauth-token-exchange", "nist-zero-trust"],
  },
  {
    kind: "scenario",
    eyebrow: "FAILURE RECOVERY",
    title: "用故障时间线验证 Agent，而不是只跑成功路径",
    intro: "同一个退款动作在调用前、调用中和调用后崩溃，恢复策略完全不同。PoC 应主动制造这些不确定状态。",
    maxColumns: 2,
    items: [
      { name: "调用前崩溃", en: "Before Call", mechanism: "Checkpoint 中没有动作账本，也没有外部 operation ID；恢复后可重新规划并执行。", decision: "恢复是否仍使用同一业务幂等键和最新权限？", boundary: "不能因为模型曾经提出调用就假设外部动作发生过。" },
      { name: "API 成功、回写前崩溃", en: "After Side Effect", mechanism: "先用幂等键、operation ID 或权威业务状态查询是否已完成，再补写结果或决定重试。", decision: "能否证明不会重复退款、重复发信或重复创建资源？", boundary: "盲目重试是生产 Agent 最危险的恢复方式之一。" },
      { name: "等待审批时策略变化", en: "Policy Changed", mechanism: "恢复前重新检查参数、资源版本、令牌、审批有效期和当前业务策略。", decision: "审批是否绑定具体工具、参数、资源版本和失效时间？", boundary: "批准旧参数不等于批准修改后的动作。" },
      { name: "部分成功且无法自动补偿", en: "Partial Success", mechanism: "冻结后续自动动作，保存证据和影响范围，进入人工恢复队列。", decision: "客户是否接受可检测、可补偿，而不是不现实的零故障承诺？", boundary: "模型不应自行编造补偿步骤或宣告最终成功。" },
    ],
    sourceIds: ["azure-durable-orchestration", "openai-agents-hitl", "azure-durable-hitl"],
  },
  {
    kind: "checklist",
    eyebrow: "MEMORY & DELEGATION",
    title: "长期记忆和多 Agent 委托都必须显式缩小信任",
    intro: "跨会话保存信息或把任务交给子 Agent，会扩大数据和权限边界。正确做法不是共享全部上下文，而是传递最小、可验证的状态。",
    maxColumns: 3,
    items: [
      { name: "候选记忆先不入库", en: "Candidate Memory", mechanism: "从事件中提取候选，保留主体、来源、用途、有效期、敏感级别和置信度。", decision: "模型摘要是否需要用户或策略确认后才能成为长期事实？", boundary: "自动摘要可能把推断、玩笑或过期信息固化。" },
      { name: "冲突、修订与删除传播", en: "Conflict & Deletion", mechanism: "写入前与现有记忆冲突检查；新记录替代旧记录，并同步清理向量、摘要和缓存副本。", decision: "客户能否查看、纠正和删除与自己相关的记忆？", boundary: "相似度召回不能解决版本、权限和有效期。" },
      { name: "委托契约", en: "Delegation Contract", mechanism: "传递 Task ID、目标、输入快照、输出 Schema、截止时间、数据分类和工具预算。", decision: "子 Agent 的结果由谁验证，失败和取消由谁承担？", boundary: "Handoff、Agent-as-tool 与 A2A 是不同控制层。" },
      { name: "权限默认不继承", en: "Permission Attenuation", mechanism: "子 Agent 使用被削减的短期身份，只访问任务所需资源，不能共享父 Agent 的宽权限令牌。", decision: "每次委托能否说明主体、执行者、scope 和允许的资源？", boundary: "跨 Agent 传递上下文不等于传递授权。" },
      { name: "限制 fan-out 与循环", en: "Bounded Delegation", mechanism: "设置并行数、委托深度、成本、超时和循环检测；父 Agent 汇总前验证每个产物。", decision: "拆成多 Agent 的收益是否超过交接、评估和成本开销？", boundary: "Agent 数量不是架构成熟度指标。" },
    ],
    sourceIds: ["aws-agentcore-memory", "oauth-token-exchange", "a2a-task-lifecycle", "nist-genai-profile"],
  },
];

export const agentEvidenceCards = [
  {
    metric: "3",
    title: "最小 Agent 的构建块",
    finding: "OpenAI 的官方实践指南把最小 Agent 概括为模型、工具和指令三部分，并进一步讨论运行循环、停止条件与护栏。",
    boundary: "这是官方实践指南中的最小设计框架，不是唯一术语体系，也不代表只接上三个构建块就具备生产可靠性。",
    sourceId: "openai-agent-guide",
    accent: true,
  },
  {
    metric: "固定 ↔ 动态",
    title: "工作流与 Agent 的关键分界",
    finding: "Anthropic 将预定义代码路径的工作流（Workflow）与由模型动态决定过程和工具使用的 Agent 分开讨论。",
    boundary: "实际系统常把两者组合；自治程度是连续谱，不必为了称作 Agent 而放弃确定性控制。",
    sourceId: "anthropic-effective-agents",
  },
  {
    metric: "短期 ↔ 长期",
    title: "Memory 需要按生命周期分层",
    finding: "Amazon Bedrock AgentCore Memory 的官方文档区分会话内短期原始事件与跨会话长期提取记忆，并使用 actor 与 session 组织隔离范围。",
    boundary: "这是具体云服务的 Memory 模型，不是所有框架的统一实现；长期提取结果仍需来源、权限、时效、纠正和删除治理。",
    sourceId: "aws-agentcore-memory",
  },
  {
    metric: "+34 / +10 pp",
    title: "ReAct 论文中的任务收益",
    finding: "ReAct 在论文的 ALFWorld 与 WebShop 实验中，相对所比较的模仿学习和强化学习方法分别提高 34 与 10 个百分点。",
    boundary: "只适用于论文任务、模型和提示设置；不能外推为企业 Agent 的通用提升或采购承诺。",
    sourceId: "react-2023",
  },
  {
    metric: "14.41% vs 78.24%",
    title: "长链任务仍有明显差距",
    finding: "WebArena 原始论文中，最佳 GPT-4 Agent 的端到端成功率为 14.41%，人类为 78.24%。",
    boundary: "这是 2023 年发布的特定网页环境基线，不代表当前模型水平；它证明评估必须看完整任务，而非单步回答。",
    sourceId: "webarena-2024",
  },
  {
    metric: "final_output ≠ 完成",
    title: "运行器终止不等于业务成功",
    finding: "OpenAI Agents SDK 以 final_output、Handoff、工具调用与 max_turns 驱动循环；业务后置条件仍需应用另外验证。",
    boundary: "这是一个 SDK 的运行语义，不是所有框架统一状态机，也不替客户定义成功。",
    sourceId: "openai-agents-run-loop",
  },
  {
    metric: "Checkpoint",
    title: "长期任务需要可恢复执行历史",
    finding: "Durable Orchestration 通过事件历史和自动检查点恢复长期流程，并在重放时复用已经完成的活动结果。",
    boundary: "持久化运行时不自动让外部副作用幂等；工具仍需调用账本、去重与补偿。",
    sourceId: "azure-durable-orchestration",
  },
];

export const agentQa = [
  {
    q: "什么样的系统才算 Agent？接了工具就是 Agent 吗？",
    a: "不一定。关键不在工具数量，而在模型是否根据当前状态决定下一步、选择工具、读取结果并持续执行，直到完成、失败或交还人工。",
    depth: "简单聊天、固定分类或单次函数调用可以是 LLM 应用，但不必称为 Agent。Agent 通常由模型、指令与工具构成，并运行在受控循环中；应用仍负责身份、授权、参数校验、执行、停止条件和审计。工具调用能力是必要条件之一，不是充分条件。",
    ask: "追问客户：模型需要动态决定哪些步骤？哪些步骤其实可以预先写死？任务何时算完成？",
    tag: "概念边界",
    basis: "官方定义 + 工程边界",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持 Agent 由模型管理执行、动态选择工具并在护栏内完成任务的定义。" },
      { sourceId: "anthropic-effective-agents", supports: "支持 Agent 依据环境反馈循环使用工具，以及工作流（Workflow）与 Agent 的区别。" },
    ],
  },
  {
    q: "感知（Perceive）和观察（Observe）有什么区别？不同框架为什么叫法不一样？",
    a: "感知建立当前任务的起点，观察读取刚刚行动后的真实结果。前者把用户、事件和多模态输入标准化为任务状态；后者用工具与环境反馈更新状态并决定继续或终止。",
    depth: "例如退款 Agent 在感知阶段识别客户、账单、意图、政策和缺失信息；调用建单 API 后，观察阶段不能只看模型描述，而要读取 API 响应和工单系统状态，确认是否真的创建成功。不同框架可能把两者合并为 observation、context 或 state update，这只是抽象粒度不同。售前比较平台时，应检查输入如何进入状态、工具结果如何回写、终态如何验证，而不是只对术语表。",
    ask: "追问客户：任务入口有哪些，哪套系统提供 ground truth？执行后用哪个业务状态证明成功？",
    tag: "动作循环",
    basis: "Agent 循环 + 工程状态边界",
    evidence: [
      { sourceId: "react-2023", supports: "支持推理、行动与环境观察交替，并由观察影响后续行动的基本循环。" },
      { sourceId: "anthropic-effective-agents", supports: "支持 Agent 根据环境反馈循环使用工具，而不是一次生成全部步骤。" },
    ],
  },
  {
    q: "Agent 的“思考（Reason）”是否必须记录完整思维链（Chain-of-Thought）？",
    a: "不需要。完整隐藏思维链不是稳定、跨模型的审计接口；生产系统应审计可验证的计划、决策摘要、工具调用、环境结果、策略判断和停止原因。",
    depth: "部分模型的隐藏推理本来就不会向开发者暴露，最多提供摘要；即使获得一段推理文字，它也不等同于真实业务依据。更可运营的做法是要求结构化动作意图：当前目标是什么、选择哪个工具、关键参数和风险级别是什么、何时应停止或接管；应用再记录真实执行与后置状态。把这些可观察轨迹作为审计材料，是基于产品接口和工程可验证性的设计结论，而不是声称论文已经给出唯一审计标准。",
    ask: "追问客户：审计真正需要解释哪项业务决策？现有日志能否关联计划、工具、授权、结果与停止原因？",
    tag: "可解释与审计",
    basis: "官方产品行为 + 可观测轨迹的工程推论",
    evidence: [
      { sourceId: "openai-model-spec-hidden-cot", supports: "直接支持部分 OpenAI 模型的隐藏思维链不向用户或开发者暴露，最多以摘要形式提供；该边界仅代表 OpenAI 模型行为。" },
      { sourceId: "react-2023", supports: "支持通过行动与环境观察形成可分析的任务轨迹；以此替代完整思维链作为生产审计主线，是本文明确标注的工程推论。" },
    ],
  },
  {
    q: "Agent 每次都要先生成一份完整计划吗？规划（Planning）到底怎么做？",
    a: "不一定。短任务可每轮只决定下一步，长任务再用里程碑计划；无论哪种方式，计划都要根据观察结果修正，而不是一次生成后执行到底。",
    depth: "常见方式包括逐步规划、计划—执行和编排者—执行者。选择依据是任务长度、工具依赖、并行机会与风险：路径短但变化多时逐步规划更灵活；长任务需要显式里程碑、预算和检查点；子任务无法预先确定且可分工时，才考虑编排者拆解。规划的输出应包含子目标、候选动作、预期结果与停止条件，并限制最大深度、轮次、时长和成本。",
    ask: "追问客户：任务路径为什么不可写死？最长有多少步，哪些里程碑必须审批，环境变化后如何重规划？",
    tag: "规划机制",
    basis: "官方架构模式",
    evidence: [
      { sourceId: "anthropic-effective-agents", supports: "支持按任务复杂度选择 prompt chaining、routing、orchestrator-workers 等模式，并让 Agent 根据反馈动态运行。" },
      { sourceId: "openai-agent-guide", supports: "支持先最大化单 Agent，再依据复杂逻辑、工具和职责边界决定是否拆分编排。" },
    ],
  },
  {
    q: "什么时候应该用 Agent，什么时候用固定工作流（Workflow）？",
    a: "步骤清楚、规则稳定、错误代价高时优先工作流；步骤无法预知、需要根据环境反馈调整、存在大量例外时再引入 Agent。",
    depth: "不要把选择做成二元对立。常见生产路线是用确定性流程包住少量 Agent 决策点：例如模型判断工单类型，但退款额度、审批和记账仍由规则与工作流控制。随着自治范围扩大，测试空间、时延、成本和复合错误都会增加。",
    ask: "追问客户：哪几个决策无法用规则表达？允许模型试错几次？哪些动作必须确定性执行？",
    tag: "路线选择",
    basis: "官方模式指南",
    evidence: [
      { sourceId: "anthropic-effective-agents", supports: "支持从最简单方案开始，并按任务可预测性选择工作流或 Agent。" },
      { sourceId: "openai-agent-guide", supports: "支持优先处理复杂判断、难维护规则和非结构化数据密集的任务。" },
    ],
  },
  {
    q: "Agent、RAG 和聊天机器人（Chatbot）到底是什么关系？",
    a: "聊天机器人是交互形态，RAG 是知识增强模式，Agent 是任务执行模式；三者可以独立存在，也可以组合。",
    depth: "聊天机器人可以只回答问题；RAG 负责从外部知识寻找证据，不负责完整业务动作；Agent 可以把 RAG 当作数据工具，再调用 CRM、工单、代码执行或审批系统完成多步任务。判断重点不是界面是否像聊天，而是模型是否控制执行过程、是否能改变外部状态。",
    ask: "追问客户：系统只提供信息，还是要跨系统执行动作？需要依据哪些知识？最终由谁确认？",
    tag: "方案边界",
    basis: "官方定义 + 组合架构",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持简单聊天机器人不属于 Agent，并区分数据工具与动作工具。" },
      { sourceId: "react-2023", supports: "支持推理与环境动作交替的基本 Agent 路线。" },
    ],
  },
  {
    q: "是不是工具越多、自治程度越高，Agent 就越强？",
    a: "不是。工具越多，选错工具、参数混淆、权限扩大和测试组合都会增加；自治越高，也意味着更长轨迹与更大的复合错误面。",
    depth: "应先按用途区分数据工具（Data Tools）、动作工具（Action Tools）与编排工具（Orchestration Tools），再为每个工具定义清晰且不重叠的名称、输入输出 Schema、错误语义和权限。搜索 / RAG 等数据工具通常只读，但返回内容仍需来源和注入隔离；业务写入需要幂等、预览、审批和补偿；工作流、队列或子 Agent 需要交接、超时和汇总验证。先把最小工具集和单 Agent 做稳，再判断是否扩展。",
    ask: "追问客户：每个工具解决什么唯一问题？哪些工具可写、可逆或涉及资金与敏感数据？",
    tag: "工具治理",
    basis: "官方工程指南",
    evidence: [
      { sourceId: "anthropic-effective-agents", supports: "支持清晰工具定义、示例、边界与大量测试的重要性。" },
      { sourceId: "openai-agent-guide", supports: "支持从单 Agent 起步，并按工具清晰度和复杂逻辑决定是否拆分。" },
    ],
  },
  {
    q: "Agent 的 Memory 是不是把所有对话永久保存？",
    a: "不是。Memory 应按目的、范围和保留期分层；会话上下文、用户偏好、业务事实和操作历史不能混为一谈。",
    depth: "先分清三层：运行状态（Run State）保存本次任务目标、步骤、工具结果和预算；短期会话记忆保存当前会话原始事件；长期记忆才跨会话提取偏好、经历或有用事实。长期写入应记录 actor / session、来源、时间、范围、保留期和可撤回方式。RAG 则从组织知识库取证，不等于记住某个用户；权威订单、余额和权限仍应每次回到业务系统读取。",
    ask: "追问客户：要记住什么、为谁记、保存多久、谁能纠正或删除？记忆是否会影响后续业务动作？",
    tag: "记忆治理",
    basis: "官方产品能力 + 风险管理",
    evidence: [
      { sourceId: "aws-agentcore-memory", supports: "支持短期原始事件与长期提取记忆分层，并以 actor / session 隔离记忆范围；不证明生成记忆天然准确。" },
      { sourceId: "nist-genai-profile", supports: "支持数据来源、隐私、持续测量与生命周期风险治理。" },
    ],
  },
  {
    q: "怎样避免 Agent 调错 API、越权或造成不可逆损失？",
    a: "不要让模型直接拥有业务权限。模型只提出调用意图，应用层完成身份绑定、授权、参数校验、策略判断和真实执行。",
    depth: "按工具风险分级：只读查询可自动执行；可逆写入可先预览再确认；资金、生产配置、删除和对外发送等高风险动作应要求审批或双人复核。凭据放在密钥系统，不进入 Prompt；以用户或工作负载身份做最小权限授权；所有调用记录输入摘要、策略结果、执行响应与关联 trace。",
    ask: "追问客户：哪些动作不可逆？使用用户授权还是服务账号？是否要求逐次同意、额度或审批流？",
    tag: "安全",
    basis: "零信任原则 + 云平台控制",
    evidence: [
      { sourceId: "nist-zero-trust", supports: "支持访问资源前验证主体并执行授权，不给予隐式信任。" },
      { sourceId: "aws-agentcore", supports: "支持在工具调用前执行确定性细粒度策略控制的云平台能力。" },
      { sourceId: "azure-foundry-agent-service", supports: "支持托管身份、RBAC、OBO 与网络隔离等平台控制面。" },
    ],
  },
  {
    q: "单智能体（Single Agent）和多智能体（Multi-Agent）怎么选？",
    a: "默认先做单智能体。只有职责、工具或安全边界确实需要分离，且单智能体的指令和选工具问题无法通过简化解决时，再拆成多智能体。",
    depth: "多 Agent 常见两类：管理者把子 Agent 当工具并汇总结果；多个 Agent 通过 handoff 转移控制。拆分能隔离上下文和专业能力，但会增加交接丢失、循环、重复调用、轨迹评估与权限传播问题。Agent 数量不是能力指标，端到端任务成功率才是。",
    ask: "追问客户：拆分是为了解决哪个已观察到的失败？每个 Agent 的输入、输出、权限和终止条件是什么？",
    tag: "架构选择",
    basis: "官方编排指南",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持单 Agent 优先，以及 manager 与 handoff 两类多 Agent 编排。" },
      { sourceId: "anthropic-effective-agents", supports: "支持 orchestrator-workers 用于无法预先确定子任务的复杂任务。" },
    ],
  },
  {
    q: "怎么评估 Agent，而不是只看回答是否像人？",
    a: "应以完整任务成功为主线，并同时检查轨迹、工具、安全、工程与业务结果。只评最终文字会漏掉碰巧答对和隐性越权。",
    depth: "冻结真实任务、初始状态和可验证终态；记录计划、工具选择、参数、工具响应、重试与停止原因。指标至少包括任务成功率、关键步骤完成率、无效调用率、策略违规率、人工接管率、P95、token / 工具成本和每个成功任务成本。自动评分必须配合规则检查、环境断言和人工复核。",
    ask: "追问客户：任务完成后哪个系统状态可以证明成功？哪类错误必须为零？谁提供验收样本和裁决？",
    tag: "评估",
    basis: "基准论文 + 风险框架",
    evidence: [
      { sourceId: "webarena-2024", supports: "支持以可验证的端到端任务成功率衡量网页 Agent，并显示长链任务难度。" },
      { sourceId: "nist-genai-profile", supports: "支持部署前后持续评估、风险分级和 Go / No-Go 门槛。" },
    ],
  },
  {
    q: "Agent 出错时，为什么普通应用日志不够？",
    a: "Agent 一次任务包含多次模型、检索和工具调用；只看最终请求日志无法知道错误在哪一步产生和传播。",
    depth: "应给每次 run 建立端到端 trace，并记录 span 级模型版本、提示版本、工具名、参数摘要、权限决策、结果状态、重试、token、时延和成本。敏感内容不应默认完整落日志。标准化 telemetry 有助于跨框架关联，但业务成功、风险等级和审批结果仍需自定义字段。",
    ask: "追问客户：当前用什么 APM / 日志平台？需要保留哪些轨迹、多久、谁能查看？",
    tag: "可观测",
    basis: "可观测标准 + 云平台能力",
    evidence: [
      { sourceId: "opentelemetry-semconv", supports: "支持用统一语义约定组织 traces、metrics、logs 和 events；具体业务字段需自行定义。" },
      { sourceId: "google-agent-platform", supports: "支持托管 Agent 运行时连接 Trace、Monitoring、Logging 与评估服务。" },
    ],
  },
  {
    q: "选择云上托管 Agent 平台，还是自己用框架搭？",
    a: "看差异化落在哪。需要快速上线、托管身份、会话、工具网关、观测和弹性时，平台更省工程；编排逻辑、运行环境或合规边界高度定制时，自建或托管代码运行时更合适。",
    depth: "评估不要只比较框架 API，要拆成模型、Agent runtime、会话 / 记忆、工具接入、身份授权、沙箱、评估、Tracing、网络隔离、地域与计价。主流云平台也支持托管自定义框架或容器，因此“平台”与“开源框架”并非绝对二选一。具体产品能力、地域、预览状态和价格必须按采购时点复核。",
    ask: "追问客户：哪些能力必须自定义？数据与执行环境能否上云？已有 IAM、APM、API 管理和容器平台能否复用？",
    tag: "云选型",
    basis: "三家云官方文档",
    evidence: [
      { sourceId: "google-agent-platform", supports: "支持托管运行、框架适配、IAM、评估与可观测等能力说明。" },
      { sourceId: "aws-agentcore", supports: "支持 Runtime、Memory、Gateway、Identity、沙箱、评估与观测等组合能力。" },
      { sourceId: "azure-foundry-agent-service", supports: "支持配置型与代码型 Agent、托管运行、身份、工具和端到端观测。" },
    ],
  },
  {
    q: "怎样控制 Agent 的延迟和成本？",
    a: "先控制轨迹长度和无效动作，再考虑换小模型。Agent 成本来自每一轮模型调用、工具、检索、沙箱和等待，不只是最终回答 token。",
    depth: "设置最大轮次、超时、重试和预算；用确定性路由跳过无需 Agent 的任务；缓存稳定只读结果；把简单分类与格式化交给小模型；并行只用于独立子任务；为每个工具设置时延和成本上限。报告每个成功任务成本，而不是平均请求成本，因为失败重试会掩盖真实 TCO。",
    ask: "追问客户：P95、任务完成时限、并发和失败重试预算是什么？哪些步骤可以异步或由工作流执行？",
    tag: "FinOps",
    basis: "官方工程指南 + PoC 测量",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持建立能力基线后逐步用更小模型优化时延与成本。" },
      { sourceId: "anthropic-effective-agents", supports: "支持 Agent 自治带来更高成本和复合错误风险，并应设置停止条件。" },
    ],
  },
  {
    q: "Agent 可以直接全自动上线吗？",
    a: "不应把“能跑通 Demo”直接等同于可全自动。应按动作风险分级，从影子模式、建议模式、确认后执行逐步扩大自治。",
    depth: "先让 Agent 只观察或生成建议，与人工结果对比；再开放低风险、可逆动作；对资金、生产、法律、安全或外部沟通保留审批。上线门槛必须按高风险场景单列，不被总体平均掩盖；超过失败、预算或循环阈值时应停止并交还人工。",
    ask: "追问客户：哪些任务允许建议、哪些可自动执行？失败时如何补偿、回滚和通知责任人？",
    tag: "上线治理",
    basis: "官方护栏建议 + 风险框架",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持高风险动作与超过失败阈值时进行人工介入。" },
      { sourceId: "nist-genai-profile", supports: "支持按风险容忍度设置上线门槛、持续复核和停止机制。" },
    ],
  },
  {
    q: "Function Calling、MCP 和 A2A 是什么关系？",
    a: "Function Calling 表达一次工具调用意图；MCP 标准化 Agent / AI 应用与工具、资源的连接；A2A 用于 Agent 之间发现、委派和交换任务结果。",
    depth: "三者可以同时出现：Agent 用 Function Calling 选择一个由 MCP Server 暴露的工具，再通过 A2A 把独立任务交给另一个 Agent。协议降低连接成本，但不会自动完成身份、授权、租户隔离、审批、限流和审计；单系统内部编排也不必为了使用 A2A 而拆成分布式架构。",
    ask: "追问客户：需要统一的是工具接入、跨系统 Agent 协作，还是单个应用内部编排？信任边界跨越了哪些团队或租户？",
    tag: "协议边界",
    basis: "官方协议架构与职责边界",
    evidence: [
      { sourceId: "mcp-architecture", supports: "支持 MCP 的 Host、Client、Server 架构和工具 / 资源互操作职责。" },
      { sourceId: "a2a-concepts", supports: "支持 A2A 的 Agent Card、Task、Message 与 Artifact 等跨 Agent 协作概念。" },
      { sourceId: "openai-function-calling", supports: "支持模型提出工具调用、应用执行并回传结果的职责分界。" },
    ],
  },
  {
    q: "Agent 的长期记忆能不能直接当客户档案或业务事实库？",
    a: "不能。长期记忆适合保存经治理的偏好、经历摘要和可复用信息；余额、订单、权限和政策等权威事实仍应在业务系统中读取。",
    depth: "至少分开任务状态、会话状态、长期记忆与权威事实。模型生成的摘要在写入长期记忆前要经过主体绑定、来源、去重、有效期和必要的用户确认；权威事实只由获授权的业务流程写入。否则错误总结会被持久化，并在未来任务中反复放大。",
    ask: "追问客户：哪些信息允许模型总结后保存，哪些必须每次回到 CRM、ERP 或策略系统读取？谁能纠正和删除？",
    tag: "记忆治理",
    basis: "云平台记忆实现 + 风险治理",
    evidence: [
      { sourceId: "aws-agentcore-memory", supports: "支持区分会话内事件与跨会话长期记忆，并按主体 / 会话隔离。" },
      { sourceId: "nist-genai-profile", supports: "支持对数据来源、隐私、生命周期和持续风险进行治理。" },
    ],
  },
  {
    q: "没有稳定 API 时，可以直接让 Agent 用 Computer Use 操作生产界面吗？",
    a: "可以作为受限补充，但不应默认成为高风险生产主通道。有稳定 API 时优先 API；Computer Use 应运行在隔离环境，并从只读、建议和人工确认开始。",
    depth: "界面会变化，视觉定位和状态判断也可能错误。需要限制网站和应用范围、使用短期凭证、屏蔽敏感信息、记录屏幕与动作轨迹、验证关键后置状态，并为付款、删除、外发和生产变更保留人工确认。固定且可脚本化的界面路径也可先比较 RPA。",
    ask: "追问客户：目标系统为何没有 API？动作是否可逆？能否提供隔离账号、沙箱环境、回放证据和人工审批？",
    tag: "执行方式",
    basis: "Agent 风险治理 + 零信任原则",
    evidence: [
      { sourceId: "nist-zero-trust", supports: "支持每次资源访问前验证主体、设备与授权，而不因运行位置默认信任。" },
      { sourceId: "nist-genai-profile", supports: "支持按使用情境、影响与风险容忍度设置控制和持续测量。" },
    ],
  },
  {
    q: "模型已经返回“任务完成”，为什么系统还不能把 Run 标成成功？",
    a: "因为模型只能结束自己的生成或运行循环，不能证明订单、工单、资源或审批等真实业务状态已经满足。Run 成功必须由权威系统的后置条件验证。",
    depth: "区分模型 final output、Agent Runtime 终止和业务完成。应用应回读真实系统的 operation ID、状态与资源版本；结果未知时进入查询或人工恢复，而不是让模型自行解释。还要记录完成、失败、取消、超时和交还人工等显式终态。",
    ask: "追问客户：哪个系统是 ground truth？成功需要满足哪些可机器验证的后置条件？",
    tag: "Run 状态机",
    basis: "官方运行循环 + 持久任务语义",
    evidence: [
      { sourceId: "openai-agents-run-loop", supports: "支持 final_output、工具调用和 max_turns 是 SDK 运行循环的结束与控制语义。" },
      { sourceId: "a2a-task-lifecycle", supports: "支持跨 Agent Task 具有显式状态与终态；不规定内部业务验证。" },
    ],
  },
  {
    q: "我们已经有 API，包装成 Agent 工具就可以安全上线了吗？",
    a: "不够。OpenAPI 或 JSON Schema 描述接口与参数形状，但生产动作还需要身份、权限、副作用等级、幂等、错误分类、后置验证和补偿语义。",
    depth: "以退款工具为例：调用前检查用户委托、金额和订单版本；写操作带幂等键；错误区分可重试、冲突、部分成功与结果未知；调用后回读退款状态；无法自动恢复时进入人工队列。模型只提出调用，应用决定是否授权并执行。",
    ask: "追问客户：API 超时后怎样确认是否已执行？重复调用、部分成功和审批参数变化分别怎样处理？",
    tag: "工具契约",
    basis: "开放标准 + 工具职责边界",
    evidence: [
      { sourceId: "openapi-3-1-1", supports: "支持机器可读地描述 API 操作和数据结构；不覆盖业务授权与事务语义。" },
      { sourceId: "openai-function-calling", supports: "支持模型提出工具调用而应用负责执行并回传结果的职责分界。" },
    ],
  },
  {
    q: "退款 API 已经成功，但 Agent 在记录结果前崩溃，重启后怎么办？",
    a: "不能盲目重试。恢复流程先用幂等键、operation ID 或权威业务状态确认退款是否存在；已完成则补写结果并继续，未完成才重新执行。",
    depth: "Checkpoint 应保存 Run 状态、调用账本、审批、模型 / Prompt / Tool 版本。恢复时先判定崩溃发生在调用前、调用中还是副作用后，并重新校验权限与资源版本。跨系统很难轻率承诺 exactly-once，应交付可去重、可检测、可补偿和可人工恢复。",
    ask: "追问客户：现有 API 是否支持幂等键或查询 operation 状态？调用账本和人工恢复入口在哪里？",
    tag: "故障恢复",
    basis: "持久编排 + 人工恢复机制",
    evidence: [
      { sourceId: "azure-durable-orchestration", supports: "支持使用执行历史与 Checkpoint 恢复长期流程并重放已完成活动结果。" },
      { sourceId: "openai-agents-hitl", supports: "支持暂停 Agent Run、持久化状态并在人工决策后恢复。" },
    ],
  },
  {
    q: "Agent 应该使用用户权限，还是一个统一服务账号？",
    a: "面向用户私有数据与个人动作时，优先用户委托或 OBO；后台无人值守任务使用独立工作负载身份。不要用一个宽权限共享账号覆盖所有 Agent、用户和租户。",
    depth: "每次执行同时记录 user subject、agent actor、应用客户端与目标资源；使用短期、限定 audience、scope 和资源的令牌。真实执行前重新授权，高风险动作做 step-up 或审批。子 Agent 默认不继承父 Agent 的全部令牌和上下文。",
    ask: "追问客户：动作代表用户还是后台服务？令牌由谁签发、scope 到什么粒度、等待期间权限变化如何重新验证？",
    tag: "身份授权",
    basis: "OAuth 标准 + 零信任原则",
    evidence: [
      { sourceId: "oauth-token-exchange", supports: "支持在 OAuth 体系中表达主体与执行者并交换受限令牌。" },
      { sourceId: "nist-zero-trust", supports: "支持每次访问资源前验证主体和授权，不因运行位置或既有会话默认信任。" },
    ],
  },
];
