export const agentEvidenceCards = [
  {
    metric: "3",
    title: "Agent 的核心组成",
    finding: "OpenAI 的官方实践指南把基础 Agent 概括为模型、工具和指令三部分；运行循环与护栏决定它能否安全完成任务。",
    boundary: "这是设计框架，不是产品认证，也不代表只接上三个组件就具备生产可靠性。",
    sourceId: "openai-agent-guide",
    accent: true,
  },
  {
    metric: "固定 ↔ 动态",
    title: "工作流与 Agent 的关键分界",
    finding: "Anthropic 将预定义代码路径的工作流（Workflow）与由模型动态决定过程和工具使用的 Agent 分开讨论。",
    boundary: "实际系统常把两者组合；自治程度是连续谱，不必为了称作 Agent 而放弃确定性控制。",
    sourceId: "anthropic-effective-agents",
  },
  {
    metric: "+34 / +10 pp",
    title: "ReAct 论文中的任务收益",
    finding: "ReAct 在论文的 ALFWorld 与 WebShop 实验中，相对所比较的模仿学习和强化学习方法分别提高 34 与 10 个百分点。",
    boundary: "只适用于论文任务、模型和提示设置；不能外推为企业 Agent 的通用提升或采购承诺。",
    sourceId: "react-2023",
  },
  {
    metric: "14.41% vs 78.24%",
    title: "长链任务仍有明显差距",
    finding: "WebArena 原始论文中，最佳 GPT-4 Agent 的端到端成功率为 14.41%，人类为 78.24%。",
    boundary: "这是 2023 年发布的特定网页环境基线，不代表当前模型水平；它证明评估必须看完整任务，而非单步回答。",
    sourceId: "webarena-2024",
  },
];

export const agentQa = [
  {
    q: "什么样的系统才算 Agent？接了工具就是 Agent 吗？",
    a: "不一定。关键不在工具数量，而在模型是否根据当前状态决定下一步、选择工具、读取结果并持续执行，直到完成、失败或交还人工。",
    depth: "简单聊天、固定分类或单次函数调用可以是 LLM 应用，但不必称为 Agent。Agent 通常由模型、指令与工具构成，并运行在受控循环中；应用仍负责身份、授权、参数校验、执行、停止条件和审计。工具调用能力是必要条件之一，不是充分条件。",
    ask: "追问客户：模型需要动态决定哪些步骤？哪些步骤其实可以预先写死？任务何时算完成？",
    tag: "概念边界",
    basis: "官方定义 + 工程边界",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持 Agent 由模型管理执行、动态选择工具并在护栏内完成任务的定义。" },
      { sourceId: "anthropic-effective-agents", supports: "支持 Agent 依据环境反馈循环使用工具，以及工作流（Workflow）与 Agent 的区别。" },
    ],
  },
  {
    q: "什么时候应该用 Agent，什么时候用固定工作流（Workflow）？",
    a: "步骤清楚、规则稳定、错误代价高时优先工作流；步骤无法预知、需要根据环境反馈调整、存在大量例外时再引入 Agent。",
    depth: "不要把选择做成二元对立。常见生产路线是用确定性流程包住少量 Agent 决策点：例如模型判断工单类型，但退款额度、审批和记账仍由规则与工作流控制。随着自治范围扩大，测试空间、时延、成本和复合错误都会增加。",
    ask: "追问客户：哪几个决策无法用规则表达？允许模型试错几次？哪些动作必须确定性执行？",
    tag: "路线选择",
    basis: "官方模式指南",
    evidence: [
      { sourceId: "anthropic-effective-agents", supports: "支持从最简单方案开始，并按任务可预测性选择工作流或 Agent。" },
      { sourceId: "openai-agent-guide", supports: "支持优先处理复杂判断、难维护规则和非结构化数据密集的任务。" },
    ],
  },
  {
    q: "Agent、RAG 和聊天机器人（Chatbot）到底是什么关系？",
    a: "聊天机器人是交互形态，RAG 是知识增强模式，Agent 是任务执行模式；三者可以独立存在，也可以组合。",
    depth: "聊天机器人可以只回答问题；RAG 负责从外部知识寻找证据，不负责完整业务动作；Agent 可以把 RAG 当作数据工具，再调用 CRM、工单、代码执行或审批系统完成多步任务。判断重点不是界面是否像聊天，而是模型是否控制执行过程、是否能改变外部状态。",
    ask: "追问客户：系统只提供信息，还是要跨系统执行动作？需要依据哪些知识？最终由谁确认？",
    tag: "方案边界",
    basis: "官方定义 + 组合架构",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持简单聊天机器人不属于 Agent，并区分数据工具与动作工具。" },
      { sourceId: "react-2023", supports: "支持推理与环境动作交替的基本 Agent 路线。" },
    ],
  },
  {
    q: "是不是工具越多、自治程度越高，Agent 就越强？",
    a: "不是。工具越多，选错工具、参数混淆、权限扩大和测试组合都会增加；自治越高，也意味着更长轨迹与更大的复合错误面。",
    depth: "应按任务最小化工具集合，给工具清晰、不重叠的名称、参数、返回格式和失败语义。高风险写操作与低风险读取操作分开授权；能用结构化 API 就不要依赖脆弱的界面操作。先把单 Agent 做到稳定，再根据提示复杂度和工具重叠问题判断是否拆分。",
    ask: "追问客户：每个工具解决什么唯一问题？哪些工具可写、可逆或涉及资金与敏感数据？",
    tag: "工具治理",
    basis: "官方工程指南",
    evidence: [
      { sourceId: "anthropic-effective-agents", supports: "支持清晰工具定义、示例、边界与大量测试的重要性。" },
      { sourceId: "openai-agent-guide", supports: "支持从单 Agent 起步，并按工具清晰度和复杂逻辑决定是否拆分。" },
    ],
  },
  {
    q: "Agent 的 Memory 是不是把所有对话永久保存？",
    a: "不是。Memory 应按目的、范围和保留期分层；会话上下文、用户偏好、业务事实和操作历史不能混为一谈。",
    depth: "短期状态用于当前运行与多轮会话；长期记忆应是经过提取、校验、授权和生命周期管理的持久信息。模型生成的总结不是自动可信事实，写入长期记忆前应记录来源、主体、时间和可撤回方式。敏感信息还要满足最小化、隔离、删除和审计要求。",
    ask: "追问客户：要记住什么、为谁记、保存多久、谁能纠正或删除？记忆是否会影响后续业务动作？",
    tag: "记忆治理",
    basis: "官方产品能力 + 风险管理",
    evidence: [
      { sourceId: "aws-agentcore", supports: "支持短期与跨会话长期记忆是不同能力；不证明生成记忆天然准确。" },
      { sourceId: "nist-genai-profile", supports: "支持数据来源、隐私、持续测量与生命周期风险治理。" },
    ],
  },
  {
    q: "怎样避免 Agent 调错 API、越权或造成不可逆损失？",
    a: "不要让模型直接拥有业务权限。模型只提出调用意图，应用层完成身份绑定、授权、参数校验、策略判断和真实执行。",
    depth: "按工具风险分级：只读查询可自动执行；可逆写入可先预览再确认；资金、生产配置、删除和对外发送等高风险动作应要求审批或双人复核。凭据放在密钥系统，不进入 Prompt；以用户或工作负载身份做最小权限授权；所有调用记录输入摘要、策略结果、执行响应与关联 trace。",
    ask: "追问客户：哪些动作不可逆？使用用户授权还是服务账号？是否要求逐次同意、额度或审批流？",
    tag: "安全",
    basis: "零信任原则 + 云平台控制",
    evidence: [
      { sourceId: "nist-zero-trust", supports: "支持访问资源前验证主体并执行授权，不给予隐式信任。" },
      { sourceId: "aws-agentcore", supports: "支持在工具调用前执行确定性细粒度策略控制的云平台能力。" },
      { sourceId: "azure-foundry-agent-service", supports: "支持托管身份、RBAC、OBO 与网络隔离等平台控制面。" },
    ],
  },
  {
    q: "单智能体（Single Agent）和多智能体（Multi-Agent）怎么选？",
    a: "默认先做单智能体。只有职责、工具或安全边界确实需要分离，且单智能体的指令和选工具问题无法通过简化解决时，再拆成多智能体。",
    depth: "多 Agent 常见两类：管理者把子 Agent 当工具并汇总结果；多个 Agent 通过 handoff 转移控制。拆分能隔离上下文和专业能力，但会增加交接丢失、循环、重复调用、轨迹评估与权限传播问题。Agent 数量不是能力指标，端到端任务成功率才是。",
    ask: "追问客户：拆分是为了解决哪个已观察到的失败？每个 Agent 的输入、输出、权限和终止条件是什么？",
    tag: "架构选择",
    basis: "官方编排指南",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持单 Agent 优先，以及 manager 与 handoff 两类多 Agent 编排。" },
      { sourceId: "anthropic-effective-agents", supports: "支持 orchestrator-workers 用于无法预先确定子任务的复杂任务。" },
    ],
  },
  {
    q: "怎么评估 Agent，而不是只看回答是否像人？",
    a: "应以完整任务成功为主线，并同时检查轨迹、工具、安全、工程与业务结果。只评最终文字会漏掉碰巧答对和隐性越权。",
    depth: "冻结真实任务、初始状态和可验证终态；记录计划、工具选择、参数、工具响应、重试与停止原因。指标至少包括任务成功率、关键步骤完成率、无效调用率、策略违规率、人工接管率、P95、token / 工具成本和每个成功任务成本。自动评分必须配合规则检查、环境断言和人工复核。",
    ask: "追问客户：任务完成后哪个系统状态可以证明成功？哪类错误必须为零？谁提供验收样本和裁决？",
    tag: "评估",
    basis: "基准论文 + 风险框架",
    evidence: [
      { sourceId: "webarena-2024", supports: "支持以可验证的端到端任务成功率衡量网页 Agent，并显示长链任务难度。" },
      { sourceId: "nist-genai-profile", supports: "支持部署前后持续评估、风险分级和 Go / No-Go 门槛。" },
    ],
  },
  {
    q: "Agent 出错时，为什么普通应用日志不够？",
    a: "Agent 一次任务包含多次模型、检索和工具调用；只看最终请求日志无法知道错误在哪一步产生和传播。",
    depth: "应给每次 run 建立端到端 trace，并记录 span 级模型版本、提示版本、工具名、参数摘要、权限决策、结果状态、重试、token、时延和成本。敏感内容不应默认完整落日志。标准化 telemetry 有助于跨框架关联，但业务成功、风险等级和审批结果仍需自定义字段。",
    ask: "追问客户：当前用什么 APM / 日志平台？需要保留哪些轨迹、多久、谁能查看？",
    tag: "可观测",
    basis: "可观测标准 + 云平台能力",
    evidence: [
      { sourceId: "opentelemetry-semconv", supports: "支持用统一语义约定组织 traces、metrics、logs 和 events；具体业务字段需自行定义。" },
      { sourceId: "google-agent-platform", supports: "支持托管 Agent 运行时连接 Trace、Monitoring、Logging 与评估服务。" },
    ],
  },
  {
    q: "选择云上托管 Agent 平台，还是自己用框架搭？",
    a: "看差异化落在哪。需要快速上线、托管身份、会话、工具网关、观测和弹性时，平台更省工程；编排逻辑、运行环境或合规边界高度定制时，自建或托管代码运行时更合适。",
    depth: "评估不要只比较框架 API，要拆成模型、Agent runtime、会话 / 记忆、工具接入、身份授权、沙箱、评估、Tracing、网络隔离、地域与计价。主流云平台也支持托管自定义框架或容器，因此“平台”与“开源框架”并非绝对二选一。具体产品能力、地域、预览状态和价格必须按采购时点复核。",
    ask: "追问客户：哪些能力必须自定义？数据与执行环境能否上云？已有 IAM、APM、API 管理和容器平台能否复用？",
    tag: "云选型",
    basis: "三家云官方文档",
    evidence: [
      { sourceId: "google-agent-platform", supports: "支持托管运行、框架适配、IAM、评估与可观测等能力说明。" },
      { sourceId: "aws-agentcore", supports: "支持 Runtime、Memory、Gateway、Identity、沙箱、评估与观测等组合能力。" },
      { sourceId: "azure-foundry-agent-service", supports: "支持配置型与代码型 Agent、托管运行、身份、工具和端到端观测。" },
    ],
  },
  {
    q: "怎样控制 Agent 的延迟和成本？",
    a: "先控制轨迹长度和无效动作，再考虑换小模型。Agent 成本来自每一轮模型调用、工具、检索、沙箱和等待，不只是最终回答 token。",
    depth: "设置最大轮次、超时、重试和预算；用确定性路由跳过无需 Agent 的任务；缓存稳定只读结果；把简单分类与格式化交给小模型；并行只用于独立子任务；为每个工具设置时延和成本上限。报告每个成功任务成本，而不是平均请求成本，因为失败重试会掩盖真实 TCO。",
    ask: "追问客户：P95、任务完成时限、并发和失败重试预算是什么？哪些步骤可以异步或由工作流执行？",
    tag: "FinOps",
    basis: "官方工程指南 + PoC 测量",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持建立能力基线后逐步用更小模型优化时延与成本。" },
      { sourceId: "anthropic-effective-agents", supports: "支持 Agent 自治带来更高成本和复合错误风险，并应设置停止条件。" },
    ],
  },
  {
    q: "Agent 可以直接全自动上线吗？",
    a: "不应把“能跑通 Demo”直接等同于可全自动。应按动作风险分级，从影子模式、建议模式、确认后执行逐步扩大自治。",
    depth: "先让 Agent 只观察或生成建议，与人工结果对比；再开放低风险、可逆动作；对资金、生产、法律、安全或外部沟通保留审批。上线门槛必须按高风险场景单列，不被总体平均掩盖；超过失败、预算或循环阈值时应停止并交还人工。",
    ask: "追问客户：哪些任务允许建议、哪些可自动执行？失败时如何补偿、回滚和通知责任人？",
    tag: "上线治理",
    basis: "官方护栏建议 + 风险框架",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持高风险动作与超过失败阈值时进行人工介入。" },
      { sourceId: "nist-genai-profile", supports: "支持按风险容忍度设置上线门槛、持续复核和停止机制。" },
    ],
  },
];
