export const agentEvidenceCards = [
  {
    metric: "3",
    title: "最小 Agent 的构建块",
    finding: "OpenAI 的官方实践指南把最小 Agent 概括为模型、工具和指令三部分，并进一步讨论运行循环、停止条件与护栏。",
    boundary: "这是官方实践指南中的最小设计框架，不是唯一术语体系，也不代表只接上三个构建块就具备生产可靠性。",
    sourceId: "openai-agent-guide",
    accent: true,
  },
  {
    metric: "固定 ↔ 动态",
    title: "工作流与 Agent 的关键分界",
    finding: "Anthropic 将预定义代码路径的工作流（Workflow）与由模型动态决定过程和工具使用的 Agent 分开讨论。",
    boundary: "实际系统常把两者组合；自治程度是连续谱，不必为了称作 Agent 而放弃确定性控制。",
    sourceId: "anthropic-effective-agents",
  },
  {
    metric: "短期 ↔ 长期",
    title: "Memory 需要按生命周期分层",
    finding: "Amazon Bedrock AgentCore Memory 的官方文档区分会话内短期原始事件与跨会话长期提取记忆，并使用 actor 与 session 组织隔离范围。",
    boundary: "这是具体云服务的 Memory 模型，不是所有框架的统一实现；长期提取结果仍需来源、权限、时效、纠正和删除治理。",
    sourceId: "aws-agentcore-memory",
  },
  {
    metric: "+34 / +10 pp",
    title: "ReAct 论文中的任务收益",
    finding: "ReAct 在论文的 ALFWorld 与 WebShop 实验中，相对所比较的模仿学习和强化学习方法分别提高 34 与 10 个百分点。",
    boundary: "只适用于论文任务、模型和提示设置；不能外推为企业 Agent 的通用提升或采购承诺。",
    sourceId: "react-2023",
  },
  {
    metric: "14.41% vs 78.24%",
    title: "长链任务仍有明显差距",
    finding: "WebArena 原始论文中，最佳 GPT-4 Agent 的端到端成功率为 14.41%，人类为 78.24%。",
    boundary: "这是 2023 年发布的特定网页环境基线，不代表当前模型水平；它证明评估必须看完整任务，而非单步回答。",
    sourceId: "webarena-2024",
  },
];

export const agentQa = [
  {
    q: "什么样的系统才算 Agent？接了工具就是 Agent 吗？",
    a: "不一定。关键不在工具数量，而在模型是否根据当前状态决定下一步、选择工具、读取结果并持续执行，直到完成、失败或交还人工。",
    depth: "简单聊天、固定分类或单次函数调用可以是 LLM 应用，但不必称为 Agent。Agent 通常由模型、指令与工具构成，并运行在受控循环中；应用仍负责身份、授权、参数校验、执行、停止条件和审计。工具调用能力是必要条件之一，不是充分条件。",
    ask: "追问客户：模型需要动态决定哪些步骤？哪些步骤其实可以预先写死？任务何时算完成？",
    tag: "概念边界",
    basis: "官方定义 + 工程边界",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持 Agent 由模型管理执行、动态选择工具并在护栏内完成任务的定义。" },
      { sourceId: "anthropic-effective-agents", supports: "支持 Agent 依据环境反馈循环使用工具，以及工作流（Workflow）与 Agent 的区别。" },
    ],
  },
  {
    q: "感知（Perceive）和观察（Observe）有什么区别？不同框架为什么叫法不一样？",
    a: "感知建立当前任务的起点，观察读取刚刚行动后的真实结果。前者把用户、事件和多模态输入标准化为任务状态；后者用工具与环境反馈更新状态并决定继续或终止。",
    depth: "例如退款 Agent 在感知阶段识别客户、账单、意图、政策和缺失信息；调用建单 API 后，观察阶段不能只看模型描述，而要读取 API 响应和工单系统状态，确认是否真的创建成功。不同框架可能把两者合并为 observation、context 或 state update，这只是抽象粒度不同。售前比较平台时，应检查输入如何进入状态、工具结果如何回写、终态如何验证，而不是只对术语表。",
    ask: "追问客户：任务入口有哪些，哪套系统提供 ground truth？执行后用哪个业务状态证明成功？",
    tag: "动作循环",
    basis: "Agent 循环 + 工程状态边界",
    evidence: [
      { sourceId: "react-2023", supports: "支持推理、行动与环境观察交替，并由观察影响后续行动的基本循环。" },
      { sourceId: "anthropic-effective-agents", supports: "支持 Agent 根据环境反馈循环使用工具，而不是一次生成全部步骤。" },
    ],
  },
  {
    q: "Agent 的“思考（Reason）”是否必须记录完整思维链（Chain-of-Thought）？",
    a: "不需要。完整隐藏思维链不是稳定、跨模型的审计接口；生产系统应审计可验证的计划、决策摘要、工具调用、环境结果、策略判断和停止原因。",
    depth: "部分模型的隐藏推理本来就不会向开发者暴露，最多提供摘要；即使获得一段推理文字，它也不等同于真实业务依据。更可运营的做法是要求结构化动作意图：当前目标是什么、选择哪个工具、关键参数和风险级别是什么、何时应停止或接管；应用再记录真实执行与后置状态。把这些可观察轨迹作为审计材料，是基于产品接口和工程可验证性的设计结论，而不是声称论文已经给出唯一审计标准。",
    ask: "追问客户：审计真正需要解释哪项业务决策？现有日志能否关联计划、工具、授权、结果与停止原因？",
    tag: "可解释与审计",
    basis: "官方产品行为 + 可观测轨迹的工程推论",
    evidence: [
      { sourceId: "openai-model-spec-hidden-cot", supports: "直接支持部分 OpenAI 模型的隐藏思维链不向用户或开发者暴露，最多以摘要形式提供；该边界仅代表 OpenAI 模型行为。" },
      { sourceId: "react-2023", supports: "支持通过行动与环境观察形成可分析的任务轨迹；以此替代完整思维链作为生产审计主线，是本文明确标注的工程推论。" },
    ],
  },
  {
    q: "Agent 每次都要先生成一份完整计划吗？规划（Planning）到底怎么做？",
    a: "不一定。短任务可每轮只决定下一步，长任务再用里程碑计划；无论哪种方式，计划都要根据观察结果修正，而不是一次生成后执行到底。",
    depth: "常见方式包括逐步规划、计划—执行和编排者—执行者。选择依据是任务长度、工具依赖、并行机会与风险：路径短但变化多时逐步规划更灵活；长任务需要显式里程碑、预算和检查点；子任务无法预先确定且可分工时，才考虑编排者拆解。规划的输出应包含子目标、候选动作、预期结果与停止条件，并限制最大深度、轮次、时长和成本。",
    ask: "追问客户：任务路径为什么不可写死？最长有多少步，哪些里程碑必须审批，环境变化后如何重规划？",
    tag: "规划机制",
    basis: "官方架构模式",
    evidence: [
      { sourceId: "anthropic-effective-agents", supports: "支持按任务复杂度选择 prompt chaining、routing、orchestrator-workers 等模式，并让 Agent 根据反馈动态运行。" },
      { sourceId: "openai-agent-guide", supports: "支持先最大化单 Agent，再依据复杂逻辑、工具和职责边界决定是否拆分编排。" },
    ],
  },
  {
    q: "什么时候应该用 Agent，什么时候用固定工作流（Workflow）？",
    a: "步骤清楚、规则稳定、错误代价高时优先工作流；步骤无法预知、需要根据环境反馈调整、存在大量例外时再引入 Agent。",
    depth: "不要把选择做成二元对立。常见生产路线是用确定性流程包住少量 Agent 决策点：例如模型判断工单类型，但退款额度、审批和记账仍由规则与工作流控制。随着自治范围扩大，测试空间、时延、成本和复合错误都会增加。",
    ask: "追问客户：哪几个决策无法用规则表达？允许模型试错几次？哪些动作必须确定性执行？",
    tag: "路线选择",
    basis: "官方模式指南",
    evidence: [
      { sourceId: "anthropic-effective-agents", supports: "支持从最简单方案开始，并按任务可预测性选择工作流或 Agent。" },
      { sourceId: "openai-agent-guide", supports: "支持优先处理复杂判断、难维护规则和非结构化数据密集的任务。" },
    ],
  },
  {
    q: "Agent、RAG 和聊天机器人（Chatbot）到底是什么关系？",
    a: "聊天机器人是交互形态，RAG 是知识增强模式，Agent 是任务执行模式；三者可以独立存在，也可以组合。",
    depth: "聊天机器人可以只回答问题；RAG 负责从外部知识寻找证据，不负责完整业务动作；Agent 可以把 RAG 当作数据工具，再调用 CRM、工单、代码执行或审批系统完成多步任务。判断重点不是界面是否像聊天，而是模型是否控制执行过程、是否能改变外部状态。",
    ask: "追问客户：系统只提供信息，还是要跨系统执行动作？需要依据哪些知识？最终由谁确认？",
    tag: "方案边界",
    basis: "官方定义 + 组合架构",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持简单聊天机器人不属于 Agent，并区分数据工具与动作工具。" },
      { sourceId: "react-2023", supports: "支持推理与环境动作交替的基本 Agent 路线。" },
    ],
  },
  {
    q: "是不是工具越多、自治程度越高，Agent 就越强？",
    a: "不是。工具越多，选错工具、参数混淆、权限扩大和测试组合都会增加；自治越高，也意味着更长轨迹与更大的复合错误面。",
    depth: "应先按用途区分数据工具（Data Tools）、动作工具（Action Tools）与编排工具（Orchestration Tools），再为每个工具定义清晰且不重叠的名称、输入输出 Schema、错误语义和权限。搜索 / RAG 等数据工具通常只读，但返回内容仍需来源和注入隔离；业务写入需要幂等、预览、审批和补偿；工作流、队列或子 Agent 需要交接、超时和汇总验证。先把最小工具集和单 Agent 做稳，再判断是否扩展。",
    ask: "追问客户：每个工具解决什么唯一问题？哪些工具可写、可逆或涉及资金与敏感数据？",
    tag: "工具治理",
    basis: "官方工程指南",
    evidence: [
      { sourceId: "anthropic-effective-agents", supports: "支持清晰工具定义、示例、边界与大量测试的重要性。" },
      { sourceId: "openai-agent-guide", supports: "支持从单 Agent 起步，并按工具清晰度和复杂逻辑决定是否拆分。" },
    ],
  },
  {
    q: "Agent 的 Memory 是不是把所有对话永久保存？",
    a: "不是。Memory 应按目的、范围和保留期分层；会话上下文、用户偏好、业务事实和操作历史不能混为一谈。",
    depth: "先分清三层：运行状态（Run State）保存本次任务目标、步骤、工具结果和预算；短期会话记忆保存当前会话原始事件；长期记忆才跨会话提取偏好、经历或有用事实。长期写入应记录 actor / session、来源、时间、范围、保留期和可撤回方式。RAG 则从组织知识库取证，不等于记住某个用户；权威订单、余额和权限仍应每次回到业务系统读取。",
    ask: "追问客户：要记住什么、为谁记、保存多久、谁能纠正或删除？记忆是否会影响后续业务动作？",
    tag: "记忆治理",
    basis: "官方产品能力 + 风险管理",
    evidence: [
      { sourceId: "aws-agentcore-memory", supports: "支持短期原始事件与长期提取记忆分层，并以 actor / session 隔离记忆范围；不证明生成记忆天然准确。" },
      { sourceId: "nist-genai-profile", supports: "支持数据来源、隐私、持续测量与生命周期风险治理。" },
    ],
  },
  {
    q: "怎样避免 Agent 调错 API、越权或造成不可逆损失？",
    a: "不要让模型直接拥有业务权限。模型只提出调用意图，应用层完成身份绑定、授权、参数校验、策略判断和真实执行。",
    depth: "按工具风险分级：只读查询可自动执行；可逆写入可先预览再确认；资金、生产配置、删除和对外发送等高风险动作应要求审批或双人复核。凭据放在密钥系统，不进入 Prompt；以用户或工作负载身份做最小权限授权；所有调用记录输入摘要、策略结果、执行响应与关联 trace。",
    ask: "追问客户：哪些动作不可逆？使用用户授权还是服务账号？是否要求逐次同意、额度或审批流？",
    tag: "安全",
    basis: "零信任原则 + 云平台控制",
    evidence: [
      { sourceId: "nist-zero-trust", supports: "支持访问资源前验证主体并执行授权，不给予隐式信任。" },
      { sourceId: "aws-agentcore", supports: "支持在工具调用前执行确定性细粒度策略控制的云平台能力。" },
      { sourceId: "azure-foundry-agent-service", supports: "支持托管身份、RBAC、OBO 与网络隔离等平台控制面。" },
    ],
  },
  {
    q: "单智能体（Single Agent）和多智能体（Multi-Agent）怎么选？",
    a: "默认先做单智能体。只有职责、工具或安全边界确实需要分离，且单智能体的指令和选工具问题无法通过简化解决时，再拆成多智能体。",
    depth: "多 Agent 常见两类：管理者把子 Agent 当工具并汇总结果；多个 Agent 通过 handoff 转移控制。拆分能隔离上下文和专业能力，但会增加交接丢失、循环、重复调用、轨迹评估与权限传播问题。Agent 数量不是能力指标，端到端任务成功率才是。",
    ask: "追问客户：拆分是为了解决哪个已观察到的失败？每个 Agent 的输入、输出、权限和终止条件是什么？",
    tag: "架构选择",
    basis: "官方编排指南",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持单 Agent 优先，以及 manager 与 handoff 两类多 Agent 编排。" },
      { sourceId: "anthropic-effective-agents", supports: "支持 orchestrator-workers 用于无法预先确定子任务的复杂任务。" },
    ],
  },
  {
    q: "怎么评估 Agent，而不是只看回答是否像人？",
    a: "应以完整任务成功为主线，并同时检查轨迹、工具、安全、工程与业务结果。只评最终文字会漏掉碰巧答对和隐性越权。",
    depth: "冻结真实任务、初始状态和可验证终态；记录计划、工具选择、参数、工具响应、重试与停止原因。指标至少包括任务成功率、关键步骤完成率、无效调用率、策略违规率、人工接管率、P95、token / 工具成本和每个成功任务成本。自动评分必须配合规则检查、环境断言和人工复核。",
    ask: "追问客户：任务完成后哪个系统状态可以证明成功？哪类错误必须为零？谁提供验收样本和裁决？",
    tag: "评估",
    basis: "基准论文 + 风险框架",
    evidence: [
      { sourceId: "webarena-2024", supports: "支持以可验证的端到端任务成功率衡量网页 Agent，并显示长链任务难度。" },
      { sourceId: "nist-genai-profile", supports: "支持部署前后持续评估、风险分级和 Go / No-Go 门槛。" },
    ],
  },
  {
    q: "Agent 出错时，为什么普通应用日志不够？",
    a: "Agent 一次任务包含多次模型、检索和工具调用；只看最终请求日志无法知道错误在哪一步产生和传播。",
    depth: "应给每次 run 建立端到端 trace，并记录 span 级模型版本、提示版本、工具名、参数摘要、权限决策、结果状态、重试、token、时延和成本。敏感内容不应默认完整落日志。标准化 telemetry 有助于跨框架关联，但业务成功、风险等级和审批结果仍需自定义字段。",
    ask: "追问客户：当前用什么 APM / 日志平台？需要保留哪些轨迹、多久、谁能查看？",
    tag: "可观测",
    basis: "可观测标准 + 云平台能力",
    evidence: [
      { sourceId: "opentelemetry-semconv", supports: "支持用统一语义约定组织 traces、metrics、logs 和 events；具体业务字段需自行定义。" },
      { sourceId: "google-agent-platform", supports: "支持托管 Agent 运行时连接 Trace、Monitoring、Logging 与评估服务。" },
    ],
  },
  {
    q: "选择云上托管 Agent 平台，还是自己用框架搭？",
    a: "看差异化落在哪。需要快速上线、托管身份、会话、工具网关、观测和弹性时，平台更省工程；编排逻辑、运行环境或合规边界高度定制时，自建或托管代码运行时更合适。",
    depth: "评估不要只比较框架 API，要拆成模型、Agent runtime、会话 / 记忆、工具接入、身份授权、沙箱、评估、Tracing、网络隔离、地域与计价。主流云平台也支持托管自定义框架或容器，因此“平台”与“开源框架”并非绝对二选一。具体产品能力、地域、预览状态和价格必须按采购时点复核。",
    ask: "追问客户：哪些能力必须自定义？数据与执行环境能否上云？已有 IAM、APM、API 管理和容器平台能否复用？",
    tag: "云选型",
    basis: "三家云官方文档",
    evidence: [
      { sourceId: "google-agent-platform", supports: "支持托管运行、框架适配、IAM、评估与可观测等能力说明。" },
      { sourceId: "aws-agentcore", supports: "支持 Runtime、Memory、Gateway、Identity、沙箱、评估与观测等组合能力。" },
      { sourceId: "azure-foundry-agent-service", supports: "支持配置型与代码型 Agent、托管运行、身份、工具和端到端观测。" },
    ],
  },
  {
    q: "怎样控制 Agent 的延迟和成本？",
    a: "先控制轨迹长度和无效动作，再考虑换小模型。Agent 成本来自每一轮模型调用、工具、检索、沙箱和等待，不只是最终回答 token。",
    depth: "设置最大轮次、超时、重试和预算；用确定性路由跳过无需 Agent 的任务；缓存稳定只读结果；把简单分类与格式化交给小模型；并行只用于独立子任务；为每个工具设置时延和成本上限。报告每个成功任务成本，而不是平均请求成本，因为失败重试会掩盖真实 TCO。",
    ask: "追问客户：P95、任务完成时限、并发和失败重试预算是什么？哪些步骤可以异步或由工作流执行？",
    tag: "FinOps",
    basis: "官方工程指南 + PoC 测量",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持建立能力基线后逐步用更小模型优化时延与成本。" },
      { sourceId: "anthropic-effective-agents", supports: "支持 Agent 自治带来更高成本和复合错误风险，并应设置停止条件。" },
    ],
  },
  {
    q: "Agent 可以直接全自动上线吗？",
    a: "不应把“能跑通 Demo”直接等同于可全自动。应按动作风险分级，从影子模式、建议模式、确认后执行逐步扩大自治。",
    depth: "先让 Agent 只观察或生成建议，与人工结果对比；再开放低风险、可逆动作；对资金、生产、法律、安全或外部沟通保留审批。上线门槛必须按高风险场景单列，不被总体平均掩盖；超过失败、预算或循环阈值时应停止并交还人工。",
    ask: "追问客户：哪些任务允许建议、哪些可自动执行？失败时如何补偿、回滚和通知责任人？",
    tag: "上线治理",
    basis: "官方护栏建议 + 风险框架",
    evidence: [
      { sourceId: "openai-agent-guide", supports: "支持高风险动作与超过失败阈值时进行人工介入。" },
      { sourceId: "nist-genai-profile", supports: "支持按风险容忍度设置上线门槛、持续复核和停止机制。" },
    ],
  },
  {
    q: "Function Calling、MCP 和 A2A 是什么关系？",
    a: "Function Calling 表达一次工具调用意图；MCP 标准化 Agent / AI 应用与工具、资源的连接；A2A 用于 Agent 之间发现、委派和交换任务结果。",
    depth: "三者可以同时出现：Agent 用 Function Calling 选择一个由 MCP Server 暴露的工具，再通过 A2A 把独立任务交给另一个 Agent。协议降低连接成本，但不会自动完成身份、授权、租户隔离、审批、限流和审计；单系统内部编排也不必为了使用 A2A 而拆成分布式架构。",
    ask: "追问客户：需要统一的是工具接入、跨系统 Agent 协作，还是单个应用内部编排？信任边界跨越了哪些团队或租户？",
    tag: "协议边界",
    basis: "官方协议架构与职责边界",
    evidence: [
      { sourceId: "mcp-architecture", supports: "支持 MCP 的 Host、Client、Server 架构和工具 / 资源互操作职责。" },
      { sourceId: "a2a-concepts", supports: "支持 A2A 的 Agent Card、Task、Message 与 Artifact 等跨 Agent 协作概念。" },
      { sourceId: "openai-function-calling", supports: "支持模型提出工具调用、应用执行并回传结果的职责分界。" },
    ],
  },
  {
    q: "Agent 的长期记忆能不能直接当客户档案或业务事实库？",
    a: "不能。长期记忆适合保存经治理的偏好、经历摘要和可复用信息；余额、订单、权限和政策等权威事实仍应在业务系统中读取。",
    depth: "至少分开任务状态、会话状态、长期记忆与权威事实。模型生成的摘要在写入长期记忆前要经过主体绑定、来源、去重、有效期和必要的用户确认；权威事实只由获授权的业务流程写入。否则错误总结会被持久化，并在未来任务中反复放大。",
    ask: "追问客户：哪些信息允许模型总结后保存，哪些必须每次回到 CRM、ERP 或策略系统读取？谁能纠正和删除？",
    tag: "记忆治理",
    basis: "云平台记忆实现 + 风险治理",
    evidence: [
      { sourceId: "aws-agentcore-memory", supports: "支持区分会话内事件与跨会话长期记忆，并按主体 / 会话隔离。" },
      { sourceId: "nist-genai-profile", supports: "支持对数据来源、隐私、生命周期和持续风险进行治理。" },
    ],
  },
  {
    q: "没有稳定 API 时，可以直接让 Agent 用 Computer Use 操作生产界面吗？",
    a: "可以作为受限补充，但不应默认成为高风险生产主通道。有稳定 API 时优先 API；Computer Use 应运行在隔离环境，并从只读、建议和人工确认开始。",
    depth: "界面会变化，视觉定位和状态判断也可能错误。需要限制网站和应用范围、使用短期凭证、屏蔽敏感信息、记录屏幕与动作轨迹、验证关键后置状态，并为付款、删除、外发和生产变更保留人工确认。固定且可脚本化的界面路径也可先比较 RPA。",
    ask: "追问客户：目标系统为何没有 API？动作是否可逆？能否提供隔离账号、沙箱环境、回放证据和人工审批？",
    tag: "执行方式",
    basis: "Agent 风险治理 + 零信任原则",
    evidence: [
      { sourceId: "nist-zero-trust", supports: "支持每次资源访问前验证主体、设备与授权，而不因运行位置默认信任。" },
      { sourceId: "nist-genai-profile", supports: "支持按使用情境、影响与风险容忍度设置控制和持续测量。" },
    ],
  },
];
