/**
 * 提示词工程模块的问答与证据卡。
 *
 * 来源标题、链接、证据类别和核验日期统一维护在
 * app/reference-content.mjs；此文件仅保存稳定 sourceId。
 */
export const promptDeepDives = [
  {
    kind: "matrix",
    eyebrow: "INSTRUCTION AUTHORITY",
    title: "先解决指令冲突，再优化措辞",
    intro: "生产输入同时包含平台规则、应用目标、用户请求、检索内容和工具结果。必须记录来源与信任级别，不能把所有自然语言都当成同等指令。",
    columnLabels: { name: "输入来源", mechanism: "处理机制", decision: "工程判断", boundary: "不能替代" },
    items: [
      { name: "平台与应用指令", en: "System / Developer", mechanism: "承载稳定目标、角色与输出契约；按模型 API 的指令层级处理冲突并版本化。", decision: "规则是建议模型遵循，还是必须由代码硬执行？", boundary: "指令层级是模型行为机制，不是 IAM 或访问控制。" },
      { name: "用户请求", en: "User Request", mechanism: "表达本次意图和输入；与高层目标冲突时限定范围，并对敏感动作要求确认。", decision: "用户是否有权提出该动作，参数是否完整且经过校验？", boundary: "自然语言请求不能自动扩大资源权限。" },
      { name: "外部内容", en: "Untrusted Content", mechanism: "网页、邮件、PDF、RAG 证据和工具返回标注为数据，只提供事实，不取得指令权限。", decision: "上下文组装器能否保留来源、ACL、时效和不可信标记？", boundary: "分隔符有助理解，但不能单独阻止提示注入。" },
      { name: "模型历史输出", en: "Assistant History", mechanism: "只作为会话历史或中间产物，关键事实和动作仍须回到权威系统验证。", decision: "哪些历史可压缩，哪些必须保留原始证据和操作编号？", boundary: "模型之前说过的话不是新的系统事实。" },
    ],
    sourceIds: ["openai-model-spec-command", "google-system-instructions", "owasp-prompt-injection"],
  },
  {
    kind: "sequence",
    eyebrow: "CONTEXT ASSEMBLY PLAN",
    title: "Context 不是一段拼接字符串，而是一份可审计装配计划",
    intro: "上下文工程应在每次调用前决定放什么、为何放、占多少 token、何时淘汰，并保留能够复盘的 Manifest。",
    items: [
      { name: "登记上下文块", en: "Register Blocks", mechanism: "每块携带 block_id、来源、ACL、有效期、信任级别、优先级和 token 估算。", decision: "能否解释某段内容为何进入本次模型调用？", boundary: "只有最终 Prompt 文本会丢失来源、权限和生命周期。" },
      { name: "分配预算", en: "Allocate Budget", mechanism: "先保护任务、硬约束和输出 Schema，再给证据、历史、示例与工具说明分配独立预算。", decision: "哪些内容可压缩，哪些被截断会改变业务含义？", boundary: "上下文窗口上限不等于所有位置都能被稳定利用。" },
      { name: "按策略排序", en: "Order by Policy", mechanism: "稳定指令与复用内容保持一致顺序；动态证据按主张和重要性组织，避免关键限制长期落在中间。", decision: "排序是否同时考虑缓存、位置偏差和引用完整性？", boundary: "为了缓存而把过期或越权内容放入稳定前缀是错误优化。" },
      { name: "淘汰与压缩", en: "Evict / Compress", mechanism: "按显式规则去重、摘要或删除低优先级块，并保护否定词、范围、版本和原文坐标。", decision: "压缩后能否证明关键主张仍有直接证据？", boundary: "摘要器会产生新文本，不能无条件当作原始证据。" },
      { name: "保存 Context Manifest", en: "Persist Manifest", mechanism: "记录块顺序、淘汰原因、token、模型、Prompt 与工具版本，供评估和事故复盘。", decision: "线上失败能否还原模型当时实际看到了什么？", boundary: "Manifest 可能含敏感元数据，日志同样需要最小化和保留策略。" },
    ],
    sourceIds: ["lost-middle", "openai-prompt-caching", "nist-genai-profile"],
  },
  {
    kind: "matrix",
    eyebrow: "OUTPUT & TOOL CONTRACT",
    title: "结构化输出之后，还有业务有效性和动作安全",
    intro: "Schema 只解决语法和字段形状。真正可交付的调用还要通过业务规则、权限、工具执行和事务后置条件。",
    columnLabels: { name: "验证层", mechanism: "验证什么", decision: "失败如何处理", boundary: "典型误判" },
    items: [
      { name: "语法有效", en: "Syntactic Validity", mechanism: "输出可以被目标解析器读取，JSON、XML 或文本格式完整。", decision: "解析失败时重试、修复还是返回明确错误？", boundary: "能解析不代表字段齐全或枚举合法。" },
      { name: "Schema 有效", en: "Schema Validity", mechanism: "字段、类型、必填项和枚举符合受支持的结构化输出约束。", decision: "拒答、截断和不支持的 Schema 特性如何单独处理？", boundary: "Schema 正确不代表日期、金额或引用真实。" },
      { name: "业务有效", en: "Business Validity", mechanism: "应用检查金额、库存、权限、状态转换、数据新鲜度和跨字段规则。", decision: "哪些不变量必须由代码或规则引擎执行？", boundary: "把业务规则全部写进 Prompt 无法提供确定性保证。" },
      { name: "工具契约有效", en: "Tool Contract", mechanism: "工具描述、输入 Schema、风险、幂等、错误类别和后置验证共同决定是否执行。", decision: "模型选中工具后，应用是否重新鉴权并验证参数？", boundary: "更多工具会增加上下文和选择歧义；动态发现也要限制范围。" },
      { name: "事务可接受", en: "Transaction Accepted", mechanism: "真实系统返回 operation ID，并回读权威状态确认动作完成或进入可恢复状态。", decision: "结果未知或部分成功时是否停止、查询、补偿或交人工？", boundary: "模型生成“成功”不能代替外部系统事实。" },
    ],
    sourceIds: ["openai-structured-outputs", "anthropic-tool-definitions", "openai-function-calling", "openapi-3-1-1"],
  },
  {
    kind: "checklist",
    eyebrow: "RELEASE & SECURITY",
    title: "把提示发布包和 Source–Sink 风险一起验收",
    intro: "提示上线不是替换一段文字。模型、上下文组装、工具、Schema、安全策略和评估集共同决定行为，也共同构成回滚单位。",
    maxColumns: 3,
    items: [
      { name: "冻结发布 Bundle", en: "Release Bundle", mechanism: "记录 prompt_version、model_snapshot、context_assembler、retriever、tool_schema、output_schema 与 safety_policy。", decision: "一次线上回答能否关联到完整配置，而不是只有 Prompt ID？", boundary: "只回滚模板可能无法消除由模型或工具版本引入的回归。" },
      { name: "做因果对比", en: "Causal Comparison", mechanism: "一次主要改变一个变量；在冻结任务集上做切片、成对比较、人工校准和失败归因。", decision: "改善来自 Prompt、模型、上下文还是工具变化？", boundary: "LLM Judge 有位置和冗长偏差，不能成为高风险唯一门禁。" },
      { name: "持续评估与灰度", en: "Continuous Evaluation", mechanism: "离线回归后走影子、Canary、在线监测和快速回滚，线上失败经确认后进入评估集。", decision: "门槛是否覆盖真实分布、边界、对抗和不可接受错误？", boundary: "文档中的示例阈值不是客户通用上线标准。" },
      { name: "标记不可信 Source", en: "Untrusted Sources", mechanism: "识别用户、网页、邮件、PDF、RAG、图像和工具结果等可被攻击者影响的入口。", decision: "每种 Source 能到达哪些模型、工作流和工具？", boundary: "仅检测恶意文本无法可靠覆盖复杂社会工程攻击。" },
      { name: "限制危险 Sink", en: "Dangerous Sinks", mechanism: "对外发、支付、数据写入、链接访问、代码执行和敏感信息传输执行最小权限、参数绑定与确认。", decision: "即使模型被误导，最大可造成的影响是否仍受确定性控制？", boundary: "系统提示更强不能替代 Sink 侧的硬限制。" },
    ],
    sourceIds: ["openai-eval-best-practices", "openai-source-sink-injection", "nist-zero-trust", "openai-prompting-guide"],
  },
];

export const promptEvidenceCards = [
  {
    metric: "4",
    title: "类常见提示组成",
    finding: "Google Cloud 将任务、系统指令、少样本示例与上下文信息列为常见组成；其中只有任务是每次请求的核心必需项。",
    boundary: "这是厂商官方的实用分类，不是跨模型统一协议；具体字段、角色名称和优先级要以所选模型 API 为准。",
    sourceId: "google-prompt-introduction",
  },
  {
    metric: "3",
    title: "项优化前提",
    finding: "Anthropic 建议先具备清晰成功标准、可实测的方法和一版待改进提示，再进入提示优化。",
    boundary: "这是工程工作流，不是效果保证；质量、成本或时延问题也可能更适合通过换模型、改数据或改架构解决。",
    sourceId: "anthropic-prompt-overview",
  },
  {
    metric: "Schema",
    title: "约束输出结构",
    finding: "Structured Outputs 可使支持的模型输出遵守所提供的 JSON Schema，并减少缺字段或无效枚举等结构错误。",
    boundary: "结构正确不等于事实正确；拒答、输出截断和不支持的 Schema 特性仍需由应用处理。",
    sourceId: "openai-structured-outputs",
    accent: true,
  },
  {
    metric: "5",
    title: "步工具调用闭环",
    finding: "官方流程明确区分：应用提供工具、模型返回调用意图、应用执行代码、回传结果、模型形成最终回答。",
    boundary: "模型生成工具名与参数不代表动作已执行或已获授权；权限、参数校验、幂等与审批仍是应用责任。",
    sourceId: "openai-function-calling",
  },
  {
    metric: "每次发布",
    title: "都运行提示评估",
    finding: "OpenAI 官方提示指南建议生产提示纳入代码版本管理，并在发布时运行代表性样例和评估检查。",
    boundary: "文档给出的是治理原则，不提供跨业务通用通过率；门槛必须由客户风险和基线决定。",
    sourceId: "openai-prompting-guide",
  },
  {
    metric: "非零风险",
    title: "系统提示不是安全边界",
    finding: "OWASP 安全指南强调：提示注入无法只靠模型内部约束彻底消除，需要结合最小权限、输入输出过滤与高风险动作审批。",
    boundary: "提示加固可降低风险，但不能替代身份鉴别、最小权限、输出验证、隔离和高风险动作审批。",
    sourceId: "owasp-prompt-injection",
  },
  {
    metric: "Source + Sink",
    title: "提示注入要控制真实影响",
    finding: "OpenAI 的安全工程文章把攻击建模为不可信输入 Source 与危险能力 Sink 的组合，并强调在检测失败时仍限制影响。",
    boundary: "这是安全分析方法，不是单一产品功能；企业仍需按自身数据与动作建立权限和确认。",
    sourceId: "openai-source-sink-injection",
  },
  {
    metric: "持续评估",
    title: "发布不是一次性打分",
    finding: "官方评估指南建议任务特定评估、生产分布样本、每次变化持续运行，并用人工反馈校准自动评分。",
    boundary: "指南中的示例任务与阈值不是跨业务标准；上线门槛必须按客户错误成本定义。",
    sourceId: "openai-eval-best-practices",
  },
];

export const promptQa = [
  {
    q: "提示词写得足够好，就能解决准确性问题吗？",
    a: "不能。提示词只能改善模型如何理解任务、使用上下文和组织输出；知识缺失、数据错误、模型能力不足、工具结果错误与业务规则缺口仍要分别治理。",
    depth: "先定位失败层：若模型不知道最新事实，优先补充 Grounding 或 RAG；若输出结构漂移，使用 Structured Outputs 与应用校验；若任务本身超出候选模型能力，换模型或拆解流程；若是确定性业务规则，放在代码和规则引擎中。Anthropic 官方也明确指出，不是所有失败指标都最适合通过提示工程改善。",
    ask: "追问客户：当前错误主要是缺知识、没听懂指令、格式不稳定，还是业务动作执行错误？",
    tag: "能力边界",
    basis: "厂商官方工作流 + 工程分层",
    evidence: [
      { sourceId: "anthropic-prompt-overview", supports: "支持先定义成功标准，并判断问题是否适合通过提示工程解决。" },
      { sourceId: "google-prompt-strategies", supports: "支持把目标、指令、上下文、示例和响应格式分开设计并迭代测试。" },
    ],
  },
  {
    q: "系统提示（System Prompt）的优先级更高，是否就等于安全？",
    a: "不等于。系统指令（System Instructions）可以提供稳定行为约束，但仍会被模型作为输入处理；不能存放密钥，也不能承担真正的授权与安全控制。",
    depth: "不同 API 的消息角色和优先级并不完全相同，不能把某一家接口的 system / developer / user 结构当成通用标准。即使模型遵循高优先级指令，也可能受到直接或间接提示注入影响。敏感信息应留在模型不可见的安全系统；访问控制、数据过滤、工具白名单和高风险审批必须由应用强制执行。",
    ask: "追问客户：哪些约束必须绝对执行？其中哪些已经在模型外通过 IAM、策略或代码落实？",
    tag: "安全边界",
    basis: "云厂商官方说明 + OWASP 安全指南",
    evidence: [
      { sourceId: "google-system-instructions", supports: "支持系统指令的用途，并明确其不能完全阻止越狱或泄漏。" },
      { sourceId: "owasp-prompt-injection", supports: "支持提示注入无法只靠系统提示彻底消除，以及最小权限和人工审批等缓解方向。" },
    ],
  },
  {
    q: "Zero-shot 和 Few-shot 怎么选？示例是不是越多越好？",
    a: "先用零样本提示（Zero-shot Prompting）建立最小基线；当任务边界、风格或标签容易误解时，再加入少量有代表性的少样本示例（Few-shot Examples）。示例不是越多越好。",
    depth: "每个示例都占用上下文，并可能把样例中的偏差、过时规则或偶然格式固化到输出。优先覆盖最常见路径、易混淆边界和应拒答样例，保持示例的输入输出结构一致；用固定评估集判断新增示例是否真正改善关键分组，而不是只看几个演示。",
    ask: "追问客户：哪些输入最容易被模型误判？有没有反例、边界例和拒答例可作为评估样本？",
    tag: "核心模式",
    basis: "云厂商官方提示指南",
    evidence: [
      { sourceId: "google-prompt-introduction", supports: "支持 Few-shot Examples 是可选的提示组成，并用于示范期望输出。" },
      { sourceId: "openai-prompting-guide", supports: "支持精简组织少样本示例，并在每次发布时运行测试。" },
    ],
  },
  {
    q: "要求模型输出 JSON，是否已经足够可靠？",
    a: "不够。文字要求“输出 JSON”只能表达意图；生产集成应优先使用模型 API 提供的结构化输出（Structured Outputs）或严格 Schema，并仍处理拒答、截断和语义错误。",
    depth: "要区分三层：可解析 JSON、符合业务 Schema、字段值在业务上正确。Structured Outputs 主要加强前两层中的结构约束，不能证明金额、日期、产品代码或判断结论真实。应用仍应做类型与范围校验、枚举映射、跨字段规则、权限检查和失败重试；高风险字段进入后端前还要有人或确定性系统复核。",
    ask: "追问客户：下游系统真正要求哪些字段、枚举和跨字段约束？错误值会造成什么业务后果？",
    tag: "结构化输出",
    basis: "官方 API 文档 + 工程边界",
    evidence: [
      { sourceId: "openai-structured-outputs", supports: "支持 JSON Schema 约束及拒答、截断、不支持特性等边界。" },
    ],
  },
  {
    q: "把 API 写进 Tool Definition，模型就能安全调用了吗？",
    a: "不能。工具定义（Tool Definition）只是告诉模型有哪些工具、何时使用和参数长什么样；模型返回的是调用意图，真正执行由应用完成。",
    depth: "应用应在每次执行前重新校验工具名、参数、用户身份、资源范围与幂等键；读写工具分开授权，高风险动作要求显式确认，并记录调用、结果和审批。严格 Schema 能减少参数形状错误，但不判断动作是否应该执行，也不赋予模型权限。对外部文档或网页触发的调用，还要防间接提示注入。",
    ask: "追问客户：工具中哪些只读、哪些会改变状态？谁有权调用、批准和撤销？",
    tag: "工具安全",
    basis: "官方工具调用流程 + 安全指南",
    evidence: [
      { sourceId: "openai-function-calling", supports: "支持模型提出调用、应用执行并回传结果的五步职责分界。" },
      { sourceId: "owasp-prompt-injection", supports: "支持最小权限、高风险人工确认和外部内容隔离。" },
    ],
  },
  {
    q: "Prompt、RAG 和 Context Engineering 是什么关系？",
    a: "Prompt 负责表达任务与约束；RAG 负责从外部知识中选择证据；上下文工程（Context Engineering）负责在每次调用前，动态选择并组装模型看到的全部信息。",
    depth: "上下文不仅包括文字指令，还可能包括身份与会话状态、检索证据、示例、工具定义、工具结果、时间和 token 预算。提示词工程是其中一部分。若答案缺少最新事实，不应靠延长系统提示硬写知识；若模型看到过多噪声，也不能仅靠一句“请仔细阅读”弥补。生产系统要分别版本化提示模板、检索策略、工具 Schema 与上下文组装逻辑。",
    ask: "追问客户：这次调用中的每一段上下文来自哪里、由谁维护、何时更新、是否经过权限过滤？",
    tag: "架构边界",
    basis: "官方提示组成 + RAG 工程边界",
    evidence: [
      { sourceId: "google-prompt-strategies", supports: "支持把 Context 与 Instructions、Examples、Response Format 作为不同组成管理。" },
      { sourceId: "openai-prompting-guide", supports: "支持区分稳定角色指引、任务细节和示例，并以工程化方式管理。" },
    ],
  },
  {
    q: "同一个 Prompt 换模型或模型升级后，可以直接上线吗？",
    a: "不可以默认等价。模型家族、快照、推理方式、消息角色、工具协议和结构化输出支持都会影响结果；升级必须做回归评估。",
    depth: "生产记录至少包含 prompt_version、model_provider、model_id / snapshot、推理参数、工具与 Schema 版本、评估集版本。升级时先做影子或离线回放，对关键任务、拒答、安全、结构正确率、P95 与单次成功成本分组比较；只有通过门槛后再逐步放量。不要为多个模型维护大量不可追溯的 if/else 文本，应使用共享意图层和少量适配层。",
    ask: "追问客户：目前调用的是浮动别名还是固定快照？升级由谁批准，能否快速回滚？",
    tag: "版本治理",
    basis: "官方提示治理建议 + 客户发布控制",
    evidence: [
      { sourceId: "openai-prompting-guide", supports: "支持生产提示版本化、代表性样例与发布评估。" },
      { sourceId: "anthropic-prompt-overview", supports: "支持先建立成功标准和实测方法再优化。" },
    ],
  },
  {
    q: "提示模板（Prompt Template）里的变量可以直接拼字符串吗？",
    a: "不建议。模板（Prompt Template）应保持稳定指令与动态变量分离；变量使用类型、长度、来源和权限校验后再注入，并用清晰边界标出不可信数据。",
    depth: "直接字符串拼接容易造成分隔符破坏、指令与数据混淆、日志泄密和模板不可测试。应用层应将客户输入、检索证据、配置和工具结果放入独立字段或结构，限定长度与字符集，对来源和敏感级别打标；模板本身进入代码审查与版本管理。变量变化和模板变化应能在追踪日志中分开定位。",
    ask: "追问客户：变量来自用户、数据库还是外部网页？其中哪些是不可信输入或敏感数据？",
    tag: "模板工程",
    basis: "官方工程建议 + 安全边界",
    evidence: [
      { sourceId: "openai-prompting-guide", supports: "支持用类型化参数或已校验输入对象替换模板变量，并用代码管理生产提示。" },
      { sourceId: "owasp-prompt-injection", supports: "支持标识并隔离外部不可信内容。" },
    ],
  },
  {
    q: "怎样评估 Prompt，而不是靠人工感觉？",
    a: "先冻结真实任务与成功标准，再比较版本。评估单位应是“模型 + Prompt + 上下文 + 工具 / Schema”的完整配置，而不是孤立的一段文字。",
    depth: "评估集要覆盖主路径、边界、拒答、敏感信息、注入与高价值失败。按任务观察正确性、完整性、忠实度、格式 / Schema 通过率、工具选择与参数正确率、拒答正确率；按工程观察 P95、输入输出 token、缓存命中和每个成功任务成本。自动评分应与抽样人工复核结合，并保留失败样本用于下一轮迭代。",
    ask: "追问客户：什么算成功？不可接受错误有哪些？谁提供权威答案并负责签署上线门槛？",
    tag: "PoC 评估",
    basis: "厂商官方评估前提 + NIST 持续测量",
    evidence: [
      { sourceId: "anthropic-prompt-overview", supports: "直接支持先定义成功标准并建立可实测方法。" },
      { sourceId: "nist-genai-profile", supports: "支持以 Govern / Map / Measure / Manage 形成持续风险管理。" },
    ],
  },
  {
    q: "Prompt Engineering 能带来哪些云服务销售机会？",
    a: "它不是单独售卖的一段文字，而会连接模型服务、Prompt 管理、AI 网关、评估、安全、日志追踪、密钥与弹性运行等云能力。",
    depth: "售前应把需求拆成可采购能力：模型目录与版本固定、提示模板与密钥分离、流量路由和限流、结构化输出与工具编排、离线评估和在线观测、敏感信息防护、审计与成本归集。具体产品名称、地域、保留策略和计价必须用目标云当期官方资料核验，不能把提示技巧包装成平台级能力承诺。",
    ask: "追问客户：谁维护模板？需要多模型路由吗？是否要求私网、审计、数据驻留和按部门分账？",
    tag: "云服务",
    basis: "工程能力映射；产品细节需当期核验",
    evidence: [
      { sourceId: "openai-prompting-guide", supports: "支持提示版本化、测试和部署流程的工程化管理。" },
      { sourceId: "nist-genai-profile", supports: "支持持续治理、测量与风险管理要求。" },
    ],
  },
  {
    q: "推理模型（Reasoning Model）还需要写很长的思维链提示吗？",
    a: "通常不需要把完整推理步骤写给模型，更不应把模型隐藏思维链当作审计证据。优先给清晰任务、必要证据、约束、输出契约和合适的推理预算。",
    depth: "通用模型在复杂任务上可能受益于任务分解或中间检查点，但推理模型往往已经在内部完成更长的推理过程。生产评估应看最终答案、引用、工具参数、可观察决策摘要和真实业务终态；要求逐字公开内部推理既不通用，也可能产生伪解释。",
    ask: "追问客户：真正需要的是更高任务成功率、可调推理预算，还是必须满足某种审计记录？",
    tag: "推理模型",
    basis: "官方模型行为边界 + 发布评估",
    evidence: [
      { sourceId: "openai-model-spec-hidden-cot", supports: "支持隐藏思维链不会直接向用户或开发者公开这一接口边界。" },
      { sourceId: "openai-prompting-guide", supports: "支持按模型与任务组织指令并用代表性评估验证，而非依赖单一固定技巧。" },
    ],
  },
  {
    q: "Prompt Chaining 和 Agent 应该怎么分？",
    a: "步骤、顺序和异常路径已知时用 Prompt Chaining 或 Workflow；只有当下一步必须根据环境反馈动态选择时，才需要 Agent。",
    depth: "Prompt Chaining 把大任务拆成可测试中间产物，路由仍由代码或流程控制；Agent 把一部分路径选择交给模型，需要额外的工具契约、状态、停止、预算、身份和轨迹评估。两者可以组合：Workflow 包住 Agent 决策点，而不是在命名上二选一。",
    ask: "追问客户：哪些步骤可以预先画出，哪些例外必须在运行时根据工具结果判断？",
    tag: "编排边界",
    basis: "厂商工程指南 + 责任分层",
    evidence: [
      { sourceId: "anthropic-effective-agents", supports: "支持区分预定义代码路径的 Workflow 与模型动态决定过程的 Agent。" },
      { sourceId: "react-2023", supports: "支持推理、动作和环境观察交替的动态 Agent 路线。" },
    ],
  },
  {
    q: "Prompt Caching 是否一定能降低很多成本？",
    a: "不一定。只有稳定且足够长的共享前缀被重复请求、产品支持相应缓存语义且请求分布匹配时，才可能形成收益。",
    depth: "设计上可把稳定指令和复用示例放前部，把用户与动态证据放后部；但缓存键、TTL、模型版本、租户隔离、计费和命中条件都由具体平台决定。应同时测缓存命中率、输入成本、P95、首 Token 延迟和错误隔离，不能把厂商标价折扣直接外推为整体应用降本。",
    ask: "追问客户：请求中有多少前缀真正相同？按租户还是全局复用？目标模型当前缓存规则和计价是什么？",
    tag: "成本优化",
    basis: "官方产品文档 + 客户流量实测",
    evidence: [
      { sourceId: "openai-prompt-caching", supports: "支持特定 OpenAI API 的自动前缀缓存机制与可观测字段；不代表其他平台或整体成本。" },
      { sourceId: "openai-prompting-guide", supports: "支持将稳定与动态提示内容分层并纳入工程化版本管理。" },
    ],
  },
  {
    q: "为什么间接提示注入比普通恶意用户输入更难防？",
    a: "因为恶意指令可能藏在系统主动检索或读取的可信外观内容里，例如网页、邮件、PDF、RAG 文档或工具结果，而不是直接由用户说出来。",
    depth: "模型会同时看到真实任务和外部内容，难以始终把自然语言稳定区分为“指令”或“数据”。因此必须在上下文中标记来源与信任区，限制工具权限，对写操作做独立策略和审批，检查输出与工具参数，并把相关攻击样本加入回归与红队。RAG 或微调都不能单独根治这一问题。",
    ask: "追问客户：模型会读取哪些外部内容，读取后能调用哪些工具，哪些动作会产生不可逆影响？",
    tag: "安全",
    basis: "行业安全指南 + 零信任原则",
    evidence: [
      { sourceId: "owasp-prompt-injection", supports: "直接支持间接提示注入可来自外部内容，以及最小权限和人工审批等分层缓解。" },
      { sourceId: "nist-zero-trust", supports: "支持访问资源前持续验证主体和权限，不因内容或网络位置默认信任。" },
    ],
  },
  {
    q: "系统、用户、检索内容和工具结果互相冲突时，模型应该听谁的？",
    a: "先按所选模型 API 的指令层级处理平台、应用与用户指令；网页、文档、RAG 和工具结果默认是数据而不是新指令。必须执行的授权和业务不变量仍放在模型外。",
    depth: "上下文块应记录来源、信任级别、ACL、时效与用途。冲突时保留原始输入和适用指令，拒绝让低信任内容覆盖高层任务边界；但不能把某家模型的角色名称当成跨厂商协议。更不能因为系统提示优先级高，就认为模型获得了 IAM 或事务权限。",
    ask: "追问客户：哪些规则是模型行为指导，哪些必须由网关、IAM、代码或规则引擎硬执行？",
    tag: "指令治理",
    basis: "官方模型行为规范 + 跨平台边界",
    evidence: [
      { sourceId: "openai-model-spec-command", supports: "支持不同指令来源具有权限层级，外部不可信内容默认不取得指令权限。" },
      { sourceId: "google-system-instructions", supports: "支持系统指令配置模型行为，同时说明其不能完全防止越狱或泄漏。" },
    ],
  },
  {
    q: "Structured Outputs 已经保证 JSON Schema，为什么还需要应用校验？",
    a: "Schema 只保证受支持范围内的字段形状，不保证字段值真实、用户有权执行、业务状态允许或外部交易已经成功。",
    depth: "至少按四层验收：语法可解析、Schema 有效、业务规则有效、事务后置条件成立。金额、库存、日期、跨字段约束、权限和状态转换由应用或规则引擎校验；拒答、截断、不支持特性和结果未知也要有单独错误路径。",
    ask: "追问客户：下游真正依赖哪些业务不变量？字段值错误或事务部分成功时如何停止与恢复？",
    tag: "输出契约",
    basis: "官方结构化输出 + 应用责任边界",
    evidence: [
      { sourceId: "openai-structured-outputs", supports: "支持用 JSON Schema 约束输出结构，并说明拒答、截断与 Schema 支持边界。" },
      { sourceId: "openapi-3-1-1", supports: "支持描述 API 数据结构，但不替代授权和业务后置条件。" },
    ],
  },
  {
    q: "工具越多，Agent 的能力是不是越强？",
    a: "不一定。每个工具的名称、描述和 Schema 都占用上下文并增加选择歧义；应只暴露当前任务所需的最小集合，必要时再做受控动态发现。",
    depth: "工具目录要有清晰、互斥的职责，描述何时使用、何时不要使用，并提供风险、幂等、错误和后置条件。评估工具选择、参数正确率、无效调用和新增 token / P95；如果多个工具高度重叠，应合并、分层路由或按权限缩小可见范围。",
    ask: "追问客户：哪些工具职责重叠？模型一次可见多少定义？动态加载由任务、身份还是租户策略决定？",
    tag: "工具上下文",
    basis: "官方工具定义 + 工程评估",
    evidence: [
      { sourceId: "anthropic-tool-definitions", supports: "支持工具名称、描述与输入 Schema 进入模型上下文并影响工具选择。" },
      { sourceId: "openai-function-calling", supports: "支持应用提供工具集合、模型提出调用而应用负责执行的控制边界。" },
    ],
  },
  {
    q: "如何证明一次 Prompt 改动真的带来提升，而不是模型或上下文碰巧变化？",
    a: "把 Prompt、模型快照、上下文组装器、检索器、工具 Schema、输出 Schema、安全策略和评估集冻结为发布 Bundle；一次主要改变一个变量并做切片对比。",
    depth: "先在代表性任务、边界与对抗集做离线回归，再走影子和 Canary。自动评分使用明确 rubric，并与人工标签校准；保存失败样本和完整 Bundle 版本，才能把退化归因到 Prompt、模型、Context 或工具。LLM Judge 的位置和冗长偏差也应进入校准。",
    ask: "追问客户：当前能否还原每次回答的完整调用配置？谁维护人工金标和回滚触发器？",
    tag: "发布治理",
    basis: "官方持续评估 + 版本工程",
    evidence: [
      { sourceId: "openai-eval-best-practices", supports: "支持任务特定、持续评估、生产样本与人工校准，并警告主观观感评估。" },
      { sourceId: "openai-prompting-guide", supports: "支持提示版本化并在发布时运行代表性评估。" },
    ],
  },
];
