/**
 * RAG 读者内容的单一事实源。
 *
 * 问答与证据卡只保存来源 ID；标题、链接、证据类型和核验日期统一由
 * sourceLedger 提供，避免正文、问答和来源列表各自维护一份链接。
 */

export const sourceLedger = {
  "bm25-book": {
    grade: "A",
    kind: "权威教材",
    shortTitle: "BM25 教材",
    title: "Introduction to Information Retrieval — Okapi BM25",
    note: "稀疏检索的概率排序、词频、逆文档频率与长度归一化基础。",
    verifiedAt: "2026-07-17",
    href: "https://nlp.stanford.edu/IR-book/html/htmledition/okapi-bm25-a-non-binary-model-1.html",
  },
  "dpr-2020": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "DPR",
    title: "Dense Passage Retrieval for Open-Domain Question Answering",
    note: "双编码器稠密检索；论文特定开放域问答数据集上，top-20 passage retrieval accuracy 较其 Lucene-BM25 基线高 9–19 个百分点，不能外推为稠密检索普遍更优。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2020.emnlp-main.550/",
  },
  "hnsw-2016": {
    grade: "A",
    kind: "一手论文",
    shortTitle: "HNSW",
    title: "Efficient and Robust Approximate Nearest Neighbor Search Using Hierarchical Navigable Small World Graphs",
    note: "解释常见向量索引 HNSW 的分层近邻图与近似最近邻搜索机制。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/1603.09320",
  },
  "rag-survey": {
    grade: "A",
    kind: "研究综述",
    shortTitle: "RAG 综述",
    title: "Retrieval-Augmented Generation for Large Language Models: A Survey",
    note: "系统整理 Naive、Advanced、Modular RAG，以及检索、增强、生成与评估环节。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2312.10997",
  },
  graphrag: {
    grade: "A",
    kind: "一手论文",
    shortTitle: "GraphRAG",
    title: "From Local to Global: A Graph RAG Approach to Query-Focused Summarization",
    note: "用实体图、社区和社区摘要处理跨整个语料的全局归纳问题。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2404.16130",
  },
  "chunking-study": {
    grade: "A",
    kind: "任务特定研究",
    shortTitle: "代码 RAG 切块实验",
    title: "How Does Chunking Affect Retrieval-Augmented Code Completion?",
    note: "代码补全任务中的切块控制实验；只能说明切块需要按任务实测，不能直接代表合同、PDF 或扫描件。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2605.04763",
  },
  "rag-original-2020": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "原始 RAG 论文",
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
    note: "RAG 的潜变量文档、Top-K 截断边缘化、RAG-Sequence / RAG-Token，以及查询编码器与生成器的联合优化。",
    verifiedAt: "2026-07-17",
    href: "https://proceedings.neurips.cc/paper/2020/hash/6b493230205f780e1bc26945df7481e5-Abstract.html",
  },
  "bert-reranker": {
    grade: "A",
    kind: "一手论文",
    shortTitle: "BERT Reranker",
    title: "Passage Re-ranking with BERT",
    note: "查询—段落联合重排的经典二阶段方法；精排只能重新排序已召回候选，不能找回候选集外的证据。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/1901.04085",
  },
  "fid-2021": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "Fusion-in-Decoder",
    title: "Leveraging Passage Retrieval with Generative Models for Open Domain Question Answering",
    note: "说明多段证据可被独立编码并在解码器聚合；更多 passage 带来的收益只适用于论文实验，不能外推为上下文越多越好。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2021.eacl-main.74/",
  },
  "replug-2024": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "REPLUG",
    title: "REPLUG: Retrieval-Augmented Black-Box Language Models",
    note: "验证冻结黑盒语言模型、在模型外训练可调检索器，并把检索文档前置到模型输入的模块化路线。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2024.naacl-long.463/",
  },
  "self-rag": {
    grade: "A",
    kind: "一手论文",
    shortTitle: "Self-RAG",
    title: "Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection",
    note: "按需决定是否检索，并通过反思 token 评价检索证据与自身生成；不表示普通 RAG 自动拥有自检能力。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2310.11511",
  },
  "lost-middle": {
    grade: "A",
    kind: "同行评审期刊论文",
    shortTitle: "Lost in the Middle",
    title: "Lost in the Middle: How Language Models Use Long Contexts",
    note: "在论文的多文档问答与键值检索实验中，相关信息位置显著影响表现；不能据此断言所有模型都相同或 RAG 必然优于长上下文。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2024.tacl-1.9/",
  },
  "contextual-retrieval": {
    grade: "B",
    kind: "厂商实验",
    shortTitle: "Contextual Retrieval",
    title: "Contextual Retrieval",
    note: "特定实验中，混合检索将 top-20 failure rate 从 5.7% 降至 2.9%，加重排后为 1.9%；只适合作为客户 PoC 的验证假设。",
    verifiedAt: "2026-07-17",
    href: "https://www.anthropic.com/engineering/contextual-retrieval",
  },
  ragas: {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "RAGAS",
    title: "RAGAS: Automated Evaluation of Retrieval Augmented Generation",
    note: "提出 Faithfulness、Answer Relevance、Context Relevance 三个无参考答案自动评估维度；不直接给出业务、安全、P95 或成本门槛。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2024.eacl-demo.16/",
  },
  "nist-genai-profile": {
    grade: "O",
    kind: "官方风险管理框架",
    shortTitle: "NIST AI 600-1",
    title: "Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile",
    note: "以 Govern / Map / Measure / Manage 组织生成式 AI 风险治理；它是自愿采用的风险框架，不是产品认证或 RAG 性能标准。",
    verifiedAt: "2026-07-17",
    href: "https://doi.org/10.6028/NIST.AI.600-1",
  },
  "nist-zero-trust": {
    grade: "O",
    kind: "官方特别出版物 / 架构指南",
    shortTitle: "NIST SP 800-207",
    title: "Zero Trust Architecture",
    note: "访问企业资源前验证主体并执行授权，不因网络位置或资产归属给予隐式信任；RAG 中的检索过滤是该原则的工程应用。",
    verifiedAt: "2026-07-17",
    href: "https://csrc.nist.gov/pubs/sp/800/207/final",
  },
  "owasp-prompt-injection": {
    grade: "G",
    kind: "社区安全指南",
    shortTitle: "OWASP LLM01",
    title: "OWASP LLM01:2025 Prompt Injection",
    note: "明确 RAG 与微调都不能完全消除提示注入（Prompt Injection）。",
    verifiedAt: "2026-07-17",
    href: "https://genai.owasp.org/llmrisk/llm01-prompt-injection/",
  },
  "owasp-vector-weaknesses": {
    grade: "G",
    kind: "社区安全指南",
    shortTitle: "OWASP LLM08",
    title: "OWASP LLM08:2025 Vector and Embedding Weaknesses",
    note: "覆盖多租户向量库的跨上下文泄漏、细粒度访问控制、逻辑隔离、来源校验与检索日志。",
    verifiedAt: "2026-07-17",
    href: "https://genai.owasp.org/llmrisk/llm082025-vector-and-embedding-weaknesses/",
  },
  "docling-report": {
    grade: "A",
    kind: "技术报告",
    shortTitle: "Docling",
    title: "Docling Technical Report",
    note: "覆盖 PDF 转换、版面分析与表格结构识别；证明解析工具的结构化能力，不直接证明采用后企业 RAG 准确率必然提升。",
    verifiedAt: "2026-07-17",
    href: "https://research.ibm.com/publications/docling-technical-report",
  },
  "pp-ocr-2020": {
    grade: "A",
    kind: "一手论文",
    shortTitle: "PP-OCR",
    title: "PP-OCR: A Practical Ultra Lightweight OCR System",
    note: "给出文本检测、方向分类和文本识别组成的实用 OCR 系统；证明扫描图像文字识别的技术路线，不保证任意扫描质量或版式都能可靠恢复。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2009.09941",
  },
  "colpali-2025": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "ColPali",
    title: "ColPali: Efficient Document Retrieval with Vision Language Models",
    note: "用视觉语言模型直接为文档页图像生成多向量表示，面向视觉丰富文档检索；论文结果不能直接外推到客户图片、语言和算力条件。",
    verifiedAt: "2026-07-17",
    href: "https://proceedings.iclr.cc/paper_files/paper/2025/hash/99e9e141aafc314f76b0ca3dd66898b3-Abstract-Conference.html",
  },
  "fine-tuning-or-retrieval": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "Fine-Tuning or Retrieval?",
    title: "Fine-Tuning or Retrieval? Comparing Knowledge Injection in LLMs",
    note: "在论文设定下，RAG 对新事实注入优于所比较的无监督微调；不能外推为所有微调都不适合知识更新。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2024.emnlp-main.15/",
  },
};

export const evidenceCards = [
  {
    metric: "2",
    title: "种原始概率形式",
    finding: "原始论文分别给出 RAG-Sequence 与 RAG-Token：前者在完整输出序列层面对候选文档求和，后者在每个 token 生成时求和。",
    boundary: "这是建模方式，不是两种云部署模板，也不是现代 API 型 RAG 的统一实现。",
    sourceId: "rag-original-2020",
  },
  {
    metric: "+9–19 pp",
    title: "Top-20 召回准确率",
    finding: "DPR 在论文所评估的开放域问答数据上，相对其 Lucene-BM25 基线取得这一绝对提升。",
    boundary: "数据集与基线特定；不能据此承诺稠密检索在客户语料上必然优于 BM25。",
    sourceId: "dpr-2020",
  },
  {
    metric: "3",
    title: "个 RAGAS 自动评估维度",
    finding: "Faithfulness、Answer Relevance 与 Context Relevance 分别观察证据使用、回答相关性和检索上下文相关性。",
    boundary: "业务结果、性能、安全和成本是本知识库追加的工程验收面，不是 RAGAS 论文的三项指标。",
    sourceId: "ragas",
  },
  {
    metric: "5.7% → 1.9%",
    title: "Top-20 检索失败率",
    finding: "Anthropic 的特定实验中，contextual dense + BM25 + rerank 达到该结果。",
    boundary: "属于厂商实验；适合提出混合检索 A/B 假设，不能直接写入采购或效果承诺。",
    sourceId: "contextual-retrieval",
    accent: true,
  },
  {
    metric: "Black-box",
    title: "冻结模型的模块化路线",
    finding: "REPLUG 展示了冻结黑盒语言模型、在模型外训练可调检索器并注入检索文档的路线。",
    boundary: "它支持检索与模型可解耦，不直接证明企业权限、回滚或可观测能力。",
    sourceId: "replug-2024",
  },
  {
    metric: "位置敏感",
    title: "长上下文并非稳定利用",
    finding: "论文实验中，相关信息处于上下文中部时，表现往往低于位于开头或结尾。",
    boundary: "结论来自特定模型与任务；它支持做位置偏差基线，不证明 RAG 必然胜出。",
    sourceId: "lost-middle",
  },
];

export const ragQa = [
  {
    q: "上下文窗口已经很长，为什么还需要 RAG？",
    a: "长上下文解决“能装下多少”，检索组件解决“该拿什么”；企业 RAG 架构还必须由数据链和应用控制面解决知识新鲜度、谁能看以及证据来自哪里。语料很小、稳定且可整体装入时，直接长上下文可能更简单。",
    depth: "不能只比较 token 上限，还要比较有效召回、上下文位置偏差、首 token 时延、重复传输成本、权限过滤和更新 SLA。研究在特定多文档问答与键值检索实验中观察到明显的位置敏感性，因此“放得下”不等于“稳定用得好”；是否采用 RAG 仍应由客户基线验证。",
    ask: "追问客户：语料多大、多久变化一次、是否分权限、答案是否必须给出处？",
    tag: "架构判断",
    basis: "论文依据 + 工程边界 + 客户基线",
    evidence: [
      { sourceId: "lost-middle", supports: "支持长上下文利用具有位置敏感性；不支持“RAG 必然更好”。" },
      { sourceId: "rag-original-2020", supports: "支持参数化记忆与外部检索记忆结合这一基本路线。" },
    ],
  },
  {
    q: "RAG 检到了正确文档，为什么仍可能答错？RAG 能消除幻觉吗？",
    a: "不能。RAG 增加了可用证据，但“检索成功”不等于证据进入最终上下文，也不等于模型会忠实使用，更不保证证据本身真实、最新且适用于当前客户。",
    depth: "至少区分四层：候选召回率（Candidate Recall）判断标准证据是否进入候选集；最终上下文覆盖判断证据是否经过过滤与重排后进入 Prompt；忠实度（Faithfulness）判断回答是否受上下文支持；事实正确性（Factual Correctness）判断证据与结论是否符合权威事实。回答可能忠实复述过期文档却仍然错误，也可能碰巧答对但没有可核验证据链。",
    ask: "追问客户：什么是权威来源？冲突版本以谁为准？是否允许拒答？哪些回答必须人工复核？",
    tag: "风险边界",
    basis: "论文指标 + 风险边界",
    evidence: [
      { sourceId: "ragas", supports: "支持把上下文相关性、回答相关性与忠实度分开观察。" },
      { sourceId: "self-rag", supports: "支持检索后仍需评价证据与生成；不表示普通 RAG 自动具备自检能力。" },
      { sourceId: "nist-genai-profile", supports: "支持以持续测量和风险管理补足单一模型指标。" },
    ],
  },
  {
    q: "做 RAG 一定要向量数据库吗？",
    a: "不一定。向量检索擅长语义相似，但精确编号、产品代码、日期、人名与强过滤条件常常更适合关键词、结构化查询或混合检索。向量数据库是候选检索基础设施，不等于完整 RAG。",
    depth: "稳健方案常用 dense + sparse + metadata filter，再对候选结果 rerank。要区分候选召回 Top-K 与最终上下文 K：前者决定召回预算，后者决定模型输入预算。Reranker 只重新排序已召回候选，不能抬高候选集本身的召回上限。小规模场景可先复用现有搜索引擎或数据库扩展。",
    ask: "追问客户：查询更像“找同义内容”还是“查精确事实”？现有搜索与数据库能否复用？",
    tag: "产品选型",
    basis: "检索研究 + 工程选型",
    evidence: [
      { sourceId: "bm25-book", supports: "支持关键词稀疏检索的基本机制。" },
      { sourceId: "dpr-2020", supports: "支持稠密候选检索的能力与数据集边界。" },
      { sourceId: "bert-reranker", supports: "支持候选召回后再做查询—段落精排的二阶段结构。" },
    ],
  },
  {
    q: "为什么系统明明有文档，还是答不到？",
    a: "应先确认正确证据在哪一层丢失：未正确入库、未进入候选集、被权限过滤或重排淘汰、未进入最终上下文，还是模型没有忠实使用。不要一开始就换更大的生成模型。",
    depth: "用带标准答案、证据位置、版本和访问身份的诊断集逐层检查：解析完整率 → Candidate Recall@K → 过滤后召回 → 重排位置 → 最终上下文覆盖 → 回答忠实度。Reranker 无法找回候选集中不存在的证据；只有证据已进入最终上下文而模型仍未正确使用时，升级生成模型才可能直接改善问题。",
    ask: "追问客户：能否提供覆盖主要业务任务与风险等级的一批真实失败问题，并标出正确文档、片段、版本和访问身份？",
    tag: "故障诊断",
    basis: "论文依据 + 分层诊断",
    evidence: [
      { sourceId: "dpr-2020", supports: "支持以候选召回能力单独观察检索阶段。" },
      { sourceId: "bert-reranker", supports: "支持在候选集内精排；不能补回未召回证据。" },
      { sourceId: "ragas", supports: "支持把上下文质量与生成忠实度分开诊断。" },
    ],
  },
  {
    q: "RAG 和微调怎么选？",
    a: "知识频繁更新、需要引用和撤回时，优先建立 RAG 基线；希望模型稳定遵循风格、格式或专门行为时，再评估微调。两者可以组合。",
    depth: "微调把模式写入参数，更新与追溯成本较高；RAG 在运行时注入证据，更便于更新与撤回。研究在特定新事实注入任务中观察到 RAG 优于所比较的无监督微调，但不能推广为“所有微调都不适合知识更新”。先定位剩余误差是事实供给还是回答行为，再决定是否训练。",
    ask: "追问客户：变化的是“事实知识”还是“回答行为”？多久变一次？是否需要逐条来源？",
    tag: "路线选择",
    basis: "任务特定论文 + 工程判断",
    evidence: [
      { sourceId: "fine-tuning-or-retrieval", supports: "支持论文设定中新事实注入的 RAG 对比结果，边界不覆盖所有微调。" },
      { sourceId: "replug-2024", supports: "支持冻结模型、把检索能力放在模型外部的模块化路线。" },
    ],
  },
  {
    q: "不同部门、不同客户的数据权限如何保证？",
    a: "权限必须由应用与检索服务强制执行，不能只写在提示词里。身份、租户、用户组和文档授权要进入候选生成、缓存与审计链路。",
    depth: "索引应保留来源 ACL，或按风险采用逻辑 / 物理隔离；检索时执行 tenant、user、group 过滤；缓存键包含权限上下文；日志脱敏并能追踪命中文档。零信任标准提供“访问资源前认证与授权”的原则，OWASP 则直接指出多租户向量库的跨上下文泄漏风险。高敏场景应把越权泄漏为零设为验收目标，并通过对抗集验证。",
    ask: "追问客户：权限来自哪个主系统？是否有租户级、文档级、行列级隔离和即时撤权要求？",
    tag: "安全",
    basis: "官方原则 + RAG 安全指南",
    evidence: [
      { sourceId: "nist-zero-trust", supports: "支持访问资源前认证与授权；检索过滤是该原则的 RAG 工程应用。" },
      { sourceId: "owasp-vector-weaknesses", supports: "直接支持多租户向量库隔离、细粒度访问控制和检索日志。" },
    ],
  },
  {
    q: "源文档更新后，多久能在回答中生效？",
    a: "这不是模型 SLA，而是数据新鲜度 SLA。应分别计量发现、解析、索引、缓存失效、权限撤销与删除传播，并按业务风险设定目标。",
    depth: "建议观测 source_version、effective_at、indexed_at 与 deletion_at，并按来源风险分级；这些字段不是 NIST 规定。具体分钟、小时或天数也不是行业通用标准，必须由客户业务门槛、目标云服务能力和 PoC 实测共同确定。删除与权限撤销通常比新增更敏感，应单独验证端到端传播时间。",
    ask: "追问客户：哪类数据最敏感？新增、修改、删除和撤权分别要求多快生效？",
    tag: "时效性",
    basis: "治理原则 + 客户 SLA / PoC",
    evidence: [
      { sourceId: "nist-genai-profile", supports: "支持数据来源、生命周期和持续风险管理；不提供通用的分钟级 SLA。" },
    ],
  },
  {
    q: "如何证明 RAG 的效果，而不是做一个漂亮 Demo？",
    a: "不能只报一个“回答正确率”。应冻结同一套真实问题与权威证据，分别验收候选召回、排序与上下文、生成质量、业务结果，以及工程与安全。",
    depth: "候选检索看 Recall@K；排序看 MRR / nDCG 和正确证据是否进入最终上下文；生成看 Faithfulness、引用正确性与拒答正确性；事实层与客户指定的权威答案核对；端到端看任务成功率与人工接受率；工程层看 P95、每个成功回答成本、更新 / 删除 SLA 和越权测试。RAGAS 直接提出的是 3 个自动评估维度，后面的业务与工程指标是交付扩展。",
    ask: "追问客户：谁提供权威答案和证据？哪类错误不可接受？上线门槛按总体平均还是按高风险场景分别设置？",
    tag: "评估",
    basis: "论文指标 + 工程验收扩展",
    evidence: [
      { sourceId: "ragas", supports: "支持 Faithfulness、Answer Relevance、Context Relevance 三项自动评估维度。" },
      { sourceId: "dpr-2020", supports: "支持候选检索阶段独立衡量 top-K passage retrieval accuracy。" },
      { sourceId: "nist-genai-profile", supports: "支持自动评估结合人工评估和持续风险管理。" },
    ],
  },
  {
    q: "PDF、扫描件、表格和图片很多，RAG 还能做好吗？",
    a: "可以，但要把数字 PDF、扫描件和视觉丰富页面视为不同数据类型。PDF 解析、OCR 与视觉文档检索各自解决不同问题，任何一条链路的质量都可能成为最终上限。",
    depth: "纯文本抽取容易打乱双栏顺序、表头、脚注和跨页表格；扫描件还要经过文本检测与识别。应按文档类型路由处理：数字 PDF 保留版面、页级坐标和结构化表格；扫描件验证 OCR 字段完整率；图表、字体或空间关系本身承载事实时，再评估直接为页面图像建立多向量表示的视觉检索。三类研究只证明对应技术可行，最终问答质量必须用客户文档、语言和算力条件实测。",
    ask: "追问客户：各类文档占比和扫描质量如何？正确答案依赖图表、表格还是正文？",
    tag: "数据工程",
    basis: "解析 / OCR / 视觉检索研究 + 客户文档 PoC",
    evidence: [
      { sourceId: "docling-report", supports: "支持 PDF 转换、版面分析与表格结构识别；不保证下游 RAG 准确率。" },
      { sourceId: "pp-ocr-2020", supports: "支持文本检测、方向分类与文字识别组成的 OCR 路线；不保证任意扫描质量。" },
      { sourceId: "colpali-2025", supports: "支持直接从文档页图像建立多向量视觉检索；效果需按客户数据复测。" },
    ],
  },
  {
    q: "怎样控制延迟和成本？",
    a: "先缩短无效链路，再缩小模型。应把解析与索引、候选召回、重排、最终上下文、生成 token 和峰值容量分别计量。",
    depth: "独立调整候选召回数量、重排数量和最终上下文数量，不要用一个 Top-K 同时代表三个阶段。可用查询分类跳过无关检索、缓存稳定结果、轻量模型做路由、只对高价值候选重排并压缩上下文。厂商实验只能说明组合策略值得 A/B，不能给出客户 P95 或成本承诺；应报告 PoC 中每个成功回答成本，并结合当期云价。",
    ask: "追问客户：并发、P95、峰值系数、平均文档长度、成功问答量和当期云价基准是什么？",
    tag: "FinOps",
    basis: "相关研究 + 工程判断；数值来自客户 PoC",
    evidence: [
      { sourceId: "contextual-retrieval", supports: "支持在特定实验中对混合检索与重排做质量 A/B；不提供通用成本或延迟阈值。" },
      { sourceId: "fid-2021", supports: "支持多段证据聚合可带来任务收益，同时提醒 passage 数量结论具有任务边界。" },
    ],
  },
  {
    q: "开源模型还是商业模型更适合？",
    a: "不能只按“开源 / 商业”标签作结论。应先冻结同一语料、问题集、安全边界和负载，再逐个候选比较质量、吞吐、可部署地域、运维责任、合规、锁定与三年 TCO。",
    depth: "RAG 可以让知识供给与生成模型相对解耦，但提示、分词、上下文和工具调用仍需适配。商业 API 是否更快交付、自托管是否更可控，都只是待验证假设，不能脱离具体产品与团队能力预判。有效证据必须包含候选服务的当期官方能力 / 地域 / 计价资料、客户负载 PoC，以及人力、容量、升级和安全运营测算；REPLUG 只支持模块化组合，不支持 TCO 结论。",
    ask: "追问客户：数据能否出域？团队是否具备 GPU / 推理运维能力？负载是否稳定？",
    tag: "模型格局",
    basis: "架构论文 + 当期报价 / PoC",
    evidence: [
      { sourceId: "replug-2024", supports: "支持冻结黑盒模型与外部检索器的模块化组合；不提供企业三年 TCO。" },
    ],
  },
  {
    q: "RAG 系统会不会被文档里的恶意指令攻击？",
    a: "会。检索内容是不可信数据，不能把它当系统指令；RAG 与微调都不能天然消除提示注入（Prompt Injection）。",
    depth: "控制包括来源白名单、入库扫描与签名、指令与证据分区、最小权限工具调用、输出校验、敏感动作二次确认、异常检索监控和红队测试。向量与嵌入层还要防数据投毒、跨租户泄漏和来源混淆。对于能执行动作的 Agent，知识检索与工具授权必须采用不同信任域。",
    ask: "追问客户：系统只回答，还是还能发邮件、下单、改配置？知识源是否允许外部写入？",
    tag: "安全",
    basis: "社区安全指南",
    evidence: [
      { sourceId: "owasp-prompt-injection", supports: "直接支持 RAG 与微调不能完全消除提示注入。" },
      { sourceId: "owasp-vector-weaknesses", supports: "支持向量库的数据投毒、访问控制与跨上下文泄漏风险。" },
    ],
  },
  {
    q: "RAG-Sequence 和 RAG-Token 是两种部署架构吗？",
    a: "不是。它们是 2020 年原始 RAG 论文中两种对检索文档进行概率边缘化的建模方式，不是两种云部署模板或产品形态。",
    depth: "RAG-Sequence 假设整段输出共享同一个潜在文档，并在完整输出序列层面对 Top-K 文档求和；RAG-Token 在每个生成 token 时分别对候选文档求和，因此不同 token 可以依赖不同文档。今天常见的“检索片段—组装上下文—调用模型 API”通常不会显式计算这两种边缘概率，不能简单贴成其中一种。",
    ask: "追问客户：讨论的是论文模型，还是实际的检索、重排、上下文组装和模型调用架构？",
    tag: "原理辨析",
    basis: "原始论文定义",
    evidence: [
      { sourceId: "rag-original-2020", supports: "直接定义 RAG-Sequence 与 RAG-Token 的概率边缘化形式。" },
    ],
  },
  {
    q: "企业做 RAG，必须把检索器和生成模型端到端联合训练吗？",
    a: "不必。多数企业项目可以先组合独立的 Embedding、搜索、Reranker 和冻结的模型服务建立可评估基线；只有明确证实通用组件无法满足领域要求时，再评估训练。",
    depth: "原始 RAG 论文联合优化查询编码器与 BART 生成器，但保持文档编码器和索引固定，这是特定研究模型设计，不是企业交付要求。模块化架构允许检索、重排和生成分别升级与计费；REPLUG 也展示了冻结黑盒语言模型、在模型外优化检索器的路线。端到端训练会增加样本、索引刷新、回归和版本耦合成本。",
    ask: "追问客户：使用不可训练的模型 API 还是自托管模型？是否有查询—证据—答案样本？失败主要在检索还是生成？",
    tag: "训练策略",
    basis: "原始论文 + 模块化研究",
    evidence: [
      { sourceId: "rag-original-2020", supports: "支持原始模型的训练范围以及固定文档编码器和索引的设计。" },
      { sourceId: "replug-2024", supports: "支持冻结黑盒语言模型、在模型外优化检索器的路线。" },
    ],
  },
  {
    q: "Top-K 是不是越大越好？已经有向量检索为什么还需要 Reranker？",
    a: "不是。候选 Top-K 是召回预算，最终上下文 K 是模型输入预算；增大候选集可能提高召回，也会增加时延和噪声。Reranker 用更精细的查询—文档联合判断重新排序，但不能找回未被召回的文档。",
    depth: "第一阶段的稀疏或稠密检索追求高吞吐和尽量不漏，第二阶段 Reranker 在较小候选集上提高排序精度，最后只把经过权限、版本、去重和冲突处理的证据放入上下文。应分别观测 Candidate Recall@K、重排后的 MRR / nDCG、最终上下文证据覆盖率、额外延迟和 token 成本；Top-K 没有跨语料通用的最佳数字。",
    ask: "追问客户：正确证据是候选阶段没找到，还是进入候选后没有排进最终上下文？可接受多少重排延迟？",
    tag: "检索调优",
    basis: "检索与重排论文 + 客户 PoC",
    evidence: [
      { sourceId: "dpr-2020", supports: "支持候选检索阶段以 top-K passage retrieval accuracy 衡量召回。" },
      { sourceId: "bert-reranker", supports: "支持候选召回后使用更精细模型重排；无法补回候选集外证据。" },
      { sourceId: "fid-2021", supports: "支持多 passage 聚合在特定任务中的作用，同时表明数量结论不能跨任务照搬。" },
    ],
  },
];
