/**
 * RAG 问答与证据卡的内容源。
 *
 * 来源标题、链接、证据类型和核验日期统一维护在
 * app/reference-content.mjs；此文件仅保存对应的 sourceId。
 */
export const ragDeepDives = [
  {
    kind: "sequence",
    eyebrow: "OFFLINE EVIDENCE CONTRACT",
    title: "一份文档什么时候才算 RAG 可用",
    intro: "数据工程负责接入、解析、清洗、去重和变更传播；RAG 不复制这条资料处理流程，而是在交接处验收：每个证据单元是否能被找到、回到原文、判断有效范围，并在删除或撤权后退出回答。",
    items: [
      { name: "接收权威资料快照", en: "Receive an Authoritative Snapshot", mechanism: "从资料处理流程接收稳定来源 ID、原始版本、生效范围、负责人、许可状态和访问规则，并记录加工版本。", decision: "缺少权威来源、版本或使用边界的资料不进入正式回答索引。", boundary: "RAG 的证据交接检查不能替代源系统的数据治理和内容审批。" },
      { name: "形成证据对象", en: "Build Evidence Objects", mechanism: "让每个可检索单元携带原文坐标、父子关系、版本、有效期、ACL 与抽取方式，回答时能稳定回跳。", decision: "先定义最小证据对象，再比较解析器、切片器和索引产品。", boundary: "只有文本和向量、没有来源坐标与版本，不足以形成可审计证据。" },
      { name: "选择切片与表示", en: "Choose Units and Representations", mechanism: "按条款、标题、表格或其他业务结构形成可独立理解的单元，并分别建立关键词、向量或结构化表示。", decision: "用真实问题比较召回、噪声、引用定位和上下文成本，不照搬通用 Chunk 数字。", boundary: "切片不能修复源文档冲突、错误 OCR 或缺失权限。" },
      { name: "发布可过滤候选", en: "Publish Filterable Candidates", mechanism: "把租户、身份、地区、产品版本和生效日期保留为确定性过滤字段，再发布到候选检索路径。", decision: "先证明过滤前后的正确证据仍可召回，同时越权证据不可见。", boundary: "自然语言 Prompt 不能替代检索层的权限与版本过滤。" },
      { name: "通过离线证据检查", en: "Pass the Offline Gate", mechanism: "用带标准证据、原文位置、版本和访问身份的问题，检查解析完整性、Candidate Recall@K、引用回跳和负向样本。", decision: "只有标准证据可被授权身份稳定找到、禁用身份稳定找不到时，资料才进入在线回答链。", boundary: "作业成功、文档数相符或向量写入完成都不是 RAG 就绪证明。" },
    ],
    sourceIds: ["docling-report", "rag-survey", "azure-search-indexer-lifecycle", "nist-zero-trust"],
  },
  {
    kind: "sequence",
    eyebrow: "OFFLINE CONSISTENCY",
    title: "知识变化只有传播到最终回答，才算在 RAG 中生效",
    intro: "数据工程负责可靠传播新增、修改、删除和 ACL 事件；RAG 负责验证自己的索引、摘要、缓存和最终回答已经切换。绿色作业状态不是端到端一致性证据。",
    items: [
      { name: "区分四类变化", en: "Separate Four Change Types", mechanism: "用稳定事件身份区分新增、修改、删除与 ACL 变化，并携带 source_version、effective_at 和 acl_version。", decision: "四类变化分别设置时限、失败队列和责任人，删除与撤权采用更严格的负向门。", boundary: "内容更新时间不能完整表达业务生效时间和权限变化。" },
      { name: "重建版本化产物", en: "Rebuild Versioned Artifacts", mechanism: "解析、切片、Embedding 和索引绑定同一发布版本，失败时隔离半成品并保留可服务的旧版本。", decision: "每次变化后抽样比较正文、坐标、候选结果、权限和版本。", boundary: "重新运行或 Reset 不一定会清除源端已经不存在的孤儿文档。" },
      { name: "失效所有派生副本", en: "Invalidate Derived Copies", mechanism: "通过 Tombstone 或显式删除清理稀疏与向量索引、摘要、检索缓存、答案缓存和权限快照。", decision: "先列出系统实际持有的副本，再为每一层定义删除与撤权证明。", boundary: "只删除源文件或主索引，会让其他副本继续返回旧内容。" },
      { name: "验证在线链已切换", en: "Verify the Online Chain", mechanism: "用真实身份查询已新增、替换、删除和撤权样本，检查候选、最终上下文、引用与回答。", decision: "把数据变化 SLA 的终点设为用户实际得到的结果，而不是同步任务状态。", boundary: "缓存命中或降级路径也必须重新执行当前权限与版本检查。" },
      { name: "持续运行一致性探针", en: "Run Consistency Probes", mechanism: "保留少量可控的正向与负向样本，持续观察传播时延、孤儿证据和旧回答复现。", decision: "超时后阻止相关回答、转人工并把故障交给数据工程或 AI Ops 处理。", boundary: "探针和 Trace 也包含身份与文档信息，必须遵守安全模块定义的访问与保留策略。" },
    ],
    sourceIds: ["aws-bedrock-kb-sync", "azure-search-indexer-lifecycle", "nist-zero-trust"],
  },
  {
    kind: "sequence",
    eyebrow: "ONLINE ANSWER POLICY",
    title: "这次请求应该回答、追问还是停下",
    intro: "在线链的起点不是把一句话直接向量化。系统要恢复当前问题、确认必要条件、执行有预算的检索，并在追问、继续检索、限定回答和拒答之间做出可解释选择。",
    items: [
      { name: "恢复当前问题", en: "Resolve the Current Turn", mechanism: "保留用户原话，并把必要的会话指代改写成可独立检索的问题；身份、时间和业务约束每轮重新取得。", decision: "只有指代或关键条件不清时追问，不让历史回答替用户补造事实。", boundary: "会话摘要不是权威证据，也不能继承上一轮的授权结论。" },
      { name: "判断是否需要检索", en: "Decide Whether to Retrieve", mechanism: "区分精确查找、语义解释、跨源归纳、结构化查询、无需外部知识和禁止自动回答的请求。", decision: "没有检索增益的请求直接回答或转确定性系统，高风险且缺少条件的请求先追问。", boundary: "所有问题都走同一向量检索会增加噪声、时延和权限面。" },
      { name: "执行硬过滤与路由", en: "Filter and Route", mechanism: "把租户、地区、产品版本、有效日期、文档类型和当前身份变成确定性过滤，再选择关键词、向量、SQL、图谱或 API。", decision: "先建立最简单路线的基线，再用失败样本证明混合或复杂路由的价值。", boundary: "模型生成的查询计划不能修改授权或业务硬条件。" },
      { name: "按预算扩展检索", en: "Expand Within a Budget", mechanism: "只有候选不足且问题确实复杂时，才使用改写、子查询、HyDE 或第二数据源，并记录每一步新增证据。", decision: "没有增量证据或达到时延、成本与轮次上限时立即停止。", boundary: "生成的假设文档和查询改写只能帮助找证据，本身不能成为回答依据。" },
      { name: "选择回答动作", en: "Choose the Answer Action", mechanism: "完整证据支持则回答；只支持部分范围则限定回答；条件缺失则追问；证据不足、冲突、过期、越权或风险过高则拒答或转人工。", decision: "把回答动作与触发原因写入 Trace，并对不同风险等级设置不同门槛。", boundary: "让模型自由决定何时拒答不能替代应用规则、证据门和人工责任。" },
    ],
    sourceIds: ["rag-survey", "self-rag", "azure-search-query-rewrite", "aws-bedrock-query-decomposition", "nist-zero-trust"],
  },
  {
    kind: "matrix",
    eyebrow: "ONLINE EVIDENCE COMPILER",
    title: "把 Top-K 整理成可以逐条核对的回答",
    intro: "RAG 的在线责任是把当前用户可访问、当前有效的候选证据组装成有限上下文，并让每项重要主张都能回到原始证据。",
    columnLabels: { name: "编排对象", mechanism: "工作机制", decision: "验收问题", boundary: "失效方式" },
    items: [
      { name: "候选集合", en: "Candidate Set", mechanism: "分别保留每条检索路线的候选、分数、过滤原因与增量命中，再去重和重排。", decision: "标准证据是没有被找到，还是找到后排位过低？", boundary: "Reranker 只能重排已有候选，不能找回候选集外的证据。" },
      { name: "有效证据对象", en: "Valid Evidence Objects", mechanism: "进入上下文前再次检查来源、原文坐标、版本、有效期、ACL 和权威等级。", decision: "当前身份现在是否有权使用该版本回答这个问题？", boundary: "相关片段可能已经过期、越权或不适用于当前地区与产品版本。" },
      { name: "冲突集合", en: "Conflict Set", mechanism: "将同一主题的不同版本、地区或条款显式分组，按适用范围选择、并列说明或停止回答。", decision: "客户是否定义权威来源、冲突规则与责任人？", boundary: "把冲突片段一起交给模型，会把业务裁决交给随机生成。" },
      { name: "主张绑定", en: "Claim Attribution", mechanism: "把回答拆成可核验主张，逐项绑定直接支持的证据，并分别检查引用正确性与覆盖完整性。", decision: "关键数字、期限、条件和结论是否各有直接支持？", boundary: "一个相关链接不能证明整段回答，也不能替代未被引用的关键主张。" },
      { name: "有据生成", en: "Grounded Generation", mechanism: "只基于已编排证据生成允许范围内的答案，同时返回来源、适用条件、不确定性和拒答原因。", decision: "答案是否忠实使用证据，并遵守前一步选定的回答动作？", boundary: "生成后再补链接是事后装饰，不是可审计的证据链。" },
    ],
    sourceIds: ["dpr-2020", "bert-reranker", "alce-2023", "ragas", "nist-genai-profile"],
  },
];

export const evidenceCards = [
  {
    metric: "+9–19 pp",
    title: "Top-20 召回准确率",
    finding: "DPR 在论文所评估的开放域问答数据上，相对其 Lucene-BM25 基线取得这一绝对提升。",
    boundary: "数据集与基线特定；不能据此承诺稠密检索在客户语料上必然优于 BM25。",
    sourceId: "dpr-2020",
  },
  {
    metric: "3",
    title: "个 RAGAS 自动评估维度",
    finding: "Faithfulness、Answer Relevance 与 Context Relevance 分别观察证据使用、回答相关性和检索上下文相关性。",
    boundary: "业务结果、性能、安全和成本是本知识库追加的工程验收面，不是 RAGAS 论文的三项指标。",
    sourceId: "ragas",
  },
  {
    metric: "5.7% → 1.9%",
    title: "Top-20 检索失败率",
    finding: "Anthropic 的特定实验中，contextual dense + BM25 + rerank 达到该结果。",
    boundary: "属于厂商实验；适合提出混合检索 A/B 假设，不能直接写入采购或效果承诺。",
    sourceId: "contextual-retrieval",
    accent: true,
  },
  {
    metric: "Black-box",
    title: "冻结模型的模块化路线",
    finding: "REPLUG 展示了冻结黑盒语言模型、在模型外训练可调检索器并注入检索文档的路线。",
    boundary: "它支持检索与模型可解耦，不直接证明企业权限、回滚或可观测能力。",
    sourceId: "replug-2024",
  },
  {
    metric: "位置敏感",
    title: "长上下文并非稳定利用",
    finding: "论文实验中，相关信息处于上下文中部时，表现往往低于位于开头或结尾。",
    boundary: "结论来自特定模型与任务；它支持做位置偏差基线，不证明 RAG 必然胜出。",
    sourceId: "lost-middle",
  },
  {
    metric: "主张级",
    title: "引用要检查正确性与完整性",
    finding: "ALCE 将引用是否真正支持对应主张，以及关键主张是否都获得引用，作为不同评估问题。",
    boundary: "论文评测方法支持拆分引用质量；不能把论文数据直接外推为客户系统准确率。",
    sourceId: "alce-2023",
  },
  {
    metric: "删除 ≠ 重置",
    title: "知识时效是端到端状态",
    finding: "Azure 官方文档明确指出 Reset / Run 不会自动清理没有源端对应物的孤儿文档，ACL 变化也可能绕过普通高水位检测。",
    boundary: "这是特定产品的实现边界；它支持设计删除与撤权验收，不代表其他产品机制相同。",
    sourceId: "azure-search-indexer-lifecycle",
  },
];

const freezeLearningItems = (items) => Object.freeze(items.map((item) => Object.freeze(item)));
const freezeLearningLabs = (items) => freezeLearningItems(items.map((item) => ({
  ...item,
  tasks: Object.freeze(item.tasks),
  sourceIds: Object.freeze(item.sourceIds),
})));

export const ragLearningContent = Object.freeze({
  outcomes: Object.freeze([
    "判断一个业务问题是否需要 RAG，并写清有据回答、限定回答与拒答的边界",
    "交给 RAG 的资料是否能检索、定位、授权、更新和撤回",
    "用真实问题选择切片、关键词、Embedding、Reranker 与生成模型，而不是按产品类别堆组件",
    "沿候选召回、最终上下文和主张引用定位失败，并留下足以复现的 RAG Trace",
    "用质量、风险、时延和单位达标回答成本决定 PoC 是上线、整改还是停止",
  ]),
  route: freezeLearningItems([
    { title: "明确采用边界", learn: "从业务结果、现有搜索基线、知识变化、权限和引用要求判断是否需要 RAG。", checkpoint: "能说明何时使用长上下文、搜索、结构化查询、微调或普通应用逻辑更简单。" },
    { title: "建立离线证据交接", learn: "验收权威来源、原文坐标、版本、有效期、ACL、稳定 ID 和删除路径。", checkpoint: "任一证据单元都能被授权身份找到、回到原文，并在撤权后消失。" },
    { title: "建立检索与模型基线", learn: "在同一问题集上比较切片、稀疏、稠密、混合、重排和生成组合。", checkpoint: "每个新增组件都有对应失败样本、增量指标和时延预算。" },
    { title: "设计在线回答决策", learn: "把问题恢复、硬过滤、检索预算、冲突处理和回答动作连接成一条可解释路径。", checkpoint: "能明确系统何时追问、继续检索、限定回答、拒答或转人工。" },
    { title: "完成 RAG 局部验收", learn: "分别检查候选召回、最终上下文、忠实度、主张引用、越权负例和更新撤回。", checkpoint: "能把失败定位给资料处理、检索、证据编排或生成环节，不用一个总分掩盖问题。" },
    { title: "形成生产交接决定", learn: "把 RAG Trace、质量切片、P95、单位达标回答成本和停止条件交给安全、评估、AI Ops 与场景负责人。", checkpoint: "PoC 结论包含上线、整改或停止决定，以及跨模块负责人和未验证假设。" },
  ]),
  labs: freezeLearningLabs([
    {
      title: "完成一次 RAG 数据就绪审阅",
      scenario: "企业售前资料来自门户、PDF、扫描件和权限系统，团队只知道同步作业已经成功。",
      tasks: [
        "抽样确认权威来源、版本、生效范围、许可、负责人和 ACL",
        "检查正文、表格、页码坐标、稳定文档 ID、Chunk ID 与父子关系",
        "用标准问题和已撤权身份验证召回、回到原文、更新和权限控制",
      ],
      deliverable: "RAG 证据交接清单、问题样本与阻塞项报告",
      acceptance: "每个通过项都有原文、版本、身份和查询证据；解析或治理缺口明确退回数据工程或安全负责人。",
      sourceIds: ["docling-report", "azure-search-indexer-lifecycle", "nist-zero-trust"],
    },
    {
      title: "比较四条检索路线",
      scenario: "同一知识库同时包含产品编号、自然语言问法和长条款，团队准备默认采用向量检索。",
      tasks: [
        "冻结带标准证据的问题集，并按精确、语义和复合条件切片",
        "分别运行 BM25、稠密、混合以及混合加 Reranker 的候选检索",
        "比较 Candidate Recall@K、最终证据覆盖、P95 和每条路线的增量价值",
      ],
      deliverable: "按问题类型拆分的检索实验表与推荐路由",
      acceptance: "路线选择由失败分布和增量证据支持；Reranker 不被用于掩盖候选召回不足。",
      sourceIds: ["bm25-book", "beir-2021", "mteb-2023", "rrf-2009", "bert-reranker"],
    },
    {
      title: "演练高风险回答并还原 Trace",
      scenario: "系统可能检索到恶意指令、旧版本、冲突条款或当前用户无权查看的文档。",
      tasks: [
        "建立越权、过期、冲突、无答案和间接提示注入样本",
        "记录查询计划、候选、过滤、重排、最终上下文、来源版本和回答动作",
        "逐项检查关键主张、引用支持、限定回答、拒答和转人工结果",
      ],
      deliverable: "RAG 风险用例集、一次完整 Trace 与责任归因报告",
      acceptance: "任何回答都能还原使用了哪些有效证据；越权内容不进入候选，证据不足不会被流畅生成掩盖。",
      sourceIds: ["owasp-prompt-injection", "owasp-vector-weaknesses", "alce-2023", "opentelemetry-genai-semconv"],
    },
    {
      title: "把 RAG PoC 结论写成经济决定",
      scenario: "Demo 看起来不错，但客户不知道它相对现有搜索或人工流程是否值得上线。",
      tasks: [
        "冻结现有流程的完成时间、成功率、人工投入和风险基线",
        "在相同任务上报告检索、回答、引用、拒答、P95 和高风险切片",
        "核算离线处理、在线检索生成、失败重试和人工接管，形成上线、整改和停止条件",
      ],
      deliverable: "RAG PoC 决策包与待交接的 ROI 假设清单",
      acceptance: "结论使用单位达标回答成本并显式保留质量与风险门；完整 ROI 交给场景与 FinOps 负责人复核。",
      sourceIds: ["ragas", "alce-2023", "nist-genai-profile", "finops-unit-economics", "opentelemetry-genai-semconv"],
    },
  ]),
});

export const ragQa = Object.freeze([
  {
    q: "上下文窗口已经很长，为什么还需要 RAG？",
    a: "长上下文解决“本次能放多少”，RAG 解决“从持续变化、带权限的资料中拿出哪些当前证据”。语料很小、稳定、权限一致且可整体装入时，直接长上下文通常更简单。",
    depth: "比较路线时不能只看 token 上限。还要测标准证据是否被选中、上下文位置偏差、首 token 时延、重复传输成本、权限过滤、引用定位和更新撤回。研究在特定多文档问答与键值检索实验中观察到位置敏感性；它支持建立客户基线，不证明 RAG 对所有任务都更好。",
    ask: "语料多大、多久变化、是否分权限、答案是否必须给出处，现有长上下文或搜索在哪些真实任务上失败？",
    tag: "方案判断",
    basis: "论文依据 + 工程边界 + 客户基线",
    evidence: [
      { sourceId: "lost-middle", supports: "支持长上下文利用具有位置敏感性；不支持“RAG 必然更好”。" },
      { sourceId: "rag-original-2020", supports: "支持参数化记忆与外部检索记忆结合这一基本路线。" },
    ],
  },
  {
    q: "RAG 和微调怎么选？",
    a: "知识频繁变化、需要引用和撤回时，先建立 RAG 基线；希望模型稳定改变格式、风格或专门行为时，再评估微调。两者解决的问题不同，也可以组合。",
    depth: "微调把模式写入参数，更新和逐条追溯成本较高；RAG 在运行时提供外部证据，更便于替换与撤回。研究只在特定新事实注入任务中观察到 RAG 优于所比较的无监督微调，不能推广成“微调不适合知识任务”。应先把误差定位为事实供给还是回答行为，再决定是否训练。",
    ask: "变化的是事实知识还是回答行为，变化频率多高，是否需要逐条来源与快速撤回？",
    tag: "方案判断",
    basis: "任务特定论文 + 工程判断",
    evidence: [
      { sourceId: "fine-tuning-or-retrieval", supports: "支持论文设定中新事实注入的 RAG 对比结果，边界不覆盖所有微调。" },
      { sourceId: "replug-2024", supports: "支持冻结模型、把检索能力放在模型外部的模块化路线。" },
    ],
  },
  {
    q: "做 RAG 一定要向量数据库吗？",
    a: "不一定。精确编号、专名和日期可以先用 BM25 或结构化查询，语义表达差异大时再验证向量检索，两类失败都存在时才比较混合检索。现有搜索或数据库达到门槛时，可以直接复用。",
    depth: "向量数据库只负责部分候选检索，不等于完整 RAG。选型要同时看过滤、更新删除、权限、索引版本、备份和运维，而不是只看相似度接口。使用 HNSW 等近似索引时，也应先建立 Recall@K、P95 和内存基线，再针对真实瓶颈调参。",
    ask: "问题更像找同义内容、查精确事实还是带条件查询，现有搜索和数据库在哪类真实问题上已经失败？",
    tag: "方案判断",
    basis: "检索研究 + 基础设施选型",
    evidence: [
      { sourceId: "bm25-book", supports: "支持关键词稀疏检索的基本机制。" },
      { sourceId: "beir-2021", supports: "支持在异构检索任务中保留 BM25 强基线并比较效果与计算成本；不替代客户语料验收。" },
      { sourceId: "hnsw-2016", supports: "支持近似向量搜索在召回、速度和结构成本之间取舍。" },
    ],
  },
  {
    q: "RAG 应该选择托管云服务，还是自己拼搜索、向量库和编排？",
    a: "先写能力与责任合同，再比较交付速度、数据边界、差异化需求和团队能力。托管服务减少部分建设工作，但不会自动接管客户的数据治理、权限验收和答案责任；自建获得更多控制，也承担更多升级与恢复工作。",
    depth: "能力合同至少覆盖数据连接、删除撤权、解析、稀疏与向量检索、过滤、重排、身份、网络、模型替换、Trace、配额、地域、SLA、备份和计价。具体产品能力必须按当期官方资料核验。RAG 模块只判断检索、证据编排和有据回答是否满足；供应、运营和完整 TCO 分别交给平台、AI Ops 与场景负责人。",
    ask: "哪些环节必须自定义，团队愿意长期承担哪些责任，目标地域、网络、权限和删除要求是否被候选服务覆盖？",
    tag: "方案判断",
    basis: "官方产品机制样本 + 责任边界分析",
    evidence: [
      { sourceId: "aws-bedrock-kb-sync", supports: "支持托管知识库提供数据源同步机制；不支持其覆盖所有连接器和治理需求。" },
      { sourceId: "azure-search-document-acl", supports: "支持特定托管搜索服务的文档级权限能力；阶段、地域与限制需当前核验。" },
      { sourceId: "azure-search-index-alias", supports: "支持特定托管搜索服务通过索引别名切换；不代表所有服务都有同等能力。" },
      { sourceId: "nist-genai-profile", supports: "支持明确供应链与风险责任，不能把托管等同于风险转移。" },
    ],
  },
  {
    q: "一个企业 RAG 是否还需要 Agent、MCP 或 A2A？",
    a: "通常不需要。只读知识问答可以由确定性应用直接执行检索、证据编排和回答。只有确实需要多步选源与循环检索时才增加 Agent；需要用标准协议暴露资源或工具时才考虑 MCP；独立 Agent 之间要委派持久任务并交付产物时才考虑 A2A。",
    depth: "Agent、MCP 和 A2A 分别改变运行控制、能力连接和跨 Agent 协作边界，不会自动提高资料质量、候选召回或引用正确性。采用前先用普通 RAG 记录无法解决的任务切片，再分别增加预算、权限、停止条件、协议版本和任务状态验收。一个应用内部固定调用搜索 API，不必为了“架构完整”引入三者。",
    ask: "普通一次检索为什么不够，需要的是自适应多步规划、标准化能力接入，还是跨系统 Agent 的持久任务协作？",
    tag: "方案判断",
    basis: "模块化 RAG + Agent 采用边界 + 官方协议模型",
    evidence: [
      { sourceId: "rag-survey", supports: "支持按问题需要采用 Advanced 或 Modular RAG，不支持把复杂度当作统一升级。" },
      { sourceId: "anthropic-effective-agents", supports: "支持从最简单可行方案开始，并区分预定义工作流与动态 Agent。" },
      { sourceId: "mcp-architecture", supports: "支持 MCP 的 Host、Client、Server 与能力交换边界；不表示每个 RAG 都需要协议。" },
      { sourceId: "a2a-concepts", supports: "支持独立 Agent 之间以任务、消息和产物协作；不适用于普通单次检索。" },
    ],
    addedAt: "2026-07-29",
  },
  {
    q: "PDF、扫描件、表格和图片很多，RAG 还能做好吗？",
    a: "可以，但必须按证据主要来自文字、结构还是像素来分流。数字 PDF 和固定字段优先保留版面与结构；扫描件需要 OCR；图表、布局或视觉关系承载答案时，再比较页面级视觉检索或两路融合。",
    depth: "数据工程负责解析、清洗和质量修复，RAG 在交接处验收标准证据能否从原页进入候选、引用能否回到页码或区域。纯文本抽取可能打乱双栏、表头、脚注和跨页表格；视觉页面表示保留版面，却增加索引、算力和精确定位难度。应按文档类型和语言分别报告证据召回、定位、P95 与成本。",
    ask: "各类文档占比如何，正确答案依赖文字、表格单元、图表趋势还是空间关系，引用需要精确到什么位置？",
    tag: "离线证据",
    basis: "解析、OCR 与视觉检索研究 + RAG 证据交接验收",
    evidence: [
      { sourceId: "docling-report", supports: "支持 PDF 转换、版面分析与表格结构识别；不保证下游 RAG 准确率。" },
      { sourceId: "pp-ocr-2020", supports: "支持文本检测、方向分类与文字识别组成的 OCR 路线；不保证任意扫描质量。" },
      { sourceId: "colpali-2025", supports: "支持直接从文档页图像建立多向量视觉检索；客户效果和成本仍需实测。" },
    ],
  },
  {
    q: "Chunk 大小和重叠比例应该设多少？",
    a: "没有跨语料通用的最佳数字。Chunk 应尽量能独立理解，且可定位、授权和撤回，再用客户问题比较不同策略的召回、噪声、上下文成本与引用定位。",
    depth: "块太小会拆断条件、表头和上下文，块太大会稀释主题并挤占窗口。可从标题、条款、表格或代码结构切分建立基线，再按失败样本评估父子块、邻接扩展或语义切分。重叠只能缓解边界断裂，也会增加索引体积与重复候选；任何研究参数都不能直接搬到不同语料。",
    ask: "答案通常落在一句、一个条款、一张表还是跨多个章节，是否必须回到精确页码和原文位置？",
    tag: "离线证据",
    basis: "任务特定研究 + 客户语料实验",
    evidence: [
      { sourceId: "chunking-study", supports: "支持切块方式会影响特定代码 RAG 任务表现，并明确参数结论具有任务边界。" },
      { sourceId: "rag-survey", supports: "支持把切块和检索前处理视为可独立设计环节。" },
      { sourceId: "lost-middle", supports: "支持长上下文对证据位置敏感；不支持简单扩大 Chunk 就能稳定改善答案。" },
    ],
  },
  {
    q: "为什么 Chunk 还要保存父子关系、页码、版本和元数据？",
    a: "因为检索命中的是片段，客户要核验的是原始业务证据。稳定文档与 Chunk ID、原文坐标、版本、有效期、ACL 和父子关系决定系统能否扩展上下文、正确引用、更新撤回和审计。",
    depth: "父子关系允许用小块召回、用完整父块回答；页码和区域支持回跳；版本与有效期避免新旧条款混用；ACL 决定当前身份能否使用；稳定 ID 让增量更新和双版本比较可以一一对应。这些字段应由权威源和确定性处理产生，模型不能临时猜测。",
    ask: "现有内容系统是否有稳定文档 ID、版本、生效日期、负责人和 ACL，引用要精确到文档、页还是表格单元？",
    tag: "离线证据",
    basis: "文档结构 + 生命周期与风险治理",
    evidence: [
      { sourceId: "docling-report", supports: "支持在文档转换中保留版面、结构与表格信息，为原文定位提供基础。" },
      { sourceId: "azure-search-indexer-lifecycle", supports: "支持索引内容具有独立生命周期，重置和运行不能替代更新与删除设计。" },
      { sourceId: "nist-genai-profile", supports: "支持治理数据来源、有效性与生命周期；具体元数据字段是工程实现。" },
    ],
  },
  {
    q: "数据库里的指标和交易数据，能不能直接切块后放进向量库？",
    a: "通常不应。需要精确计算、过滤、聚合和实时口径的数据，应通过受控 SQL、语义层或业务 API 查询；向量检索适合寻找指标定义、说明文档和候选实体。",
    depth: "RAG 在线链可以按问题把查文和查数分流：检索识别指标、口径与证据，确定性查询负责权限、时间范围、聚合和数值结果，模型只组织有据解释。把交易表切成文本块容易形成过期快照、错误聚合和行列权限缺口。结构化查询的安全、资源和语义层由数据与安全模块负责，RAG 只验收返回结果能否作为当前证据使用。",
    ask: "问题是在查定义还是算数，权威口径在哪里，是否有语义层、行列权限、审计和只读查询环境？",
    tag: "离线证据",
    basis: "模块化 RAG + 数据与风险治理",
    evidence: [
      { sourceId: "rag-survey", supports: "支持 Modular RAG 按任务路由不同检索与增强组件；不支持把所有数据统一向量化。" },
      { sourceId: "nist-genai-profile", supports: "支持治理数据有效性、访问风险和系统输出；具体 SQL 控制是工程扩展。" },
      { sourceId: "alce-2023", supports: "支持重要结论需要可核验证据；结构化结果仍要保留查询、时间与来源。" },
    ],
  },
  {
    q: "用户用中文提问、证据主要是英文时，跨语言检索应该怎样设计？",
    a: "先区分“多种语言各查本语言资料”和“查询语言与证据语言不同”。后者应在同一问题集上比较多语言 Embedding、查询翻译后检索、资料翻译后建立单语索引，以及关键词与向量融合；没有一种路线可只凭模型标签决定。",
    depth: "为每种语言对冻结问题、原始证据和可接受答案，分别测 Candidate Recall@K、术语、数字、专名、否定、引用回跳、P95 和成本。翻译可提高词面一致性，也可能改变产品名、条款和限定条件；应保留原查询、翻译版本与原文证据，回答可以本地化解释，但关键引用仍回到权威原文。跨语言检索研究提供实验路线，不代表企业语料表现。",
    ask: "用户语言与权威资料语言分别是什么，哪些术语或专名不能翻译，答案是否必须同时显示原文和译文？",
    tag: "离线证据",
    basis: "跨语言检索基准 + 模块化检索 + 主张级引用",
    evidence: [
      { sourceId: "clirmatrix-2020", supports: "支持查询语言与文档语言不同的跨语言检索数据集与评估路线；不支持企业语料上的固定收益。" },
      { sourceId: "rag-survey", supports: "支持按任务组合查询处理、检索与增强组件；不提供跨语言通用最佳方案。" },
      { sourceId: "alce-2023", supports: "支持关键主张需由直接引用覆盖；翻译后的表述仍应回到原始证据。" },
    ],
    addedAt: "2026-07-29",
  },
  {
    q: "源文档更新后，多久能在回答中生效？",
    a: "终点不是同步作业结束，而是授权用户在最终回答中看到新版本、看不到旧版本。新增、修改、删除与撤权应分别计算发现、解析、索引、缓存失效和在线验证时间。",
    depth: "数据工程负责可靠传播变化，RAG 负责验证自己的候选、最终上下文、引用和缓存已经切换。记录 source_version、effective_at、indexed_at、acl_version 与 deletion_at，并用正向和负向样本测端到端时延。具体分钟或小时不是通用标准，应由业务风险、目标服务能力和 PoC 共同确定。",
    ask: "新增、修改、删除和撤权分别要求多快生效，哪类变化超时后必须阻断回答或转人工？",
    tag: "离线证据",
    basis: "官方同步机制 + 零信任原则 + 客户 SLA",
    evidence: [
      { sourceId: "aws-bedrock-kb-sync", supports: "支持新增、修改和删除需要经同步传播到托管知识库。" },
      { sourceId: "azure-search-indexer-lifecycle", supports: "支持 Reset 不自动清理孤儿文档，部分 ACL 变化可能绕过普通高水位检测。" },
      { sourceId: "nist-zero-trust", supports: "支持每次资源访问前按当前主体和策略重新授权。" },
    ],
  },
  {
    q: "不同部门、不同客户的数据权限如何保证？",
    a: "权限必须由身份系统、应用和检索服务确定性执行，不能只写在提示词里。当前主体、租户、用户组、文档 ACL 和数据版本要进入候选生成、缓存键、返回前检查与审计。",
    depth: "安全模块负责身份、策略、隔离和事件响应；RAG 的局部验收是：未授权证据不进入候选，授权变化能传播到所有派生副本，回答与引用不会泄漏正文或元数据。高敏场景应使用真实身份的正负样本验证，而不是只检查配置存在。",
    ask: "权限来自哪个权威系统，是否有租户、文档或行列级隔离，撤权要多快传播，缓存如何区分身份？",
    tag: "离线证据",
    basis: "零信任原则 + RAG 检索安全边界",
    evidence: [
      { sourceId: "nist-zero-trust", supports: "支持访问企业资源前认证和授权；检索过滤是该原则的 RAG 局部实现。" },
      { sourceId: "owasp-vector-weaknesses", supports: "支持多租户向量库隔离、细粒度访问控制和检索日志。" },
      { sourceId: "azure-search-document-acl", supports: "支持特定搜索服务把文档访问控制用于结果过滤；限制需当前核验。" },
    ],
  },
  {
    q: "RAG 系统会不会被文档里的恶意指令攻击？",
    a: "会。检索内容是不可信数据，不能被提升为系统指令；RAG、微调和系统提示词都不能天然消除间接提示注入。",
    depth: "安全模块负责完整威胁模型和控制体系。RAG 的局部责任是保留来源、隔离指令与证据、限制可检索范围，并验证恶意内容不会改变回答策略或触发高权限动作。若系统还能调用工具，检索证据与工具授权必须是不同信任域；任何写操作继续由 Agent、应用规则与人工审批控制。",
    ask: "系统只读回答还是能执行动作，知识源由谁写入，恶意文档最远能影响到哪个工具或业务状态？",
    tag: "离线证据",
    basis: "社区安全指南 + RAG 局部控制边界",
    evidence: [
      { sourceId: "owasp-prompt-injection", supports: "直接支持 RAG 与微调不能完全消除提示注入。" },
      { sourceId: "owasp-vector-weaknesses", supports: "支持向量库的数据投毒、访问控制与跨上下文泄漏风险。" },
    ],
  },
  {
    q: "解析、Embedding、Reranker、生成和评估模型，应该怎样组合选型？",
    a: "把它们视为五个独立岗位，不寻找一个“最强模型”统一解决。解析模型按证据恢复验收，Embedding 按候选召回验收，Reranker 按候选内排序验收，生成模型按忠实与任务结果验收，评估模型按与人工裁决的一致性和稳定性验收。",
    depth: "冻结同一语料、问题、身份、版本与负载，先用简单可替换组件建立基线，再只替换一个岗位。记录解析器、切片、Embedding、索引、Reranker、生成模型、Prompt 和评估器的完整版本组合。候选召回不足时换更大生成模型通常无效；评估模型也不能自证可靠，必须与人工样本校准。是否使用开源、自托管或商业 API，另按数据地域、容量、运维和完整 TCO 比较。",
    ask: "当前失败发生在哪个岗位，各岗位的局部指标、硬约束、替换成本和人工裁决样本是什么？",
    tag: "在线检索",
    basis: "模块化研究 + 分阶段检索与评估",
    evidence: [
      { sourceId: "docling-report", supports: "支持文档解析与结构恢复是独立处理阶段；不证明下游回答质量。" },
      { sourceId: "mteb-2023", supports: "支持 Embedding 需要按任务与语言分别评估，论文未发现一种方法支配所有任务。" },
      { sourceId: "bert-reranker", supports: "支持候选召回后由独立模型进行查询—段落重排。" },
      { sourceId: "replug-2024", supports: "支持冻结黑盒生成模型并在模型外组合检索器的模块化路线。" },
      { sourceId: "ragas", supports: "支持把上下文相关性、回答相关性和忠实度分开评估；不支持评估模型自动可靠。" },
    ],
    addedAt: "2026-07-29",
  },
  {
    q: "Hybrid Search、RRF 和 Reranker 各自解决什么问题？",
    a: "Hybrid Search 让关键词与向量两路尽量不漏；RRF 按各路名次融合候选；Reranker 对有限候选做更细的查询—证据判断。候选 Top-K 是召回预算，最终上下文 K 是回答预算，不能混为一个数字。",
    depth: "BM25 与向量分数来自不同空间，不能直接比较；RRF 主要用排名合并。Reranker 读取问题和候选全文，通常更慢，只能重排已有候选。应分别测稀疏和稠密的增量召回、融合后的 Candidate Recall@K、重排后的 MRR 或 nDCG、最终证据覆盖与新增 P95。只有正确证据已进入候选但排得低时，Reranker 才直接解决瓶颈。",
    ask: "失败属于编号或专名未命中、同义表达未命中，还是正确证据已经进入候选却排不进最终上下文？",
    tag: "在线检索",
    basis: "稀疏、稠密与二阶段排序研究 + 客户实验",
    evidence: [
      { sourceId: "bm25-book", supports: "支持稀疏检索对词项、稀有度和文档长度的基本评分机制。" },
      { sourceId: "dpr-2020", supports: "支持以 top-K passage retrieval accuracy 单独观察候选召回。" },
      { sourceId: "rrf-2009", supports: "支持用各候选列表中的排名倒数进行融合，不要求不同检索分数处于同一量纲。" },
      { sourceId: "bert-reranker", supports: "支持候选召回之后进行查询—段落联合重排，不能补回候选外证据。" },
    ],
  },
  {
    q: "为什么系统明明有文档，还是答不到？",
    a: "先确认正确证据在哪一层丢失：资料交接未通过、未进入候选、被权限或版本过滤、重排淘汰、未进入最终上下文，还是模型没有忠实使用。不要一开始就更换生成模型。",
    depth: "用带标准答案、证据位置、版本和访问身份的诊断集依次检查解析完整性、Candidate Recall@K、过滤后召回、重排位置、最终上下文覆盖和回答忠实度。Reranker 不能找回候选外证据；只有证据进入最终上下文而模型仍未正确使用时，生成模型或 Prompt 才是直接候选原因。",
    ask: "能否提供覆盖主要任务和风险等级的失败问题，并标出正确文档、片段、版本与访问身份？",
    tag: "在线检索",
    basis: "分阶段论文指标 + 局部故障诊断",
    evidence: [
      { sourceId: "dpr-2020", supports: "支持候选检索阶段独立衡量召回。" },
      { sourceId: "bert-reranker", supports: "支持在候选集内精排；不能补回未召回证据。" },
      { sourceId: "ragas", supports: "支持把上下文质量与生成忠实度分开诊断。" },
    ],
  },
  {
    q: "开启 Agentic Retrieval 或查询分解后，是不是一定更准确？",
    a: "不一定。它们只在多意图、多跳或需要选源的问题上可能带来增量证据；精确编号、短事实和单跳请求可能因改写丢词、调用增加而更慢或更差。",
    depth: "保留原问题，并按精确查找、语义解释、多跳比较和跨源任务建立切片。对每次改写与子查询记录命中文档、增量召回、额外 P95 和成本；没有新证据或达到预算时立即停止。HyDE 的假设文档只能帮助找到真实资料，不能成为证据。某些产品改写能力仍处预览，功能阶段与限制需当前核验。",
    ask: "真实问题中有多少需要多跳或跨源，哪些编号、日期、否定和业务条件不能被改写丢失？",
    tag: "在线检索",
    basis: "论文机制 + 官方产品边界 + 客户切片实验",
    evidence: [
      { sourceId: "hyde-2023", supports: "支持假设文档改善特定零样本稠密检索，并明确生成内容可能幻觉。" },
      { sourceId: "azure-search-query-rewrite", supports: "支持保留原查询并生成替代查询，也说明精确唯一词项可能丢失。" },
      { sourceId: "aws-bedrock-query-decomposition", supports: "支持复杂查询可选地分解为多个子查询，并可能增加查询次数。" },
    ],
  },
  {
    q: "多轮会话中的历史问题和答案，应该怎样参与下一轮检索？",
    a: "历史用于消解“它、那个版本、继续比较”等指代，不应直接成为权威证据。每轮都保留原话，生成可独立检索的当前问题，并重新取得身份、时间、地区和产品版本等硬条件。",
    depth: "把会话状态分成用户已确认条件、待确认假设、检索证据和模型回答。只有用户确认或权威系统提供的条件才能进入确定性过滤；上一轮模型回答不能被下一轮当作事实。比较使用原问题、独立问题和历史摘要三种路线的 Candidate Recall、条件保留、越权负例与时延，并对过长会话压缩后回放关键任务。",
    ask: "哪些会话条件必须跨轮保留，哪些需要每轮重新确认，历史会话是否可能跨用户、租户或权限变化？",
    tag: "在线检索",
    basis: "模块化查询处理 + 原查询保留 + 零信任边界",
    evidence: [
      { sourceId: "rag-survey", supports: "支持查询处理与检索增强可以作为独立组件设计；不提供多轮会话通用实现。" },
      { sourceId: "azure-search-query-rewrite", supports: "支持保留原查询并记录改写；不支持把模型改写当作用户新条件。" },
      { sourceId: "nist-zero-trust", supports: "支持每次资源访问按当前主体和策略授权，不能因上一轮访问建立隐式信任。" },
    ],
    addedAt: "2026-07-29",
  },
  {
    q: "证据不足时，系统应该追问、继续检索、限定回答还是拒答？",
    a: "缺少用户才能提供的必要条件时追问；问题完整但候选证据不足时，在预算内继续检索；只有部分主张有证据时限定回答；证据缺失、冲突、过期、越权或风险过高时拒答或转人工。",
    depth: "先为任务定义必需条件、最小证据、允许范围、风险等级和检索预算，再把四种动作写成应用规则。继续检索必须记录新增证据并受轮次、P95 与成本限制；限定回答要明确未覆盖范围；拒答要说明可行动原因但不能泄漏无权证据。模型可以辅助分类，最终门槛、转人工和高风险禁答由应用与业务负责人控制。",
    ask: "哪些条件只能向用户确认，什么证据足以支持完整或部分答案，哪些任务无论多流畅都必须拒答或人工复核？",
    tag: "有据回答",
    basis: "检索后自检研究 + 主张级引用 + 风险治理",
    evidence: [
      { sourceId: "self-rag", supports: "支持按需检索并评价证据与生成；不表示普通 RAG 自动拥有可靠决策策略。" },
      { sourceId: "alce-2023", supports: "支持把主张是否被引用支持与关键主张覆盖完整性分开检查。" },
      { sourceId: "nist-genai-profile", supports: "支持按风险情境制定测量、人工复核和管理动作；不提供通用阈值。" },
    ],
    addedAt: "2026-07-29",
  },
  {
    q: "RAG 检到了正确文档，为什么仍可能答错？RAG 能消除幻觉吗？",
    a: "不能。候选命中不表示正确证据进入最终上下文，也不表示生成模型会忠实使用，更不保证证据本身真实、最新并适用于当前客户。",
    depth: "至少分开四层：Candidate Recall 判断标准证据是否进入候选；最终上下文覆盖判断过滤与重排后是否仍保留；Faithfulness 判断回答是否受上下文支持；Factual Correctness 判断证据与结论是否符合权威事实。回答可能忠实复述过期文档却仍然错误，也可能碰巧答对但没有可核验链路。",
    ask: "什么是权威来源，冲突版本以谁为准，是否允许限定或拒答，哪些回答必须人工复核？",
    tag: "有据回答",
    basis: "RAG 评估指标 + 风险边界",
    evidence: [
      { sourceId: "ragas", supports: "支持把上下文相关性、回答相关性与忠实度分开观察。" },
      { sourceId: "self-rag", supports: "支持检索后仍需评价证据与生成；不表示普通 RAG 自动自检。" },
      { sourceId: "nist-genai-profile", supports: "支持以持续测量和风险管理补足单一模型指标。" },
    ],
  },
  {
    q: "答案已经带出处，是否就可以认定可信或合规？",
    a: "不能。还要确认出处是否直接支持对应主张、是否覆盖所有关键主张、是否为当前有效版本，以及当前用户是否有权查看。",
    depth: "把答案拆成数字、期限、条件和结论等可核验主张，逐项绑定原文坐标，并分别验收引用正确性和完整性。一个相关链接可能没有支持具体结论；一个准确引用也可能来自过期或不适用版本。合规结论由治理、法律与业务负责人作出，RAG 只提供可核验证据链。",
    ask: "哪些主张必须逐项有证据，谁决定权威版本，引用能否回到当前用户有权访问的原文位置？",
    tag: "有据回答",
    basis: "同行评审引用评估 + 风险治理",
    evidence: [
      { sourceId: "alce-2023", supports: "支持把引用是否支撑主张与关键主张是否被完整覆盖分开评估。" },
      { sourceId: "nist-genai-profile", supports: "支持对来源、有效性、透明度和生成式 AI 风险持续治理。" },
    ],
  },
  {
    q: "GraphRAG 是不是向量 RAG 的升级版，所有知识库都应该上？",
    a: "不是。GraphRAG 主要面向跨大量文档的关系发现、主题归纳和全局问题；单跳事实、精确条款与常规问答仍应保留普通检索基线。",
    depth: "GraphRAG 要抽取实体与关系、构建社区并生成分层摘要，增加索引时间、模型调用、更新一致性和质量治理。只有失败问题确实需要跨文档关系或全局归纳，且能定义实体、关系和摘要门槛时才值得验证。图谱结果也不能替代原文引用、权限过滤与普通事实召回。",
    ask: "真实问题中有多少需要跨文档归纳或关系推理，实体与关系由谁校验，知识变化后图和摘要如何更新？",
    tag: "有据回答",
    basis: "GraphRAG 一手论文 + RAG 架构综述",
    evidence: [
      { sourceId: "graphrag", supports: "支持用实体图、社区和社区摘要处理跨语料全局归纳问题。" },
      { sourceId: "rag-survey", supports: "支持按问题需要采用 Advanced 或 Modular RAG，而非把复杂架构视为统一升级。" },
    ],
  },
  {
    q: "如何证明 RAG 的效果，而不是做一个漂亮 Demo？",
    a: "冻结同一批真实问题、权威证据、访问身份、版本和负载，分别验收候选召回、最终上下文、有据回答、拒答、风险、时延与单位达标回答成本，并在测试前写明上线、整改和停止条件。",
    depth: "RAG 提供本地分层结果：Candidate Recall@K、过滤后召回、最终证据覆盖、Faithfulness、主张引用、无答案与越权负例、P95 和每个达标回答成本。通用评估方法由评估模块负责，安全红线由安全模块负责，完整业务 ROI 由场景与 FinOps 负责人负责。总体平均不能掩盖关键任务或高风险切片，PoC 只证明所测数据、版本与负载下的可行性。",
    ask: "真实问题从哪里抽样，谁裁决答案和证据，哪些错误一票否决，PoC 相对现有流程要改变什么决定？",
    tag: "局部验收",
    basis: "检索、生成与引用评估 + 风险门 + 业务基线",
    evidence: [
      { sourceId: "dpr-2020", supports: "支持候选检索阶段独立衡量 top-K passage retrieval accuracy。" },
      { sourceId: "ragas", supports: "支持把上下文、回答相关性与忠实度分开评估。" },
      { sourceId: "alce-2023", supports: "支持把引用正确性和引用完整性分别纳入验收。" },
      { sourceId: "nist-genai-profile", supports: "支持按风险情境建立测量、管理和持续监测门槛。" },
    ],
  },
  {
    q: "RAG 上线几个月后效果变差，应该怎样排查？",
    a: "先用同一冻结集和线上失败样本沿资料交接、候选、过滤、重排、最终上下文和生成逐层比较，再把确定的变化交给数据工程、模型或 AI Ops 处理；不要先凭感觉改 Prompt 或换模型。",
    depth: "一次 RAG Trace 至少关联当前问题与身份、查询计划、各路候选、过滤原因、重排、最终上下文、证据版本、模型与 Prompt 版本、回答动作、时延和 token。正文日志要最小化，可保存稳定来源 ID、哈希或受控快照。RAG 定义定位所需字段和局部质量信号，AI Ops 负责版本发布、告警、容量、事故恢复与长期保留。",
    ask: "退化从何时、哪些用户和任务开始，能否把失败还原到候选、过滤、最终证据和完整组件版本？",
    tag: "局部验收",
    basis: "持续 RAG 评估 + 标准遥测 + AI Ops 边界",
    evidence: [
      { sourceId: "ragas", supports: "支持将上下文相关性、回答相关性与忠实度分开衡量。" },
      { sourceId: "opentelemetry-genai-semconv", supports: "支持用标准化遥测关联生成式 AI、检索和应用链路；RAG 质量字段需项目扩展。" },
      { sourceId: "nist-genai-profile", supports: "支持部署后持续测量、监测和管理生成式 AI 风险。" },
    ],
  },
  {
    q: "怎样控制延迟和成本？",
    a: "先删除没有增量证据的步骤，再考虑缩小模型。分别给查询规划、候选召回、重排、上下文和生成设置预算，只对确有价值的任务增加复杂路线。",
    depth: "RAG 的本地口径包括离线解析、Embedding 与索引，以及在线路由、搜索、重排、上下文、生成、失败重试和人工接管，并以每个达标回答成本比较路线。记录各阶段 P50、P95、调用数、token 和成功切片。AI Ops 负责容量、发布和异常处置，场景与 FinOps 负责人把本地 Cost to Serve 连接到采用率、人工节省、风险与完整 ROI。",
    ask: "哪类请求必须达到什么 P95，哪些检索步骤没有增量证据，每月变化量、查询量、成功率和人工接管率是多少？",
    tag: "局部验收",
    basis: "组合检索与多证据生成研究 + 标准遥测 + 单位经济边界",
    evidence: [
      { sourceId: "contextual-retrieval", supports: "支持在特定实验中比较混合检索和重排的质量增益；不提供通用成本或延迟阈值。" },
      { sourceId: "fid-2021", supports: "支持多段证据聚合会改变生成链路和任务表现；不提供通用最优数量。" },
      { sourceId: "opentelemetry-genai-semconv", supports: "支持记录生成式 AI 调用、用量和链路属性；业务成本口径需项目定义。" },
      { sourceId: "finops-unit-economics", supports: "支持把资源效率单位与业务结果单位区分，并用单位经济形成决策基线；不单独证明 RAG ROI。" },
    ],
  },
]);
