/**
 * RAG 问答与证据卡的内容源。
 *
 * 来源标题、链接、证据类型和核验日期统一维护在
 * app/reference-content.mjs；此文件仅保存对应的 sourceId。
 */
export const ragDeepDives = [
  {
    kind: "sequence",
    eyebrow: "QUERY PLANNING",
    title: "先生成查询计划，再决定是否以及怎样检索",
    intro: "复杂检索不是把用户原话直接向量化。查询计划要保留原问题、提取硬约束、选择知识源，并只在能带来增量召回时增加改写或分解。",
    items: [
      { name: "保留原始问题", en: "Preserve Original Query", mechanism: "把用户原话、身份、会话与时间一起保存，避免改写后无法还原型号、否定、日期和限定词。", decision: "所有改写都应与原问题并存，并能在 Trace 中比较贡献。", boundary: "模型生成的改写不是用户的新授权，也不能覆盖原始业务条件。" },
      { name: "识别问题与风险", en: "Classify Intent & Risk", mechanism: "判断是精确查找、语义解释、关系归纳、结构化查询还是无需检索，同时标注答案风险。", decision: "精确编号优先关键词或结构化查询；复杂多跳问题才考虑规划型检索。", boundary: "问题分类错误会把请求送入不合适的数据源。" },
      { name: "提取硬过滤条件", en: "Extract Hard Filters", mechanism: "将租户、地区、产品版本、有效日期、文档类型和访问身份转成确定性过滤条件。", decision: "过滤条件由应用校验，不能只藏在自然语言 Prompt 中。", boundary: "过滤过严会漏召回，过滤过松会越权或混入错误版本。" },
      { name: "选择检索路线", en: "Route Retrieval", mechanism: "在关键词、向量、SQL、图谱、API 或不检索之间路由，并为每路设置预算和停止条件。", decision: "先建立单路基线，再用真实失败样本证明组合价值。", boundary: "更多检索器会增加时延、成本和故障路径，不等于更准确。" },
      { name: "按需改写或分解", en: "Rewrite or Decompose", mechanism: "对多意图问题做子查询，对语义缺口尝试查询扩展或 HyDE，并记录每个子查询的增量命中。", decision: "只对明确复杂问题启用；用候选召回和业务成功率验证。", boundary: "HyDE 的假设文档可能幻觉，只能帮助找真实文档，不能当证据。" },
    ],
    sourceIds: ["hyde-2023", "azure-search-query-rewrite", "aws-bedrock-query-decomposition"],
  },
  {
    kind: "sequence",
    eyebrow: "KNOWLEDGE LIFECYCLE",
    title: "新增、修改、删除与撤权是四条不同的时效链",
    intro: "绿色的同步任务只证明作业完成，不证明旧内容已经不可检索。生产 RAG 要把知识变化一直验证到缓存、权限和最终回答。",
    items: [
      { name: "记录有效版本", en: "Version the Source", mechanism: "知识单元保存 source_version、valid_from、valid_to、supersedes、indexed_at 与 acl_version。", decision: "先定义权威版本和冲突规则，再谈同步频率。", boundary: "更新时间不能完整表达业务生效时间与权限变化。" },
      { name: "传播变更事件", en: "Propagate Change Events", mechanism: "用 CDC、对象存储事件或调度任务区分新增、修改、删除和 ACL 变化。", decision: "按变化类型分别设置 SLA、失败队列和责任人。", boundary: "某些 ACL 变化不会更新内容时间戳，普通高水位检测可能看不到。" },
      { name: "重建索引产物", en: "Rebuild Index Artifacts", mechanism: "解析、切块、Embedding 与索引均带版本；失败时保持旧版本可服务并隔离半成品。", decision: "索引任务完成后抽样验证内容、坐标、权限与版本。", boundary: "Reset 或重新运行不一定删除源端已不存在的孤儿文档。" },
      { name: "删除并失效缓存", en: "Delete & Invalidate", mechanism: "通过 Tombstone 或显式删除动作清理向量、稀疏索引、摘要、问答缓存和权限快照。", decision: "删除与撤权优先级通常高于新增，应单独做负向验收。", boundary: "先物理删除源文件、后通知索引可能留下无法追踪的孤儿。" },
      { name: "端到端一致性探针", en: "Consistency Probe", mechanism: "用已删除、已撤权和已替换样本持续查询，验证系统不会再返回正文、元数据或缓存答案。", decision: "以用户身份的最终检索结果作为 SLA 终点，而不是作业状态。", boundary: "探针与日志本身也要遵守敏感数据和保留策略。" },
    ],
    sourceIds: ["aws-bedrock-kb-sync", "azure-search-indexer-lifecycle", "nist-zero-trust"],
  },
  {
    kind: "matrix",
    eyebrow: "EVIDENCE COMPILER",
    title: "把“拼接片段”升级为主张级证据编排",
    intro: "上下文组装的目标不是塞满 token，而是让每项重要结论都能回到当前有效、用户有权访问的原始证据。",
    columnLabels: { name: "编排对象", mechanism: "工作机制", decision: "验收问题", boundary: "失效方式" },
    items: [
      { name: "证据对象", en: "Evidence Object", mechanism: "统一携带来源 ID、原文坐标、版本、有效期、ACL、权威等级与抽取方式。", decision: "任一回答片段能否稳定回跳到原文？", boundary: "只有链接、没有版本和坐标，无法证明当时看到了什么。" },
      { name: "冲突集合", en: "Conflict Set", mechanism: "对同一主题的不同版本、地区或条款显式分组，按适用范围决定选用、并列说明或拒答。", decision: "客户是否定义了权威来源和冲突责任人？", boundary: "把冲突片段一起塞给模型只会把决策责任转移给随机生成。" },
      { name: "主张绑定", en: "Claim Attribution", mechanism: "将答案拆成可核验主张，逐项绑定支持证据，并分别计算引用正确性与覆盖完整性。", decision: "关键数字、期限和结论是否各有直接支持？", boundary: "引用一个相关文档不代表该文档支持整段回答。" },
      { name: "限定或拒答", en: "Scope or Abstain", mechanism: "证据不足、过期、冲突或越权时，缩小回答范围、说明不确定性或转人工。", decision: "哪些主张必须有证据，哪些允许经验性建议？", boundary: "生成后再补链接是事后装饰，不是可审计证据链。" },
    ],
    sourceIds: ["alce-2023", "ragas", "nist-genai-profile"],
  },
  {
    kind: "checklist",
    eyebrow: "ZERO-DOWNTIME CHANGE",
    title: "Embedding、索引与权限变更的无停机发布清单",
    intro: "模型或 Embedding 升级不是替换一个配置项，而是一次数据迁移和检索发布。业务可以不停机，但通常无法跳过全量回填与双版本验证。",
    maxColumns: 3,
    items: [
      { name: "稳定 Chunk ID 与语料快照", en: "Stable IDs & Snapshot", mechanism: "冻结或标记语料版本，以稳定文档和 Chunk ID 建立新索引。", decision: "能否把同一标准证据在新旧索引中一一对应？", boundary: "不同 Embedding 的向量不能在同一空间直接比较。" },
      { name: "新旧索引双写", en: "Dual Indexing", mechanism: "迁移期让新增、修改、删除和 ACL 变化同时传播到两套索引。", decision: "双写失败是否有重放、补偿和一致性告警？", boundary: "双索引会暂时增加存储、算力和运营复杂度。" },
      { name: "影子查询与切片比较", en: "Shadow Queries", mechanism: "对真实流量影子检索，比较候选召回、排序、P95、成本和越权负例。", decision: "总体平均之外，高风险切片是否没有退化？", boundary: "HTTP 成功和平均分改善都不能掩盖关键场景失败。" },
      { name: "别名或网关切换", en: "Alias / Gateway Cutover", mechanism: "通过索引别名或应用路由小流量切换，并保留旧索引回滚窗口。", decision: "切换单位、观察时间和回滚触发器是否明确？", boundary: "别名是具体产品能力，功能阶段和限制需现场核验。" },
      { name: "退役前负向验证", en: "Negative Verification", mechanism: "确认旧内容、已删除文档和已撤权身份在新索引、缓存和最终回答中均不可见。", decision: "谁签署删除、权限和审计一致性后才允许退役旧索引？", boundary: "只比较正向召回会漏掉最严重的权限与删除回归。" },
    ],
    sourceIds: ["azure-search-document-acl", "azure-search-index-alias", "azure-search-indexer-lifecycle", "opentelemetry-semconv"],
  },
];

export const evidenceCards = [
  {
    metric: "+9–19 pp",
    title: "Top-20 召回准确率",
    finding: "DPR 在论文所评估的开放域问答数据上，相对其 Lucene-BM25 基线取得这一绝对提升。",
    boundary: "数据集与基线特定；不能据此承诺稠密检索在客户语料上必然优于 BM25。",
    sourceId: "dpr-2020",
  },
  {
    metric: "3",
    title: "个 RAGAS 自动评估维度",
    finding: "Faithfulness、Answer Relevance 与 Context Relevance 分别观察证据使用、回答相关性和检索上下文相关性。",
    boundary: "业务结果、性能、安全和成本是本知识库追加的工程验收面，不是 RAGAS 论文的三项指标。",
    sourceId: "ragas",
  },
  {
    metric: "5.7% → 1.9%",
    title: "Top-20 检索失败率",
    finding: "Anthropic 的特定实验中，contextual dense + BM25 + rerank 达到该结果。",
    boundary: "属于厂商实验；适合提出混合检索 A/B 假设，不能直接写入采购或效果承诺。",
    sourceId: "contextual-retrieval",
    accent: true,
  },
  {
    metric: "Black-box",
    title: "冻结模型的模块化路线",
    finding: "REPLUG 展示了冻结黑盒语言模型、在模型外训练可调检索器并注入检索文档的路线。",
    boundary: "它支持检索与模型可解耦，不直接证明企业权限、回滚或可观测能力。",
    sourceId: "replug-2024",
  },
  {
    metric: "位置敏感",
    title: "长上下文并非稳定利用",
    finding: "论文实验中，相关信息处于上下文中部时，表现往往低于位于开头或结尾。",
    boundary: "结论来自特定模型与任务；它支持做位置偏差基线，不证明 RAG 必然胜出。",
    sourceId: "lost-middle",
  },
  {
    metric: "主张级",
    title: "引用要检查正确性与完整性",
    finding: "ALCE 将引用是否真正支持对应主张，以及关键主张是否都获得引用，作为不同评估问题。",
    boundary: "论文评测方法支持拆分引用质量；不能把论文数据直接外推为客户系统准确率。",
    sourceId: "alce-2023",
  },
  {
    metric: "删除 ≠ 重置",
    title: "知识时效是端到端状态",
    finding: "Azure 官方文档明确指出 Reset / Run 不会自动清理没有源端对应物的孤儿文档，ACL 变化也可能绕过普通高水位检测。",
    boundary: "这是特定产品的实现边界；它支持设计删除与撤权验收，不代表其他产品机制相同。",
    sourceId: "azure-search-indexer-lifecycle",
  },
];

export const ragQa = [
  {
    q: "上下文窗口已经很长，为什么还需要 RAG？",
    a: "长上下文解决“能装下多少”，检索组件解决“该拿什么”；企业 RAG 架构还必须由数据链和应用控制面解决知识新鲜度、谁能看以及证据来自哪里。语料很小、稳定且可整体装入时，直接长上下文可能更简单。",
    depth: "不能只比较 token 上限，还要比较有效召回、上下文位置偏差、首 token 时延、重复传输成本、权限过滤和更新 SLA。研究在特定多文档问答与键值检索实验中观察到明显的位置敏感性，因此“放得下”不等于“稳定用得好”；是否采用 RAG 仍应由客户基线验证。",
    ask: "追问客户：语料多大、多久变化一次、是否分权限、答案是否必须给出处？",
    tag: "架构判断",
    basis: "论文依据 + 工程边界 + 客户基线",
    evidence: [
      { sourceId: "lost-middle", supports: "支持长上下文利用具有位置敏感性；不支持“RAG 必然更好”。" },
      { sourceId: "rag-original-2020", supports: "支持参数化记忆与外部检索记忆结合这一基本路线。" },
    ],
  },
  {
    q: "RAG 检到了正确文档，为什么仍可能答错？RAG 能消除幻觉吗？",
    a: "不能。RAG 增加了可用证据，但“检索成功”不等于证据进入最终上下文，也不等于模型会忠实使用，更不保证证据本身真实、最新且适用于当前客户。",
    depth: "至少区分四层：候选召回率（Candidate Recall）判断标准证据是否进入候选集；最终上下文覆盖判断证据是否经过过滤与重排后进入 Prompt；忠实度（Faithfulness）判断回答是否受上下文支持；事实正确性（Factual Correctness）判断证据与结论是否符合权威事实。回答可能忠实复述过期文档却仍然错误，也可能碰巧答对但没有可核验证据链。",
    ask: "追问客户：什么是权威来源？冲突版本以谁为准？是否允许拒答？哪些回答必须人工复核？",
    tag: "风险边界",
    basis: "论文指标 + 风险边界",
    evidence: [
      { sourceId: "ragas", supports: "支持把上下文相关性、回答相关性与忠实度分开观察。" },
      { sourceId: "self-rag", supports: "支持检索后仍需评价证据与生成；不表示普通 RAG 自动具备自检能力。" },
      { sourceId: "nist-genai-profile", supports: "支持以持续测量和风险管理补足单一模型指标。" },
    ],
  },
  {
    q: "做 RAG 一定要向量数据库吗？",
    a: "不一定。向量检索擅长语义相似，但精确编号、产品代码、日期、人名与强过滤条件常常更适合关键词、结构化查询或混合检索。向量数据库是候选检索基础设施，不等于完整 RAG。",
    depth: "稳健方案常用 dense + sparse + metadata filter，再对候选结果 rerank。要区分候选召回 Top-K 与最终上下文 K：前者决定召回预算，后者决定模型输入预算。Reranker 只重新排序已召回候选，不能抬高候选集本身的召回上限。小规模场景可先复用现有搜索引擎或数据库扩展。",
    ask: "追问客户：查询更像“找同义内容”还是“查精确事实”？现有搜索与数据库能否复用？",
    tag: "产品选型",
    basis: "检索研究 + 工程选型",
    evidence: [
      { sourceId: "bm25-book", supports: "支持关键词稀疏检索的基本机制。" },
      { sourceId: "dpr-2020", supports: "支持稠密候选检索的能力与数据集边界。" },
      { sourceId: "bert-reranker", supports: "支持候选召回后再做查询—段落精排的二阶段结构。" },
    ],
  },
  {
    q: "为什么系统明明有文档，还是答不到？",
    a: "应先确认正确证据在哪一层丢失：未正确入库、未进入候选集、被权限过滤或重排淘汰、未进入最终上下文，还是模型没有忠实使用。不要一开始就换更大的生成模型。",
    depth: "用带标准答案、证据位置、版本和访问身份的诊断集逐层检查：解析完整率 → Candidate Recall@K → 过滤后召回 → 重排位置 → 最终上下文覆盖 → 回答忠实度。Reranker 无法找回候选集中不存在的证据；只有证据已进入最终上下文而模型仍未正确使用时，升级生成模型才可能直接改善问题。",
    ask: "追问客户：能否提供覆盖主要业务任务与风险等级的一批真实失败问题，并标出正确文档、片段、版本和访问身份？",
    tag: "故障诊断",
    basis: "论文依据 + 分层诊断",
    evidence: [
      { sourceId: "dpr-2020", supports: "支持以候选召回能力单独观察检索阶段。" },
      { sourceId: "bert-reranker", supports: "支持在候选集内精排；不能补回未召回证据。" },
      { sourceId: "ragas", supports: "支持把上下文质量与生成忠实度分开诊断。" },
    ],
  },
  {
    q: "RAG 和微调怎么选？",
    a: "知识频繁更新、需要引用和撤回时，优先建立 RAG 基线；希望模型稳定遵循风格、格式或专门行为时，再评估微调。两者可以组合。",
    depth: "微调把模式写入参数，更新与追溯成本较高；RAG 在运行时注入证据，更便于更新与撤回。研究在特定新事实注入任务中观察到 RAG 优于所比较的无监督微调，但不能推广为“所有微调都不适合知识更新”。先定位剩余误差是事实供给还是回答行为，再决定是否训练。",
    ask: "追问客户：变化的是“事实知识”还是“回答行为”？多久变一次？是否需要逐条来源？",
    tag: "路线选择",
    basis: "任务特定论文 + 工程判断",
    evidence: [
      { sourceId: "fine-tuning-or-retrieval", supports: "支持论文设定中新事实注入的 RAG 对比结果，边界不覆盖所有微调。" },
      { sourceId: "replug-2024", supports: "支持冻结模型、把检索能力放在模型外部的模块化路线。" },
    ],
  },
  {
    q: "不同部门、不同客户的数据权限如何保证？",
    a: "权限必须由应用与检索服务强制执行，不能只写在提示词里。身份、租户、用户组和文档授权要进入候选生成、缓存与审计链路。",
    depth: "索引应保留来源 ACL，或按风险采用逻辑 / 物理隔离；检索时执行 tenant、user、group 过滤；缓存键包含权限上下文；日志脱敏并能追踪命中文档。零信任标准提供“访问资源前认证与授权”的原则，OWASP 则直接指出多租户向量库的跨上下文泄漏风险。高敏场景应把越权泄漏为零设为验收目标，并通过对抗集验证。",
    ask: "追问客户：权限来自哪个主系统？是否有租户级、文档级、行列级隔离和即时撤权要求？",
    tag: "安全",
    basis: "官方原则 + RAG 安全指南",
    evidence: [
      { sourceId: "nist-zero-trust", supports: "支持访问资源前认证与授权；检索过滤是该原则的 RAG 工程应用。" },
      { sourceId: "owasp-vector-weaknesses", supports: "直接支持多租户向量库隔离、细粒度访问控制和检索日志。" },
    ],
  },
  {
    q: "源文档更新后，多久能在回答中生效？",
    a: "这不是模型 SLA，而是数据新鲜度 SLA。应分别计量发现、解析、索引、缓存失效、权限撤销与删除传播，并按业务风险设定目标。",
    depth: "建议观测 source_version、effective_at、indexed_at 与 deletion_at，并按来源风险分级；这些字段不是 NIST 规定。具体分钟、小时或天数也不是行业通用标准，必须由客户业务门槛、目标云服务能力和 PoC 实测共同确定。删除与权限撤销通常比新增更敏感，应单独验证端到端传播时间。",
    ask: "追问客户：哪类数据最敏感？新增、修改、删除和撤权分别要求多快生效？",
    tag: "时效性",
    basis: "治理原则 + 客户 SLA / PoC",
    evidence: [
      { sourceId: "nist-genai-profile", supports: "支持数据来源、生命周期和持续风险管理；不提供通用的分钟级 SLA。" },
    ],
  },
  {
    q: "如何证明 RAG 的效果，而不是做一个漂亮 Demo？",
    a: "不能只报一个“回答正确率”。应冻结同一套真实问题与权威证据，分别验收候选召回、排序与上下文、生成质量、业务结果，以及工程与安全。",
    depth: "候选检索看 Recall@K；排序看 MRR / nDCG 和正确证据是否进入最终上下文；生成看 Faithfulness、引用正确性与拒答正确性；事实层与客户指定的权威答案核对；端到端看任务成功率与人工接受率；工程层看 P95、每个成功回答成本、更新 / 删除 SLA 和越权测试。RAGAS 直接提出的是 3 个自动评估维度，后面的业务与工程指标是交付扩展。",
    ask: "追问客户：谁提供权威答案和证据？哪类错误不可接受？上线门槛按总体平均还是按高风险场景分别设置？",
    tag: "评估",
    basis: "论文指标 + 工程验收扩展",
    evidence: [
      { sourceId: "ragas", supports: "支持 Faithfulness、Answer Relevance、Context Relevance 三项自动评估维度。" },
      { sourceId: "dpr-2020", supports: "支持候选检索阶段独立衡量 top-K passage retrieval accuracy。" },
      { sourceId: "nist-genai-profile", supports: "支持自动评估结合人工评估和持续风险管理。" },
    ],
  },
  {
    q: "PDF、扫描件、表格和图片很多，RAG 还能做好吗？",
    a: "可以，但要把数字 PDF、扫描件和视觉丰富页面视为不同数据类型。PDF 解析、OCR 与视觉文档检索各自解决不同问题，任何一条链路的质量都可能成为最终上限。",
    depth: "纯文本抽取容易打乱双栏顺序、表头、脚注和跨页表格；扫描件还要经过文本检测与识别。应按文档类型路由处理：数字 PDF 保留版面、页级坐标和结构化表格；扫描件验证 OCR 字段完整率；图表、字体或空间关系本身承载事实时，再评估直接为页面图像建立多向量表示的视觉检索。三类研究只证明对应技术可行，最终问答质量必须用客户文档、语言和算力条件实测。",
    ask: "追问客户：各类文档占比和扫描质量如何？正确答案依赖图表、表格还是正文？",
    tag: "数据工程",
    basis: "解析 / OCR / 视觉检索研究 + 客户文档 PoC",
    evidence: [
      { sourceId: "docling-report", supports: "支持 PDF 转换、版面分析与表格结构识别；不保证下游 RAG 准确率。" },
      { sourceId: "pp-ocr-2020", supports: "支持文本检测、方向分类与文字识别组成的 OCR 路线；不保证任意扫描质量。" },
      { sourceId: "colpali-2025", supports: "支持直接从文档页图像建立多向量视觉检索；效果需按客户数据复测。" },
    ],
  },
  {
    q: "怎样控制延迟和成本？",
    a: "先缩短无效链路，再缩小模型。应把解析与索引、候选召回、重排、最终上下文、生成 token 和峰值容量分别计量。",
    depth: "独立调整候选召回数量、重排数量和最终上下文数量，不要用一个 Top-K 同时代表三个阶段。可用查询分类跳过无关检索、缓存稳定结果、轻量模型做路由、只对高价值候选重排并压缩上下文。厂商实验只能说明组合策略值得 A/B，不能给出客户 P95 或成本承诺；应报告 PoC 中每个成功回答成本，并结合当期云价。",
    ask: "追问客户：并发、P95、峰值系数、平均文档长度、成功问答量和当期云价基准是什么？",
    tag: "FinOps",
    basis: "相关研究 + 工程判断；数值来自客户 PoC",
    evidence: [
      { sourceId: "contextual-retrieval", supports: "支持在特定实验中对混合检索与重排做质量 A/B；不提供通用成本或延迟阈值。" },
      { sourceId: "fid-2021", supports: "支持多段证据聚合可带来任务收益，同时提醒 passage 数量结论具有任务边界。" },
    ],
  },
  {
    q: "开源模型还是商业模型更适合？",
    a: "不能只按“开源 / 商业”标签作结论。应先冻结同一语料、问题集、安全边界和负载，再逐个候选比较质量、吞吐、可部署地域、运维责任、合规、锁定与三年 TCO。",
    depth: "RAG 可以让知识供给与生成模型相对解耦，但提示、分词、上下文和工具调用仍需适配。商业 API 是否更快交付、自托管是否更可控，都只是待验证假设，不能脱离具体产品与团队能力预判。有效证据必须包含候选服务的当期官方能力 / 地域 / 计价资料、客户负载 PoC，以及人力、容量、升级和安全运营测算；REPLUG 只支持模块化组合，不支持 TCO 结论。",
    ask: "追问客户：数据能否出域？团队是否具备 GPU / 推理运维能力？负载是否稳定？",
    tag: "模型格局",
    basis: "架构论文 + 当期报价 / PoC",
    evidence: [
      { sourceId: "replug-2024", supports: "支持冻结黑盒模型与外部检索器的模块化组合；不提供企业三年 TCO。" },
    ],
  },
  {
    q: "RAG 系统会不会被文档里的恶意指令攻击？",
    a: "会。检索内容是不可信数据，不能把它当系统指令；RAG 与微调都不能天然消除提示注入（Prompt Injection）。",
    depth: "控制包括来源白名单、入库扫描与签名、指令与证据分区、最小权限工具调用、输出校验、敏感动作二次确认、异常检索监控和红队测试。向量与嵌入层还要防数据投毒、跨租户泄漏和来源混淆。对于能执行动作的 Agent，知识检索与工具授权必须采用不同信任域。",
    ask: "追问客户：系统只回答，还是还能发邮件、下单、改配置？知识源是否允许外部写入？",
    tag: "安全",
    basis: "社区安全指南",
    evidence: [
      { sourceId: "owasp-prompt-injection", supports: "直接支持 RAG 与微调不能完全消除提示注入。" },
      { sourceId: "owasp-vector-weaknesses", supports: "支持向量库的数据投毒、访问控制与跨上下文泄漏风险。" },
    ],
  },
  {
    q: "企业做 RAG，必须把检索器和生成模型端到端联合训练吗？",
    a: "不必。多数企业项目可以先组合独立的 Embedding、搜索、Reranker 和冻结的模型服务建立可评估基线；只有明确证实通用组件无法满足领域要求时，再评估训练。",
    depth: "原始 RAG 论文联合优化查询编码器与 BART 生成器，但保持文档编码器和索引固定，这是特定研究模型设计，不是企业交付要求。模块化架构允许检索、重排和生成分别升级与计费；REPLUG 也展示了冻结黑盒语言模型、在模型外优化检索器的路线。端到端训练会增加样本、索引刷新、回归和版本耦合成本。",
    ask: "追问客户：使用不可训练的模型 API 还是自托管模型？是否有查询—证据—答案样本？失败主要在检索还是生成？",
    tag: "训练策略",
    basis: "原始论文 + 模块化研究",
    evidence: [
      { sourceId: "rag-original-2020", supports: "支持原始模型的训练范围以及固定文档编码器和索引的设计。" },
      { sourceId: "replug-2024", supports: "支持冻结黑盒语言模型、在模型外优化检索器的路线。" },
    ],
  },
  {
    q: "Top-K 是不是越大越好？已经有向量检索为什么还需要 Reranker？",
    a: "不是。候选 Top-K 是召回预算，最终上下文 K 是模型输入预算；增大候选集可能提高召回，也会增加时延和噪声。Reranker 用更精细的查询—文档联合判断重新排序，但不能找回未被召回的文档。",
    depth: "第一阶段的稀疏或稠密检索追求高吞吐和尽量不漏，第二阶段 Reranker 在较小候选集上提高排序精度，最后只把经过权限、版本、去重和冲突处理的证据放入上下文。应分别观测 Candidate Recall@K、重排后的 MRR / nDCG、最终上下文证据覆盖率、额外延迟和 token 成本；Top-K 没有跨语料通用的最佳数字。",
    ask: "追问客户：正确证据是候选阶段没找到，还是进入候选后没有排进最终上下文？可接受多少重排延迟？",
    tag: "检索调优",
    basis: "检索与重排论文 + 客户 PoC",
    evidence: [
      { sourceId: "dpr-2020", supports: "支持候选检索阶段以 top-K passage retrieval accuracy 衡量召回。" },
      { sourceId: "bert-reranker", supports: "支持候选召回后使用更精细模型重排；无法补回候选集外证据。" },
      { sourceId: "fid-2021", supports: "支持多 passage 聚合在特定任务中的作用，同时表明数量结论不能跨任务照搬。" },
    ],
  },
  {
    q: "Hybrid Search、RRF 和 Reranker 各自解决什么问题？",
    a: "Hybrid Search 让关键词与向量两路尽量不漏；RRF 把两路排名合并；Reranker 再对有限候选做更细的查询—证据判断。三者是分工，不是同一能力的三个名字。",
    depth: "BM25 与向量分数来自不同空间，不能假设数值可以直接比较；RRF 主要利用各路名次融合候选。Reranker 读取问题和候选全文，通常更准确也更慢，因此只放在候选阶段之后。应分别测两路增量召回、融合后的 Candidate Recall、重排后的排序质量和新增 P95，而不是只看最终回答。",
    ask: "追问客户：失败查询主要是编号 / 专名未命中、同义表达未命中，还是正确证据进入候选后排位太低？",
    tag: "检索架构",
    basis: "检索论文 + 厂商实验边界",
    evidence: [
      { sourceId: "bm25-book", supports: "支持稀疏检索对词项、稀有度与文档长度的基本评分机制。" },
      { sourceId: "bert-reranker", supports: "支持在候选召回之后进行查询—段落联合重排。" },
      { sourceId: "contextual-retrieval", supports: "支持混合检索与重排值得在客户语料上做组合实验，不提供通用收益承诺。" },
    ],
  },
  {
    q: "什么时候值得上 Agentic RAG、GraphRAG 或多模态 RAG？",
    a: "先让普通 RAG 在真实问题上达到可诊断基线，再只为明确的问题形态增加复杂度：多步选源用 Agentic，跨文档关系归纳用 GraphRAG，答案依赖图表与版面时用多模态。",
    depth: "三类扩展改变的是不同环节：Agentic RAG 增加路由、循环和工具；GraphRAG 增加实体关系、社区与摘要索引；多模态 RAG 增加视觉解析或页面级表示。它们会扩大索引成本、运行轨迹、评估集和安全面，不能用架构名称代替适用性证据。",
    ask: "追问客户：普通 RAG 的失败样本中，有多少确实需要多步查询、全局关系分析或视觉信息，而不是基础解析与召回问题？",
    tag: "架构演进",
    basis: "RAG 综述 + GraphRAG / 视觉检索研究",
    evidence: [
      { sourceId: "rag-survey", supports: "支持 Naive、Advanced 与 Modular RAG 的能力分层和组件化视角。" },
      { sourceId: "graphrag", supports: "支持 GraphRAG 面向跨语料全局归纳问题的研究路线。" },
      { sourceId: "colpali-2025", supports: "支持视觉丰富文档的页面多向量检索路线；不保证所有文档都需要视觉检索。" },
    ],
  },
  {
    q: "RAG 上线几个月后效果变差，应该怎样排查？",
    a: "先比较同一冻结评估集与线上失败样本，沿数据、切块、召回、重排、上下文、生成六段定位变化；不要先凭感觉改 Prompt 或换模型。",
    depth: "检查源文档、解析器、Embedding、索引、过滤规则、Reranker、模型、Prompt 和缓存版本是否变化，并按来源、问题类型、租户与时间切片。HTTP 正常不代表答案质量正常；线上应保存可脱敏的 Trace、来源 ID、组件版本和拒答原因，失败样本经人工确认后回流评估集。",
    ask: "追问客户：是否能把一次失败回答还原到命中文档、候选排名、最终上下文和确切模型 / Prompt 版本？",
    tag: "生产运营",
    basis: "持续评估 + 风险管理",
    evidence: [
      { sourceId: "ragas", supports: "支持将上下文相关性、回答相关性与忠实度分开衡量。" },
      { sourceId: "nist-genai-profile", supports: "支持部署后持续测量、监测和管理生成式 AI 风险。" },
      { sourceId: "opentelemetry-semconv", supports: "支持用标准化遥测关联模型与应用链路；业务质量字段仍需项目定义。" },
    ],
  },
  {
    q: "开启 Agentic Retrieval 或查询分解后，是不是一定更准确？",
    a: "不一定。它们只在多意图、多跳或需要选源的问题上可能增加有效召回；精确编号、短事实和简单单跳请求可能因改写丢词、调用变多而变慢甚至变差。",
    depth: "建立查询切片：精确查找、语义解释、多跳比较、跨源任务分别保留原查询基线。对每个子查询记录命中文档、增量召回、额外 P95 和成本；如果分解没有带来新证据，就应回到确定性单次检索。Azure 文档还明确警告生成式改写可能遗漏产品代码等精确词项，且该能力当前标注为预览。",
    ask: "追问客户：真实问题中有多少需要多跳或跨源？哪些唯一编号、日期和否定条件绝不能被改写丢失？",
    tag: "查询规划",
    basis: "论文机制 + 官方产品边界 + 客户切片实验",
    evidence: [
      { sourceId: "hyde-2023", supports: "支持用假设文档改善特定零样本稠密检索，并明确生成文档可能包含幻觉。" },
      { sourceId: "azure-search-query-rewrite", supports: "支持保留原查询并生成替代查询，也直接说明改写可能遗漏精确唯一词项。" },
      { sourceId: "aws-bedrock-query-decomposition", supports: "支持复杂查询可选地分解为多个子查询，并可能增加查询次数。" },
    ],
  },
  {
    q: "文档已经删除或用户已经撤权，为什么系统还会回答旧内容？",
    a: "因为源系统、解析产物、向量与关键词索引、摘要、缓存和权限快照是不同副本。任何一层没有收到删除或撤权事件，都可能继续暴露旧内容。",
    depth: "沿完整链路检查 source_version、删除 Tombstone、索引作业、孤儿文档、ACL 版本、问答缓存和最终引用。新增、修改、删除和撤权要有独立 SLA 与负向探针；任务显示成功后，仍需用已撤权身份查询并确认正文、元数据和缓存答案均不可见。",
    ask: "追问客户：权限变化是否会更新源文件时间戳？哪些派生层和缓存持有内容？删除与撤权要求多快端到端生效？",
    tag: "时效与权限",
    basis: "官方同步机制 + 零信任验收",
    evidence: [
      { sourceId: "aws-bedrock-kb-sync", supports: "支持新增、修改与删除需要通过增量同步传播到知识库。" },
      { sourceId: "azure-search-indexer-lifecycle", supports: "支持 Reset 不自动删除孤儿文档，并说明部分 ACL 变化可能绕过高水位检测。" },
      { sourceId: "nist-zero-trust", supports: "支持每次资源访问前重新认证授权，而非信任旧权限快照。" },
    ],
  },
  {
    q: "答案已经带出处，是否就可以认定可信或合规？",
    a: "不能。还要确认出处是否直接支持对应主张、是否覆盖所有关键主张、是否为当前有效版本，以及当前用户是否有权查看。",
    depth: "把答案拆成数字、期限、条件和结论等可核验主张，分别绑定原文坐标；对引用正确性和引用完整性单独验收。一个相关链接可能没有支持具体结论；一个准确引用也可能来自过期或不适用版本。高风险任务还要保留证据对象、冲突处理和人工复核记录。",
    ask: "追问客户：哪些主张必须逐项有证据？谁决定权威版本？引用能否回到用户有权访问的原文位置？",
    tag: "证据治理",
    basis: "同行评审引用评估 + 风险治理",
    evidence: [
      { sourceId: "alce-2023", supports: "支持把引用是否支撑主张与关键主张是否被完整覆盖分开评估。" },
      { sourceId: "nist-genai-profile", supports: "支持对来源、有效性、透明度和生成式 AI 风险持续治理。" },
    ],
  },
  {
    q: "更换 Embedding 模型或重建索引时，RAG 必须停机吗？",
    a: "通常需要全量回填新向量，但不必让在线业务停机。可采用新旧索引并存、双写变化、影子查询、小流量切换和保留旧索引回滚的蓝绿迁移。",
    depth: "先冻结语料快照和稳定 Chunk ID，在新索引完成全量 Embedding；迁移期让新增、修改、删除和 ACL 变化同步进入两边。用同一问题集比较召回、排序、P95、成本与越权负例，再通过别名或应用路由灰度切换。最后确认删除与撤权一致性后才退役旧索引。",
    ask: "追问客户：索引能否双写？是否有稳定文档 ID、路由层、影子流量、回滚窗口和额外存储预算？",
    tag: "无停机迁移",
    basis: "官方索引能力 + 工程发布方法",
    evidence: [
      { sourceId: "azure-search-index-alias", supports: "支持通过稳定别名指向搜索索引，为切换与回滚提供具体产品机制。" },
      { sourceId: "azure-search-indexer-lifecycle", supports: "支持索引重建、增量同步与删除处理具有不同生命周期。" },
      { sourceId: "opentelemetry-semconv", supports: "支持以标准遥测关联影子查询和组件版本；质量门槛仍需项目定义。" },
    ],
  },
];
