import { moduleList } from "./knowledge-map.mjs";
import { moduleContentRegistry } from "./module-content-registry.mjs";
import { moduleCurriculumContent } from "./module-curriculum-content.mjs";
import { moduleLearningContent } from "./module-learning-content.mjs";

/**
 * 全站统一来源台账（Reference Ledger）。
 *
 * 模块正文只保存来源 ID；标题、链接、证据类别、边界与核验日期统一在此维护。
 * referenceModules 明确记录每个模块使用的来源，避免新增模块时把来源误归到 RAG。
 */

export const sourceLedger = {
  "google-mlops-predictive-ai": {
    grade: "P",
    kind: "官方架构指南",
    shortTitle: "Google Cloud MLOps",
    title: "MLOps: Continuous delivery and automation pipelines in machine learning",
    note: "说明预测式 AI 的 CI、CD、持续训练、数据与模型验证、Feature Store 和元数据管理；该页面明确主要适用于 predictive AI，不能直接当作生成式 AI 应用工程的完整规范。",
    verifiedAt: "2026-07-21",
    href: "https://docs.cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning",
  },
  "aws-sagemaker-feature-store": {
    grade: "P",
    kind: "官方产品文档",
    shortTitle: "SageMaker Feature Store",
    title: "Create, store, and share features with Feature Store — Amazon SageMaker AI",
    note: "区分低延迟在线最新特征与供训练、探索和批量预测使用的离线历史，并说明训练—服务偏差、元数据和删除行为；产品能力不自动保证时间正确性或数据质量。",
    verifiedAt: "2026-07-21",
    href: "https://docs.aws.amazon.com/sagemaker/latest/dg/feature-store.html",
  },
  "aws-sagemaker-model-registry": {
    grade: "P",
    kind: "官方产品文档",
    shortTitle: "SageMaker Model Registry",
    title: "Model Registration Deployment with Model Registry — Amazon SageMaker AI",
    note: "列出模型生产目录、版本、指标、血缘、阶段、审批、部署和 CI/CD 能力；这些产品对象不能替代组织自己的风险分级与批准责任。",
    verifiedAt: "2026-07-21",
    href: "https://docs.aws.amazon.com/sagemaker/latest/dg/model-registry.html",
  },
  "azure-ml-registries": {
    grade: "P",
    kind: "官方产品文档",
    shortTitle: "Azure ML Registries",
    title: "Machine Learning registries — Azure Machine Learning",
    note: "说明在工作区之外集中存储并共享模型、环境、组件和数据资产，以及从开发向测试和生产晋升；身份、网络、区域和数据控制仍需单独验证。",
    verifiedAt: "2026-07-21",
    href: "https://learn.microsoft.com/en-us/azure/machine-learning/concept-machine-learning-registries-mlops?view=azureml-api-2",
  },
  "nist-ai-rmf": {
    grade: "O",
    kind: "官方风险管理框架",
    shortTitle: "NIST AI RMF",
    title: "NIST Artificial Intelligence Risk Management Framework",
    note: "NIST 当前页面说明 AI RMF 供自愿采用、用于在 AI 产品与系统生命周期中纳入可信风险，并明确 AI RMF 1.0 正在修订；它不是产品认证或法律合规结论。",
    verifiedAt: "2026-07-21",
    href: "https://www.nist.gov/itl/ai-risk-management-framework",
  },
  "iso-iec-42001": {
    grade: "O",
    kind: "国际标准",
    shortTitle: "ISO/IEC 42001:2023",
    title: "ISO/IEC 42001:2023 — Artificial intelligence management system",
    note: "ISO 官方页面说明该标准规定组织建立、实施、维护并持续改进 AI 管理体系的要求；管理体系标准不直接证明单个模型输出正确、安全或满足所有法律。",
    verifiedAt: "2026-07-21",
    href: "https://www.iso.org/standard/42001",
  },
  "bm25-book": {
    grade: "A",
    kind: "权威教材",
    shortTitle: "BM25 教材",
    title: "Introduction to Information Retrieval — Okapi BM25",
    note: "稀疏检索的概率排序、词频、逆文档频率与长度归一化基础。",
    verifiedAt: "2026-07-17",
    href: "https://nlp.stanford.edu/IR-book/html/htmledition/okapi-bm25-a-non-binary-model-1.html",
  },
  "dpr-2020": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "DPR",
    title: "Dense Passage Retrieval for Open-Domain Question Answering",
    note: "双编码器稠密检索；论文特定开放域问答数据集上，top-20 passage retrieval accuracy 较其 Lucene-BM25 基线高 9–19 个百分点，不能外推为稠密检索普遍更优。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2020.emnlp-main.550/",
  },
  "hnsw-2016": {
    grade: "A",
    kind: "一手论文",
    shortTitle: "HNSW",
    title: "Efficient and Robust Approximate Nearest Neighbor Search Using Hierarchical Navigable Small World Graphs",
    note: "解释常见向量索引 HNSW 的分层近邻图与近似最近邻搜索机制。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/1603.09320",
  },
  "rag-survey": {
    grade: "A",
    kind: "研究综述",
    shortTitle: "RAG 综述",
    title: "Retrieval-Augmented Generation for Large Language Models: A Survey",
    note: "系统整理 Naive、Advanced、Modular RAG，以及检索、增强、生成与评估环节。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2312.10997",
  },
  graphrag: {
    grade: "A",
    kind: "一手论文",
    shortTitle: "GraphRAG",
    title: "From Local to Global: A Graph RAG Approach to Query-Focused Summarization",
    note: "用实体图、社区和社区摘要处理跨整个语料的全局归纳问题。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2404.16130",
  },
  "chunking-study": {
    grade: "A",
    kind: "任务特定研究",
    shortTitle: "代码 RAG 切块实验",
    title: "How Does Chunking Affect Retrieval-Augmented Code Completion?",
    note: "代码补全任务中的切块控制实验；只能说明切块需要按任务实测，不能直接代表合同、PDF 或扫描件。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2605.04763",
  },
  "rag-original-2020": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "原始 RAG 论文",
    title: "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks",
    note: "原始 RAG 定义、检索与生成的协同方式、外部知识增强机制，以及查询编码器与生成器的联合优化范围。",
    verifiedAt: "2026-07-17",
    href: "https://proceedings.neurips.cc/paper/2020/hash/6b493230205f780e1bc26945df7481e5-Abstract.html",
  },
  "bert-reranker": {
    grade: "A",
    kind: "一手论文",
    shortTitle: "BERT Reranker",
    title: "Passage Re-ranking with BERT",
    note: "查询—段落联合重排的经典二阶段方法；精排只能重新排序已召回候选，不能找回候选集外的证据。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/1901.04085",
  },
  "fid-2021": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "Fusion-in-Decoder",
    title: "Leveraging Passage Retrieval with Generative Models for Open Domain Question Answering",
    note: "说明多段证据可被独立编码并在解码器聚合；更多 passage 带来的收益只适用于论文实验，不能外推为上下文越多越好。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2021.eacl-main.74/",
  },
  "replug-2024": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "REPLUG",
    title: "REPLUG: Retrieval-Augmented Black-Box Language Models",
    note: "验证冻结黑盒语言模型、在模型外训练可调检索器，并把检索文档前置到模型输入的模块化路线。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2024.naacl-long.463/",
  },
  "self-rag": {
    grade: "A",
    kind: "一手论文",
    shortTitle: "Self-RAG",
    title: "Self-RAG: Learning to Retrieve, Generate, and Critique through Self-Reflection",
    note: "按需决定是否检索，并通过反思 token 评价检索证据与自身生成；不表示普通 RAG 自动拥有自检能力。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2310.11511",
  },
  "lost-middle": {
    grade: "A",
    kind: "同行评审期刊论文",
    shortTitle: "Lost in the Middle",
    title: "Lost in the Middle: How Language Models Use Long Contexts",
    note: "在论文的多文档问答与键值检索实验中，相关信息位置显著影响表现；不能据此断言所有模型都相同或 RAG 必然优于长上下文。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2024.tacl-1.9/",
  },
  "contextual-retrieval": {
    grade: "B",
    kind: "厂商实验",
    shortTitle: "Contextual Retrieval",
    title: "Contextual Retrieval",
    note: "特定实验中，混合检索将 top-20 failure rate 从 5.7% 降至 2.9%，加重排后为 1.9%；只适合作为客户 PoC 的验证假设。",
    verifiedAt: "2026-07-17",
    href: "https://www.anthropic.com/engineering/contextual-retrieval",
  },
  ragas: {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "RAGAS",
    title: "RAGAS: Automated Evaluation of Retrieval Augmented Generation",
    note: "提出 Faithfulness、Answer Relevance、Context Relevance 三个无参考答案自动评估维度；不直接给出业务、安全、P95 或成本门槛。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2024.eacl-demo.16/",
  },
  "nist-genai-profile": {
    grade: "O",
    kind: "官方风险管理框架",
    shortTitle: "NIST AI 600-1",
    title: "Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile",
    note: "以 Govern / Map / Measure / Manage 组织生成式 AI 风险治理；它是自愿采用的风险框架，不是产品认证或 RAG 性能标准。",
    verifiedAt: "2026-07-17",
    href: "https://doi.org/10.6028/NIST.AI.600-1",
  },
  "nist-aml-100-2e2025": {
    grade: "O",
    kind: "官方技术报告 / 攻击分类",
    shortTitle: "NIST AML Taxonomy",
    title: "NIST AI 100-2 E2025 — Adversarial Machine Learning: A Taxonomy and Terminology of Attacks and Mitigations",
    note: "为规避、投毒、隐私与滥用等对抗性机器学习攻击提供统一术语和生命周期视角；分类不是认证，也不证明列出的缓解措施在具体系统中有效。",
    verifiedAt: "2026-07-20",
    href: "https://csrc.nist.gov/pubs/ai/100/2/e2025/final",
  },
  "nist-zero-trust": {
    grade: "O",
    kind: "官方特别出版物 / 架构指南",
    shortTitle: "NIST SP 800-207",
    title: "Zero Trust Architecture",
    note: "访问企业资源前验证主体并执行授权，不因网络位置或资产归属给予隐式信任；RAG 中的检索过滤是该原则的工程应用。",
    verifiedAt: "2026-07-17",
    href: "https://csrc.nist.gov/pubs/sp/800/207/final",
  },
  "owasp-prompt-injection": {
    grade: "G",
    kind: "社区安全指南",
    shortTitle: "OWASP LLM01",
    title: "OWASP LLM01:2025 Prompt Injection",
    note: "将提示注入（Prompt Injection）列为生成式 AI 应用的重要风险，并明确 RAG、微调或系统提示都不能单独消除该风险。",
    verifiedAt: "2026-07-17",
    href: "https://genai.owasp.org/llmrisk/llm01-prompt-injection/",
  },
  "owasp-llm-top-ten": {
    grade: "G",
    kind: "社区安全指南",
    shortTitle: "OWASP LLM Top 10",
    title: "OWASP Top 10 for LLM Applications 2025",
    note: "汇总提示注入、敏感信息泄露、供应链、数据与模型投毒、输出处理、过度授权及向量弱点等常见风险；适合检查威胁模型是否漏项，不是合规认证。",
    verifiedAt: "2026-07-20",
    href: "https://genai.owasp.org/llm-top-10/",
  },
  "owasp-vector-weaknesses": {
    grade: "G",
    kind: "社区安全指南",
    shortTitle: "OWASP LLM08",
    title: "OWASP LLM08:2025 Vector and Embedding Weaknesses",
    note: "覆盖多租户向量库的跨上下文泄漏、细粒度访问控制、逻辑隔离、来源校验与检索日志。",
    verifiedAt: "2026-07-17",
    href: "https://genai.owasp.org/llmrisk/llm082025-vector-and-embedding-weaknesses/",
  },
  "china-ai-content-labeling": {
    grade: "O",
    kind: "官方规范性文件",
    shortTitle: "生成合成内容标识办法",
    title: "人工智能生成合成内容标识办法",
    note: "规定显式与隐式标识及服务提供者、传播平台等主体的相关义务，自 2025 年 9 月 1 日起施行；具体适用性仍需按产品、内容与角色判断。",
    verifiedAt: "2026-07-21",
    href: "https://www.nrta.gov.cn/art/2025/3/14/art_113_70340.html?xxgkhide=1",
  },
  "c2pa-2-4": {
    grade: "O",
    kind: "开放标准",
    shortTitle: "C2PA 2.4",
    title: "C2PA Technical Specification 2.4",
    note: "定义签名 Manifest、内容绑定、编辑与来源声明及验证状态；它能验证声明与资产的关联和防篡改，不证明内容真实、版权成立、身份正确或已经合规，凭证也可能被移除。",
    verifiedAt: "2026-07-20",
    href: "https://spec.c2pa.org/specifications/specifications/2.4/specs/C2PA_Specification.html",
  },
  "gb-45438-2025": {
    grade: "O",
    kind: "强制性国家标准",
    shortTitle: "GB 45438-2025",
    title: "网络安全技术 人工智能生成合成内容标识方法",
    note: "国家标准全文公开系统显示该标准于 2025 年 2 月 28 日发布、2025 年 9 月 1 日实施；工程落地仍要核对正式文本与适用范围。",
    verifiedAt: "2026-07-21",
    href: "https://openstd.samr.gov.cn/bzgk/std/newGbInfo?hcno=F32EA2A561F1886CD8D606513512D547",
  },
  "eu-ai-act": {
    grade: "O",
    kind: "官方法规实施页面",
    shortTitle: "EU AI Act",
    title: "European AI Act — Regulatory Framework",
    note: "欧盟委员会页面当前列出 2026 年 8 月的总体适用节点，并记录 2026 年政治协议后部分高风险系统延至 2027 或 2028 的安排；时间表仍属动态事实，页面摘要不能替代正式法律文本与具体法律意见。",
    verifiedAt: "2026-07-21",
    href: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai",
  },
  "docling-report": {
    grade: "A",
    kind: "技术报告",
    shortTitle: "Docling",
    title: "Docling Technical Report",
    note: "覆盖 PDF 转换、版面分析与表格结构识别；证明解析工具的结构化能力，不直接证明采用后企业 RAG 准确率必然提升。",
    verifiedAt: "2026-07-17",
    href: "https://research.ibm.com/publications/docling-technical-report",
  },
  "pp-ocr-2020": {
    grade: "A",
    kind: "一手论文",
    shortTitle: "PP-OCR",
    title: "PP-OCR: A Practical Ultra Lightweight OCR System",
    note: "给出文本检测、方向分类和文本识别组成的实用 OCR 系统；证明扫描图像文字识别的技术路线，不保证任意扫描质量或版式都能可靠恢复。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2009.09941",
  },
  "colpali-2025": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "ColPali",
    title: "ColPali: Efficient Document Retrieval with Vision Language Models",
    note: "用视觉语言模型直接为文档页图像生成多向量表示，面向视觉丰富文档检索；论文结果不能直接外推到客户图片、语言和算力条件。",
    verifiedAt: "2026-07-17",
    href: "https://proceedings.iclr.cc/paper_files/paper/2025/hash/99e9e141aafc314f76b0ca3dd66898b3-Abstract-Conference.html",
  },
  "fine-tuning-or-retrieval": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "Fine-Tuning or Retrieval?",
    title: "Fine-Tuning or Retrieval? Comparing Knowledge Injection in LLMs",
    note: "在论文设定下，RAG 对新事实注入优于所比较的无监督微调；不能外推为所有微调都不适合知识更新。",
    verifiedAt: "2026-07-17",
    href: "https://aclanthology.org/2024.emnlp-main.15/",
  },
  "hf-trl-data-formats": {
    grade: "P",
    kind: "官方工程文档",
    shortTitle: "TRL 数据格式",
    title: "Hugging Face TRL — Dataset Formats and Types",
    note: "说明文本、对话、提示—补全与偏好数据的标准和 conversational 表示；用于核对训练器输入结构，不代表特定数据集质量或适用性。",
    verifiedAt: "2026-07-20",
    href: "https://huggingface.co/docs/trl/en/dataset_formats",
  },
  "hf-trl-chat-templates": {
    grade: "P",
    kind: "官方工程文档",
    shortTitle: "TRL Chat Templates",
    title: "Hugging Face TRL — Chat Templates",
    note: "解释聊天模板、角色格式、特殊 Token 与训练时损失掩码；不同基座模板并不通用，必须按目标模型配置复核。",
    verifiedAt: "2026-07-20",
    href: "https://huggingface.co/docs/trl/chat_templates",
  },
  "hf-trl-sft-trainer": {
    grade: "P",
    kind: "官方工程文档",
    shortTitle: "TRL SFTTrainer",
    title: "Hugging Face TRL — SFT Trainer",
    note: "说明监督微调训练器支持的数据类型、训练与评估配置及模型模板处理；工具能力不等于训练结果有效，仍需独立任务评估。",
    verifiedAt: "2026-07-20",
    href: "https://huggingface.co/docs/trl/en/sft_trainer",
  },
  "hf-trl-dpo-trainer": {
    grade: "P",
    kind: "官方工程文档",
    shortTitle: "TRL DPOTrainer",
    title: "Hugging Face TRL — DPO Trainer",
    note: "说明 DPO 的 chosen/rejected 偏好数据和训练配置；文档证明实现方式，不证明某项偏好目标或数据标注天然正确。",
    verifiedAt: "2026-07-20",
    href: "https://huggingface.co/docs/trl/en/dpo_trainer",
  },
  "hf-trl-peft": {
    grade: "P",
    kind: "官方工程文档",
    shortTitle: "TRL × PEFT",
    title: "Hugging Face TRL — PEFT Integration",
    note: "说明 LoRA、QLoRA 与 TRL 训练器的集成，以及冻结基座、训练额外参数的常见方式；实际质量、显存和服务兼容仍需按模型与硬件验证。",
    verifiedAt: "2026-07-20",
    href: "https://huggingface.co/docs/trl/peft_integration",
  },
  "openai-agent-guide": {
    grade: "B",
    kind: "厂商实践指南",
    shortTitle: "OpenAI Agent 指南",
    title: "A practical guide to building agents",
    note: "将基础 Agent 概括为模型、工具和指令，并说明单 / 多 Agent 编排、护栏、停止条件与人工介入；属于厂商经验框架，不是通用产品认证或效果保证。",
    verifiedAt: "2026-07-17",
    href: "https://openai.com/business/guides-and-resources/a-practical-guide-to-building-ai-agents/",
  },
  "openai-model-spec-hidden-cot": {
    grade: "P",
    kind: "官方模型行为规范",
    shortTitle: "OpenAI Model Spec · Hidden CoT",
    title: "OpenAI Model Spec (2025-10-27) — Hidden chain-of-thought",
    note: "说明部分 OpenAI 模型会生成隐藏思维链，但不会向用户或开发者暴露，最多可能提供摘要。该来源只能证明 OpenAI 模型的接口与信息边界，不能外推为所有模型或唯一审计标准。",
    verifiedAt: "2026-07-17",
    href: "https://model-spec.openai.com/2025-10-27",
  },
  "anthropic-effective-agents": {
    grade: "B",
    kind: "厂商工程指南",
    shortTitle: "Building Effective Agents",
    title: "Building effective agents",
    note: "区分预定义代码路径的 Workflow 与由模型动态决定过程和工具使用的 Agent，并整理常见编排模式；属于厂商工程经验，模式适配仍需客户 PoC。",
    verifiedAt: "2026-07-17",
    href: "https://www.anthropic.com/engineering/building-effective-agents",
  },
  "react-2023": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "ReAct",
    title: "ReAct: Synergizing Reasoning and Acting in Language Models",
    note: "提出推理、动作与环境观察交替的 Agent 路线；ALFWorld / WebShop 的 34 / 10 个百分点提升只适用于论文任务、模型和提示设置，不能外推为企业 Agent 通用收益。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2210.03629",
  },
  "webarena-2024": {
    grade: "A",
    kind: "同行评审论文",
    shortTitle: "WebArena",
    title: "WebArena: A Realistic Web Environment for Building Autonomous Agents",
    note: "以可复现网站和可验证终态评估长链网页任务；原始论文最佳 GPT-4 Agent 为 14.41%，人类为 78.24%，是 2023 年实验基线，不代表当前模型水平。",
    verifiedAt: "2026-07-17",
    href: "https://arxiv.org/abs/2307.13854",
  },
  "google-agent-platform": {
    grade: "P",
    kind: "官方产品文档",
    shortTitle: "Google Agent Platform",
    title: "Scale your agents — Gemini Enterprise Agent Platform",
    note: "说明托管 Agent Runtime、Sessions、Memory、沙箱、身份、Tracing、Logging、Monitoring 与评估等平台能力；产品名称、地域、发布阶段、配额和价格须按采购时点复核。",
    verifiedAt: "2026-07-17",
    href: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/scale",
  },
  "aws-agentcore": {
    grade: "P",
    kind: "官方产品文档",
    shortTitle: "Amazon Bedrock AgentCore",
    title: "Overview — Amazon Bedrock AgentCore",
    note: "说明 Runtime、Memory、Gateway、Identity、沙箱、Observability、Evaluations 与 Policy 等模块化能力；官方能力说明不等于特定客户任务成功率，发布状态与地域须当期复核。",
    verifiedAt: "2026-07-17",
    href: "https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/what-is-bedrock-agentcore.html",
  },
  "aws-agentcore-memory": {
    grade: "P",
    kind: "官方产品文档",
    shortTitle: "AgentCore Memory",
    title: "Memory — Amazon Bedrock AgentCore",
    note: "区分会话内原始事件形成的短期记忆，与通过语义、摘要、偏好、情节或自定义策略提取并跨会话检索的长期记忆，并说明按 actor / session 隔离；这是 AgentCore 的产品实现，不是所有 Agent 框架的统一定义。",
    verifiedAt: "2026-07-17",
    href: "https://docs.aws.amazon.com/bedrock-agentcore/latest/devguide/harness-memory.html",
  },
  "azure-foundry-agent-service": {
    grade: "P",
    kind: "官方产品文档",
    shortTitle: "Microsoft Foundry Agent Service",
    title: "What is Microsoft Foundry Agent Service?",
    note: "说明配置型与代码型 Agent、模型和工具、托管身份 / RBAC / OBO、网络隔离及端到端观测；产品能力、区域、预览状态与计价须按采购时点复核。",
    verifiedAt: "2026-07-17",
    href: "https://learn.microsoft.com/en-us/azure/foundry/agents/overview",
  },
  "opentelemetry-semconv": {
    grade: "O",
    kind: "开放可观测规范",
    shortTitle: "OpenTelemetry SemConv",
    title: "OpenTelemetry Semantic Conventions",
    note: "为 traces、metrics、logs、events 和资源定义核心与跨组件语义命名；GenAI 专用约定已迁往独立仓库，业务成功、审批与风险字段仍需项目自行扩展。",
    verifiedAt: "2026-07-17",
    href: "https://opentelemetry.io/docs/specs/semconv/",
  },
  "opentelemetry-genai-semconv": {
    grade: "O",
    kind: "开放可观测规范",
    shortTitle: "OTel GenAI SemConv",
    title: "OpenTelemetry Semantic Conventions for Generative AI",
    note: "独立维护生成式 AI 客户端、Agent、MCP、检索与工具调用等遥测语义；当前仍在开发，内容字段多为可选采集，采用时应固定版本并自行补充业务终态、审批和风险字段。",
    verifiedAt: "2026-07-21",
    href: "https://github.com/open-telemetry/semantic-conventions-genai",
  },
  "openai-prompting-guide": {
    grade: "P",
    kind: "官方技术文档",
    shortTitle: "OpenAI Prompting",
    title: "Prompting | OpenAI API",
    note: "建议将生产提示作为应用代码版本化，用类型化或已校验输入构造动态部分，并在每次发布时运行代表性测试与评估；这些是厂商特定建议，不是跨模型消息协议。",
    verifiedAt: "2026-07-17",
    href: "https://developers.openai.com/api/docs/guides/prompting",
  },
  "openai-structured-outputs": {
    grade: "P",
    kind: "官方 API 文档",
    shortTitle: "Structured Outputs",
    title: "Structured model outputs | OpenAI API",
    note: "Structured Outputs 可使支持模型的输出遵守所提供 JSON Schema；仍需处理拒答、截断和不支持的 Schema 特性，结构遵循不证明字段值事实正确或业务合规。",
    verifiedAt: "2026-07-17",
    href: "https://developers.openai.com/api/docs/guides/structured-outputs",
  },
  "openai-function-calling": {
    grade: "P",
    kind: "官方 API 文档",
    shortTitle: "Function Calling",
    title: "Function calling | OpenAI API",
    note: "工具调用是应用与模型之间的五步闭环；工具定义和 strict Schema 不授予权限，执行、参数校验与审批仍属于应用责任。",
    verifiedAt: "2026-07-17",
    href: "https://developers.openai.com/api/docs/guides/function-calling",
  },
  "google-prompt-introduction": {
    grade: "P",
    kind: "官方技术文档",
    shortTitle: "Google Prompt 入门",
    title: "Introduction to prompting | Gemini Enterprise Agent Platform",
    note: "将 Task、System Instructions、Few-shot Examples 与 Contextual Information 列为常见提示组成；该分类服务于 Google 模型与平台，不是跨厂商正式标准。",
    verifiedAt: "2026-07-17",
    href: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/prompts/introduction-prompt-design",
  },
  "google-prompt-strategies": {
    grade: "P",
    kind: "官方技术文档",
    shortTitle: "Google Prompt 策略",
    title: "Overview of prompting strategies | Gemini Enterprise Agent Platform",
    note: "把提示工程描述为以目标和成功结果为前提的测试驱动迭代过程，覆盖目标、指令、约束、上下文、Few-shot 与响应格式等组成。",
    verifiedAt: "2026-07-17",
    href: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/prompts/prompt-design-strategies",
  },
  "google-system-instructions": {
    grade: "P",
    kind: "官方技术文档",
    shortTitle: "Google System Instructions",
    title: "System instructions | Gemini Enterprise Agent Platform",
    note: "说明系统指令可定义角色、格式、风格、目标和上下文，同时明确它不能完全阻止越狱或泄漏，不应存放敏感信息；角色和优先级以具体 API 为准。",
    verifiedAt: "2026-07-17",
    href: "https://docs.cloud.google.com/gemini-enterprise-agent-platform/models/prompts/system-instruction-introduction",
  },
  "anthropic-prompt-overview": {
    grade: "P",
    kind: "官方技术文档",
    shortTitle: "Anthropic Prompt Overview",
    title: "Prompt engineering overview | Claude Platform Docs",
    note: "提示优化前应先有清晰成功标准、可实测方法和初版提示；并指出并非所有失败指标都适合靠提示工程解决，例如时延与成本有时更适合换模型。",
    verifiedAt: "2026-07-17",
    href: "https://platform.claude.com/docs/en/build-with-claude/prompt-engineering/overview",
  },
  "transformer-2017": {
    grade: "A", kind: "同行评审论文", shortTitle: "Transformer",
    title: "Attention Is All You Need",
    note: "提出以自注意力为核心的 Transformer 架构；支持解释并行训练与注意力机制，不代表所有后续模型实现完全相同。",
    verifiedAt: "2026-07-17", href: "https://arxiv.org/abs/1706.03762",
  },
  "gqa-2023": {
    grade: "A", kind: "同行评审论文", shortTitle: "Grouped-Query Attention",
    title: "GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints",
    note: "比较 Multi-Head、Multi-Query 与 Grouped-Query Attention，并展示减少 KV Head 的质量与速度折中；论文结论受模型、硬件和实验设定限制。",
    verifiedAt: "2026-07-20", href: "https://aclanthology.org/2023.emnlp-main.298/",
  },
  "sentencepiece-2018": {
    grade: "A", kind: "同行评审论文", shortTitle: "SentencePiece",
    title: "SentencePiece: A simple and language independent subword tokenizer and detokenizer for Neural Text Processing",
    note: "提出直接从原始文本训练、以子词单元完成分词与还原的语言无关方法；支持解释 Token 边界由词表和分词器决定，不代表所有模型采用同一算法或词表。",
    verifiedAt: "2026-07-20", href: "https://aclanthology.org/D18-2012/",
  },
  "switch-transformer-2022": {
    grade: "A", kind: "同行评审期刊论文", shortTitle: "Switch Transformer",
    title: "Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity",
    note: "研究稀疏 Mixture-of-Experts 路线，以路由器为每个 Token 选择部分专家；支持区分总参数与激活参数，不证明 MoE 模型必然优于稠密模型。",
    verifiedAt: "2026-07-20", href: "https://www.jmlr.org/papers/v23/21-0998.html",
  },
  "chinchilla-2022": {
    grade: "A", kind: "一手论文", shortTitle: "Chinchilla Scaling",
    title: "Training Compute-Optimal Large Language Models",
    note: "研究模型规模与训练 token 配比的计算最优关系；结论受论文模型族、数据和训练设定限制，不能直接换算客户训练预算。",
    verifiedAt: "2026-07-17", href: "https://arxiv.org/abs/2203.15556",
  },
  "lora-2021": {
    grade: "A", kind: "同行评审论文", shortTitle: "LoRA",
    title: "LoRA: Low-Rank Adaptation of Large Language Models",
    note: "提出冻结基础权重并训练低秩适配矩阵的参数高效微调方法；实际质量、显存与速度仍取决于模型、任务和实现。",
    verifiedAt: "2026-07-17", href: "https://arxiv.org/abs/2106.09685",
  },
  "qlora-2023": {
    grade: "A", kind: "同行评审论文", shortTitle: "QLoRA",
    title: "QLoRA: Efficient Finetuning of Quantized LLMs",
    note: "展示量化基础模型上的参数高效微调路线；论文实验不能外推为任意模型、硬件和客户数据都能保持同等质量。",
    verifiedAt: "2026-07-17", href: "https://arxiv.org/abs/2305.14314",
  },
  "instructgpt-2022": {
    grade: "A", kind: "同行评审论文", shortTitle: "InstructGPT",
    title: "Training language models to follow instructions with human feedback",
    note: "展示监督微调、偏好数据和强化学习形成指令跟随模型的路线；支持训练阶段分工，不构成通用企业效果承诺。",
    verifiedAt: "2026-07-17", href: "https://arxiv.org/abs/2203.02155",
  },
  "dpo-2023": {
    grade: "A", kind: "同行评审论文", shortTitle: "DPO",
    title: "Direct Preference Optimization: Your Language Model is Secretly a Reward Model",
    note: "提出直接用偏好对优化语言模型的对齐方法；适用性依赖偏好数据质量、任务与基线。",
    verifiedAt: "2026-07-17", href: "https://arxiv.org/abs/2305.18290",
  },
  "deepseek-r1-2025": {
    grade: "A", kind: "同行评审期刊论文", shortTitle: "DeepSeek-R1",
    title: "DeepSeek-R1 incentivizes reasoning in LLMs through reinforcement learning",
    note: "展示可验证奖励、强化学习、冷启动数据、多阶段训练与蒸馏在一个模型族中的组合路线；结果不能外推为强化学习会自动提升所有开放任务，也不能把内部推理当作审计解释。",
    verifiedAt: "2026-07-20", href: "https://www.nature.com/articles/s41586-025-09422-z",
  },
  "clip-2021": {
    grade: "A", kind: "同行评审论文", shortTitle: "CLIP",
    title: "Learning Transferable Visual Models From Natural Language Supervision",
    note: "通过图像—文本对比学习形成共享语义表征；支持跨模态检索基础，不保证视觉事实、计数或空间推理正确。",
    verifiedAt: "2026-07-17", href: "https://arxiv.org/abs/2103.00020",
  },
  "vit-2021": {
    grade: "A", kind: "同行评审论文", shortTitle: "Vision Transformer",
    title: "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale",
    note: "将图像 Patch 序列交给 Transformer 的经典路线；用于解释视觉 token 化，不代表所有多模态模型采用相同架构或计费。",
    verifiedAt: "2026-07-17", href: "https://arxiv.org/abs/2010.11929",
  },
  "vllm-2023": {
    grade: "A", kind: "同行评审论文", shortTitle: "vLLM / PagedAttention",
    title: "Efficient Memory Management for Large Language Model Serving with PagedAttention",
    note: "提出 PagedAttention 与面向 LLM Serving 的 KV Cache 内存管理；论文吞吐结果受模型、硬件和负载限制。",
    verifiedAt: "2026-07-17", href: "https://arxiv.org/abs/2309.06180",
  },
  "vllm-prefix-caching": {
    grade: "P", kind: "官方技术文档", shortTitle: "vLLM Prefix Caching",
    title: "Automatic Prefix Caching — vLLM",
    note: "说明自动前缀缓存复用共享前缀的 KV Cache，并明确它主要减少 Prefill 计算而不减少新 Token 的 Decode 时间；具体收益依赖前缀命中、负载与隔离策略。",
    verifiedAt: "2026-07-20", href: "https://docs.vllm.ai/en/latest/features/automatic_prefix_caching/",
  },
  "distserve-2024": {
    grade: "A", kind: "同行评审论文", shortTitle: "DistServe",
    title: "DistServe: Disaggregating Prefill and Decoding for Goodput-optimized Large Language Model Serving",
    note: "直接研究 Prefill / Decode 分离以及 TTFT、TPOT 约束下的 Goodput；论文收益受模型、硬件、网络、调度和请求分布限制。",
    verifiedAt: "2026-07-20", href: "https://www.usenix.org/conference/osdi24/presentation/zhong-yinmin",
  },
  "flashattention-2022": {
    grade: "A", kind: "同行评审论文", shortTitle: "FlashAttention",
    title: "FlashAttention: Fast and Memory-Efficient Exact Attention with IO-Awareness",
    note: "通过 IO-aware 算法减少注意力计算的内存访问；具体收益依赖序列、硬件、内核与推理栈。",
    verifiedAt: "2026-07-17", href: "https://arxiv.org/abs/2205.14135",
  },
  "mcp-architecture": {
    grade: "O", kind: "官方技术文档", shortTitle: "MCP Architecture",
    title: "Architecture overview — Model Context Protocol",
    note: "定义 Host、Client、Server、数据层、传输层及 Tools / Resources / Prompts 等核心原语；协议不规定 AI 应用怎样管理模型或上下文。",
    verifiedAt: "2026-07-17", href: "https://modelcontextprotocol.io/docs/learn/architecture",
  },
  "mcp-authorization": {
    grade: "O", kind: "官方技术文档", shortTitle: "MCP Authorization",
    title: "Authorization — Model Context Protocol Specification",
    note: "规定远程 MCP 的授权角色、发现、访问令牌与安全考虑；实现仍需结合身份系统、租户策略和业务权限。",
    verifiedAt: "2026-07-21", href: "https://modelcontextprotocol.io/specification/2025-11-25/basic/authorization",
  },
  "mcp-security": {
    grade: "O", kind: "官方安全指南", shortTitle: "MCP Security",
    title: "Security Best Practices — Model Context Protocol",
    note: "整理 MCP 实现中的令牌、代理、会话与权限风险；属于协议安全指南，不替代组织自身威胁建模和控制验证。",
    verifiedAt: "2026-07-17", href: "https://modelcontextprotocol.io/docs/tutorials/security/security_best_practices",
  },
  "mcp-tasks-2025-11-25": {
    grade: "O", kind: "官方协议文档", shortTitle: "MCP Tasks",
    title: "Tasks — Model Context Protocol 2025-11-25",
    note: "定义对 MCP 请求进行耐久包装的实验性 Task、轮询、延迟结果、状态和取消语义；它仍可能演进，也不等同于 A2A 的跨 Agent Task。",
    verifiedAt: "2026-07-21", href: "https://modelcontextprotocol.io/specification/2025-11-25/basic/utilities/tasks",
  },
  "mcp-elicitation-2025-11-25": {
    grade: "O", kind: "官方协议文档", shortTitle: "MCP Elicitation",
    title: "Elicitation — Model Context Protocol 2025-11-25",
    note: "定义 Form 与 URL 两种用户交互模式；密码、API Key、访问令牌和支付凭据不得经 Form 收集，URL 交互仍需展示目标域名并取得用户同意。Elicitation 不替代 MCP 或业务授权。",
    verifiedAt: "2026-07-20", href: "https://modelcontextprotocol.io/specification/2025-11-25/client/elicitation",
  },
  "a2a-concepts": {
    grade: "O", kind: "官方技术文档", shortTitle: "A2A Core Concepts",
    title: "Core Concepts — A2A Protocol",
    note: "定义 Agent Card、Task、Message、Part 与 Artifact 等跨 Agent 协作对象；不规定单个 Agent 内部实现。",
    verifiedAt: "2026-07-17", href: "https://a2a-protocol.org/latest/topics/key-concepts/",
  },
  "a2a-specification": {
    grade: "O", kind: "官方技术文档", shortTitle: "A2A Specification",
    title: "A2A Protocol Specification",
    note: "A2A 最新规范入口，覆盖发现、任务生命周期、交互与协议绑定；版本、SDK 和产品支持需在采购与实施时点复核。",
    verifiedAt: "2026-07-17", href: "https://a2a-protocol.org/latest/specification/",
  },
  "a2a-spec-1-0-0": {
    grade: "O", kind: "官方协议文档", shortTitle: "A2A 1.0.0",
    title: "A2A Protocol Specification v1.0.0",
    note: "固定 A2A 1.0.0 的版本协商、AgentInterface、多协议绑定、Agent Card 签名和任务语义；网络连通或签名有效不证明业务能力、质量或授权成立。",
    verifiedAt: "2026-07-21", href: "https://a2a-protocol.org/v1.0.0/specification/",
  },
  "openai-models": {
    grade: "P", kind: "模型目录", shortTitle: "OpenAI Models",
    title: "Models — OpenAI API",
    note: "OpenAI 官方模型目录；型号、能力、上下文、可用接口、退役与计价属于高时效事实，必须按使用时点复核。",
    verifiedAt: "2026-07-17", href: "https://developers.openai.com/api/docs/models",
  },
  "openai-reasoning-guide": {
    grade: "P", kind: "官方技术文档", shortTitle: "OpenAI Reasoning Guide",
    title: "Reasoning models — OpenAI API",
    note: "说明部分 OpenAI 模型可用 reasoning effort 调节思考强度，并带来质量、速度与 Token 使用取舍；这是厂商特定的当前 API 能力，支持值和默认值随模型而异。",
    verifiedAt: "2026-07-20", href: "https://developers.openai.com/api/docs/guides/reasoning",
  },
  "google-models": {
    grade: "P", kind: "模型目录", shortTitle: "Gemini Models",
    title: "Models — Gemini API",
    note: "Google 官方 Gemini 模型目录；型号、能力、限制和发布阶段会变化，不在知识正文固化当前排名。",
    verifiedAt: "2026-07-17", href: "https://ai.google.dev/gemini-api/docs/models",
  },
  "anthropic-models": {
    grade: "P", kind: "模型目录", shortTitle: "Claude Models",
    title: "Models overview — Claude Platform Docs",
    note: "Anthropic 官方 Claude 模型目录；能力、生命周期、区域和定价应在选型时重新核验。",
    verifiedAt: "2026-07-17", href: "https://platform.claude.com/docs/en/about-claude/models/overview",
  },
  "openai-prompt-caching": {
    grade: "P", kind: "官方技术文档", shortTitle: "Prompt Caching",
    title: "Prompt caching | OpenAI API",
    note: "说明 OpenAI API 的前缀缓存、命中与用量可见性；只适用于该产品当期机制，不能外推为所有平台或整体应用成本。",
    verifiedAt: "2026-07-17", href: "https://developers.openai.com/api/docs/guides/prompt-caching",
  },
  "cloudflare-ai-gateway": {
    grade: "P", kind: "官方产品文档", shortTitle: "Cloudflare AI Gateway",
    title: "AI Gateway — Cloudflare Docs",
    note: "说明 AI 网关的统一接入、分析、缓存、限流、日志和路由等产品能力；产品范围、计费和限制需按采购时点复核。",
    verifiedAt: "2026-07-17", href: "https://developers.cloudflare.com/ai-gateway/",
  },
  "kubernetes-dra": {
    grade: "O", kind: "官方技术文档", shortTitle: "Kubernetes DRA",
    title: "Dynamic Resource Allocation — Kubernetes",
    note: "说明 Kubernetes 中按设备属性、拓扑与声明分配资源的机制；功能状态和字段与 Kubernetes 版本相关。",
    verifiedAt: "2026-07-21", href: "https://kubernetes.io/docs/concepts/scheduling-eviction/dynamic-resource-allocation/",
  },
  "kubernetes-dra-1-34-ga": {
    grade: "O", kind: "官方技术文档", shortTitle: "Kubernetes DRA GA",
    title: "Kubernetes v1.34: DRA has graduated to GA",
    note: "记录 DRA 核心 API 在 Kubernetes 1.34 进入稳定 v1 并默认启用；新增特性、具体驱动与厂商支持仍有各自成熟度和兼容矩阵。",
    verifiedAt: "2026-07-21", href: "https://kubernetes.io/blog/2025/09/01/kubernetes-v1-34-dra-updates/",
  },
  "nvidia-gpu-operator": {
    grade: "P", kind: "官方产品文档", shortTitle: "NVIDIA GPU Operator",
    title: "NVIDIA GPU Operator Documentation",
    note: "说明驱动、容器运行时、设备插件、监控和 GPU 软件栈的 Kubernetes 生命周期管理；兼容矩阵与功能随版本变化。",
    verifiedAt: "2026-07-17", href: "https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/index.html",
  },
  "hyde-2023": {
    grade: "A", kind: "同行评审论文", shortTitle: "HyDE",
    title: "Precise Zero-Shot Dense Retrieval without Relevance Labels",
    note: "HyDE 先生成假设文档再检索真实语料；论文明确假设文档可能包含幻觉，因此它只能作为检索中介，不能作为回答证据。",
    verifiedAt: "2026-07-17", href: "https://aclanthology.org/2023.acl-long.99/",
  },
  "azure-search-query-rewrite": {
    grade: "P", kind: "官方产品文档", shortTitle: "Azure 查询改写",
    title: "Rewrite Queries with Semantic Ranker — Azure AI Search",
    note: "说明生成式查询改写会保留原查询并产生替代查询，也警告改写可能遗漏唯一标识或产品代码；当前文档标注为预览能力。",
    verifiedAt: "2026-07-17", href: "https://learn.microsoft.com/en-us/azure/search/semantic-how-to-query-rewrite",
  },
  "aws-bedrock-query-decomposition": {
    grade: "P", kind: "官方产品文档", shortTitle: "Bedrock 查询分解",
    title: "Configure and Customize Queries and Response Generation — Amazon Bedrock",
    note: "说明复杂查询可被拆成多个子查询，并可能执行多次知识库查询；它是可选产品能力，不代表所有请求都应启用。",
    verifiedAt: "2026-07-17", href: "https://docs.aws.amazon.com/bedrock/latest/userguide/kb-test-config.html",
  },
  "alce-2023": {
    grade: "A", kind: "同行评审论文", shortTitle: "ALCE",
    title: "Enabling Large Language Models to Generate Text with Citations",
    note: "提出面向长文本生成的引用正确性与引用完整性评估；有链接不等于全部关键主张都获得证据支持。",
    verifiedAt: "2026-07-17", href: "https://aclanthology.org/2023.emnlp-main.398/",
  },
  "aws-bedrock-kb-sync": {
    grade: "P", kind: "官方产品文档", shortTitle: "Bedrock 增量同步",
    title: "Sync a Data Source — Amazon Bedrock",
    note: "说明新增、修改或删除源文件后需要执行同步，增量任务只处理上次同步后的变化；任务完成仍需业务侧验证最终可检索状态。",
    verifiedAt: "2026-07-17", href: "https://docs.aws.amazon.com/bedrock/latest/userguide/kb-managed-sync.html",
  },
  "azure-search-indexer-lifecycle": {
    grade: "P", kind: "官方产品文档", shortTitle: "Azure 索引器生命周期",
    title: "Run or Reset Indexers — Azure AI Search",
    note: "说明高水位增量检测、Reset 与删除孤儿文档的差异，并指出部分 ACL 变化不会更新时间戳；预览 API 不能作为跨云通用能力承诺。",
    verifiedAt: "2026-07-17", href: "https://learn.microsoft.com/en-us/azure/search/search-howto-run-reset-indexers",
  },
  "azure-search-document-acl": {
    grade: "P", kind: "官方产品文档", shortTitle: "Azure 文档级访问控制",
    title: "Document-Level Access Control — Azure AI Search",
    note: "说明文档级授权过滤的产品实现方向；数据源、API 版本、预览状态和适用限制必须按部署时点核验。",
    verifiedAt: "2026-07-17", href: "https://learn.microsoft.com/en-us/azure/search/search-document-level-access-overview",
  },
  "azure-search-index-alias": {
    grade: "P", kind: "官方产品文档", shortTitle: "Azure Index Alias",
    title: "Create an Index Alias — Azure AI Search",
    note: "说明通过稳定别名切换目标索引的产品机制，可用于蓝绿迁移；功能阶段和限制不应外推为所有云搜索服务的共同事实。",
    verifiedAt: "2026-07-17", href: "https://learn.microsoft.com/en-us/azure/search/search-how-to-alias",
  },
  "openai-agents-run-loop": {
    grade: "P", kind: "官方 SDK 文档", shortTitle: "OpenAI Agent Run Loop",
    title: "Running Agents — OpenAI Agents SDK",
    note: "说明模型输出、工具调用、Handoff、final_output 与 max_turns 组成的运行器循环；SDK 结束条件不等于客户业务后置条件已满足。",
    verifiedAt: "2026-07-17", href: "https://openai.github.io/openai-agents-python/running_agents/",
  },
  "openai-agents-hitl": {
    grade: "P", kind: "官方 SDK 文档", shortTitle: "OpenAI HITL",
    title: "Human-in-the-Loop — OpenAI Agents SDK",
    note: "说明工具审批导致 Run 暂停、保存状态并在批准或拒绝后恢复；审批仍需绑定具体动作、参数和业务权限。",
    verifiedAt: "2026-07-17", href: "https://openai.github.io/openai-agents-python/human_in_the_loop/",
  },
  "a2a-task-lifecycle": {
    grade: "O", kind: "官方协议文档", shortTitle: "A2A Task Lifecycle",
    title: "Life of a Task — Agent2Agent Protocol",
    note: "说明跨 Agent Task 的状态与终态语义；它可作为外部任务协议参考，但不规定 Agent 内部运行时实现。",
    verifiedAt: "2026-07-17", href: "https://a2a-protocol.org/latest/topics/life-of-a-task/",
  },
  "openapi-3-1-1": {
    grade: "O", kind: "开放标准", shortTitle: "OpenAPI 3.1.1",
    title: "OpenAPI Specification v3.1.1",
    note: "定义 HTTP API 的机器可读接口描述；输入输出结构不能替代授权、幂等、补偿或业务后置条件。",
    verifiedAt: "2026-07-17", href: "https://spec.openapis.org/oas/v3.1.1.html",
  },
  "oauth-token-exchange": {
    grade: "O", kind: "互联网标准", shortTitle: "OAuth Token Exchange",
    title: "RFC 8693 — OAuth 2.0 Token Exchange",
    note: "定义在受控条件下交换主体或执行者令牌的标准机制；不能把共享服务账号或宽权限令牌自动视为用户委托。",
    verifiedAt: "2026-07-17", href: "https://www.rfc-editor.org/rfc/rfc8693.html",
  },
  "azure-durable-orchestration": {
    grade: "P", kind: "官方产品文档", shortTitle: "Durable Orchestration",
    title: "Durable Orchestrations — Microsoft Azure",
    note: "说明长期工作流的实例身份、事件历史、自动 Checkpoint、重放、外部事件和恢复；副作用活动仍需可重试与幂等设计。",
    verifiedAt: "2026-07-17", href: "https://learn.microsoft.com/en-us/azure/durable-task/common/durable-task-orchestrations",
  },
  "azure-durable-hitl": {
    grade: "P", kind: "官方产品文档", shortTitle: "Durable Human Interaction",
    title: "Human Interaction Pattern — Microsoft Azure Durable Task",
    note: "说明长期流程等待外部人工事件、设置超时并继续执行的耐久交互模式；它提供运行机制，不替代审批政策。",
    verifiedAt: "2026-07-17", href: "https://learn.microsoft.com/en-us/azure/durable-task/common/durable-task-human-interaction",
  },
  "openai-model-spec-command": {
    grade: "O", kind: "官方模型行为规范", shortTitle: "OpenAI Model Spec",
    title: "OpenAI Model Spec — Chain of Command",
    note: "说明不同来源指令的权限层级和不可信数据边界；这是模型行为规范，不是企业 IAM、授权策略或跨厂商统一协议。",
    verifiedAt: "2026-07-17", href: "https://model-spec.openai.com/",
  },
  "anthropic-tool-definitions": {
    grade: "P", kind: "官方产品文档", shortTitle: "Claude Tool Definitions",
    title: "Define Tools — Claude Platform",
    note: "说明工具名称、描述与输入 Schema 会进入模型上下文并影响工具选择；业务授权、幂等和执行后验证仍由应用负责。",
    verifiedAt: "2026-07-17", href: "https://platform.claude.com/docs/en/agents-and-tools/tool-use/define-tools",
  },
  "anthropic-tool-search": {
    grade: "P", kind: "官方产品文档", shortTitle: "Claude Tool Search",
    title: "Tool Search Tool — Claude Platform",
    note: "展示工具目录按需搜索和延迟加载的产品实现；发现结果只是候选能力，业务授权、工具版本、参数校验与执行后验证仍由应用负责，厂商观察不能外推为通用阈值。",
    verifiedAt: "2026-07-20", href: "https://platform.claude.com/docs/en/agents-and-tools/tool-use/tool-search-tool",
  },
  "openai-eval-best-practices": {
    grade: "P", kind: "官方工程指南", shortTitle: "OpenAI Evals 指南",
    title: "Evaluation Best Practices — OpenAI API",
    note: "支持任务特定、持续评估、生产分布样本和人工校准，并警告只靠主观观感或通用指标；示例阈值不能直接作为客户门槛。",
    verifiedAt: "2026-07-17", href: "https://developers.openai.com/api/docs/guides/evaluation-best-practices",
  },
  "llm-as-judge-2023": {
    grade: "A", kind: "同行评审论文", shortTitle: "LLM-as-a-Judge",
    title: "Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena",
    note: "研究模型评审与人工偏好的关系，并记录位置、冗长等偏差；观察依赖当时模型、任务和提示，不能外推为所有 Judge 的固定准确率。",
    verifiedAt: "2026-07-20", href: "https://papers.neurips.cc/paper_files/paper/2023/hash/91f18a1287b398d378ef22505bf41832-Abstract-Datasets_and_Benchmarks.html",
  },
  "openai-source-sink-injection": {
    grade: "O", kind: "官方安全工程文章", shortTitle: "Source–Sink 注入分析",
    title: "Designing AI Agents to Resist Prompt Injection",
    note: "把提示注入建模为不可信 Source 与危险 Sink 的组合，并强调即使检测失败也要通过权限、确认和确定性控制限制影响。",
    verifiedAt: "2026-07-17", href: "https://openai.com/index/designing-agents-to-resist-prompt-injection/",
  },
};

const referenceShortTitles = Object.freeze({
  "solution-patterns": "Solution Patterns",
  "model-landscape": "Model Landscape",
  rag: "RAG",
  "ai-agent": "Agent",
  multimodal: "Multimodal",
  mcp: "MCP",
  a2a: "A2A",
  evaluation: "Evaluation",
  "ai-governance": "AI Governance",
  security: "Security",
  "ai-gateway": "AI Gateway",
  "ai-ops": "AI Ops",
  "predictive-ai-mlops": "Predictive AI & MLOps",
  llm: "LLM",
  "prompt-engineering": "Prompt",
  "fine-tuning": "Fine-tuning",
  "llm-training": "LLM Training",
  "llm-inference": "LLM Inference",
  "data-engineering": "Data Engineering",
  "ai-infra-platform": "Infra Platform",
  "ai-infra-compute": "Infra Compute",
});

const additionalSourceIds = Object.freeze({
  rag: [
    "bm25-book", "dpr-2020", "hnsw-2016", "rag-survey", "graphrag", "chunking-study",
    "rag-original-2020", "bert-reranker", "fid-2021", "replug-2024", "self-rag",
    "lost-middle", "contextual-retrieval", "ragas", "nist-genai-profile", "nist-zero-trust",
    "owasp-prompt-injection", "owasp-vector-weaknesses", "docling-report", "pp-ocr-2020",
    "colpali-2025", "fine-tuning-or-retrieval", "opentelemetry-semconv",
  ],
  "ai-agent": [
    "openai-agent-guide", "openai-model-spec-hidden-cot", "anthropic-effective-agents", "react-2023",
    "webarena-2024", "google-agent-platform", "aws-agentcore", "aws-agentcore-memory",
    "azure-foundry-agent-service", "opentelemetry-semconv", "nist-genai-profile", "nist-zero-trust",
    "mcp-architecture", "a2a-concepts", "openai-function-calling",
  ],
  "prompt-engineering": [
    "openai-prompting-guide", "openai-structured-outputs", "openai-function-calling",
    "google-prompt-introduction", "google-prompt-strategies", "google-system-instructions",
    "anthropic-prompt-overview", "openai-model-spec-hidden-cot", "openai-prompt-caching",
    "anthropic-effective-agents", "react-2023", "nist-genai-profile", "nist-zero-trust",
    "owasp-prompt-injection",
  ],
});

function contentSourceIds(slug) {
  const content = moduleContentRegistry[slug];
  if (!content) return [];
  return [
    ...content.evidenceCards.map((card) => card.sourceId),
    ...content.qa.flatMap((item) => item.evidence.map((reference) => reference.sourceId)),
    ...(content.deepDives ?? []).flatMap((block) => block.sourceIds ?? []),
  ];
}

function learningSourceIds(slug) {
  const learning = moduleLearningContent[slug];
  if (!learning) return [];
  return learning.labs.flatMap((lab) => lab.sourceIds);
}

function curriculumSourceIds(slug) {
  const curriculum = moduleCurriculumContent[slug];
  if (!curriculum) return [];
  return curriculum.chapters.flatMap((chapter) => chapter.sourceIds);
}

export const referenceModules = moduleList.map((module) => ({
  id: module.slug,
  zh: module.zh,
  en: module.en,
  shortTitle: referenceShortTitles[module.slug],
  href: module.href,
  sourceIds: [...new Set([
    ...contentSourceIds(module.slug),
    ...learningSourceIds(module.slug),
    ...curriculumSourceIds(module.slug),
    ...(additionalSourceIds[module.slug] ?? []),
  ])],
}));
