/**
 * 专业术语中英对照的内部注册表。模块质量契约只引用稳定 termId，避免
 * 每个页面和测试各自维护一套译法。英文版未来应复用 termId 与来源关系，
 * 但文案仍需独立撰写和专业校对。
 */
export const terminology = Object.freeze({
  rag: Object.freeze({ zh: "检索增强生成", en: "Retrieval-Augmented Generation", abbr: "RAG", description: "先检索外部证据，再把证据交给模型生成可核验回答。" }),
  retrieval: Object.freeze({ zh: "检索", en: "Retrieval" }),
  augmentation: Object.freeze({ zh: "增强", en: "Augmentation" }),
  generation: Object.freeze({ zh: "生成", en: "Generation" }),
  "sparse-retrieval": Object.freeze({ zh: "稀疏检索", en: "Sparse Retrieval" }),
  "dense-retrieval": Object.freeze({ zh: "稠密检索", en: "Dense Retrieval" }),
  reranking: Object.freeze({ zh: "重排", en: "Reranking" }),
  grounding: Object.freeze({ zh: "有据生成", en: "Grounding" }),
  "ai-agent": Object.freeze({ zh: "智能体", en: "AI Agent", abbr: "Agent", description: "能围绕目标规划步骤、调用工具并根据结果继续行动的 AI 应用。" }),
  perceive: Object.freeze({ zh: "感知", en: "Perceive" }),
  reason: Object.freeze({ zh: "思考", en: "Reason" }),
  act: Object.freeze({ zh: "行动", en: "Act" }),
  observe: Object.freeze({ zh: "观察", en: "Observe" }),
  planning: Object.freeze({ zh: "规划", en: "Planning" }),
  memory: Object.freeze({ zh: "记忆", en: "Memory" }),
  tools: Object.freeze({ zh: "工具", en: "Tools" }),
  "prompt-engineering": Object.freeze({ zh: "提示词工程", en: "Prompt Engineering" }),
  "context-engineering": Object.freeze({ zh: "上下文工程", en: "Context Engineering" }),
  instructions: Object.freeze({ zh: "稳定指令", en: "Instructions" }),
  context: Object.freeze({ zh: "动态上下文", en: "Context" }),
  "tools-schema": Object.freeze({ zh: "能力接口", en: "Tools & Schema" }),
  "structured-outputs": Object.freeze({ zh: "结构化输出", en: "Structured Outputs" }),
  "prompt-injection": Object.freeze({ zh: "提示注入", en: "Prompt Injection" }),
  "solution-patterns": Object.freeze({ zh: "场景解决方案", en: "Solution Patterns" }),
  "model-landscape": Object.freeze({ zh: "模型格局与选型", en: "Model Landscape" }),
  multimodal: Object.freeze({ zh: "多模态", en: "Multimodal AI" }),
  mcp: Object.freeze({ zh: "模型上下文协议", en: "Model Context Protocol", abbr: "MCP", description: "让 AI 应用以统一方式发现并调用外部工具、资源和提示的开放协议。" }),
  a2a: Object.freeze({ zh: "智能体间协议", en: "Agent2Agent Protocol", abbr: "A2A", description: "用于不同智能体之间发现能力、委托任务和交换任务状态的协议。" }),
  evaluation: Object.freeze({ zh: "评估", en: "Evaluation" }),
  security: Object.freeze({ zh: "AI 安全", en: "AI Security" }),
  "ai-gateway": Object.freeze({ zh: "AI 网关", en: "AI Gateway" }),
  "ai-ops": Object.freeze({ zh: "AI 可观测与运营", en: "AI Operations" }),
  llm: Object.freeze({ zh: "大语言模型", en: "Large Language Model", abbr: "LLM", description: "从大量文本中学习语言分布，并按上下文逐 Token 生成输出的模型。" }),
  "fine-tuning": Object.freeze({ zh: "微调", en: "Fine-tuning" }),
  "llm-training": Object.freeze({ zh: "大模型训练", en: "LLM Training" }),
  "llm-inference": Object.freeze({ zh: "大模型推理", en: "LLM Inference" }),
  "data-engineering": Object.freeze({ zh: "AI 数据工程", en: "Data Engineering for AI" }),
  "ai-infra-platform": Object.freeze({ zh: "AI 基础设施平台", en: "AI Infrastructure Platform" }),
  "ai-infra-compute": Object.freeze({ zh: "AI 算力基础设施", en: "AI Compute Infrastructure" }),
  transformer: Object.freeze({ zh: "Transformer 架构", en: "Transformer Architecture" }),
  attention: Object.freeze({ zh: "注意力机制", en: "Attention Mechanism" }),
  "kv-cache": Object.freeze({ zh: "键值缓存", en: "Key-Value Cache", abbr: "KV Cache", description: "复用已生成 Token 的注意力键和值，减少后续解码的重复计算。" }),
  "model-routing": Object.freeze({ zh: "模型路由", en: "Model Routing" }),
  "distributed-training": Object.freeze({ zh: "分布式训练", en: "Distributed Training" }),
  lora: Object.freeze({ zh: "低秩适配", en: "Low-Rank Adaptation", abbr: "LoRA", description: "冻结大部分模型参数，只训练小型低秩矩阵的参数高效微调方法。" }),
  "batching": Object.freeze({ zh: "动态批处理", en: "Dynamic Batching" }),
  observability: Object.freeze({ zh: "可观测性", en: "Observability" }),
  guardrails: Object.freeze({ zh: "护栏", en: "Guardrails" }),
  "identity-authorization": Object.freeze({ zh: "身份与授权", en: "Identity & Authorization" }),
  "tool-discovery": Object.freeze({ zh: "工具发现", en: "Tool Discovery" }),
  "agent-collaboration": Object.freeze({ zh: "智能体协作", en: "Agent Collaboration" }),
  "golden-set": Object.freeze({ zh: "黄金评估集", en: "Golden Evaluation Set" }),
  "document-intelligence": Object.freeze({ zh: "文档智能", en: "Document Intelligence" }),
  "resource-scheduling": Object.freeze({ zh: "资源调度", en: "Resource Scheduling" }),
  "heterogeneous-compute": Object.freeze({ zh: "异构算力", en: "Heterogeneous Compute" }),
  api: Object.freeze({ zh: "应用程序编程接口", en: "Application Programming Interface", abbr: "API", description: "软件系统之间以约定格式发起请求、返回结果的接口契约。" }),
  iam: Object.freeze({ zh: "身份与访问管理", en: "Identity and Access Management", abbr: "IAM", description: "管理谁能以什么身份访问哪些资源，并记录授权与审计关系。" }),
  hitl: Object.freeze({ zh: "人在回路", en: "Human in the Loop", abbr: "HITL", description: "在高风险、模糊或不可逆环节由人工审批、纠正或接管。" }),
  poc: Object.freeze({ zh: "概念验证", en: "Proof of Concept", abbr: "PoC", description: "用受控范围验证关键假设、风险和验收指标，而不是提前承诺完整上线。" }),
  sla: Object.freeze({ zh: "服务等级协议", en: "Service Level Agreement", abbr: "SLA", description: "对可用性、性能、支持或补偿等服务水平作出的可度量约定。" }),
  tco: Object.freeze({ zh: "总拥有成本", en: "Total Cost of Ownership", abbr: "TCO", description: "把采购、运行、集成、人工维护和失败处理等完整成本一起计算。" }),
  acl: Object.freeze({ zh: "访问控制列表", en: "Access Control List", abbr: "ACL", description: "明确哪些用户或身份可以访问哪些资源及操作。" }),
  dlp: Object.freeze({ zh: "数据防泄漏", en: "Data Loss Prevention", abbr: "DLP", description: "识别并阻止敏感数据通过输入、输出、日志或文件等路径被不当传递。" }),
  sft: Object.freeze({ zh: "监督微调", en: "Supervised Fine-tuning", abbr: "SFT", description: "用输入和理想输出示范继续训练模型，使其更稳定地执行目标任务。" }),
  qlora: Object.freeze({ zh: "量化低秩适配", en: "Quantized Low-Rank Adaptation", abbr: "QLoRA", description: "在量化且冻结的基础模型上训练 LoRA Adapter，以降低微调显存需求。" }),
  dpo: Object.freeze({ zh: "直接偏好优化", en: "Direct Preference Optimization", abbr: "DPO", description: "使用偏好对让模型更倾向获选回答，适合能比较好坏但难写唯一答案的任务。" }),
  bm25: Object.freeze({ zh: "最佳匹配 25", en: "Best Matching 25", abbr: "BM25", description: "基于词频、逆文档频率和文档长度归一化的经典关键词相关性排序方法。" }),
  ann: Object.freeze({ zh: "近似最近邻", en: "Approximate Nearest Neighbor", abbr: "ANN", description: "以少量精度换取大规模向量近邻检索速度的算法类别。" }),
  hnsw: Object.freeze({ zh: "分层可导航小世界图", en: "Hierarchical Navigable Small World", abbr: "HNSW", description: "用多层近邻图加速向量搜索的常见 ANN 索引结构。" }),
  rrf: Object.freeze({ zh: "倒数排名融合", en: "Reciprocal Rank Fusion", abbr: "RRF", description: "按候选在多份排序中的名次合并结果，常用于融合关键词与向量召回。" }),
  qkv: Object.freeze({ zh: "查询、键和值", en: "Query, Key and Value", abbr: "Q / K / V", description: "注意力计算中的三组表示：提出查询、参与匹配，并提供最终聚合的信息。" }),
  ttft: Object.freeze({ zh: "首个 Token 时间", en: "Time to First Token", abbr: "TTFT", description: "从请求发出到收到首个输出 Token 的时间，反映提示处理与排队体验。" }),
  tpot: Object.freeze({ zh: "每个输出 Token 时间", en: "Time per Output Token", abbr: "TPOT", description: "首个 Token 之后生成每个 Token 的平均时间，直接影响持续输出速度。" }),
  moe: Object.freeze({ zh: "混合专家模型", en: "Mixture of Experts", abbr: "MoE", description: "每个 Token 只激活部分专家网络，以较低单次计算换取更大的总参数容量。" }),
});

export function requireTerm(termId) {
  const term = terminology[termId];
  if (!term) throw new Error(`Unknown terminology termId: ${termId}`);
  return term;
}
