// Agent · 智能体（AI Agent）模块配置。
// 本文件是该模块在全站注册表中的唯一配置源：正文只引用，不复制。
// 注册表（发布、地图、发现、简报、英文、Reference、问答等）全部从本文件派生。
import { deepFreeze } from "../freeze.mjs";
import { agentDeepDives, agentEvidenceCards, agentQa } from "../../agent-content.mjs";
import { fieldQuestions } from "../../question-field-kit.mjs";

const slug = "ai-agent";

// brief 正文：15 键统一结构 + 专用页面的呈现扩展字段。页面只引用，不复制。
const brief = {
  slug,
  definition: "一个受应用控制的 Run：模型根据当前状态选择下一步、请求工具并吸收环境结果。",
  position: "Agent 位于应用控制的任务运行层；模型选择下一步，应用负责授权、执行、恢复和验收。",
  presentation: "dedicated",
  principleTitle: "Agent 的基础概念与工作循环",
  principles: [],
  decisions: [],
  deepDiveTitle: "Agent 的生产托管条件",
  deepDiveLead: "生产托管要回答四个问题：Run 以什么终态结束，工具怎样受权执行，进程崩溃后从哪里恢复，记忆与委托怎样维持最小信任。",
  deepDives: agentDeepDives,
  criticalBoundary: "工具调用意图、工具执行成功和业务完成是三件事；身份、授权、真实动作、停止与最终验收必须留在确定性控制层。",
  cloudHooks: [
    { stage: "模型与路由", services: "模型即服务、模型目录、推理端点、AI 网关、内容安全", value: "按任务复杂度选择模型并统一限流、版本和策略", discover: "哪些决策需要强模型？是否允许跨地域或多模型？" },
    { stage: "Agent Runtime", services: "托管 Agent 运行时、Serverless、容器、Kubernetes、任务队列", value: "运行循环和长任务，管理状态、超时、重试与弹性", discover: "任务持续多久？同步还是异步？失败如何恢复？" },
    { stage: "工具接入", services: "API 网关、MCP Gateway、函数计算、工作流、事件总线、SaaS 连接器", value: "把业务 API 整理成可发现、可校验、可管理的工具", discover: "有哪些现成 API？读写动作如何分级和审批？" },
    { stage: "知识与状态", services: "托管搜索、向量库、数据库、对象存储、缓存、会话与 Memory", value: "保存证据、任务状态和经过治理的长期记忆", discover: "哪些状态是权威事实？谁能修改、撤回和删除？" },
    { stage: "身份与安全", services: "IAM、工作负载身份、密钥管理、策略引擎、WAF、私网与沙箱", value: "让每次工具调用绑定真实主体并执行最小权限", discover: "用用户身份还是服务身份？哪些动作不可逆？" },
    { stage: "可观测与评估", services: "Tracing、日志、指标、APM、评估平台、告警、SIEM", value: "还原任务轨迹，定位失败并持续检查质量和风险", discover: "怎样确认任务最终完成？日志能否关联模型与工具步骤？" },
    { stage: "运营与 FinOps", services: "预算、配额、成本分析、缓存、容量与发布平台", value: "控制轮次、工具消耗和每个成功任务成本", discover: "P95、并发、任务预算和回滚要求是什么？" },
  ],
  relatedSlugs: ["llm", "prompt-engineering", "rag", "solution-patterns", "mcp", "a2a", "evaluation", "security"],
  qa: agentQa,
  evidenceCards: agentEvidenceCards,
  facts: [
    { label: "采用条件", value: "新证据会改变下一步" },
    { label: "模型责任", value: "提出结构化动作意图" },
    { label: "应用责任", value: "身份、策略、执行与停止" },
    { label: "完成证据", value: "权威系统后置条件" },
  ],
  chapters: [
    { id: "agent-principle", label: "是否需要 Agent", eyebrow: "采用边界" },
    { id: "agent-loop", label: "一次 Agent Run", eyebrow: "任务循环" },
    { id: "harness", label: "Harness 与工程边界", eyebrow: "运行控制" },
    { id: "capabilities", label: "规划、工具与核心能力", eyebrow: "动作契约" },
    { id: "memory-interaction", label: "状态、记忆与互操作", eyebrow: "恢复边界" },
    { id: "architecture", label: "架构与生产托管", eyebrow: "上线设计" },
    { id: "poc", label: "PoC、评估与上线门", eyebrow: "验收证据" },
    { id: "evidence", label: "现场证据与问答", eyebrow: "客户查证" },
  ],
  designChain: [
    { zh: "任务与最终状态", en: "Task & Outcome" },
    { zh: "指令与工具", en: "Instructions & Tools" },
    { zh: "身份与策略", en: "Identity & Policy" },
    { zh: "评测与红队", en: "Evals & Red Team" },
    { zh: "版本与发布", en: "Version & Release" },
  ],
  servingChain: [
    { zh: "请求与身份", en: "Request & Identity" },
    { zh: "Agent 循环", en: "Agent Loop" },
    { zh: "策略与工具", en: "Policy & Tools" },
    { zh: "状态与记忆", en: "State & Memory" },
    { zh: "验证或接管", en: "Verify / Handoff" },
  ],
  conceptLinks: [
    { concept: "模型与推理", owner: "大语言模型原理", href: "/modules/llm", relation: "能力底座", local: "模型负责理解状态和选择下一步，但不应直接获得业务权限。" },
    { concept: "指令与上下文", owner: "提示词工程", href: "/modules/prompt-engineering", relation: "行为约束", local: "把角色、目标、边界、工具规则和输出契约组织为可版本化指令。" },
    { concept: "RAG 与知识", owner: "RAG · 检索增强生成", href: "/modules/rag", relation: "数据工具", local: "为 Agent 提供可更新证据；检索只是任务链中的一种工具能力。" },
    { concept: "工作流 · Workflow", owner: "场景解决方案", href: "/modules/solution-patterns", relation: "确定性骨架", local: "固定规则负责可预测路径，Agent 只处理真正需要动态判断的节点。" },
    { concept: "MCP", owner: "模型上下文协议", href: "/modules/mcp", relation: "工具互操作", local: "标准化工具与上下文的连接方式，不替代身份、授权和业务审批。" },
    { concept: "A2A", owner: "A2A · 智能体间协议", href: "/modules/a2a", relation: "Agent 协作", local: "面向 Agent 发现、委派与结果交换；不等于多 Agent 架构本身。" },
    { concept: "评估与治理", owner: "评估", href: "/modules/evaluation", relation: "上线检查", local: "用可验证的最终状态衡量任务成功，并检查轨迹、安全、时延与成本。" },
    { concept: "身份与授权", owner: "AI 安全", href: "/modules/security", relation: "执行边界", local: "应用在每次工具调用前绑定主体、验证权限、执行策略并留下审计证据。" },
  ],
  agentLoop: [
    { zh: "感知", en: "Perceive" },
    { zh: "思考", en: "Reason" },
    { zh: "行动", en: "Act" },
    { zh: "观察", en: "Observe" },
    { zh: "继续 / 终止", en: "Continue / Stop" },
  ],
  agentActions: [
    {
      code: "01",
      title: "感知 · Perceive",
      definition: "把用户请求、系统事件和当前环境状态，整理成 Agent 此刻能够处理的任务表示。感知不是把所有数据塞进上下文，而是识别目标、对象、约束、身份和仍缺少的信息。",
      mechanism: "入口层先完成身份绑定、意图识别、输入校验与上下文选择；必要时调用搜索、OCR、数据库或传感器接口补齐证据，再形成结构化任务状态。",
      io: "输入：自然语言、事件、会话状态、业务记录。输出：目标、已知事实、约束、风险等级、待确认项。",
      failure: "常见失败：误解目标、忽略附件或权限、把不可信内容当指令、上下文过载、引用了过期状态。",
      control: "工程控制：输入 Schema、来源标记、Prompt Injection 隔离、时效检查、缺失字段追问。",
      cloud: "云服务连接：多模态模型、文档解析 / OCR、托管搜索、事件总线、API 网关、身份服务。",
      presales: "售前判断：客户的任务入口有哪些？哪套系统是事实源？输入是否跨模态、跨租户或有实时性要求？",
    },
    {
      code: "02",
      title: "思考 · Reason",
      definition: "基于目标、当前状态和可用工具，判断下一步是补充信息、调用工具、修改计划、给出结果，还是停止并交还人工。这里的重点是可执行决策，不是展示模型内部推理文字。",
      mechanism: "模型把任务状态与工具契约进行匹配，评估候选动作的前置条件、风险与预期结果；复杂任务可先规划，简单任务可逐步决策，并在每次观察后重新判断。",
      io: "输入：任务状态、计划、记忆、工具目录、策略与预算。输出：结构化动作意图、参数草案、决策摘要或终止原因。",
      failure: "常见失败：凭空假设、目标漂移、选择错误工具、反复规划不行动、忽略业务规则或把不确定判断说成事实。",
      control: "工程控制：限定动作空间、结构化输出、风险规则、轮次 / token 预算、检查点、低置信度接管。",
      cloud: "云服务连接：模型服务与路由、AI 网关、内容安全、策略引擎、评估平台、Prompt 版本管理。",
      presales: "售前判断：哪些决策确实需要模型？正确性如何验证？是否允许模型在多个工具之间自主选择？",
    },
    {
      code: "03",
      title: "行动 · Act",
      definition: "把模型提出的动作意图交给应用执行：查询知识、调用 API、运行代码、发送消息或修改业务状态。模型提出调用，不代表它拥有凭据或可以绕过审批。",
      mechanism: "应用根据工具 Schema 校验参数，绑定用户或工作负载身份，执行授权与策略判断；通过后才调用真实系统，并把结果、错误与操作凭证返回给 Agent。",
      io: "输入：工具名、结构化参数、调用主体、策略上下文。输出：执行结果、错误码、资源版本、操作编号与可回滚信息。",
      failure: "常见失败：选错 API、参数越界、重复扣款 / 重复建单、超时后误重试、越权调用、部分成功未补偿。",
      control: "工程控制：最小权限、参数白名单、幂等键、预览与审批、超时重试、事务 / 补偿、沙箱与审计。",
      cloud: "云服务连接：API / MCP Gateway、函数计算、工作流、IAM、密钥管理、沙箱、私网连接与消息队列。",
      presales: "售前判断：哪些动作只读、可逆或高风险？现有 API 是否稳定？失败后能否回滚、补偿和追责？",
    },
    {
      code: "04",
      title: "观察 · Observe",
      definition: "读取行动产生的真实环境反馈，并判断预期状态是否已经发生。观察与感知的区别是：感知建立本轮起点，观察验证刚刚行动的结果。",
      mechanism: "解析工具返回、回读权威系统、比较前置 / 后置状态，更新任务状态和证据；随后触发下一轮思考，或确认完成、失败、超时和人工接管。",
      io: "输入：API 响应、数据库状态、事件、错误、Trace。输出：已验证事实、状态增量、异常、完成证据和下一轮信号。",
      failure: "常见失败：把 HTTP 200 当业务成功、忽略异步状态、相信模型生成的成功描述、未发现部分失败、旧结果污染下一轮。",
      control: "工程控制：后置条件、Read-after-Write、来源与时间戳、Checkpoint、异常分类、最终状态检查和人工复核。",
      cloud: "云服务连接：数据库 / 缓存、事件总线、Tracing、日志与指标、评估平台、告警和状态存储。",
      presales: "售前判断：客户用哪个系统状态证明任务完成？异步结果多久可见？失败和人工接管由谁运营？",
    },
  ],
  engineeringScopes: [
    { scope: "一次交互", name: "Prompt Engineering", question: "这一轮应该怎样告诉模型？", input: "任务说明、示例与约束", owner: "Prompt 负责人", owns: "任务说明、示例、约束与输出契约。", boundary: "不决定上下文选择，也不执行工具或业务规则。" },
    { scope: "每次调用", name: "Context Engineering", question: "每一步应该让模型看到什么？", input: "身份、历史、证据与工具定义", owner: "应用 / 数据团队", owns: "身份、历史、证据、工具定义与当前状态的选择和装配。", boundary: "不负责任务循环、授权与故障恢复。" },
    { scope: "完整任务", name: "Harness Engineering", question: "整个任务如何运行、行动、验证、恢复和受控？", input: "动作意图、工具契约、状态与策略", owner: "Agent 平台 / 应用团队", owns: "运行循环、工具执行、状态、权限、预算、验证、恢复和观测。", boundary: "不定义业务成功，也不代替业务 Owner 验收。" },
    { scope: "完整产品", name: "Agent 工程 · Agent Engineering", question: "如何把模型、Harness 与业务系统做成可运营产品？", input: "业务流程、体验、风险与 SLO", owner: "业务 Owner + 产品 + 工程", owns: "业务流程、体验、组织责任、发布、治理与长期运营。", boundary: "各责任团队仍需分别签字并完成运营交接。" },
  ],
  harnessLayers: [
    { title: "内层 Harness", en: "Inner Harness", body: "直接围绕模型调用：上下文装配、工具选择与参数、循环、压缩、停止、结构化输出和局部评分。" },
    { title: "外层 Harness", en: "Outer Harness", body: "围绕完整任务运行：身份与审批、沙箱、工作区、检查点、重试、终态验证、Trace、发布与人工接管。" },
  ],
  harnessNeighbors: [
    { name: "Tool", role: "提供一个可调用能力", boundary: "不负责完整任务循环与恢复。" },
    { name: "MCP", role: "标准化工具、资源与 Prompt 的连接", boundary: "不自动提供业务授权和终态验证。" },
    { name: "Skill / Rule", role: "提供可复用知识、步骤或约束", boundary: "通常由 Harness 发现、注入和执行。" },
    { name: "Workflow", role: "以代码或流程图确定路径与状态", boundary: "可包住 Agent，也可被 Harness 调用。" },
    { name: "Framework", role: "提供开发抽象和组件 API", boundary: "实现范围可能只覆盖部分 Harness。" },
    { name: "Sandbox", role: "隔离命令、代码、网络和文件副作用", boundary: "是 Harness 的执行控制之一。" },
    { name: "Agent Platform", role: "把运行时、身份、观测与运营产品化", boundary: "通常承载一个或多个 Harness。" },
  ],
  harnessEvaluationDimensions: [
    "任务成功与关键后置条件",
    "多次运行稳定性与复现率",
    "Token、时间、金额与工具调用预算",
    "P95 与每个成功任务成本",
    "工具、权限和轨迹正确性",
    "策略违规与不可逆误执行",
    "阻塞识别、Safe Exit 与人工接管",
    "崩溃恢复、幂等、Kill Switch 与补偿",
    "独立证据、版本与失败归因",
    "模型、环境与业务迁移成本",
  ],
  architecturePatterns: [
    { name: "确定性工作流 · Deterministic Workflow", cue: "步骤清楚、规则稳定、错误代价高", pipeline: "固定步骤 → 条件分支 → 人工审批", boundary: "最易测试和审计；不要为追求 Agent 标签而增加自治。" },
    { name: "工作流中的 LLM 步骤 · LLM Step", cue: "需要语义提取、分类或草稿，但后续路径固定", pipeline: "Workflow 决定何时调用 → 模型返回结构化结果 → 规则继续", boundary: "模型参与一个节点，不等于需要可循环的 Agent Run。" },
    { name: "单智能体 · Single Agent", cue: "新证据会改变下一步，但职责仍集中", pipeline: "模型 ↔ 获准工具 ↔ 环境反馈，循环至退出", boundary: "默认的 Agent 起点；必须先定义 Run、预算、终态和接管。" },
    { name: "多智能体 · Multi-Agent", cue: "子任务独立并行，或上下文、权限必须隔离", pipeline: "父任务委托 → 子任务执行 → 父任务验证与收口", boundary: "只有实测收益覆盖交接、P95、权限传播和评估成本时才拆分。" },
  ],
  coreCapabilities: [
    {
      code: "P",
      title: "规划 · Planning",
      definition: "把目标分解为可检查的子目标，并选择顺序、工具、依赖和停止条件。规划是当前信息下的行动假设，不是必须照做到底的脚本。",
      mechanism: "简单任务采用逐步规划（每轮只定下一步）；长任务采用计划—执行（先列里程碑，再逐项验证）；可并行任务可由编排者拆给执行者，汇总后再校验。",
      io: "输入：目标、当前状态、工具能力、约束、时间与成本预算。输出：里程碑、候选动作、依赖、预期结果、检查点和退出条件。",
      failure: "常见失败：过度规划、遗漏前置条件、计划与工具不匹配、环境变化后仍照旧执行、拆分过细导致成本激增。",
      control: "工程控制：计划 Schema、最大深度 / 轮次、预算、关键里程碑审批、每次观察后重规划、最终状态检查。",
      cloud: "云服务连接：Agent Runtime、工作流 / 任务编排、模型路由、队列、分布式任务、评估与 Trace。",
      presales: "售前判断：路径为什么不可预先确定？任务最长多久？哪些里程碑必须人工确认？并行带来的收益是否覆盖成本？",
    },
    {
      code: "M",
      title: "记忆 · Memory",
      definition: "为后续决策保留有用信息。当前 Run 的工作状态、跨轮会话信息和跨会话长期记忆用途不同；记忆不是把全部聊天记录永久保存。",
      mechanism: "运行状态保存本次任务的目标、步骤、工具结果与预算；短期会话记忆保存当前会话事件与上下文；情节记忆保存过去任务经历；语义记忆保存经过核验的偏好或事实。长期写入前提取、去重、校验来源，读取时按主体、任务和时效检索。",
      io: "输入：对话、工具结果、用户确认、业务事件。输出：带主体、来源、时间、置信度、范围与保留期的记忆条目，或与当前任务相关的记忆片段。",
      failure: "常见失败：错误总结被永久化、跨用户串记忆、旧偏好覆盖新事实、敏感信息过度保留、检索到记忆却忽略适用范围。",
      control: "工程控制：命名空间、来源、TTL、版本、用户确认、访问控制、加密、纠正 / 删除、写入与读取评估。",
      cloud: "云服务连接：会话存储、数据库、向量检索、对象存储、缓存、KMS、数据治理与生命周期管理。",
      presales: "售前判断：要记住什么、为谁记、保存多久？谁能纠正和删除？哪些事实必须每次回到权威系统读取？",
    },
    {
      code: "T",
      title: "工具 · Tools",
      definition: "Agent 与外部世界交互的受控能力接口，包括知识工具（搜索 / RAG）、动作工具（业务 API）、计算工具（代码 / 函数）和协作工具（消息 / 其他 Agent）。",
      mechanism: "工具目录向模型暴露名称、唯一用途、输入输出 Schema、错误语义和使用边界；模型选择并生成参数，应用负责校验、授权、执行，把真实结果送回观察阶段。",
      io: "输入：工具描述、调用意图、结构化参数、身份与策略。输出：结构化结果、错误、操作凭证、资源状态和审计记录。",
      failure: "常见失败：工具职责重叠、描述含糊、参数幻觉、返回内容注入、读写权限混放、错误语义不足导致无限重试。",
      control: "工程控制：清晰 Tool Contract、最小工具集、读写分级、Schema、IAM、幂等、超时、限流、审批、审计与沙箱。",
      cloud: "云服务连接：API Gateway、MCP Gateway、函数计算、SaaS 连接器、服务目录、IAM、密钥、工作流与服务网格。",
      presales: "售前判断：工具是否已有 API？模型能否清楚区分？谁是调用主体？哪些写操作需要预览、审批和补偿？",
    },
  ],
  memoryLayers: [
    { layer: "当前任务状态", en: "Work State", stores: "目标、当前步骤、工具结果、预算、停止原因", read: "每一轮", write: "运行时在检查点更新", boundary: "任务结束后按审计与恢复要求保留；不能冒充业务事实源。" },
    { layer: "会话状态", en: "Session State", stores: "本次会话历史、临时偏好、未完成事项", read: "当前会话", write: "对话或事件触发", boundary: "应有 TTL、用户与租户隔离，避免无限累积。" },
    { layer: "长期记忆", en: "Long-term Memory", stores: "经确认的偏好、情节摘要、可复用经验", read: "与主体和任务相关时", write: "提取、去重、校验后", boundary: "允许纠正与删除；模型总结不能自动成为长期真相。" },
    { layer: "权威业务事实", en: "Authoritative Facts", stores: "订单、余额、政策、权限、资源真实状态", read: "需要做决定或验收时", write: "只由业务系统和获授权流程", boundary: "Agent 可以读取或提出变更，但不能把 Memory 当作权威记录。" },
  ],
  interactionBoundaries: [
    { capability: "Function Calling", purpose: "表达一次工具调用意图和结构化参数", owns: "模型 ↔ 应用", boundary: "应用仍负责授权、执行、幂等、回读与审批。" },
    { capability: "MCP", purpose: "统一发现并连接工具、资源与提示原语", owns: "Agent / AI 应用 ↔ 工具与数据", boundary: "不是 Agent 编排器，也不提供天然安全认证。" },
    { capability: "A2A", purpose: "发现其他 Agent、委派任务并交换任务状态与产物", owns: "Agent ↔ Agent", boundary: "单系统内部编排不必为了使用协议而拆成分布式协作。" },
    { capability: "API / RPA / Computer Use", purpose: "把决策变成外部系统动作", owns: "应用侧控制规则 ↔ 目标系统", boundary: "有稳定 API 时优先 API；界面操作需隔离环境、最小权限与回放证据。" },
  ],
  systemLens: [
    {
      id: "agent-run",
      label: "一次 Run",
      title: "一次 Agent Run 按受控状态机推进",
      description: "每一轮都要从环境事实开始，以可验证状态结束；模型负责提出下一步，应用负责执行和确认。",
      takeaway: "工具返回成功不等于业务完成，必须由权威系统状态和最终状态检查来结束 Run。",
      nodes: [
        { label: "感知", en: "Perceive", detail: "绑定身份，读取请求、事件、事实源与仍缺少的信息。", signal: "输出：结构化任务状态" },
        { label: "思考", en: "Reason", detail: "在工具、策略、预算和当前状态下选择下一步。", signal: "输出：动作意图或停止原因" },
        { label: "行动", en: "Act", detail: "应用校验参数、授权、审批和幂等后调用真实系统。", signal: "输出：操作编号与真实返回" },
        { label: "观察", en: "Observe", detail: "回读权威状态，判断预期后置条件是否发生。", signal: "输出：已验证事实与异常" },
        { label: "继续或终止", en: "Continue / Stop", detail: "更新检查点，继续下一轮、交还人工或记录最终状态。", signal: "输出：可恢复的 Run 状态" },
      ],
    },
    {
      id: "agent-controls",
      label: "控制规则",
      title: "执行面、控制面与证据面分权",
      description: "规划、记忆和工具属于执行面；身份、策略、预算与停止属于控制面；权威状态、防篡改日志和独立评分属于证据面。",
      takeaway: "Agent 可以改变执行路径，但不能放宽自己的权限、修改验收标准或删除证明发生了什么的证据。",
      nodes: [
        { label: "执行面", detail: "模型、Harness、工具和沙箱运行任务，产出候选动作、调用和产物。", signal: "约束：版本、环境与资源上限" },
        { label: "身份与策略", detail: "在动作发生时绑定用户或工作负载身份并重新授权。", signal: "控制：最小权限与动态策略" },
        { label: "预算与停止", detail: "同时限制轮次、时间、Token、金额、工具调用和委托深度。", signal: "控制：Safe Exit 与 Kill Switch" },
        { label: "权威状态", detail: "从业务系统和云控制面回读真实副作用与最终状态。", signal: "证据：operation ID 与后置条件" },
        { label: "独立审计", detail: "由执行主体无权改写的日志、评分器和人工裁决保全证据。", signal: "证据：防篡改、可关联、可复核" },
      ],
    },
    {
      id: "agent-recovery",
      label: "一次故障",
      title: "动作结果未知是最危险的失败",
      description: "长任务、异步 API 和网络重试会产生模糊状态；可靠 Agent 必须能恢复、确认、补偿并留下证据。",
      takeaway: "每个写操作都需要幂等键、操作编号、后置条件和可恢复检查点，高风险路径还需要人工接管。",
      nodes: [
        { label: "动作已提交", detail: "Agent 发起退款、建单或资源变更，请求可能已被系统接受。", signal: "记录：幂等键与业务操作号" },
        { label: "进程中断", detail: "模型超时、Worker 崩溃或响应在网络中丢失。", signal: "保存：动作前检查点与调用证据" },
        { label: "恢复 Run", detail: "从持久状态恢复，而不是重新生成整段计划。", signal: "读取：已执行步骤与未决动作" },
        { label: "回读事实", detail: "查询业务系统确认动作成功、失败、仍处理中或状态未知。", signal: "判断：权威后置条件" },
        { label: "继续、补偿或人审", detail: "只在状态明确后继续；未知或高风险状态交还人工。", signal: "留下：最终状态、原因与审计轨迹" },
      ],
    },
  ],
  releaseAcceptanceGates: [
    { name: "端到端任务成功率", check: "由权威业务终态判定，阈值由业务 Owner 签字。", releaseBlocking: true },
    { name: "关键步骤完成率", check: "关键动作单独设门，不能被总体平均掩盖。", releaseBlocking: true },
    { name: "策略违规 = 0", check: "命中策略就暂停，不用总体成功率抵消。", releaseBlocking: true },
    { name: "高风险误执行 = 0", check: "资金、生产变更和对外发送单独计数。", releaseBlocking: true },
    { name: "人工接管率", check: "同时检查接管是否及时、是否真正解决问题。" },
    { name: "Safe Exit 上线硬门", check: "不可完成、无新增证据、权限扩大或证据面受威胁时能主动停止。", releaseBlocking: true },
    { name: "独立证据上线硬门", check: "关键授权、外部副作用和业务终态不能只由 Agent 自报。", releaseBlocking: true },
    { name: "P95 / 完成时长", check: "按任务类型和风险分层，不用平均响应时间代替。" },
    { name: "每个成功任务成本", check: "计入失败重试、工具调用和人工处理。" },
    { name: "可恢复 / 可隔离", check: "演练检查点恢复、Kill Switch、迟到结果隔离、补偿、人工接管和发布回退。" },
  ],
};

export default Object.freeze({
  slug,
  zh: "Agent · 智能体",
  en: "AI Agent",
  titleId: "agent-title",
  layerNo: "02",
  routeKind: "dedicated",
  introducedAt: "2026-07-17",
  updatedAt: "2026-09-04",
  requiredTerms: Object.freeze(["ai-agent","harness","harness-engineering","agent-engineering","perceive","reason","act","observe","planning","memory","tools"]),
  knowledgeView: "control-architecture",
  readingProfile: null,
  visualProfile: "dense-reading",
  legacyUndatedQuestionSetSha256: "53b2a8990c5769cdddd525727b6135d534dd4bbadc5501fa4fc32555e85bf114",
  contentContract: deepFreeze({"principle":["Agent 的基础概念与工作循环"],"mechanism":["感知—思考—行动—观察","规划、记忆与工具"],"boundary":["模型会调用 API，不等于模型拥有 API 权限"],"cloud":["Agent 技术环节与云服务机会"],"customer":["客户高频问题与深度回答"]}),
  brief,
  curriculum: null,
  learning: null,
  extensionViews: null,
  discovery: deepFreeze({"summary":"让模型在受控循环中规划、调用工具并推进业务任务。","cue":"客户希望 AI 不只回答，还要跨系统完成动作"}),
  referenceShortTitle: "Agent",
  additionalSourceIds: Object.freeze(["openai-agent-guide","openai-model-spec-hidden-cot","anthropic-effective-agents","react-2023","webarena-2024","google-agent-platform","aws-agentcore","aws-agentcore-memory","azure-foundry-agent-service","opentelemetry-semconv","nist-genai-profile","nist-zero-trust","mcp-architecture","a2a-concepts","openai-function-calling","openai-harness-engineering","anthropic-agent-evals","microsoft-agent-harness","nist-agent-standards","openai-hugging-face-incident-technical-report-2026","metr-openai-hf-incident-2026","ncsc-agentic-ai-risk-interim-2026","harness-bench-2026","configuring-agentic-coding-tools","swe-bench","terminal-bench","swe-rebench","product-codex-docs","product-claude-code-docs","product-github-copilot-coding-agent","product-cursor-docs","product-kiro-cli","product-devin-docs","product-openhands-docs","product-cline-docs","product-aider-docs","product-opencode-docs","product-antigravity-migration","product-gemini-cli-individual-transition","product-antigravity-cli-migration","product-gemini-cli-releases","product-qwen-code-docs","product-kimi-code-docs","product-codebuddy-docs","product-comate-agent-docs","product-tongyi-lingma","product-qoder-cn-series","product-qoder-cn-ide","product-qoder-cn-ide-changelog"]),
  englishUpdatedAt: "2026-09-04",
  englishReaderConfig: deepFreeze({"titleId":"ai-agent-english-title","shortTitle":"AI Agent","criticalBoundary":"A tool-call intent, successful tool execution, and business completion are three different claims. Deterministic controls must retain identity, authorization, real-world execution, stopping, and final acceptance.","facts":[{"label":"Adoption condition","value":"New evidence changes the next step"},{"label":"Model responsibility","value":"Propose structured action intent"},{"label":"Application responsibility","value":"Identity, policy, execution, and stopping"},{"label":"Completion proof","value":"Authoritative business postconditions"}],"directories":{"quick":[{"id":"ai-agent-english-primer-title","label":"Control loop","eyebrow":"Separate intent from authority"},{"id":"agent-adoption-decision","label":"Adoption decision","eyebrow":"Prove the path must adapt"}],"learn":[{"id":"agent-operating-model","label":"Operating model","eyebrow":"Bound the run"},{"id":"agent-harness-engineering","label":"Harness engineering","eyebrow":"Control model-facing state"},{"id":"agent-control-architecture","label":"Control architecture","eyebrow":"Place deterministic authority"},{"id":"agent-production-runtime","label":"Production runtime","eyebrow":"Recover durable work"},{"id":"agent-interoperability","label":"Interoperability","eyebrow":"Delegate without broad authority"},{"id":"agent-memory-poisoning","label":"Memory controls","eyebrow":"Preserve provenance and recovery"}],"field":[{"id":"agent-low-code-choice","label":"Delivery choice","eyebrow":"Test platform fit"},{"id":"agent-cloud-evaluation","label":"Cloud and PoC","eyebrow":"Map controls and proof"},{"id":"evidence","label":"Evidence and limits","eyebrow":"State what sources prove"},{"id":"qa","label":"Customer questions","eyebrow":"Answer with boundaries"},{"id":"related-modules","label":"Related modules","eyebrow":"Explore adjacent topics"}]},"groupIds":{"quick":["agent-adoption-decision"],"learn":["agent-operating-model","agent-harness-engineering","agent-control-architecture","agent-production-runtime","agent-interoperability","agent-memory-poisoning"],"field":["agent-low-code-choice","agent-cloud-evaluation"]},"fieldGroupsBeforeEvidence":true}),
  unifiedBriefConfig: null,
  fieldKitEntries: Object.freeze(fieldQuestions.filter((entry) => entry.questionRef.moduleId === slug)),
});
