const freezeItems = (items) => Object.freeze(items.map((item) => Object.freeze(item)));
const block = (type, title, items, extra = {}) => Object.freeze({ type, title, ...extra, items: freezeItems(items) });
const section = (id, eyebrow, title, lead, blocks) => Object.freeze({ id, eyebrow, title, lead, blocks: Object.freeze(blocks) });
const question = (id, copy) => Object.freeze({ ...copy, id, evidence: freezeItems(copy.evidence) });

export const englishModule = Object.freeze({
  slug: "a2a",
  title: "Agent2Agent Protocol",
  subtitle: "Delegate durable work across independent agents without confusing discovery with trust",
  definition: "The Agent2Agent Protocol (A2A) lets an application, service, or agent discover and interact with an independently operated remote agent. The remote agent may return a Message directly or create a stateful Task, then report status and optional Artifacts.",
  position: "This module covers the protocol and interoperability layer. A2A governs collaboration with independently operated remote agents; it does not replace local orchestration, queues, or business workflows. Agents typically access tools and data through MCP or conventional APIs.",
  relatedSlugs: Object.freeze(["ai-agent", "mcp", "ai-gateway", "security", "ai-ops"]),
  sections: Object.freeze([
    section("a2a-collaboration-model", "COLLABORATION CONTRACT", "Track collaboration without exposing private reasoning", "A2A creates value when immediate interaction or stateful delegation crosses a real ownership, system, or trust boundary. The value comes from explicit response, recovery, and acceptance semantics—not from increasing the number of agents.", [
      block("cards", "Five operating principles", [
        { id: "principle-agent-card-discovery", title: "Agent Card and discovery", body: "An Agent Card describes identity, endpoints, skills, supported interfaces, and security requirements so a client can assess how to interact.", decision: "Verify provenance, domain, version, transport, and—where supplied—the card signature. A self-declared skill is not an identity or quality certification." },
        { id: "principle-stateful-task", title: "Use a Task only when work needs state", body: "A remote agent may answer an immediate, self-contained interaction with a Message. It creates a Task when work must be tracked, paused, or recovered across time and connections.", decision: "Clients must handle both Message and Task responses. Task implementations must also define auditable persistence, recovery, cancellation, retry, and timeout rules." },
        { id: "principle-message-artifact-separation", title: "Separate Messages, Parts, and optional Artifacts", body: "A Message represents an immediate response or Task interaction, Parts carry typed content, and an Artifact is an optional Task output. Critical state and outcomes must not exist only in a Message that may not be persisted.", decision: "Exchange large or sensitive files through controlled storage references, then validate media type, integrity, safety, access, and business acceptance independently." },
        { id: "principle-delivery-modes", title: "Response path and delivery mode follow the work", body: "A direct Message, Task polling, subscription, streaming, and push suit different response rhythms and client-connectivity conditions. A delivery channel is not authoritative Task state.", decision: "Choose based on whether state tracking is needed, task duration, network boundary, and client availability; validate callback destinations, authentication, idempotency, and rate limits for push." },
        { id: "principle-opaque-collaboration", title: "Opaque internals can still have an auditable boundary", body: "An agent can expose capabilities, permitted inputs, observable state, and artifacts without disclosing private prompts, tools, or hidden reasoning.", decision: "Audit cross-organization collaboration through contracts, state, evidence, and acceptance rather than demanding internal chain-of-thought." },
      ]),
      block("boundary", "Critical boundary", [{ id: "critical-a2a-mcp-boundary", title: "A2A coordinates remote agents; MCP connects applications to tools and data", body: "One agent may use MCP internally and use A2A to obtain a direct Message or delegate stateful work to another independently operated agent.", boundary: "Discovery, interoperability, a protocol-level COMPLETED state, and a capability declaration establish neither trusted identity, business authorization, nor result acceptance." }]),
    ]),
    section("a2a-curriculum", "COURSE MAP", "Build from discovery to versioned Message-or-Task collaboration", "A2A defines protocol objects, operations, and binding contracts. Product quality, durable storage, business authorization, and result acceptance remain implementation and organizational responsibilities.", [
      block("cards", "Nine course chapters", [
        { id: "curriculum-agent-tool-boundary", title: "A2A versus MCP Tasks", body: "MCP lets an application or model access tools and resources; A2A lets a client interact with an independent remote agent through a Message or stateful Task. A2A Task is a core collaboration object, while MCP Tasks is an optional extension for durable protocol requests; their IDs and lifecycles require an explicit mapping.", decision: "Choose according to independent responsibility, state ownership, and organizational boundary, then govern the two lifecycles and authorization paths separately.", boundary: "Internal multi-agent calls do not automatically require A2A, and A2A never substitutes for tool authorization or authoritative business state.", sourceIds: ["a2a-mcp-boundary", "mcp-tasks-extension"] },
        { id: "curriculum-agent-card", title: "Agent Card and capability discovery", body: "The Agent Card declares identity, interaction endpoints, skills, capabilities, and supported interfaces. Treat it as versioned discovery metadata that must be verified and cached under policy.", decision: "Use capability declarations to form a candidate, then use organizational trust and operational evidence to approve it.", boundary: "Declaring a skill is not a commitment to quality, a right to customer data, or authorization for a particular task.", sourceIds: ["a2a-concepts", "a2a-specification"] },
        { id: "curriculum-core-objects", title: "Message, Task, Part, and Artifact", body: "SendMessage returns either a Message or a Task. Messages carry an interaction, a Task represents stateful work, Parts carry typed content, and Artifacts are optional Task outputs.", decision: "Use a direct Message for an immediate, self-contained interaction; use a Task when the interaction needs lifecycle management, and validate any Artifact independently.", boundary: "A Message is not guaranteed to be persisted, a Task need not produce an Artifact, and protocol delivery does not make an output trusted or safe to consume.", sourceIds: ["a2a-concepts", "a2a-specification"] },
        { id: "curriculum-task-lifecycle", title: "Exact Task states and recovery", body: "The specification defines nine TaskState enum values. TASK_STATE_UNSPECIFIED is the unspecified enum value; the eight non-UNSPECIFIED operational values are TASK_STATE_SUBMITTED, TASK_STATE_WORKING, TASK_STATE_INPUT_REQUIRED, TASK_STATE_AUTH_REQUIRED, TASK_STATE_COMPLETED, TASK_STATE_FAILED, TASK_STATE_CANCELED, and TASK_STATE_REJECTED. Later short labels omit the TASK_STATE_ prefix for readability.", decision: "Resume the same Task from an interrupted state; create a new related Task for revision after a terminal state. Handle duplicates, disconnection, late results, and idempotency explicitly.", boundary: "CancelTask does not prove that remote work stopped or side effects were reversed, and a network retry is not automatically a safe business retry.", sourceIds: ["a2a-specification", "opentelemetry-semconv"] },
        { id: "curriculum-version-binding", title: "A2A v1.0.1 release and 1.0 negotiation", body: "As of 2026-08-01, the latest tagged release is v1.0.1, while wire compatibility is still negotiated through A2A-Version Major.Minor 1.0. AgentInterface declares its URL, binding, and protocol version.", decision: "Track release patch, negotiated protocol version, binding, SDK, and agent capability version separately in the compatibility matrix.", boundary: "The specification says patch numbers should not be used in requests, responses, or Agent Cards and must not participate in version negotiation. Connectivity and a shared 1.0 label do not prove that every binding, SDK, or product adopted the same fixes and capabilities.", sourceIds: ["a2a-release-1-0-1", "a2a-specification"] },
        { id: "curriculum-collaboration-topology", title: "Collaboration topology and internal orchestration", body: "Central coordination, peer delegation, and hierarchical collaboration offer different control and scaling characteristics. Internal orchestration can share more state; an external A2A boundary should minimize contracts and data exposure.", decision: "Place stable contracts at ownership boundaries and keep high-frequency fine-grained coordination inside one runtime.", boundary: "More agents increase coordination, tracing, and error propagation and do not automatically improve quality.", sourceIds: ["anthropic-effective-agents", "a2a-concepts"] },
        { id: "curriculum-trust-audit", title: "Identity, artifacts, and audit", body: "Verify the caller, target agent, task authorization, and artifact access, then correlate tasks, messages, state events, policies, and external actions. Audit observed commitments and outcomes rather than hidden reasoning.", decision: "Use task evidence, policy versions, and external-action records to prove the boundary.", boundary: "Opaque internals do not remove provider responsibility, but requesting hidden chain-of-thought is not a sound substitute for audit evidence.", sourceIds: ["a2a-specification", "opentelemetry-semconv", "opentelemetry-genai-semconv"] },
        { id: "curriculum-reliability", title: "Idempotency, cancellation, and recovery", body: "A remote agent may continue after a network timeout. The delegator needs a stable Task ID, authoritative status queries, idempotency keys, cancellation semantics, partial-artifact rules, and human escalation.", decision: "Write recovery into the task contract before setting timeouts and retries.", boundary: "Cancellation receipt does not prove that side effects were reversed, and technical completion does not establish business acceptance.", sourceIds: ["a2a-concepts", "nist-genai-profile"] },
        { id: "curriculum-adoption-boundary", title: "Adoption boundary", body: "A2A fits independently operated agents that need capability discovery and durable task collaboration. A fixed integration, one organization's internal workflow, or simple event notification is often clearer through APIs, queues, or workflow engines.", decision: "Adopt A2A only when cross-boundary collaboration value exceeds protocol, identity, and operating cost.", boundary: "Calling a design 'multi-agent' does not establish a business or reliability benefit.", sourceIds: ["a2a-concepts", "anthropic-effective-agents"] },
      ]),
    ]),
    section("a2a-decisions", "PRESALES DECISIONS", "Use ownership, duration, trust, and artifact constraints to choose the boundary", "The protocol is a justified external contract only when another independently operated agent owns meaningful work.", [
      block("table", "Five recurring decisions", [
        { id: "decision-need-a2a", title: "Is A2A needed instead of one agent?", cells: ["Work must be delegated to a specialist agent with independent deployment, ownership, framework, cloud, or release cycle.", "Use A2A only where a genuine system boundary exists; keep subtasks in a local orchestrator otherwise.", "Artificially splitting one application does not create quality and adds handoff and evaluation cost."] },
        { id: "decision-a2a-internal-runtime", title: "How should A2A divide work from the internal agent framework?", cells: ["Internal nodes either share state, code, and a trust domain or are operated by different services or organizations.", "Use the local framework for fine-grained internal state and expose one stable A2A task contract at the external boundary.", "A2A does not replace an internal runtime or require every internal node to become externally visible."] },
        { id: "decision-delivery-mode", title: "Should the task block or deliver asynchronously?", cells: ["The task may wait for people or external systems, and the client may not remain connected.", "Use blocking for short work, polling for queryable long work, streaming for progressive output, and controlled push for offline notification.", "Push requires destination validation, authentication, idempotency, and rate limiting; never accept an arbitrary model-generated callback URL."] },
        { id: "decision-cross-organization-trust", title: "How do agents establish trust across organizations?", cells: ["The agent identity, caller, tenant, task scope, data class, and audit requirement can all be verified.", "Verify the Agent Card and server identity, use OAuth 2.0 or mTLS, and restrict authorization to the task, operation, and tenant.", "Finding an agent does not grant permission to delegate work or receive protected artifacts."] },
        { id: "decision-large-sensitive-artifacts", title: "How should large or sensitive artifacts be delivered?", cells: ["Outputs are large, regulated, cross-region, or must be retained for a defined period.", "Exchange short-lived controlled object references, hashes, and metadata; govern storage access and retention independently.", "A2A messages are not a bypass around storage access, region, retention, or deletion controls."] },
      ], { columns: ["Customer signal", "Recommended action", "Boundary"] }),
    ]),
    section("a2a-practice", "LEARN, PRACTICE, PROVE", "Design both immediate interaction and recoverable delegation", "Practice moves from protocol choice and the Message-or-Task branch to exact state recovery, cross-domain authorization, observability, and business acceptance.", [
      block("cards", "Learning outcomes", [
        { id: "outcome-a2a-mcp-boundary", title: "Separate A2A and MCP Tasks", body: "Determine whether the counterparty is an independent remote agent or merely exposes a tool or resource, then map the two Task lifecycles only when needed." },
        { id: "outcome-a2a-core-objects", title: "Handle Agent Card followed by Message or Task", body: "Connect discovery, immediate interaction, durable state, and optional deliverable outputs without collapsing their control meanings." },
        { id: "outcome-a2a-long-task", title: "Design disconnected and asynchronous work", body: "Recover through authoritative state and idempotent delivery instead of assuming a persistent stream." },
        { id: "outcome-a2a-trust-audit", title: "Establish cross-organization trust and audit", body: "Prove identity, task authorization, state, external actions, and artifact acceptance without exposing private reasoning." },
      ]),
      block("steps", "Recommended learning route", [
        { id: "route-decide-protocol-boundary", title: "Decide whether a protocol boundary exists", body: "Compare a single runtime, internal multi-agent coordination, and cross-system delegation.", decision: "Checkpoint: explain why one local subagent is insufficient." },
        { id: "route-master-task-state", title: "Choose Message or Task, then master exact states", body: "Cover a direct Message and a Task response. For Tasks, model all eight non-UNSPECIFIED operational states, whose formal enum names use the TASK_STATE_ prefix, plus optional Artifacts.", decision: "Checkpoint: handle both response types, duplicate delivery, disconnection, and cancellation explicitly." },
        { id: "route-handle-trust-operations", title: "Handle trust and operation", body: "Verify capability declarations, caller identity, artifact permissions, and cross-domain audit.", decision: "Checkpoint: prove the execution boundary without demanding internal prompts." },
        { id: "route-recovery-cancellation", title: "Complete recovery and cancellation semantics", body: "Use authoritative task state, idempotency, partial artifacts, compensation, and human takeover for uncertain outcomes.", decision: "Checkpoint: never repeat a high-impact action blindly after a timeout." },
        { id: "route-validate-adoption-value", title: "Validate adoption value", body: "Compare A2A with APIs, events, workflows, and internal orchestration for the same requirement.", decision: "Checkpoint: add the protocol only when independent agent collaboration changes the outcome." },
      ]),
      block("cards", "Practice labs", [
        { id: "lab-recoverable-research-task", title: "Design a recoverable long interaction", subtitle: "A claim-intake agent may answer immediately or wait for evidence from another region", body: "Cover both SendMessage outcomes, all eight non-UNSPECIFIED operational TaskState values, reconnection, duplicate messages, cancellation, and optional Artifact access and acceptance.", decision: "Deliverable: a dual-path contract, Task state machine, and abnormal-path test table.", boundary: "Completion criterion: the client never assumes every interaction creates a Task; refresh, disconnection, and duplicate delivery do not create unexplained actions, and COMPLETED is not treated as business acceptance.", sourceIds: ["a2a-concepts", "a2a-specification", "a2a-release-1-0-1"] },
        { id: "lab-a2a-internal-orchestration", title: "Divide A2A from internal orchestration", subtitle: "An enterprise framework must collaborate with a partner's agent", body: "Mark internal shared state and the external minimum contract; assign discovery, identity, audit, and degradation responsibilities.", decision: "Deliverable: a protocol boundary diagram and responsibility matrix.", boundary: "Completion criterion: internal implementation can evolve independently and partner failure cannot propagate without a controlled path.", sourceIds: ["a2a-concepts", "anthropic-effective-agents", "nist-zero-trust"] },
        { id: "lab-cross-team-delegation", title: "Define a cross-region delegation contract", subtitle: "A claim-intake agent asks an immediate question or delegates a multi-hour evidence review", body: "Specify Agent Card expectations, Message-or-Task response, caller identity, budget, optional Artifact, all exact states, cancellation, and human takeover.", decision: "Deliverable: an A2A dual-path contract and recovery diagram.", boundary: "Completion criterion: direct Message, Task state, business result, accountable owner, and side-effect recovery remain distinct.", sourceIds: ["a2a-concepts", "a2a-specification", "a2a-release-1-0-1", "nist-genai-profile"] },
      ]),
    ]),
    section("a2a-task-lifecycle", "MESSAGE OR TASK LIFECYCLE", "Choose the response object before designing recovery", "The remote agent may return a Message directly or create a Task. Once it creates a Task, the implementation must preserve authoritative state; blocking, streaming, polling, subscription, and push are delivery mechanisms.", [
      block("steps", "A recoverable delegation sequence", [
        { id: "task-submit-accept", title: "Send a Message and choose the response object", body: "The caller uses a verified Agent Card to send a Message. The remote agent returns a Message for an immediate interaction or creates a stable server-side Task ID for work that must be tracked.", decision: "Test both Message and Task outcomes against the contract; persist the Task contract and state when recovery is required.", boundary: "Receiving a request does not imply acceptance of an unbounded goal, and Task persistence is an implementation responsibility rather than a protocol-mandated database.", sourceIds: ["a2a-specification", "nist-zero-trust"] },
        { id: "task-work-progress", title: "Work and report progress", body: "The provider executes internally while exposing only standardized state, messages, and necessary progress. A stream never replaces durable task state.", decision: "Use workflow, queues, and distributed traces for retries, timeouts, and intermediate artifacts.", boundary: "Private reasoning is not required evidence for a cross-organization audit.", sourceIds: ["a2a-concepts", "opentelemetry-semconv", "opentelemetry-genai-semconv"] },
        { id: "task-input-authorization", title: "Wait for input or authorization", body: "INPUT_REQUIRED and AUTH_REQUIRED interrupt a Task for missing business data, user confirmation, or a new authorization grant rather than forcing a guess or ambiguous failure.", decision: "Represent the reason and allowed response structurally and resume the same Task through an approved workflow.", boundary: "Additional input must not silently expand the original authorization.", sourceIds: ["a2a-specification"] },
        { id: "task-terminal-state", title: "Reach one exact terminal state", body: "COMPLETED, FAILED, CANCELED, and REJECTED have different meanings. A terminal Task cannot be resumed; revised work requires a new Task whose relationship is maintained by the client.", decision: "Drive business follow-up from authoritative state, preserve idempotency, and record retry or compensation separately.", boundary: "A timeout is neither proof of failure nor permission to repeat an irreversible action; CancelTask also does not prove side effects were reversed.", sourceIds: ["a2a-specification", "nist-genai-profile"] },
        { id: "task-deliver-verify-artifact", title: "Deliver and verify an optional Artifact", body: "A Task may have no Artifact. When one exists, validate media type, provenance, safety, access, integrity, and business conditions independently.", decision: "Use protected object storage for large outputs; maintain cross-Task version lineage and acceptance or rejection in the client and business application.", boundary: "COMPLETED means the provider ended execution; it does not prove that the output met the caller's business standard.", sourceIds: ["a2a-concepts", "nist-genai-profile"] },
      ]),
      block("table", "Choose the collaboration topology", [
        { id: "topology-one-runtime", title: "One runtime", cells: ["Nodes share code, state, release cycle, and security boundary.", "Use local workflows or an agent framework.", "Adding a network protocol increases latency and failure surface without creating an ownership boundary."] },
        { id: "topology-cross-team", title: "Cross-team service", cells: ["A specialist provider upgrades independently and owns its capability.", "Use a private agent catalog, A2A Tasks, enterprise identity, cross-service tracing, and agreed SLOs.", "A shared enterprise identity does not grant unrestricted data flow between teams."] },
        { id: "topology-cross-organization", title: "Cross-organization or cross-cloud", cells: ["Parties have different identity, network, data, audit, and incident regimes.", "Use gateways, OAuth 2.0 or mTLS, task-scoped authorization, controlled artifact exchange, and contractual operating boundaries.", "Interoperability does not establish legal, data, or operational trust."] },
        { id: "topology-human-long-task", title: "Human-in-the-loop long task", cells: ["Work alternates among automation, human input, approval, and revision across sessions or workdays.", "Use a durable workflow, approval queue, notification, timeout, and structured decision events.", "Human participation is a normal protocol path for some high-impact tasks, not an exceptional fallback."] },
      ], { columns: ["Ownership and lifecycle", "Recommended boundary", "Boundary"] }),
    ]),
    section("a2a-cloud", "DELIVERY RESPONSIBILITIES", "Connect runtime, durable tasks, identity, artifacts, and observability", "Cloud services can host and connect agents; the solution still needs a task owner, scoped authorization, artifact contract, and recovery semantics.", [
      block("table", "Four delivery stages", [
        { id: "cloud-agent-runtime-catalog", title: "Agent runtime and catalog", cells: ["Managed agent runtime, containers, service discovery, private catalog, and DNS", "Run independent agents and publish approved capability endpoints.", "Which teams, clouds, and trust domains own the agents, and is discovery public or private?"] },
        { id: "cloud-task-messaging", title: "Tasks and messaging", cells: ["Task store, database, queue, event bus, and workflow engine", "Persist state for long tasks, retry, cancellation, push, and recovery.", "How long can work run, can it wait for a person, and what are terminal, retry, and compensation rules?"] },
        { id: "cloud-identity-boundary", title: "Identity and boundary", cells: ["API gateway, OAuth/OIDC, mTLS, IAM, WAF, and policy engine", "Verify agent and caller identity and limit task scope, tenant, operation, and traffic.", "Who may delegate which task, and how are subjects and tenants mapped across organizations?"] },
        { id: "cloud-artifacts-observability", title: "Artifacts and observability", cells: ["Object storage, KMS, tracing, logs, audit, and cost monitoring", "Deliver large outputs safely and correlate cross-agent state, calls, errors, and cost.", "How are artifacts encrypted, retained, withdrawn, and tied to one distributed Task trace?"] },
      ], { columns: ["Service capabilities", "Value", "Discovery question"] }),
    ]),
  ]),
  qa: Object.freeze([
    question("a2a-versus-mcp", { q: "What is the practical difference between A2A and MCP?", a: "A2A supports Message-or-Task interaction with an independent remote agent. MCP connects an AI application or agent to tools, resources, and prompt templates.", depth: "A claim-intake agent could use A2A to obtain an immediate Message from a regional specialist or delegate a stateful Task; that specialist could use MCP to access knowledge and tools. A2A Task is a core cross-agent object, while MCP Tasks is an optional extension for durable requests. Their IDs, states, cancellation, and authoritative business outcomes require explicit mappings.", ask: "Is the counterparty an agent that independently accepts work and may deliver an artifact, or a database/API capability?", tag: "Protocol boundary", basis: "A2A and MCP protocol boundary", evidence: [{ sourceId: "a2a-mcp-boundary", supports: "Supports the complementary boundary: A2A for collaboration with independent remote agents and MCP for access to tools and resources." }, { sourceId: "mcp-tasks-extension", supports: "Supports MCP Tasks as an explicitly adopted durable-request extension whose semantics differ from an A2A Task." }] }),
    question("existing-agent-framework", { q: "If we already use a multi-agent framework, do we still need A2A?", a: "Only when collaboration crosses a system, deployment, ownership, or trust boundary. Agents that share code and state inside one application are usually better served by the local framework.", depth: "A2A provides a stable external contract and durable task boundary rather than replacing the internal state machine. An entire internally orchestrated system can be exposed as one A2A agent; its private nodes need not become separate external agents.", ask: "Are the collaborators independently deployed, upgraded, authorized, or owned by different organizations?", tag: "Architecture choice", basis: "External protocol boundary plus internal orchestration", evidence: [{ sourceId: "a2a-specification", supports: "Supports external exchange of tasks, messages, state, and artifacts through the A2A contract." }, { sourceId: "anthropic-effective-agents", supports: "Supports selecting orchestration complexity according to task needs inside one application." }] }),
    question("long-task-disconnection", { q: "How does a long task survive a lost connection?", a: "Work that needs tracking should return a Task. The implementation must let the client recover by Task ID through a query or subscription rather than treating the connection or a Message as the only state store.", depth: "Persist the eight non-UNSPECIFIED operational states: TASK_STATE_SUBMITTED, TASK_STATE_WORKING, TASK_STATE_INPUT_REQUIRED, TASK_STATE_AUTH_REQUIRED, TASK_STATE_COMPLETED, TASK_STATE_FAILED, TASK_STATE_CANCELED, and TASK_STATE_REJECTED. Query or resubscribe after a stream breaks and retry push delivery idempotently. Do not leave critical facts only in a Message that may not be persisted. A2A defines objects and operations; it does not mandate a database or exactly-once execution.", ask: "Where is Task state stored, and how are reconnection, duplicate callbacks, and service restart recovered?", tag: "Reliability", basis: "A2A Task model", evidence: [{ sourceId: "a2a-concepts", supports: "Defines Task as a stateful unit of work with a lifecycle." }, { sourceId: "a2a-specification", supports: "Defines synchronous, streaming, and asynchronous Task interaction plus state semantics." }] }),
    question("audit-opaque-agent", { q: "How can an A2A agent be audited without exposing its internal tools and prompts?", a: "Audit the identities, task contract, state changes, observable inputs and outputs, policy decisions, external actions, and artifact acceptance—not a complete internal chain-of-thought.", depth: "The delegator records who assigned which task, against which Agent Card and authorization, and which states and artifacts were received. The provider retains its internal execution and policy evidence. Task identifiers and trace context correlate the records while sensitive implementation details remain isolated.", ask: "In a dispute, which facts must both parties prove, and which internal information is prohibited from crossing the boundary?", tag: "Audit and observability", basis: "Task contract plus distributed tracing", evidence: [{ sourceId: "a2a-specification", supports: "Defines standard exchange of task, message, state, and artifact information." }, { sourceId: "opentelemetry-semconv", supports: "Supports trace context and common telemetry across distributed services." }, { sourceId: "opentelemetry-genai-semconv", supports: "Supports evolving attributes for agent and tool operations; cross-organization task evidence remains an application contract." }] }),
    question("message-queue-not-enough", { q: "Why not let multiple agents communicate only through an ordinary message queue?", a: "A queue transports events but does not define capability discovery, Message-or-Task responses, Task states, Artifact semantics, cancellation, or the responsibilities of collaborating agents.", depth: "For a fixed system integration, an API or event may be simpler. Independent agent services may need both a direct Message path and a server-side Task contract covering the eight non-UNSPECIFIED operational TaskState values. A queue can still implement transport or internal workflow.", ask: "Does the counterparty independently decide how to complete the objective, how long can work run, and who owns final state and any artifacts?", tag: "Adoption decision", basis: "A2A task semantics plus distributed-system boundary", evidence: [{ sourceId: "a2a-concepts", supports: "Organizes collaboration through Agent Card, Task, Message, Part, and Artifact rather than transport alone." }] }),
    question("task-failure-recovery-owner", { q: "Who owns recovery after an A2A task fails or times out?", a: "The delegator owns the business timeout and final decision; the provider owns accurate Task-state reporting. Both parties must agree idempotency, cancellation, retry, compensation, and human takeover.", depth: "A network timeout does not prove non-execution, and blind retry can duplicate an order or approval. Query authoritative state through a stable Task ID, distinguish interrupted states from terminal states and technical state from business outcome, and create a new related Task rather than mutating a terminal one when revision is required.", ask: "What is the worst side effect of duplicate execution, can authoritative status be queried after timeout, and who can take over manually?", tag: "Failure recovery", basis: "Task lifecycle plus business idempotency", evidence: [{ sourceId: "a2a-concepts", supports: "Supports stateful Task collaboration and optional Artifacts for cross-agent results." }, { sourceId: "nist-genai-profile", supports: "Supports risk management and human oversight for high-impact generative-AI behavior." }] }),
    question("cancellation-not-stop-proof", { q: "Does an A2A cancellation request guarantee that remote work has stopped?", a: "No. CancelTask may return that the Task is not cancelable, and a successful cancellation changes protocol state without promising to reverse business side effects.", depth: "After requesting cancellation, the delegator should query the authoritative Task state and reconcile side effects with the business system. The provider can report CANCELED or an error such as TaskNotCancelableError; it cannot prove reversal of an external action. Payments, resource creation, and other side effects require business-system idempotency, reversal, and compensation outside agent Messages.", ask: "How quickly must work stop after cancellation, and who detects and compensates any side effect that already occurred?", tag: "Cancellation semantics", basis: "Task lifecycle plus business compensation", evidence: [{ sourceId: "a2a-specification", supports: "Defines CancelTask, TaskNotCancelableError, and CANCELED state without promising rollback of business side effects." }, { sourceId: "nist-genai-profile", supports: "Supports response, recovery, and human oversight for high-impact AI actions." }] }),
    question("central-or-peer-topology", { q: "Should one orchestrator control all agents, or should agents collaborate peer to peer?", a: "Use explicit orchestration for fixed responsibility and high-risk workflows. Add peer autonomy only when dynamic collaboration materially changes the task.", depth: "Central coordination makes budget, identity, state, and audit easier to enforce but can bottleneck scale. Peer delegation is flexible and increases loops, duplicate delegation, authorization propagation, and cost risk. A business task owner can retain final control while allowing local A2A collaboration.", ask: "Who owns the final result, and who enforces budget, identity, and stop conditions when the topology changes?", tag: "Collaboration topology", basis: "Incremental complexity plus risk management", evidence: [{ sourceId: "anthropic-effective-agents", supports: "Supports starting with simpler composable patterns and adding multi-agent complexity only when the task warrants it." }, { sourceId: "a2a-concepts", supports: "Supports collaboration among independent agents through task and artifact semantics." }] }),
    question("agent-card-trust", { q: "Does discovering an Agent Card prove the remote agent's identity and capability?", a: "No. The card is a discovery entry. Verify its origin, transport, organizational identity, version, supported interface, and actual behavior before approval.", depth: "A controlled catalog should bind the card to server identity, owner, allowed tasks, authentication requirements, and suspension state. Run contract tests before first use. Dynamic discovery must not bypass vendor onboarding, network policy, data governance, or business authorization.", ask: "Who publishes and signs the Agent Card, which trust anchor validates it, and how is capability revalidated after a change?", tag: "Discovery trust", basis: "Capability discovery plus organizational trust", evidence: [{ sourceId: "a2a-specification", supports: "Defines Agent Card metadata for capabilities and interaction endpoints." }, { sourceId: "nist-zero-trust", supports: "Rejects implicit trust based only on location or declaration." }] }),
    question("delegate-minimum-authorization", { q: "May the delegator pass all of a user's permissions to a remote agent?", a: "It should not. Delegate the minimum authority bound to the current task, resource, tenant, and lifetime rather than copying a long-lived identity or complete permission set.", depth: "Distinguish the end user, delegating agent, executing agent, and resource server. The remote agent receives only the capability needed for the explicit task, with a traceable authorization chain, consent, revocation, and audit. Cross-organization calls must also map subjects and tenants deliberately.", ask: "Does the remote agent represent the user or the delegating service, when does authority expire, and who can revoke it?", tag: "Cross-domain delegation", basis: "Identity chain plus minimum authorization", evidence: [{ sourceId: "a2a-specification", supports: "Requires defined authentication and interaction contracts for A2A communication." }, { sourceId: "nist-zero-trust", supports: "Supports short-lived, resource-focused, continually evaluated access." }] }),
    question("artifact-business-acceptance", { q: "Can an A2A Artifact enter the next business stage immediately?", a: "Not by default. An Artifact is an optional Task output whose type, integrity, provenance, safety, and business acceptance criteria require independent validation.", depth: "A direct Message has no required Artifact, and a Task is not guaranteed to produce one. Use protected object references for large or sensitive outputs. The client and business application maintain cross-Task version lineage, withdrawal, and who accepted which version. Technical COMPLETED state is not delivery acceptance.", ask: "Who validates and accepts the artifact, and how is an incorrect version withdrawn after downstream use?", tag: "Artifact acceptance", basis: "Artifact boundary plus business acceptance", evidence: [{ sourceId: "a2a-concepts", supports: "Distinguishes Message, Task, and optional Artifact as separate collaboration objects." }, { sourceId: "nist-genai-profile", supports: "Supports validation and human oversight for generated outputs." }] }),
    question("a2a-one-point-zero-acceptance", { q: "A service claims A2A 1.0 compatibility. Is network connectivity enough for acceptance?", a: "No. As of 2026-08-01, the latest tagged release is v1.0.1, but wire negotiation still uses A2A-Version 1.0; verify every AgentInterface, binding, object, and error semantic.", depth: "The specification says patch numbers should not be used in requests, responses, or Agent Cards and must not participate in version negotiation. A client declares Major.Minor on each request and unsupported versions must fail explicitly. Test direct Message, Task, all eight non-UNSPECIFIED operational states, optional Artifact, streaming, authentication, authorization, cancellation, and failure separately for HTTP+JSON, JSON-RPC, or gRPC. Verify independently whether a specific SDK or product adopted the v1.0.1 fixes.", ask: "Which protocol versions and bindings are advertised, and how will upgrades prevent silent downgrade and rerun the complete capability suite?", tag: "Protocol reliability", basis: "Patch release plus version negotiation and binding contract", evidence: [{ sourceId: "a2a-release-1-0-1", supports: "Supports v1.0.1 as the latest official patch release as of the verification date." }, { sourceId: "a2a-specification", supports: "Supports wire negotiation through Major.Minor A2A-Version 1.0 and common semantics across bindings." }], addedAt: "2026-07-20" }),
  ]),
  evidenceCards: Object.freeze([
    Object.freeze({ id: "card-task-artifact", metric: "Card → Message | Task → Artifact?", title: "Discovery leads to two response paths", finding: "The Agent Card describes candidate capability; the remote agent may return a Message directly or create a Task that may produce an Artifact.", boundary: "An Artifact is optional, and neither capability self-description, protocol terminal state, nor output delivery establishes business acceptance.", sourceId: "a2a-concepts", accent: true }),
    Object.freeze({ id: "blocking-to-push", metric: "Blocking ↔ push", title: "Delivery mode follows task duration and connectivity", finding: "Blocking, polling, streaming, and push support different result timing and client availability patterns.", boundary: "Asynchronous delivery still depends on durable Task state, idempotency, callback security, and recovery.", sourceId: "a2a-specification" }),
    Object.freeze({ id: "agent-versus-tool", metric: "Agent ↔ agent", title: "A2A and MCP point in different directions", finding: "A2A coordinates independently operated agents; MCP connects applications or agents to tools and resources.", boundary: "A system may use both protocols, but their authorization assumptions and lifecycle objects remain distinct.", sourceId: "a2a-mcp-boundary" }),
    Object.freeze({ id: "contract-not-chain-of-thought", metric: "Contract, not chain-of-thought", title: "Opaque agents can still be governed", finding: "Identity, task state, observable messages, external actions, and artifacts can form an auditable collaboration boundary without exposing private reasoning.", boundary: "Keeping internals private does not remove the provider's internal audit and quality responsibilities.", sourceId: "a2a-concepts" }),
  ]),
  terms: Object.freeze({
    a2a: Object.freeze({ name: "Agent2Agent Protocol", abbr: "A2A", definition: "A protocol for discovering and interacting with independently operated remote agents, which may return a Message directly or create a stateful Task across system or organizational boundaries." }),
    "agent-card": Object.freeze({ name: "Agent Card", definition: "Versioned discovery metadata that declares an agent's identity, endpoints, supported interfaces, capabilities, skills, and security requirements; it is neither identity proof nor a quality certification." }),
    "a2a-message": Object.freeze({ name: "A2A Message", definition: "A unit of interaction that may be sent by a user, agent, or service and can itself be the direct SendMessage response; it is not guaranteed to be persisted or to create a Task." }),
    "a2a-task": Object.freeze({ name: "A2A Task", definition: "The server-side stateful object created when remote work needs tracking, interruption, or recovery; its persistence mechanism and cross-Task lineage are implementation responsibilities." }),
    artifact: Object.freeze({ name: "Artifact", definition: "An optional output associated with a Task that requires independent type, integrity, access, retention, lineage, and business-acceptance controls." }),
    "agent-collaboration": Object.freeze({ name: "Agent Collaboration", definition: "Coordinated work among independently responsible agents through explicit tasks, state, artifacts, authorization, and recovery boundaries." }),
    "identity-authorization": Object.freeze({ name: "Identity & Authorization", definition: "Verifying the real caller and target and deciding whether a subject may perform a specific action on a protected resource under the current context." }),
  }),
  sources: Object.freeze({
    "a2a-concepts": Object.freeze({ kind: "Official technical documentation", shortTitle: "A2A Core Concepts", note: "Explains Agent Card, Message, Task, Part, optional Artifact, and delivery patterns, including the Message-or-Task response branch. It does not mandate persistence or certify an implementation or agent capability." }),
    "a2a-specification": Object.freeze({ kind: "Official protocol specification", shortTitle: "A2A Protocol Specification", note: "Defines normative A2A operations, objects, exact Task states, Major.Minor version negotiation, bindings, authentication considerations, and cancellation behavior. Protocol compliance does not prove persistence, business acceptance, authorization, or rollback of side effects." }),
    "a2a-mcp-boundary": Object.freeze({ kind: "Official technical documentation", shortTitle: "A2A and MCP", note: "Explains A2A as collaboration with independent remote agents and MCP as access to tools and resources. It does not define a universal mapping between A2A Task and the optional MCP Tasks extension or merge their authorization and business-state semantics." }),
    "mcp-tasks-extension": Object.freeze({ kind: "Official protocol extension", shortTitle: "MCP Tasks Extension", note: "Defines durable request handles, ttlMs, pollIntervalMs, working/input_required/completed/failed/cancelled states, polling, updates, recovery, and cooperative cancellation. An MCP Task is not an A2A inter-agent task or proof of business completion." }),
    "anthropic-effective-agents": Object.freeze({ kind: "Vendor engineering guidance", shortTitle: "Building Effective Agents", note: "Recommends matching orchestration complexity to task needs and starting with simpler composable patterns. It is vendor-authored guidance, not an A2A standard." }),
    "opentelemetry-semconv": Object.freeze({ kind: "Open observability specification", shortTitle: "OpenTelemetry Semantic Conventions", note: "Defines evolving common telemetry semantics and trace context. Adopted versions must be pinned, while business outcomes, media- or agent-specific evidence, and project policy fields remain application responsibilities." }),
    "opentelemetry-genai-semconv": Object.freeze({ kind: "Open observability specification", shortTitle: "OpenTelemetry GenAI Conventions", note: "Defines evolving telemetry conventions for generative-AI clients, retrieval, agents, MCP, and Tool calls. Projects must pin the adopted version and add their own business outcomes, access controls, approvals, evidence coverage, and risk fields." }),
    "nist-genai-profile": Object.freeze({ kind: "Official risk-management framework", shortTitle: "NIST AI 600-1", note: "Organizes generative-AI risk management around Govern, Map, Measure, and Manage. It is a voluntary resource, not product certification, a universal compliance checklist, a model ranking, or a performance standard." }),
    "nist-zero-trust": Object.freeze({ kind: "Official architecture guidance", shortTitle: "NIST SP 800-207", note: "Defines zero-trust principles for explicit, resource-focused access decisions without implicit trust. It does not provide an MCP/A2A implementation, AI quality evaluation, or business compensation design." }),
    "a2a-release-1-0-1": Object.freeze({ kind: "Official release record", shortTitle: "A2A v1.0.1 Release", note: "Records v1.0.1 as the latest tagged A2A patch release as of 2026-08-01. The specification says patch numbers should not be used in requests, responses, or Agent Cards and must not participate in version negotiation; the release tag also does not prove that a specific implementation adopted every fix." }),
  }),
});
