const freezeItems = (items) => Object.freeze(items.map((item) => Object.freeze(item)));
const block = (type, title, items, extra = {}) => Object.freeze({ type, title, ...extra, items: freezeItems(items) });
const section = (id, eyebrow, title, lead, blocks) => Object.freeze({ id, eyebrow, title, lead, blocks: Object.freeze(blocks) });
const question = (id, copy) => Object.freeze({ ...copy, id, evidence: freezeItems(copy.evidence) });

export const englishModule = Object.freeze({
  slug: "a2a",
  title: "Agent2Agent Protocol",
  subtitle: "Delegate durable work across independent agents without confusing discovery with trust",
  definition: "The Agent2Agent Protocol (A2A) enables independently operated agents to discover capabilities, delegate work, exchange task state, and deliver artifacts across frameworks, systems, clouds, or organizations.",
  position: "This module sits in the protocol and interoperability layer. A2A defines horizontal agent-to-agent collaboration; an agent's internal orchestration remains an implementation concern, while tools and data are commonly accessed through MCP or ordinary APIs.",
  relatedSlugs: Object.freeze(["ai-agent", "mcp", "ai-gateway", "security", "ai-ops"]),
  sections: Object.freeze([
    section("a2a-collaboration-model", "COLLABORATION CONTRACT", "Make the task, state, and artifact the external contract", "A2A is useful when independently owned agents need a durable collaboration boundary. The value comes from explicit responsibility and recovery semantics, not from increasing the number of agents.", [
      block("cards", "Five operating principles", [
        { id: "principle-agent-card-discovery", title: "Agent Card and discovery", body: "An Agent Card describes identity, endpoints, skills, supported interfaces, and security requirements so a client can assess how to interact.", decision: "Verify provenance, domain, version, transport, and—where supplied—the card signature. A self-declared skill is not an identity or quality certification." },
        { id: "principle-stateful-task", title: "A stateful Task owns durable work", body: "A Task represents work that can span messages, time, and connections. The server's durable task store—not an open network stream—must be the authoritative state.", decision: "Define transitions, terminal states, cancellation, retry, timeout, and whether a failure creates a new Task." },
        { id: "principle-message-artifact-separation", title: "Separate messages, parts, and artifacts", body: "Messages carry interaction, Parts carry typed content, and Artifacts represent deliverable outputs that can be versioned and accepted.", decision: "Exchange large or sensitive files through controlled storage references with integrity and access metadata rather than embedding unbounded binary content." },
        { id: "principle-delivery-modes", title: "Delivery mode follows task duration", body: "Short work can block; longer work can be polled, streamed, or delivered through push notifications. The choice changes recovery and security requirements.", decision: "Validate callback destinations, authentication, idempotency, and rate limits for push delivery." },
        { id: "principle-opaque-collaboration", title: "Opaque internals can still have an auditable boundary", body: "An agent can expose capability, accepted input, observable state, and artifacts without sharing private prompts, tools, or hidden reasoning.", decision: "Audit cross-organization collaboration through contracts, state, evidence, and acceptance rather than demanding internal chain-of-thought." },
      ]),
      block("boundary", "Critical boundary", [{ id: "critical-a2a-mcp-boundary", title: "A2A coordinates agents; MCP connects applications to tools and data", body: "One agent may use MCP internally and use A2A to delegate an objective to another independently operated agent.", boundary: "Discovery, protocol compatibility, and capability self-description establish neither identity trust nor authorization." }]),
    ]),
    section("a2a-curriculum", "COURSE MAP", "Build from agent discovery to versioned, recoverable task collaboration", "The current 1.0 specification defines protocol and binding contracts. Product quality, business authorization, and artifact acceptance remain application and organizational responsibilities.", [
      block("cards", "Nine course chapters", [
        { id: "curriculum-agent-tool-boundary", title: "Agent versus tool boundary", body: "MCP lets an application or model access tools and resources; A2A lets an independent agent collaborate through a task. An A2A agent can use MCP without exposing that internal tool graph.", decision: "Choose according to independent responsibility, state ownership, and organizational boundary.", boundary: "Internal multi-agent calls do not automatically require A2A, and A2A never substitutes for tool authorization.", sourceIds: ["a2a-concepts", "mcp-architecture"] },
        { id: "curriculum-agent-card", title: "Agent Card and capability discovery", body: "The Agent Card declares identity, interaction endpoints, skills, capabilities, and supported interfaces. Treat it as versioned discovery metadata that must be verified and cached under policy.", decision: "Use capability declarations to form a candidate, then use organizational trust and operational evidence to approve it.", boundary: "Declaring a skill is not a commitment to quality, a right to customer data, or authorization for a particular task.", sourceIds: ["a2a-concepts", "a2a-specification"] },
        { id: "curriculum-core-objects", title: "Task, Message, Part, and Artifact", body: "Messages carry interaction, a Task owns stateful work, Parts carry typed content, and Artifacts represent deliverable results. Keeping conversation separate from output preserves clarity across input requests and multiple artifact versions.", decision: "Use Tasks for lifecycle and Artifacts for independently validated outputs.", boundary: "Protocol delivery does not make an Artifact trusted, correctly versioned, or safe to consume.", sourceIds: ["a2a-concepts", "a2a-specification"] },
        { id: "curriculum-task-lifecycle", title: "Task state and recovery", body: "A long-running Task may progress, require input or authorization, complete, fail, cancel, or reject. Clients must handle duplicate events, disconnection, late results, and idempotency; servers must define terminal and retry semantics.", decision: "Define authoritative state and recovery before selecting blocking, streaming, polling, or push.", boundary: "A network retry is not automatically a safe business retry; duplicate execution may create irreversible side effects.", sourceIds: ["a2a-specification", "opentelemetry-semconv"] },
        { id: "curriculum-version-binding", title: "A2A 1.0 version and binding negotiation", body: "A2A 1.0 uses the A2A-Version header for Major.Minor request semantics. AgentInterface declares a URL, protocol binding, and protocol version; the same capability may be exposed through HTTP+JSON, JSON-RPC, or gRPC.", decision: "Track protocol version, binding, SDK, and agent capability version separately in the compatibility matrix.", boundary: "Connectivity does not prove functional or error-mapping parity across bindings. Unsupported versions should fail explicitly rather than downgrade silently.", sourceIds: ["a2a-spec-1-0-0"] },
        { id: "curriculum-collaboration-topology", title: "Collaboration topology and internal orchestration", body: "Central coordination, peer delegation, and hierarchical collaboration offer different control and scaling characteristics. Internal orchestration can share more state; an external A2A boundary should minimize contracts and data exposure.", decision: "Place stable contracts at ownership boundaries and keep high-frequency fine-grained coordination inside one runtime.", boundary: "More agents increase coordination, tracing, and error propagation and do not automatically improve quality.", sourceIds: ["anthropic-effective-agents", "a2a-concepts"] },
        { id: "curriculum-trust-audit", title: "Identity, artifacts, and audit", body: "Verify the caller, target agent, task authorization, and artifact access, then correlate tasks, messages, state events, policies, and external actions. Audit observed commitments and outcomes rather than hidden reasoning.", decision: "Use task evidence, policy versions, and external-action records to prove the boundary.", boundary: "Opaque internals do not remove provider responsibility, but requesting hidden chain-of-thought is not a sound substitute for audit evidence.", sourceIds: ["a2a-specification", "opentelemetry-semconv", "opentelemetry-genai-semconv"] },
        { id: "curriculum-reliability", title: "Idempotency, cancellation, and recovery", body: "A remote agent may continue after a network timeout. The delegator needs a stable Task ID, authoritative status queries, idempotency keys, cancellation semantics, partial-artifact rules, and human escalation.", decision: "Write recovery into the task contract before setting timeouts and retries.", boundary: "Cancellation receipt does not prove that side effects were reversed, and technical completion does not establish business acceptance.", sourceIds: ["a2a-concepts", "nist-genai-profile"] },
        { id: "curriculum-adoption-boundary", title: "Adoption boundary", body: "A2A fits independently operated agents that need capability discovery and durable task collaboration. A fixed integration, one organization's internal workflow, or simple event notification is often clearer through APIs, queues, or workflow engines.", decision: "Adopt A2A only when cross-boundary collaboration value exceeds protocol, identity, and operating cost.", boundary: "Calling a design 'multi-agent' does not establish a business or reliability benefit.", sourceIds: ["a2a-concepts", "anthropic-effective-agents"] },
      ]),
    ]),
    section("a2a-decisions", "PRESALES DECISIONS", "Use ownership, duration, trust, and artifact constraints to choose the boundary", "The protocol is a justified external contract only when another independently operated agent owns meaningful work.", [
      block("table", "Five recurring decisions", [
        { id: "decision-need-a2a", title: "Is A2A needed instead of one agent?", cells: ["Work must be delegated to a specialist agent with independent deployment, ownership, framework, cloud, or release cycle.", "Use A2A only where a genuine system boundary exists; keep subtasks in a local orchestrator otherwise.", "Artificially splitting one application does not create quality and adds handoff and evaluation cost."] },
        { id: "decision-a2a-internal-runtime", title: "How should A2A divide work from the internal agent framework?", cells: ["Internal nodes either share state, code, and a trust domain or are operated by different services or organizations.", "Use the local framework for fine-grained internal state and expose one stable A2A task contract at the external boundary.", "A2A does not replace an internal runtime or require every internal node to become externally visible."] },
        { id: "decision-delivery-mode", title: "Should the task block or deliver asynchronously?", cells: ["The task may wait for people or external systems, and the client may not remain connected.", "Use blocking for short work, polling for queryable long work, streaming for progressive output, and controlled push for offline notification.", "Push requires destination validation, authentication, idempotency, and rate limiting; never accept an arbitrary model-generated callback URL."] },
        { id: "decision-cross-organization-trust", title: "How do agents establish trust across organizations?", cells: ["The agent identity, caller, tenant, task scope, data class, and audit requirement can all be verified.", "Verify the Agent Card and server identity, use OAuth 2.0 or mTLS, and restrict authorization to the task, operation, and tenant.", "Finding an agent does not grant permission to delegate work or receive protected artifacts."] },
        { id: "decision-large-sensitive-artifacts", title: "How should large or sensitive artifacts be delivered?", cells: ["Outputs are large, regulated, cross-region, or must be retained for a defined period.", "Exchange short-lived controlled object references, hashes, and metadata; govern storage access and retention independently.", "A2A messages are not a bypass around storage access, region, retention, or deletion controls."] },
      ], { columns: ["Customer signal", "Recommended action", "Boundary"] }),
    ]),
    section("a2a-practice", "LEARN, PRACTICE, PROVE", "Design the collaboration boundary as a recoverable distributed task", "Practice moves from protocol choice to state recovery, cross-domain authorization, observability, and business acceptance.", [
      block("cards", "Learning outcomes", [
        { id: "outcome-a2a-mcp-boundary", title: "Separate A2A and MCP responsibilities", body: "Determine whether the counterparty owns a task or merely exposes a tool or resource." },
        { id: "outcome-a2a-core-objects", title: "Use Agent Card, Task, Message, and Artifact correctly", body: "Connect discovery, interaction, durable state, and deliverable outputs without collapsing their control meanings." },
        { id: "outcome-a2a-long-task", title: "Design disconnected and asynchronous work", body: "Recover through authoritative state and idempotent delivery instead of assuming a persistent stream." },
        { id: "outcome-a2a-trust-audit", title: "Establish cross-organization trust and audit", body: "Prove identity, task authorization, state, external actions, and artifact acceptance without exposing private reasoning." },
      ]),
      block("steps", "Recommended learning route", [
        { id: "route-decide-protocol-boundary", title: "Decide whether a protocol boundary exists", body: "Compare a single runtime, internal multi-agent coordination, and cross-system delegation.", decision: "Checkpoint: explain why one local subagent is insufficient." },
        { id: "route-master-task-state", title: "Master the task state machine", body: "Model initial messages, progress, input and authorization waits, artifacts, terminal states, and rejection.", decision: "Checkpoint: handle duplicate delivery, disconnection, and cancellation explicitly." },
        { id: "route-handle-trust-operations", title: "Handle trust and operation", body: "Verify capability declarations, caller identity, artifact permissions, and cross-domain audit.", decision: "Checkpoint: prove the execution boundary without demanding internal prompts." },
        { id: "route-recovery-cancellation", title: "Complete recovery and cancellation semantics", body: "Use authoritative task state, idempotency, partial artifacts, compensation, and human takeover for uncertain outcomes.", decision: "Checkpoint: never repeat a high-impact action blindly after a timeout." },
        { id: "route-validate-adoption-value", title: "Validate adoption value", body: "Compare A2A with APIs, events, workflows, and internal orchestration for the same requirement.", decision: "Checkpoint: add the protocol only when independent agent collaboration changes the outcome." },
      ]),
      block("cards", "Practice labs", [
        { id: "lab-recoverable-research-task", title: "Design a recoverable long task", subtitle: "A research agent may wait for additional user files", body: "Define states, events, terminal outcomes, reconnection, duplicate messages, cancellation, and artifact access and retention.", decision: "Deliverable: a task state machine and abnormal-path test table.", boundary: "Acceptance: refresh, disconnection, and duplicate delivery neither create unexplained duplicate tasks nor lose artifacts.", sourceIds: ["a2a-concepts", "a2a-specification", "opentelemetry-semconv"] },
        { id: "lab-a2a-internal-orchestration", title: "Divide A2A from internal orchestration", subtitle: "An enterprise framework must collaborate with a partner's agent", body: "Mark internal shared state and the external minimum contract; assign discovery, identity, audit, and degradation responsibilities.", decision: "Deliverable: a protocol boundary diagram and responsibility matrix.", boundary: "Acceptance: internal implementation can evolve independently and partner failure cannot propagate without a controlled path.", sourceIds: ["a2a-concepts", "anthropic-effective-agents", "nist-zero-trust"] },
        { id: "lab-cross-team-delegation", title: "Define a cross-team delegation contract", subtitle: "A sales agent delegates a multi-hour proposal asset to a delivery agent", body: "Specify Agent Card expectations, input, caller identity, budget, expected Artifact, progress, input required, completion, failure, cancellation, and takeover.", decision: "Deliverable: an A2A contract and recovery diagram.", boundary: "Acceptance: task state, business result, accountable owner, and side-effect recovery are distinct.", sourceIds: ["a2a-concepts", "a2a-specification", "nist-genai-profile"] },
      ]),
    ]),
    section("a2a-task-lifecycle", "DURABLE TASK LIFECYCLE", "Continue safely across disconnection, input waits, and failure", "The Task is the server-side source of truth; blocking, streaming, polling, and push are result-delivery mechanisms.", [
      block("steps", "A recoverable delegation sequence", [
        { id: "task-submit-accept", title: "Submit and accept", body: "The caller uses a verified Agent Card to submit objective, input, constraints, and correlation identifiers; the provider creates a stable Task ID.", decision: "Validate caller, tenant, task scope, and protocol version before persisting the contract.", boundary: "Receiving a request does not imply acceptance of an unbounded goal.", sourceIds: ["a2a-spec-1-0-0", "nist-zero-trust"] },
        { id: "task-work-progress", title: "Work and report progress", body: "The provider executes internally while exposing only standardized state, messages, and necessary progress. A stream never replaces durable task state.", decision: "Use workflow, queues, and distributed traces for retries, timeouts, and intermediate artifacts.", boundary: "Private reasoning is not required evidence for a cross-organization audit.", sourceIds: ["a2a-concepts", "opentelemetry-semconv", "opentelemetry-genai-semconv"] },
        { id: "task-input-authorization", title: "Wait for input or authorization", body: "A Task may pause for missing business data, user confirmation, or a new authorization grant rather than guess or fail ambiguously.", decision: "Represent the reason and allowed response structurally and resume the same Task through an approved workflow.", boundary: "Additional input must not silently expand the original authorization." , sourceIds: ["a2a-spec-1-0-0"] },
        { id: "task-terminal-state", title: "Reach a defined terminal state", body: "Completion, failure, cancellation, and rejection have different meanings and must carry error, compensation, and retry information.", decision: "Drive business follow-up from the authoritative state; enforce idempotency and retry budgets.", boundary: "A timeout is neither proof of failure nor permission to repeat an irreversible action.", sourceIds: ["a2a-specification", "nist-genai-profile"] },
        { id: "task-deliver-verify-artifact", title: "Deliver and verify artifacts", body: "Bind each Artifact to Task, media type, version, integrity value, and access policy, then validate it against the business contract.", decision: "Use protected object storage for large artifacts and write acceptance back into the audit trail.", boundary: "Task completion states that the provider finished; it does not prove customer acceptance." , sourceIds: ["a2a-concepts", "nist-genai-profile"] },
      ]),
      block("table", "Choose the collaboration topology", [
        { id: "topology-one-runtime", title: "One runtime", cells: ["Nodes share code, state, release cycle, and security boundary.", "Use local workflows or an agent framework.", "Adding a network protocol increases latency and failure surface without creating an ownership boundary."] },
        { id: "topology-cross-team", title: "Cross-team service", cells: ["A specialist provider upgrades independently and owns its capability.", "Use a private agent catalog, A2A Tasks, enterprise identity, cross-service tracing, and agreed SLOs.", "A shared enterprise identity does not grant unrestricted data flow between teams."] },
        { id: "topology-cross-organization", title: "Cross-organization or cross-cloud", cells: ["Parties have different identity, network, data, audit, and incident regimes.", "Use gateways, OAuth 2.0 or mTLS, task-scoped authorization, controlled artifact exchange, and contractual operating boundaries.", "Interoperability does not establish legal, data, or operational trust."] },
        { id: "topology-human-long-task", title: "Human-in-the-loop long task", cells: ["Work alternates among automation, human input, approval, and revision across sessions or workdays.", "Use a durable workflow, approval queue, notification, timeout, and structured decision events.", "Human participation is a normal protocol path for some high-impact tasks, not an exceptional fallback."] },
      ], { columns: ["Ownership and lifecycle", "Recommended boundary", "Boundary"] }),
    ]),
    section("a2a-cloud", "DELIVERY RESPONSIBILITIES", "Connect runtime, durable tasks, identity, artifacts, and observability", "Cloud services can host and connect agents; the solution still needs a task owner, scoped authorization, artifact contract, and recovery semantics.", [
      block("table", "Four delivery stages", [
        { id: "cloud-agent-runtime-catalog", title: "Agent runtime and catalog", cells: ["Managed agent runtime, containers, service discovery, private catalog, and DNS", "Run independent agents and publish approved capability endpoints.", "Which teams, clouds, and trust domains own the agents, and is discovery public or private?"] },
        { id: "cloud-task-messaging", title: "Tasks and messaging", cells: ["Task store, database, queue, event bus, and workflow engine", "Persist state for long tasks, retry, cancellation, push, and recovery.", "How long can work run, can it wait for a person, and what are terminal, retry, and compensation rules?"] },
        { id: "cloud-identity-boundary", title: "Identity and boundary", cells: ["API gateway, OAuth/OIDC, mTLS, IAM, WAF, and policy engine", "Verify agent and caller identity and limit task scope, tenant, operation, and traffic.", "Who may delegate which task, and how are subjects and tenants mapped across organizations?"] },
        { id: "cloud-artifacts-observability", title: "Artifacts and observability", cells: ["Object storage, KMS, tracing, logs, audit, and cost monitoring", "Deliver large outputs safely and correlate cross-agent state, calls, errors, and cost.", "How are artifacts encrypted, retained, withdrawn, and tied to one distributed Task trace?"] },
      ], { columns: ["Service capabilities", "Value", "Discovery question"] }),
    ]),
  ]),
  qa: Object.freeze([
    question("a2a-versus-mcp", { q: "What is the practical difference between A2A and MCP?", a: "A2A coordinates task delegation and state among independent agents. MCP connects an AI application or agent to tools, resources, and prompt templates.", depth: "A procurement agent could delegate contract review to a legal agent through A2A; the legal agent could then use MCP to access a contract repository and approval tool. They can be combined, but task state, tool authorization, and audit responsibility remain separate.", ask: "Is the counterparty an agent that independently accepts work and delivers an artifact, or a database/API capability?", tag: "Protocol boundary", basis: "A2A concept model plus MCP architecture", evidence: [{ sourceId: "a2a-concepts", supports: "Supports collaboration through Agent Card, Task, Message, Part, and Artifact." }, { sourceId: "mcp-architecture", supports: "Supports MCP Host, Client, and Server roles for connecting tools and context capabilities." }] }),
    question("existing-agent-framework", { q: "If we already use a multi-agent framework, do we still need A2A?", a: "Only when collaboration crosses a system, deployment, ownership, or trust boundary. Agents that share code and state inside one application are usually better served by the local framework.", depth: "A2A provides a stable external contract and durable task boundary rather than replacing the internal state machine. An entire internally orchestrated system can be exposed as one A2A agent; its private nodes need not become separate external agents.", ask: "Are the collaborators independently deployed, upgraded, authorized, or owned by different organizations?", tag: "Architecture choice", basis: "External protocol boundary plus internal orchestration", evidence: [{ sourceId: "a2a-specification", supports: "Supports external exchange of tasks, messages, state, and artifacts through the A2A contract." }, { sourceId: "anthropic-effective-agents", supports: "Supports selecting orchestration complexity according to task needs inside one application." }] }),
    question("long-task-disconnection", { q: "How does a long task survive a lost connection?", a: "The server must persist authoritative Task state, and the client recovers through the Task ID, query, subscription, or controlled notification rather than treating the network connection as the state store.", depth: "Record transitions, terminal states, cancellation, input waits, and authorization waits. After a stream breaks, query the Task again. Retry push delivery idempotently. Bind Artifacts to the Task and their versions so a service restart cannot detach the output from its work record.", ask: "Where is Task state stored, and how are reconnection, duplicate callbacks, and service restart recovered?", tag: "Reliability", basis: "A2A Task model", evidence: [{ sourceId: "a2a-concepts", supports: "Defines Task as a stateful unit of work with a lifecycle." }, { sourceId: "a2a-specification", supports: "Defines blocking, streaming, polling, and asynchronous task interactions and state semantics." }] }),
    question("audit-opaque-agent", { q: "How can an A2A agent be audited without exposing its internal tools and prompts?", a: "Audit the identities, task contract, state changes, observable inputs and outputs, policy decisions, external actions, and artifact acceptance—not a complete internal chain-of-thought.", depth: "The delegator records who assigned which task, against which Agent Card and authorization, and which states and artifacts were received. The provider retains its internal execution and policy evidence. Task identifiers and trace context correlate the records while sensitive implementation details remain isolated.", ask: "In a dispute, which facts must both parties prove, and which internal information is prohibited from crossing the boundary?", tag: "Audit and observability", basis: "Task contract plus distributed tracing", evidence: [{ sourceId: "a2a-specification", supports: "Defines standard exchange of task, message, state, and artifact information." }, { sourceId: "opentelemetry-semconv", supports: "Supports trace context and common telemetry across distributed services." }, { sourceId: "opentelemetry-genai-semconv", supports: "Supports evolving attributes for agent and tool operations; cross-organization task evidence remains an application contract." }] }),
    question("message-queue-not-enough", { q: "Why not let multiple agents communicate only through an ordinary message queue?", a: "A queue transports events but does not define capability discovery, task state, artifact semantics, cancellation, or the responsibilities of collaborating agents.", depth: "For a fixed system integration, an API or event may be simpler. Independent agent services may need to declare capabilities and manage accepted, working, input-required, completed, failed, rejected, and canceled states around a durable Task. A queue can still implement transport or internal workflow, while the task contract remains explicit.", ask: "Does the counterparty independently decide how to complete the objective, how long can work run, and who owns final state and artifacts?", tag: "Adoption decision", basis: "A2A task semantics plus distributed-system boundary", evidence: [{ sourceId: "a2a-concepts", supports: "Organizes collaboration through Agent Card, Task, Message, Part, and Artifact rather than transport alone." }] }),
    question("task-failure-recovery-owner", { q: "Who owns recovery after an A2A task fails or times out?", a: "The delegator owns the business timeout and final decision; the provider owns accurate task state. Both parties must agree idempotency, cancellation, retry, compensation, and human takeover.", depth: "A network timeout does not prove non-execution, and blind retry can duplicate an order or approval. Query authoritative state through a stable Task ID and idempotency key, distinguish technical state from business outcome, and define whether cancellation is guaranteed, best effort, or requires compensation.", ask: "What is the worst side effect of duplicate execution, can authoritative status be queried after timeout, and who can take over manually?", tag: "Failure recovery", basis: "Task lifecycle plus business idempotency", evidence: [{ sourceId: "a2a-concepts", supports: "Supports durable Task state and Artifacts for cross-agent results." }, { sourceId: "nist-genai-profile", supports: "Supports risk management and human oversight for high-impact generative-AI behavior." }] }),
    question("cancellation-not-stop-proof", { q: "Does an A2A cancellation request guarantee that remote work has stopped?", a: "Do not assume so. The contract must distinguish stopping further work, reversing existing side effects, and rejecting a delivered artifact.", depth: "After cancellation, the delegator should still query authoritative state. The provider should report whether work is progressing, complete, not cancelable, or requires compensation. Payments, resource creation, and other side effects require business-system idempotency and compensation outside agent messaging.", ask: "How quickly must work stop after cancellation, and who detects and compensates any side effect that already occurred?", tag: "Cancellation semantics", basis: "Task lifecycle plus business compensation", evidence: [{ sourceId: "a2a-concepts", supports: "Uses durable Task state rather than treating one message as the collaboration result." }, { sourceId: "nist-genai-profile", supports: "Supports response, recovery, and human oversight for high-impact AI actions." }] }),
    question("central-or-peer-topology", { q: "Should one orchestrator control all agents, or should agents collaborate peer to peer?", a: "Use explicit orchestration for fixed responsibility and high-risk workflows. Add peer autonomy only when dynamic collaboration materially changes the task.", depth: "Central coordination makes budget, identity, state, and audit easier to enforce but can bottleneck scale. Peer delegation is flexible and increases loops, duplicate delegation, authorization propagation, and cost risk. A business task owner can retain final control while allowing local A2A collaboration.", ask: "Who owns the final result, and who enforces budget, identity, and stop conditions when the topology changes?", tag: "Collaboration topology", basis: "Incremental complexity plus risk management", evidence: [{ sourceId: "anthropic-effective-agents", supports: "Supports starting with simpler composable patterns and adding multi-agent complexity only when the task warrants it." }, { sourceId: "a2a-concepts", supports: "Supports collaboration among independent agents through task and artifact semantics." }] }),
    question("agent-card-trust", { q: "Does discovering an Agent Card prove the remote agent's identity and capability?", a: "No. The card is a discovery entry. Verify its origin, transport, organizational identity, version, supported interface, and actual behavior before approval.", depth: "A controlled catalog should bind the card to server identity, owner, allowed tasks, authentication requirements, and suspension state. Run contract tests before first use. Dynamic discovery must not bypass vendor onboarding, network policy, data governance, or business authorization.", ask: "Who publishes and signs the Agent Card, which trust anchor validates it, and how is capability revalidated after a change?", tag: "Discovery trust", basis: "Capability discovery plus organizational trust", evidence: [{ sourceId: "a2a-specification", supports: "Defines Agent Card metadata for capabilities and interaction endpoints." }, { sourceId: "nist-zero-trust", supports: "Rejects implicit trust based only on location or declaration." }] }),
    question("delegate-minimum-authorization", { q: "May the delegator pass all of a user's permissions to a remote agent?", a: "It should not. Delegate the minimum authority bound to the current task, resource, tenant, and lifetime rather than copying a long-lived identity or complete permission set.", depth: "Distinguish the end user, delegating agent, executing agent, and resource server. The remote agent receives only the capability needed for the explicit task, with a traceable authorization chain, consent, revocation, and audit. Cross-organization calls must also map subjects and tenants deliberately.", ask: "Does the remote agent represent the user or the delegating service, when does authority expire, and who can revoke it?", tag: "Cross-domain delegation", basis: "Identity chain plus minimum authorization", evidence: [{ sourceId: "a2a-specification", supports: "Requires defined authentication and interaction contracts for A2A communication." }, { sourceId: "nist-zero-trust", supports: "Supports short-lived, resource-focused, continually evaluated access." }] }),
    question("artifact-business-acceptance", { q: "Can an A2A Artifact enter the next business stage immediately?", a: "Not by default. Validate its type, integrity, provenance, version, safety, and business acceptance criteria before consumption.", depth: "Handle messages, task state, and Artifacts separately. Use protected object references and hashes for large or sensitive outputs. The receiver validates format, content safety, and business conditions and records who accepted which version. Technical completion is not delivery acceptance.", ask: "Who validates and accepts the artifact, and how is an incorrect version withdrawn after downstream use?", tag: "Artifact acceptance", basis: "Artifact integrity plus business acceptance", evidence: [{ sourceId: "a2a-concepts", supports: "Defines Task, Message, and Artifact as distinct collaboration objects." }, { sourceId: "nist-genai-profile", supports: "Supports validation and human oversight for generated outputs." }] }),
    question("a2a-one-point-zero-acceptance", { q: "A service claims A2A 1.0 compatibility. Is network connectivity enough for acceptance?", a: "No. Verify A2A-Version, each AgentInterface URL, protocol binding and version, and functional and error-mapping parity for every advertised binding.", depth: "A client declares Major.Minor on each request, and unsupported versions must fail explicitly. Test Task, Message, Artifact, streaming, authentication, authorization, and failure cases separately for HTTP+JSON, JSON-RPC, or gRPC. Agent Card signatures are optional in 1.0 and support origin and integrity only when trusted keys, transport, and revocation are validated; they neither prove capability quality nor authorize use.", ask: "Which protocol versions and bindings are advertised, and how will upgrades prevent silent downgrade and rerun the complete capability suite?", tag: "Protocol reliability", basis: "Version negotiation plus binding contract", evidence: [{ sourceId: "a2a-spec-1-0-0", supports: "Defines A2A-Version, AgentInterface, multiple bindings, and optional Agent Card signing in A2A 1.0." }], addedAt: "2026-07-20" }),
  ]),
  evidenceCards: Object.freeze([
    Object.freeze({ id: "card-task-artifact", metric: "Card → Task → Artifact", title: "Discovery leads to a deliverable task contract", finding: "The Agent Card describes capability, the Task preserves collaboration state, and the Artifact carries a result for independent acceptance.", boundary: "Capability self-description is neither identity verification nor quality certification.", sourceId: "a2a-concepts", accent: true }),
    Object.freeze({ id: "blocking-to-push", metric: "Blocking ↔ push", title: "Delivery mode follows task duration and connectivity", finding: "Blocking, polling, streaming, and push support different result timing and client availability patterns.", boundary: "Asynchronous delivery still depends on durable Task state, idempotency, callback security, and recovery.", sourceId: "a2a-specification" }),
    Object.freeze({ id: "agent-versus-tool", metric: "Agent ↔ agent", title: "A2A and MCP point in different directions", finding: "A2A coordinates independently operated agents; MCP connects applications or agents to tools and resources.", boundary: "A system may use both protocols, but their authorization assumptions and lifecycle objects remain distinct.", sourceId: "mcp-architecture" }),
    Object.freeze({ id: "contract-not-chain-of-thought", metric: "Contract, not chain-of-thought", title: "Opaque agents can still be governed", finding: "Identity, task state, observable messages, external actions, and artifacts can form an auditable collaboration boundary without exposing private reasoning.", boundary: "Keeping internals private does not remove the provider's internal audit and quality responsibilities.", sourceId: "a2a-concepts" }),
  ]),
  terms: Object.freeze({
    a2a: Object.freeze({ name: "Agent2Agent Protocol", abbr: "A2A", definition: "A protocol for discovering independently operated agents, delegating stateful tasks, exchanging status, and delivering artifacts across system or organizational boundaries." }),
    "agent-card": Object.freeze({ name: "Agent Card", definition: "Versioned discovery metadata that declares an agent's identity, endpoints, supported interfaces, capabilities, skills, and security requirements; it is not a quality certification." }),
    "a2a-task": Object.freeze({ name: "A2A Task", definition: "The durable stateful object for a delegated unit of work, including lifecycle, messages, status events, and associated artifacts." }),
    artifact: Object.freeze({ name: "Artifact", definition: "A deliverable output associated with a Task that requires independent version, integrity, access, retention, and business-acceptance controls." }),
    "agent-collaboration": Object.freeze({ name: "Agent Collaboration", definition: "Coordinated work among independently responsible agents through explicit tasks, state, artifacts, authorization, and recovery boundaries." }),
    "identity-authorization": Object.freeze({ name: "Identity & Authorization", definition: "Verifying the real caller and target and deciding whether a subject may perform a specific action on a protected resource under the current context." }),
  }),
  sources: Object.freeze({
    "a2a-concepts": Object.freeze({ kind: "Official technical documentation", shortTitle: "A2A Core Concepts", note: "Explains Agent Card, Task, Message, Part, Artifact, and delivery patterns. Concept documentation does not certify a particular implementation or agent capability." }),
    "a2a-specification": Object.freeze({ kind: "Official protocol specification", shortTitle: "A2A Protocol Specification", note: "Defines normative A2A operations, objects, bindings, authentication considerations, and task interactions. Protocol compliance does not prove business quality or authorization." }),
    "opentelemetry-semconv": Object.freeze({ kind: "Open observability specification", shortTitle: "OpenTelemetry Semantic Conventions", note: "Defines evolving common telemetry semantics and trace context. Adopted versions must be pinned, while business outcomes, media- or agent-specific evidence, and project policy fields remain application responsibilities." }),
    "opentelemetry-genai-semconv": Object.freeze({ kind: "Open observability specification", shortTitle: "OpenTelemetry GenAI Conventions", note: "Defines evolving telemetry conventions for generative-AI clients, retrieval, agents, MCP, and Tool calls. Projects must pin the adopted version and add their own business outcomes, access controls, approvals, evidence coverage, and risk fields." }),
    "anthropic-effective-agents": Object.freeze({ kind: "Vendor engineering guidance", shortTitle: "Building Effective Agents", note: "Recommends matching orchestration complexity to task needs and starting with simpler composable patterns. It is vendor-authored guidance, not an A2A standard." }),
    "mcp-architecture": Object.freeze({ kind: "Official technical documentation", shortTitle: "MCP Architecture", note: "Defines MCP Host, Client, and Server responsibilities and server capabilities. It supports the A2A/MCP boundary but does not establish business authorization, agent-to-agent tasks, or Server trust." }),
    "nist-genai-profile": Object.freeze({ kind: "Official risk-management framework", shortTitle: "NIST AI 600-1", note: "Organizes generative-AI risk management around Govern, Map, Measure, and Manage. It is a voluntary resource, not product certification, a universal compliance checklist, a model ranking, or a performance standard." }),
    "nist-zero-trust": Object.freeze({ kind: "Official architecture guidance", shortTitle: "NIST SP 800-207", note: "Defines zero-trust principles for explicit, resource-focused access decisions without implicit trust. It does not provide an MCP/A2A implementation, AI quality evaluation, or business compensation design." }),
    "a2a-spec-1-0-0": Object.freeze({ kind: "Official protocol specification", shortTitle: "A2A 1.0.0", note: "Pins the A2A 1.0.0 contract for A2A-Version, AgentInterface, protocol bindings, optional Agent Card signatures, task behavior, authentication, and authorization responsibilities. Compatibility still requires per-binding tests and customer acceptance." }),
  }),
});
