const freeze = Object.freeze;
const items = (values) => freeze(values.map((value) => freeze(value)));

export const englishModule = freeze({
  slug: "ai-gateway",
  title: "AI Gateway",
  subtitle: "Centralize model traffic controls without hiding behavioral and policy differences",
  definition: "An AI gateway is a unified traffic and governance entry point between AI applications or agents and model or tool services. It centralizes access, identity, routing, rate limits, security, cost, and observability in an auditable enforcement plane.",
  position: "It connects chat applications, RAG, agents, and business APIs to public model APIs, third-party models, self-hosted inference, and MCP servers. It governs calls across providers; it does not perform model reasoning or own business-process orchestration.",
  relatedSlugs: freeze(["llm-inference", "mcp", "a2a", "ai-agent", "ai-ops", "security"]),
  sections: items([
    { id: "gateway-policy-data-plane", eyebrow: "POLICY AND DATA PLANE", title: "Make routing, identity, and failure semantics explicit at the shared entry point", lead: "Unify stable request semantics while preserving differences that change quality, risk, region, or recovery. A gateway earns its place only when it removes duplicated controls or creates measurable governance evidence.", blocks: items([
      { type: "steps", title: "Six operating principles", items: items([
        { id: "gateway-unified-access", title: "Unified access", body: "Decouple applications from endpoint and version details through a stable API or SDK while retaining provider-specific capabilities as explicit contract fields.", decision: "Protocol compatibility does not establish behavioral equivalence." },
        { id: "gateway-credential-isolation", title: "Identity and credential isolation", body: "Applications use workload identity or short-lived credentials; the gateway maps them to provider access without spreading long-lived secrets into clients, prompts, or repositories.", decision: "Retain tenant, user, and application identity separately for accountability." },
        { id: "gateway-policy-routing", title: "Policy-aware routing", body: "Choose an endpoint using task, risk, modality, data classification, region, validated quality, capacity, latency, and cost.", decision: "Define which boundaries may change during fallback before automating it." },
        { id: "gateway-traffic-cost", title: "Traffic and cost governance", body: "Apply quotas, rate limits, concurrency, token, and budget controls before requests; attribute actual attempts and successful outcomes after them.", decision: "Match each limit to the real bottleneck rather than one convenient average." },
        { id: "gateway-safety-audit", title: "Guardrails and audit", body: "Enforce input, output, and tool policy, sensitive-data handling, and audit at a shared point while leaving resource-side authorization and transaction controls intact.", decision: "The gateway cannot authorize a business action on behalf of the system of record." },
        { id: "gateway-end-to-end-telemetry", title: "End-to-end telemetry", body: "Join application, retrieval, model, tool, retry, usage, cost, and error events under one trace and version context.", decision: "Capture content only under explicit sensitivity, purpose, and retention policy." },
      ]) },
      { type: "boundary", title: "Critical boundary", items: items([{ id: "gateway-policy-boundary", title: "One endpoint is not one behavior", body: "A normalized payload can reduce integration cost without making model quality, tool support, context, error semantics, safety policy, or data handling interchangeable.", boundary: "Every routed and fallback path still requires task-level evaluation and a tested recovery contract." }]) },
    ]) },
    { id: "gateway-curriculum", eyebrow: "COURSE MAP", title: "Design the gateway from contract to controlled rollout", lead: "Treat the gateway as a critical data plane with a versioned policy plane, not as a transparent proxy.", blocks: items([
      { type: "cards", items: items([
        { id: "gateway-chapter-access", title: "Unified access and capability contracts", body: "Normalize requests, streams, errors, usage, identity, and tool envelopes while exposing modality, structured-output, context, and provider-specific semantics that affect outcomes.", decision: "Normalize stable semantics and publish material differences.", boundary: "API compatibility does not remove regression testing.", sourceIds: freeze(["cloudflare-ai-gateway", "opentelemetry-genai-semconv"]) },
        { id: "gateway-chapter-identity", title: "Identity and downstream credentials", body: "Preserve caller, tenant, workload, and delegated-user identity; issue or map short-lived provider credentials and bind tokens to protected resources.", decision: "Prevent a shared gateway account from erasing the authorization chain.", boundary: "Central authentication cannot replace each tool's business authorization.", sourceIds: freeze(["nist-zero-trust", "mcp-authorization"]) },
        { id: "gateway-chapter-routing", title: "Routing and fallback", body: "Route by hard policy first, then validated capability, health, capacity, latency, and cost. Maintain approved candidates, prohibited tasks, permitted degradation, and stop conditions.", decision: "Record why a route was selected and make the router independently reversible.", boundary: "Fallback can change quality, region, tools, data handling, and safety semantics.", sourceIds: freeze(["cloudflare-ai-gateway", "nist-genai-profile"]) },
        { id: "gateway-chapter-reliability", title: "Timeout, retry, and streaming semantics", body: "Assign one retry owner, a total deadline, retryable errors, idempotency rules, and behavior before and after the first output token.", decision: "Bound retry amplification across application, SDK, gateway, and provider.", boundary: "A partial stream or state-changing tool call usually cannot be replayed safely.", sourceIds: freeze(["cloudflare-ai-gateway", "opentelemetry-semconv"]) },
        { id: "gateway-chapter-budget", title: "Rate limits, quotas, and budgets", body: "Control requests, tokens, concurrency, tool loops, and spend by consumer, task, model, and environment, while preserving capacity for protected traffic.", decision: "Optimize cost per successful outcome after quality and risk gates.", boundary: "A budget cutoff can shift cost into failed work or manual recovery.", sourceIds: freeze(["cloudflare-ai-gateway", "opentelemetry-genai-semconv"]) },
        { id: "gateway-chapter-cache", title: "Semantic and exact caching", body: "Reuse only responses whose identity, tenant, data, model, prompt, tool, policy, language, and freshness boundaries are compatible; reauthorize at read time.", decision: "Define prohibited classes and invalidation before measuring hit rate.", boundary: "Semantic similarity does not establish that two users may share a result.", sourceIds: freeze(["cloudflare-ai-gateway", "nist-zero-trust"]) },
        { id: "gateway-chapter-policy-release", title: "Policy packaging and release", body: "Version routing, limits, retries, guardrails, caching, and logging together. Use replay, shadow decisions, protected cohorts, progressive rollout, and atomic rollback.", decision: "Treat policy changes as production changes with evidence and approval.", boundary: "A percentage rollout alone does not protect high-risk requests.", sourceIds: freeze(["nist-genai-profile", "opentelemetry-genai-semconv"]) },
        { id: "gateway-chapter-observability", title: "Observability and business attribution", body: "Record logical requests and actual attempts, routing reasons, cache and retry state, model and policy versions, tool calls, latency, usage, and the business end state.", decision: "Separate request cost from cost per successful task.", boundary: "Provider usage data alone cannot attribute business value or risk.", sourceIds: freeze(["opentelemetry-genai-semconv", "cloudflare-ai-gateway"]) },
      ]) },
    ]) },
    { id: "gateway-study-guide", eyebrow: "LEARN, PRACTICE, PROVE", title: "Introduce AI-specific controls only where the existing platform has a measured gap", lead: "The goal is a simpler, observable policy chain—not an additional layer for its own sake.", blocks: items([
      { type: "cards", title: "Learning outcomes", items: items([
        { id: "gateway-outcome-boundary", title: "Separate API and AI gateway responsibilities", body: "Reuse mature network and API controls while identifying model-aware semantics that need an extension." },
        { id: "gateway-outcome-routing", title: "Design controlled routing", body: "Combine hard policy, evaluated capability, health, fallback, and stop conditions." },
        { id: "gateway-outcome-governance", title: "Govern identity, cache, tools, and spend", body: "Keep current authorization and version boundaries intact across centralization." },
        { id: "gateway-outcome-observability", title: "Prove policy outcomes", body: "Link the gateway decision to model calls, tool actions, costs, and business completion." },
      ]) },
      { type: "steps", title: "Recommended route", items: items([
        { id: "gateway-route-contract", title: "Establish the request contract", body: "Normalize models, streams, errors, usage, identity, and explicit capabilities.", decision: "Checkpoint: applications do not hard-code provider differences that the gateway owns." },
        { id: "gateway-route-policy", title: "Add explicit policies", body: "Define routing, limits, budgets, cache, fallback, guardrails, and logging with owners and failure modes.", decision: "Checkpoint: every policy has a signal, stop condition, and rollback." },
        { id: "gateway-route-release", title: "Release through replay and shadow", body: "Compare proposed decisions offline, observe them without side effects, then canary by tenant, task, and risk.", decision: "Checkpoint: high-risk traffic remains outside an unproven change." },
        { id: "gateway-route-recovery", title: "Exercise provider and gateway failure", body: "Test stop, approved fallback, bypass, restoration, and policy equivalence under realistic streaming and tool conditions.", decision: "Checkpoint: continuity never silently removes required controls." },
        { id: "gateway-route-attribution", title: "Close business attribution", body: "Join logical tasks, actual attempts, retries, cache, tools, and final outcome.", decision: "Checkpoint: a cost claim distinguishes calling cost from successful-task cost." },
      ]) },
      { type: "cards", title: "Practice labs", items: items([
        { id: "gateway-lab-routing", title: "Release a controlled routing policy", body: "Move 30% of eligible simple requests to a lower-cost model after offline replay and shadow validation; protect high-risk groups and set quality and tail-latency rollback thresholds.", decision: "Deliverable: policy version, evidence, and rollback runbook.", boundary: "Acceptance: protected traffic cannot enter the experiment and regressions are detected before complaints.", sourceIds: freeze(["cloudflare-ai-gateway", "opentelemetry-genai-semconv", "nist-genai-profile"]) },
        { id: "gateway-lab-cache", title: "Decide whether semantic caching is justified", body: "Classify cacheable and prohibited FAQ traffic, design identity and version keys, define freshness and invalidation, and test harmful near matches.", decision: "Deliverable: cache policy and false-hit test set.", boundary: "Acceptance: benefits use successful outcomes, and no cache hit bypasses current authorization.", sourceIds: freeze(["nist-zero-trust", "nist-genai-profile"]) },
        { id: "gateway-lab-failure", title: "Exercise provider failure and streaming interruption", body: "Inject timeouts, rate limits, partial streams, and tool-side effects; verify retry ownership, approved fallback, user-visible states, and restoration.", decision: "Deliverable: failure matrix and recovery evidence.", boundary: "Acceptance: one request cannot multiply without bound or duplicate a business action.", sourceIds: freeze(["cloudflare-ai-gateway", "opentelemetry-genai-semconv"]) },
      ]) },
    ]) },
    { id: "gateway-presales-decisions", eyebrow: "PRESALES DECISIONS", title: "Five choices that determine whether a gateway reduces or adds operational risk", lead: "Start with duplicated controls, behavioral boundaries, and failure ownership. Select a gateway pattern only after the operating problem and the evidence of improvement are explicit.", blocks: items([
      { type: "table", columns: freeze(["Decision signal", "Recommended position", "Boundary"]), items: items([
        { id: "gateway-decision-introduce", title: "When is a dedicated AI gateway justified?", cells: freeze(["Several applications or model providers now duplicate credentials and integration logic, or the organization cannot attribute cost and risk consistently.", "Prove unified identity, routing, limits, and tracing in one high-value traffic domain before migrating more applications. A small, low-volume experiment may remain on the model platform's native endpoint.", "Do not add a layer for its own sake. The gateway must remove duplicated controls or create measurable governance evidence."]) },
        { id: "gateway-decision-api-layer", title: "Reuse the API gateway or add AI-aware controls?", cells: freeze(["The existing API gateway already handles network access, authentication, and basic rate limits but cannot interpret streaming, token usage, model versions, prompt policy, or tool calls.", "Retain mature enterprise API controls and add only the model-aware routing, cost, guardrail, and semantic telemetry that has a clear owner.", "Do not let both layers retry, throttle, cache, or rewrite the same request without an explicit precedence contract."]) },
        { id: "gateway-decision-managed", title: "Managed or self-hosted?", cells: freeze(["The choice depends on delivery speed, private networking, data residency, policy extensibility, portability, and the team's ability to operate a critical data plane.", "Validate model coverage, identity integration, network topology, policy extension points, log retention, service commitments, and billing with a representative path. A managed control plane with a private data plane may be appropriate where supported.", "Regions, supported providers, features, and service commitments change; verify the purchasing decision against current official documentation and contract terms."]) },
        { id: "gateway-decision-cache", title: "Enable semantic caching?", cells: freeze(["A material share of traffic is similar, read-only, reusable, and tolerant of a defined freshness window, while latency or cost is a measured constraint.", "Pilot only where authorization, tenant, language, model, prompt, tool, policy, and freshness boundaries can be encoded and rechecked on every read.", "Semantic similarity does not establish permission to share. Personalized, sensitive, real-time, or action-triggering requests should not be reused across users by default."]) },
        { id: "gateway-decision-mcp", title: "Route MCP traffic through the gateway?", cells: freeze(["Agents use multiple MCP servers and tool credentials, authorization, audit, or network egress is fragmented.", "Use the gateway where it adds registration, identity exchange, policy enforcement, and call telemetry; continue to apply MCP authorization and least privilege at each protected resource and business tool.", "MCP is an interoperability protocol and the gateway is an enforcement point. Neither one makes a tool invocation authorized merely because the call was successfully transported."]) },
      ]) },
    ]) },
    { id: "gateway-production-deep-dive", eyebrow: "PRODUCTION JUDGMENT", title: "Turn a unified entry point into a verifiable governance data plane", lead: "Forwarding requests is the easy part. The production test is whether policy changes can be released safely and whether failures across proxies, retries, identity mappings, and providers remain attributable.", blocks: items([
      { type: "steps", title: "Release a policy bundle without creating an untracked change source", items: items([
        { id: "gateway-deep-freeze-bundle", title: "Freeze the policy bundle", body: "Bind routing rules, model catalog, limits, retries, guardrails, log fields, and exception lists to one version with its approver and effective scope.", decision: "Require every request to resolve to the exact policy bundle that governed it, not merely the current configuration.", boundary: "The gateway policy version does not replace independent versions for the model, prompt, retrieval data, or tool schema.", sourceIds: freeze(["nist-genai-profile", "opentelemetry-genai-semconv"]) },
        { id: "gateway-deep-offline-replay", title: "Run an offline replay", body: "Use appropriately minimized historical traffic to compare old and proposed routing, blocking, quota, cost, and fallback decisions without executing high-impact tools.", decision: "Investigate false blocks, regional changes, and capability mismatches before online exposure.", boundary: "Replay cannot reproduce every live quota, network failure, or transient provider condition.", sourceIds: freeze(["nist-genai-profile", "cloudflare-ai-gateway"]) },
        { id: "gateway-deep-shadow-decision", title: "Shadow the decision", body: "Continue executing the approved policy while the candidate computes and records its proposed action against real traffic.", decision: "Explain differences by rule, input attribute, tenant, task, and risk slice; an aggregate agreement rate is insufficient for protected traffic.", boundary: "Shadow processing can still expose sensitive metadata, so access, purpose, region, and retention controls continue to apply.", sourceIds: freeze(["nist-genai-profile", "opentelemetry-genai-semconv"]) },
        { id: "gateway-deep-segmented-canary", title: "Canary by risk segment", body: "Enable the candidate by tenant, application, task, and risk tier while observing business success, tail latency, retries, blocks, and cost per successful task.", decision: "Begin with low-risk, read-only traffic and keep high-impact actions behind separate approval.", boundary: "A percentage alone is not a safety boundary; a small critical cohort can disappear inside a healthy aggregate.", sourceIds: freeze(["nist-genai-profile", "opentelemetry-genai-semconv"]) },
        { id: "gateway-deep-evidence-rollback", title: "Roll back with evidence", body: "Atomically restore the last validated bundle when a threshold is crossed and retain the trigger, affected requests, routing decisions, and downstream outcomes for review.", decision: "Exercise rollback before release and ensure a control-plane outage cannot prevent the data plane from using its last validated policy.", boundary: "Rolling back gateway policy cannot undo a payment, deletion, message, or other side effect that has already occurred.", sourceIds: freeze(["nist-genai-profile", "opentelemetry-genai-semconv"]) },
      ]) },
      { type: "table", title: "Diagnose the control chain before blaming the model or provider", columns: freeze(["Failure mechanism", "Corrective analysis", "Boundary"]), items: items([
        { id: "gateway-deep-retry-multiplication", title: "Tail latency and traffic spike together", cells: freeze(["The application, API gateway, AI gateway, and model SDK each retry, multiplying attempts until connections or quotas are exhausted.", "Count attempts at every layer under one trace, then assign one retry owner, a total deadline, and explicit idempotency conditions.", "Removing duplicate retries does not eliminate the need for bounded recovery from errors that are demonstrably transient and safe to replay."]), sourceIds: freeze(["opentelemetry-semconv", "opentelemetry-genai-semconv"]) },
        { id: "gateway-deep-stream-buffering", title: "Time to first output rises after adding the gateway", cells: freeze(["An intermediary buffers the full response for inspection or logging and breaks upstream streaming behavior.", "Measure model-side, gateway-ingress, and client-visible first-event times separately, and verify how every proxy handles the streaming protocol.", "Some output policies require complete content. If so, state the experience tradeoff instead of presenting buffered delivery as streaming."]), sourceIds: freeze(["opentelemetry-semconv", "opentelemetry-genai-semconv"]) },
        { id: "gateway-deep-identity-collapse", title: "The audit trail shows only one shared account", cells: freeze(["The gateway maps users, tenants, and applications to one downstream credential without retaining a trustworthy principal and delegation chain.", "Verify that traces, audit records, and downstream policy can answer who acted, for whom, on which resource, and under which authorization.", "Propagating an identifier must not turn an unverified client assertion into an authenticated identity."]), sourceIds: freeze(["nist-zero-trust", "mcp-authorization"]) },
        { id: "gateway-deep-quota-mismatch", title: "Gateway limits pass while the provider still throttles", cells: freeze(["The entry point limits requests, while the downstream service constrains tokens, concurrency, model, or region; long requests and bursts escape the average.", "Model requests, tokens, concurrency, queueing, and downstream allowance together and load-test the actual request-length distribution.", "A local estimate does not supersede the provider's effective quota or error semantics."]), sourceIds: freeze(["cloudflare-ai-gateway", "opentelemetry-genai-semconv"]) },
        { id: "gateway-deep-semantic-failover", title: "Failover returns success but the task fails", cells: freeze(["The alternate endpoint returns a successful response but lacks equivalent context, tool, schema, language, regional, or safety behavior.", "Treat every fallback as a release path and validate its supported equivalence range with task-level evaluations.", "Continuity policy must state in advance what may degrade; an incident is not the time to guess which contract can be sacrificed."]), sourceIds: freeze(["nist-genai-profile", "cloudflare-ai-gateway"]) },
      ]) },
    ]) },
    { id: "gateway-cloud", eyebrow: "CLOUD CONNECTIONS", title: "Map gateway responsibilities to existing cloud and enterprise controls", lead: "Use product capabilities to implement a defined responsibility boundary. The architecture still needs explicit owners for identity, routing, tool authorization, observability, and business outcomes.", blocks: items([
      { type: "table", columns: freeze(["Service capabilities", "Value", "Discovery question"]), items: items([
        { id: "gateway-cloud-ingress", title: "Ingress and identity", cells: freeze(["API management, load balancing, web application firewall, IAM, workload identity, and secrets management", "Keep model credentials inside a controlled cloud boundary while reusing enterprise authentication, network, and audit controls.", "Who holds model credentials today, and are user attribution, private access, or cross-account authorization required?"]), sourceIds: freeze(["nist-zero-trust"]) },
        { id: "gateway-cloud-routing", title: "Model catalog and routing", cells: freeze(["Model services, service discovery, traffic management, policy engines, disaster recovery, and multi-region ingress", "Decouple applications from individual endpoints and create an explicit policy path across managed and self-hosted models.", "How many providers are in scope, and which data, capability, regional, and quality boundaries must remain unchanged during a switch?"]), sourceIds: freeze(["cloudflare-ai-gateway", "nist-genai-profile"]) },
        { id: "gateway-cloud-tools", title: "Safety and tool governance", cells: freeze(["Content safety, data loss prevention, MCP or API registries, zero-trust access, and approval workflow", "Connect input and output controls, tool discovery, and high-impact action review to shared security services.", "Which requests contain sensitive data, and which tools can write to production, pay, delete, or communicate externally?"]), sourceIds: freeze(["mcp-authorization", "nist-zero-trust"]) },
        { id: "gateway-cloud-observability", title: "Observability and FinOps", cells: freeze(["Tracing, logs, metrics, cost management, alerting, and analytics storage", "Compare task success, tail latency, token use, retries, and cost per successful outcome across models and consumers.", "Can one business task be joined to its routing decision, model and tool calls, errors, cost, and authoritative final outcome?"]), sourceIds: freeze(["opentelemetry-semconv", "opentelemetry-genai-semconv", "cloudflare-ai-gateway"]) },
      ]) },
    ]) },
  ]),
  qa: items([
    { id: "api-gateway-versus-ai-gateway", q: "We already have an API gateway. Why would we need an AI gateway?", a: "Reuse the existing gateway for network, authentication, and API lifecycle controls. Add an AI-aware layer only when token accounting, model routing, streaming, prompt and response policy, tool governance, or generative-AI telemetry is a demonstrated gap.", depth: "The layers normally divide responsibility rather than replace one another. Prove concrete outcomes such as one less integration, fewer distributed secrets, and a traceable end-to-end task, and test for conflicting retries, timeouts, and rate limits.", ask: "Which AI semantics are invisible today, and what cost, risk, or release delay has that caused?", tag: "Architecture boundary", basis: "Product capability plus observability standards", evidence: items([{ sourceId: "cloudflare-ai-gateway", supports: "Provides an official product example of proxying, analytics, caching, rate limiting, and multi-provider governance." }, { sourceId: "opentelemetry-genai-semconv", supports: "Provides common generative-AI telemetry semantics while leaving business outcomes to the application." }]) },
    { id: "routing-cost-speed-quality", q: "Can automatic multi-model routing make the system cheaper, faster, and more accurate at the same time?", a: "Do not promise all three. Routing selects from measured candidates; quality, latency, cost, and compliance usually require priorities and non-negotiable gates.", depth: "Build task-level offline baselines, then record routing reason, model version, success, P95 latency, and cost per successful task online. Validate context, tool protocol, structured output, region, and safety equivalence for every fallback.", ask: "Which metric is a hard gate, and may a failure path degrade quality, function, or region?", tag: "Model routing", basis: "Risk management plus online validation", evidence: items([{ sourceId: "nist-genai-profile", supports: "Supports context- and risk-tolerance-based measurement rather than deployment by feature claim alone." }, { sourceId: "opentelemetry-genai-semconv", supports: "Supports comparable provider, model, token, latency, and error attributes." }]) },
    { id: "gateway-single-point-failure", q: "Can the AI gateway become a single point of failure or a performance bottleneck?", a: "Yes, so treat it as a critical data plane: scale statelessly, define timeout and retry ownership, deploy for fault isolation, version policy, and observe the gateway itself.", depth: "Test time to first token, long streams, concurrency, downstream throttling, connection exhaustion, and provider failure—not only average proxy overhead. Separate control-plane from data-plane failure and state which controls an emergency bypass preserves.", ask: "On gateway failure, should traffic stop, degrade, or bypass, and which controls can never be skipped?", tag: "Reliability", basis: "Critical data-plane engineering", evidence: items([{ sourceId: "cloudflare-ai-gateway", supports: "Demonstrates a managed proxy on the centralized multi-provider call path; current SLA and regional claims require procurement-time verification." }, { sourceId: "nist-zero-trust", supports: "Requires policy evaluation for resource access rather than implicit trust based on network path." }]) },
    { id: "mcp-through-gateway-security", q: "Does connecting an MCP server through the gateway make tool calls secure?", a: "No. The gateway can centralize authentication, policy, and audit, but every tool call still needs a real principal, explicit authorization, validated arguments, and least privilege in the business service.", depth: "MCP authorization governs how a client obtains resource access; it does not replace tool-specific authorization. Guard against confused clients, token passthrough, broad scopes, and cross-tenant logs. Add confirmation, approval, idempotency, and compensation for money, deletion, or production change.", ask: "Who is the principal, what resource and action does the scope cover, and who approves high-impact tools?", tag: "MCP governance", basis: "MCP authorization plus zero trust", evidence: items([{ sourceId: "mcp-authorization", supports: "Defines resource-server, client, user-consent, and token boundaries for MCP authorization." }, { sourceId: "nist-zero-trust", supports: "Requires principal verification and least-privilege authorization before access." }]) },
    { id: "routing-signal-selection", q: "Which signals should drive model routing in an AI gateway?", a: "Use task, risk, modality, data boundary, validated quality, and real-time capacity—not only the lowest price or round-robin model names.", depth: "Begin with explainable rules: sensitive data reaches only approved endpoints, vision work reaches validated multimodal models, and critical tasks use approved versions. Record dynamic routing reasons and candidate paths and optimize cost per successful task while preserving output and safety contracts.", ask: "Which requests may never reach a provider or region, and how will a wrong route be detected and reversed?", tag: "Routing policy", basis: "Policy control plus application evaluation", evidence: items([{ sourceId: "cloudflare-ai-gateway", supports: "Supports centralized proxying, analytics, and management across model providers." }, { sourceId: "nist-genai-profile", supports: "Supports applying risk tolerance and context of use when selecting controls." }]) },
    { id: "retry-fallback-amplification", q: "Why can gateway retries and fallback make an outage worse?", a: "If the application, SDK, gateway, and provider all retry, they amplify traffic, cost, and duplicate actions while obscuring the original error.", depth: "Assign one retry owner and a total deadline; retry only explicit transient, idempotent operations a bounded number of times. Partial streams, state-changing tools, and provider throttling usually cannot be replayed blindly. Fallback also needs context, schema, and safety compatibility.", ask: "Which layers retry today, how many calls can one request produce, and can a tool action be duplicated?", tag: "Reliability", basis: "Retry budget plus observability", evidence: items([{ sourceId: "opentelemetry-genai-semconv", supports: "Supports joining requests, model calls, and agent operations in common telemetry." }, { sourceId: "cloudflare-ai-gateway", supports: "Places caching, rate limiting, and failure policy on a centralized model-traffic path." }]) },
    { id: "safe-policy-release", q: "How should an AI gateway policy be released safely?", a: "Version routing, limits, retries, guardrails, cache, and logging as one policy bundle; replay and shadow its decisions before a risk-segmented canary.", depth: "Replay compares old and proposed decisions without executing high-impact actions. Shadow mode records the proposed choice without changing the response. Canary by tenant, task, and risk, then atomically roll back on quality, latency, risk, or cost thresholds.", ask: "Which changes affect business outcomes, who approves them, and can the exact policy used for a request be reconstructed?", tag: "Policy release", basis: "Release governance plus observability", evidence: items([{ sourceId: "nist-genai-profile", supports: "Supports measuring and managing risk before and after system changes." }, { sourceId: "opentelemetry-genai-semconv", supports: "Supports joining generative-AI calls with common version attributes." }]) },
    { id: "arbitrary-model-failover", q: "During provider failure, should the gateway switch automatically to any available model?", a: "No. Switch only to candidates prevalidated for capability, data boundary, and safety policy. Block or escalate tasks when no candidate meets hard gates.", depth: "A successful response can still lack required tools, schema, context, language, or region. Maintain evidence, permitted degradation, and prohibited tasks for every path and exercise route reason, quality, tail latency, and recovery.", ask: "During failure, may quality, function, region, or latency change, and which tasks cannot degrade automatically?", tag: "Failure degradation", basis: "Model equivalence plus risk gates", evidence: items([{ sourceId: "nist-genai-profile", supports: "Supports identifying dependency failure and preparing proportionate response and recovery." }, { sourceId: "cloudflare-ai-gateway", supports: "Supports centralized multi-provider proxying and failover features while leaving equivalence validation to the application." }]) },
    { id: "cross-user-cache-hit", q: "May an AI gateway return a cache hit directly to another user?", a: "Not by default. The cache key and eligibility policy must include every tenant, principal, model, prompt, tool, data, and policy version that can change output or authorization.", depth: "Separate public static, tenant, and user-authorized content. Decide reuse before insertion, reauthorize on every hit, and invalidate for policy, revocation, knowledge, and model change. Do not cache high-risk responses when isolation cannot be proved.", ask: "Which identity and version dimensions enter the key, and how quickly does revocation prevent old hits?", tag: "Cache isolation", basis: "Cache semantics plus current authorization", evidence: items([{ sourceId: "nist-zero-trust", supports: "Requires current subject and resource authorization on every access path, including cached results." }, { sourceId: "cloudflare-ai-gateway", supports: "Provides a gateway caching capability whose isolation semantics remain an application design responsibility." }]) },
    { id: "gateway-cost-attribution", q: "If all model traffic crosses the gateway, can it allocate every business cost accurately?", a: "Not yet. It must also join tenant, task, model, retries, cache, tools, and final business outcome.", depth: "Provider billing often sees endpoint usage only. Record the logical request and each actual attempt, distinguish user traffic, retries, shadows, and evaluations, then allocate by successful task. Without an outcome, the result is call cost rather than business cost.", ask: "How many model and tool calls form one task, and who owns retries and shadow traffic?", tag: "Cost attribution", basis: "Logical request plus actual attempts", evidence: items([{ sourceId: "opentelemetry-genai-semconv", supports: "Supports model, usage, and invocation-correlation attributes." }, { sourceId: "cloudflare-ai-gateway", supports: "Supports observing requests and usage at a shared multi-model entry point." }]) },
    { id: "direct-provider-break-glass", q: "Can an application retain a direct model path for emergencies?", a: "A break-glass path can exist, but it must not become a permanent governance back door.", depth: "Provide equivalent identity, data, audit, and safety controls and restrict activation conditions, owner, and automatic expiry. Failure drills must prove that the path preserves region, content-policy, and sensitive-logging requirements.", ask: "Who can activate direct access, which controls remain, and how is the path verified and closed?", tag: "Bypass governance", basis: "Continuity plus control equivalence", evidence: items([{ sourceId: "nist-zero-trust", supports: "Requires policy enforcement on every access path regardless of network route." }, { sourceId: "nist-genai-profile", supports: "Supports controlled response and recovery for dependency failure." }]) },
    { id: "midstream-model-switch", q: "After part of a streamed response reaches the user, can the gateway switch models without loss?", a: "Usually not. Emitted content, context state, and billing give a midstream switch semantic consequences.", depth: "Before the first token, policy may retry or fall back. After streaming begins, define whether to terminate, restart, or attempt a clearly marked continuation and return a machine-readable state. High-risk output may be buffered before display at the cost of time to first token.", ask: "What does the user see after interruption, and is continuation, regeneration, or explicit failure permitted?", tag: "Streaming failure", basis: "Output commitment plus recovery semantics", evidence: items([{ sourceId: "opentelemetry-genai-semconv", supports: "Supports response and generation-call attributes useful for attributing streamed failures." }, { sourceId: "nist-genai-profile", supports: "Supports transparent response and recovery mechanisms for system failure." }]) },
  ]),
  evidenceCards: items([
    { id: "gateway-common-telemetry", metric: "Common semantics", title: "Cross-model telemetry needs shared fields", finding: "OpenTelemetry provides semantic conventions for generative-AI model calls, agents, and related events across frameworks and providers.", boundary: "Standard fields do not automatically provide business success, risk labels, or cost ownership.", sourceId: "opentelemetry-genai-semconv", accent: true },
    { id: "gateway-tool-authorization", metric: "Authorization boundary", title: "Protocol access is not tool authorization", finding: "The MCP authorization specification separates client, authorization server, and resource server and binds access tokens to protected resources.", boundary: "It cannot replace tool-level business permissions, argument validation, approval, or transaction controls.", sourceId: "mcp-authorization" },
    { id: "gateway-routing-risk-loop", metric: "Continuous governance", title: "Routing policy belongs in the risk loop", finding: "The NIST Generative AI Profile calls for risk to be identified, measured, managed, and reviewed in the context of use.", boundary: "The framework supplies a method, not a universal routing threshold or release pass rate.", sourceId: "nist-genai-profile" },
  ]),
  terms: freeze({
    api: freeze({ name: "Application Programming Interface", abbr: "API", definition: "A software contract through which systems exchange requests and results in an agreed format." }),
    "shadow-traffic": freeze({ name: "Shadow Traffic", definition: "A controlled copy or replay used to observe a candidate decision without returning its response or causing an unapproved side effect." }),
    observability: freeze({ name: "Observability", definition: "Using metrics, logs, traces, and version context to explain what a system did and why." }),
    guardrails: freeze({ name: "Guardrails", definition: "Detection, constraints, or blocking around input, context, output, and action; they do not replace identity or business authorization." }),
    "identity-authorization": freeze({ name: "Identity & Authorization", definition: "Establishing the real principal and deciding whether it may access a resource or perform an action in context." }),
    "ai-gateway": freeze({ name: "AI Gateway", definition: "A shared enforcement point between applications and model or tool endpoints for identity, routing, budgets, safety, and telemetry." }),
    "model-routing": freeze({ name: "Model Routing", definition: "Selecting an endpoint and fallback according to task, quality, latency, cost, region, policy, and failure state." }),
    "rate-limiting": freeze({ name: "Rate Limiting", definition: "Constraining requests, tokens, or concurrency by identity, tenant, model, or time window to protect capacity and control abnormal traffic." }),
    "semantic-cache": freeze({ name: "Semantic Cache", definition: "Reusing a validated response for a semantically similar request only within compatible identity, authorization, version, and freshness boundaries." }),
    slo: freeze({ name: "Service Level Objective", abbr: "SLO", definition: "A measurable internal or agreed service target used for operating decisions and error-budget management." }),
    finops: freeze({ name: "FinOps", definition: "A cross-functional operating practice that connects technology use, unit cost, budgets, and business value." }),
  }),
  sources: freeze({
    "nist-genai-profile": freeze({ kind: "Official risk-management framework", shortTitle: "NIST AI 600-1", note: "Organizes generative-AI risk around Govern, Map, Measure, and Manage. It is voluntary guidance and does not define product-specific routing or release thresholds." }),
    "opentelemetry-genai-semconv": freeze({ kind: "Open observability specification", shortTitle: "OTel GenAI SemConv", note: "Provides evolving semantics for generative-AI clients, agents, retrieval, MCP, and tool calls. Pin the adopted version and add business outcomes, policy decisions, and cost ownership." }),
    "cloudflare-ai-gateway": freeze({ kind: "Official product documentation", shortTitle: "Cloudflare AI Gateway", note: "Documents a managed AI gateway with proxying, analytics, caching, rate limiting, and provider-management capabilities. Features, plans, regions, and service commitments are time-sensitive and provider-specific." }),
    "opentelemetry-semconv": freeze({ kind: "Open observability specification", shortTitle: "OpenTelemetry Semantic Conventions", note: "Defines common semantic names for traces, metrics, logs, events, and resources. GenAI-specific conventions evolve separately, and business fields remain implementation-defined." }),
    "nist-zero-trust": freeze({ kind: "Official architecture publication", shortTitle: "NIST SP 800-207", note: "Defines zero-trust architecture around explicit subject and resource authentication and authorization rather than network-location trust." }),
    "mcp-authorization": freeze({ kind: "Official protocol specification", shortTitle: "MCP Authorization", note: "Separates client, authorization-server, and resource-server responsibilities and binds tokens to protected resources. It does not replace tool-internal business authorization." }),
  }),
});
