const freezeItems = (items) => Object.freeze(items.map((item) => Object.freeze(item)));
const block = (type, title, items, extra = {}) => Object.freeze({ type, title, ...extra, items: freezeItems(items) });
const section = (id, eyebrow, title, lead, blocks) => Object.freeze({ id, eyebrow, title, lead, blocks: Object.freeze(blocks) });
const question = (id, copy) => Object.freeze({ ...copy, id, evidence: freezeItems(copy.evidence) });

export const englishModule = Object.freeze({
  slug: "fine-tuning",
  title: "Fine-tuning",
  subtitle: "Shape repeatable behavior without turning model weights into a knowledge base",
  definition: "Fine-tuning continues training from an existing model so that a repeatable task pattern, output contract, tone, or domain behavior is expressed more consistently in model weights or an adapter. A production program includes data governance, evaluation, release, monitoring, feedback, and rollback—not merely a completed training job.",
  position: "This module sits in the model-customization layer. It receives stable behavior requirements that prompting and retrieval cannot reliably meet, then connects training infrastructure, model and adapter governance, inference, evaluation, and production operations.",
  relatedSlugs: Object.freeze(["prompt-engineering", "rag", "llm-training", "evaluation", "llm-inference", "ai-infra-platform"]),
  sections: Object.freeze([
    section(
      "tuning-lifecycle",
      "CUSTOMIZATION DISCIPLINE",
      "Fine-tuning is a governed release loop, not a shortcut around application design",
      "Start by identifying whether the unresolved problem is knowledge, behavior, or base-model capability. Choose the least invasive method that can meet the acceptance criteria, and bind the resulting model change to evidence and a rollback path.",
      [
        block("cards", "Five operating principles", [
          { id: "principle-separate-knowledge-behavior-capability", title: "Separate knowledge, behavior, and capability", body: "Use retrieval for current, private, attributable facts; use fine-tuning for stable behavioral patterns; change the base model when the required capability is fundamentally absent.", decision: "Test prompting, retrieval, workflow controls, and model replacement as explicit baselines before training." },
          { id: "principle-choose-adaptation-scope", title: "Match the adaptation scope to the evidence", body: "Full fine-tuning updates the complete parameter set. LoRA learns low-rank updates against frozen weights; QLoRA trains a LoRA adapter against a quantized frozen base.", decision: "Begin with a parameter-efficient method for enterprise behavior customization unless evidence justifies the wider cost and regression surface of full fine-tuning." },
          { id: "principle-data-before-training-code", title: "Data quality precedes training code", body: "Roles, chat templates, target answers, refusal examples, permissions, personal data handling, deduplication, and test isolation define the training signal. A framework cannot repair a bad demonstration.", decision: "Approve the data card, sample specification, and frozen evaluation set before selecting hyperparameters." },
          { id: "principle-define-exam-first", title: "Define the exam before training", body: "Training loss measures fit to the optimization objective. It does not prove task success, safety retention, general capability, or serving economics.", decision: "Set pass, pause, and unacceptable-regression thresholds for representative and high-risk slices before the first run." },
          { id: "principle-release-and-rollback", title: "Treat every adapter as a release unit", body: "A model or adapter must be registered, evaluated, deployed gradually, observed, and reversible. Adjudicated failures become governed candidates for the next data revision.", decision: "Bind the dataset, base model, adapter, tokenizer, template, evaluation report, and runtime image into one reproducible release manifest." },
        ]),
        block("boundary", "Critical boundary", [
          { id: "critical-tuning-boundary", title: "Weights are the wrong control plane for volatile facts and hard permissions", body: "Fine-tuning writes behavioral tendencies into a model or adapter, so update, withdrawal, and causal attribution are heavier than with prompts or retrieval.", boundary: "Do not use fine-tuning in place of a current knowledge source, a business database, an authorization system, or deterministic policy." },
        ]),
      ],
    ),
    section(
      "tuning-curriculum",
      "COURSE MAP",
      "Follow the complete path from customization choice to governed adapter operations",
      "The curriculum keeps data format, optimization method, evaluation, serving, and lifecycle controls in one decision chain.",
      [
        block("cards", "Nine course chapters", [
          { id: "curriculum-customization-ladder", title: "Customization ladder", body: "A prompt changes the current instruction, retrieval supplies external knowledge, tools provide deterministic capabilities, and fine-tuning changes behavioral tendencies in weights. Classify the gap before choosing the intervention.", decision: "Train only for stable, recurring behavior that lighter controls cannot meet.", boundary: "Fine-tuning does not guarantee factual recall and does not replace current data or hard business rules.", sourceIds: ["nist-genai-profile", "lora-2021"] },
          { id: "curriculum-adaptation-methods", title: "Full fine-tuning, LoRA, and QLoRA", body: "Full fine-tuning changes all weights. LoRA stores a low-rank task update. QLoRA reduces training-memory pressure by adapting a quantized frozen base.", decision: "Select the smallest method that meets the capability, data, compute, and deployment boundary.", boundary: "Parameter efficiency does not imply low data requirements or guaranteed quality retention.", sourceIds: ["lora-2021", "qlora-2023"] },
          { id: "curriculum-dataset-chat-template", title: "Dataset and chat template", body: "Identify whether each example is plain text, prompt-completion, conversational, or preference data. Align roles, special tokens, and templates with the target base; preserve provenance, license, deduplication, and an isolated test split.", decision: "Prove the format and learning objective with a small, high-value set before scaling volume.", boundary: "A wrong template changes the effective task; synthetic examples can reproduce the teacher model's errors and style bias.", sourceIds: ["hf-trl-data-formats", "hf-trl-chat-templates", "nist-genai-profile"] },
          { id: "curriculum-training-diagnostics", title: "Training diagnostics", body: "Interpret training and validation loss together with learning rate, gradients, throughput, and task slices to distinguish underfitting, overfitting, data defects, leakage, and numerical instability.", decision: "Change only a small number of controlled variables in each reproducible experiment.", boundary: "Lower loss shows closer fit to the objective, not better production behavior or safety.", sourceIds: ["hf-trl-sft-trainer", "nist-genai-profile"] },
          { id: "curriculum-supervised-fine-tuning", title: "Supervised fine-tuning", body: "SFT learns task steps, format, tone, refusal, and boundary behavior from high-quality demonstrations. It is often the first post-training stage when an acceptable answer can be written directly.", decision: "Use unseen tasks and retained-capability tests to decide whether further training is warranted.", boundary: "Validation loss cannot stand in for business preference, safety, or reasoning stability.", sourceIds: ["instructgpt-2022", "hf-trl-sft-trainer"] },
          { id: "curriculum-preference-verifiable-reward", title: "Preference optimization and verifiable reward", body: "DPO uses chosen and rejected responses to shift relative preference. Reward-based training requires an outcome that can be scored reliably and a grader that resists reward gaming.", decision: "Use preference optimization when good and bad can be compared; consider reward training only when results are genuinely verifiable.", boundary: "A high reward is not proof of real-world correctness, and no reward stage removes the need for held-out human judgment and safety regression.", sourceIds: ["deepseek-r1-2025", "dpo-2023", "hf-trl-dpo-trainer", "nist-genai-profile"] },
          { id: "curriculum-managed-self-hosted", title: "Managed versus self-hosted training", body: "Managed services reduce environment, scheduling, recovery, and serving work but constrain models, methods, regions, and observability. Self-hosting expands control and transfers infrastructure and security responsibilities to the adopter.", decision: "Choose on data boundary, method flexibility, team capability, and continuing operating cost.", boundary: "The ability to submit a job does not establish that the dataset, region, base model, and output ownership meet the requirement.", sourceIds: ["nist-genai-profile", "lora-2021"] },
          { id: "curriculum-evaluation-release", title: "Four-layer evaluation and release", body: "Inspect data coverage and leakage, training stability, target and retained task behavior, then serving latency, throughput, memory, and cost. Compare against the unchanged base and lighter alternatives under the same conditions.", decision: "Release on sliced evidence and business value, never on one average score.", boundary: "A target-task gain can hide catastrophic forgetting or a result too fragile to reproduce.", sourceIds: ["nist-genai-profile", "openai-eval-best-practices"] },
          { id: "curriculum-adapter-operations", title: "Adapter operations", body: "An adapter is compatible with a specific base, tokenizer, chat template, quantization choice, inference runtime, dataset, and evaluation record. Dynamic loading enables version choice; merging creates a new full-weight artifact.", decision: "Put training, evaluation, serving, canary, and rollback metadata in the same release manifest.", boundary: "A base-model or template change invalidates any assumption that the existing adapter remains compatible or safe.", sourceIds: ["lora-2021", "qlora-2023", "hf-trl-peft"] },
        ]),
      ],
    ),
    section(
      "tuning-decisions",
      "PRESALES DECISIONS",
      "Use the problem, signal, and control boundary to select a customization path",
      "These decisions keep method names secondary to the behavior being changed and the evidence needed for release.",
      [
        block("table", "Five recurring decisions", [
          { id: "decision-stable-behavior-problem", title: "Is this truly a stable behavior problem?", cells: ["Prompting and examples are already controlled, yet format, tone, classification, or a narrow task behavior still drifts.", "Measure the prompting and retrieval baseline, then run a small SFT or LoRA experiment using adjudicated demonstrations.", "Do not encode current facts or rapidly changing policy primarily in weights."] },
          { id: "decision-lora-qlora-full", title: "LoRA, QLoRA, or full fine-tuning?", cells: ["Compute, multi-task operation, rollback speed, and the depth of the desired behavioral change differ.", "Use LoRA as the default starting point; consider QLoRA when training memory is constrained; evaluate full fine-tuning only after a parameter-efficient approach fails a clear gate.", "The method name does not predict the result. Target layers, data, sequence length, and evaluation determine quality and resource use."] },
          { id: "decision-data-sufficiency", title: "Is there enough usable customer data?", cells: ["The customer has a small expert-reviewed set or a large uncurated history.", "Build a compact set covering normal, difficult, and refusal cases; expand according to observed error slices.", "There is no universal sample count. Coverage, correctness, and consistency matter more than raw volume."] },
          { id: "decision-post-sft-method", title: "Should SFT be followed by DPO or reward training?", cells: ["The model can perform the task, but relative preference, refusal calibration, or verifiable outcomes remain below the gate.", "Use DPO when reviewers can compare responses; consider reward training only when a reliable, abuse-resistant scorer exists.", "Preference data can amplify annotator bias, and reward functions can be gamed. Retain human calibration."] },
          { id: "decision-managed-or-self-built", title: "Managed fine-tuning or a self-built stack?", cells: ["Data residency, model openness, method support, required runtime control, and team capability constrain the delivery model.", "Prefer managed training for supported standard tasks within the data boundary; self-host when open weights or custom methods and runtime control are essential.", "Supported models, methods, regions, and artifact rights are product facts that must be rechecked at procurement time."] },
        ], { columns: ["Customer signal", "Recommended action", "Boundary"] }),
      ],
    ),
    section(
      "tuning-practice",
      "LEARN, PRACTICE, PROVE",
      "Build a repeatable customization method",
      "Each learning step ends with a checkpoint or review artifact that can be used in a customer design decision.",
      [
        block("cards", "Learning outcomes", [
          { id: "outcome-separate-customization-problems", title: "Separate knowledge, behavior, and new capability", body: "Diagnose whether the problem belongs in retrieval, workflow, model selection, or training." },
          { id: "outcome-compare-adaptation-investment", title: "Compare full, LoRA, and QLoRA investment", body: "Connect parameter scope to compute, quality, deployment, and lifecycle responsibility." },
          { id: "outcome-govern-training-evaluation-data", title: "Govern training and evaluation data", body: "Preserve provenance, format, rights, privacy, coverage, deduplication, and test isolation." },
          { id: "outcome-operate-adapters", title: "Operate an adapter as a release artifact", body: "Bind it to its compatible base and runtime, then release and roll it back under evidence." },
        ]),
        block("steps", "Recommended learning route", [
          { id: "route-prove-fine-tuning", title: "Prove fine-tuning is the right intervention", body: "Use prompting, retrieval, workflow, and model replacement as controlled alternatives.", decision: "Checkpoint: explain why the gap is stable behavior rather than missing current knowledge." },
          { id: "route-select-parameter-scope", title: "Select the parameter-update scope", body: "Compare full fine-tuning, LoRA, and QLoRA across the capability goal, memory, training, and deployment path.", decision: "Checkpoint: choose the lightest sufficient method instead of the most fashionable one." },
          { id: "route-validate-data-template", title: "Validate dataset format and chat template", body: "Fix roles, special tokens, provenance, versions, and separation among training, validation, frozen test, and risk slices.", decision: "Checkpoint: every sample can be inspected, reproduced, and loaded exactly as the target model expects." },
          { id: "route-diagnose-training", title: "Diagnose training with curves and slices", body: "Relate loss, learning rate, throughput, target tasks, retained capabilities, and safety cases.", decision: "Checkpoint: distinguish underfitting, overfitting, data defects, and evaluation leakage." },
          { id: "route-select-feedback-method", title: "Select the feedback method", body: "Use demonstrations, preference pairs, or verifiable outcomes according to what reviewers can reliably provide.", decision: "Checkpoint: do not hide different feedback signals behind one generic 'alignment' label." },
          { id: "route-release-and-rollback", title: "Complete evaluation, release, and rollback", body: "Compare the base and lighter alternatives, test service performance, bind artifacts, and define canary and rollback.", decision: "Checkpoint: lower training loss is never the only release criterion." },
        ]),
        block("cards", "Practice labs", [
          { id: "lab-customization-route", title: "Decide whether a requirement should be fine-tuned", subtitle: "Product facts, brand voice, and fixed JSON are mixed in one request", body: "Separate knowledge, style, and structure; design retrieval, prompt/schema, and fine-tuning baselines; define success and maintenance cost for each.", decision: "Deliverable: a customization decision tree and experiment plan.", boundary: "Acceptance: each problem has an independently testable route; training is not the default for all three.", sourceIds: ["nist-genai-profile", "openai-structured-outputs", "lora-2021"] },
          { id: "lab-lora-release-gate", title: "Design a LoRA release gate", subtitle: "Offline quality improved, but production readiness is unknown", body: "Create unseen and high-risk slices; compare quality, refusal, latency, and memory; version the adapter, base, and inference configuration with rollback.", decision: "Deliverable: an evaluation report and deployment manifest.", boundary: "Acceptance: gains are stable on representative slices and remain reproducible after deployment.", sourceIds: ["lora-2021", "qlora-2023", "nist-genai-profile"] },
          { id: "lab-conversation-data-audit", title: "Audit a conversational SFT dataset", subtitle: "Historical support conversations have inconsistent roles, templates, and answer quality", body: "Normalize roles and templates; inspect duplicates, leakage, sensitive data, refusal cases, rights, and provenance; create isolated evaluation splits.", decision: "Deliverable: a data card, cleaning report, and loadable sample set.", boundary: "Acceptance: no frozen test item enters training, and important boundaries include positive and negative examples.", sourceIds: ["hf-trl-data-formats", "hf-trl-chat-templates", "nist-genai-profile"] },
          { id: "lab-loss-business-mismatch", title: "Diagnose a convincing but ineffective training curve", subtitle: "Training and validation loss fall while business reviewers see no material gain", body: "Inspect template memorization, duplicates, and leakage; compare the base by task and risk slice; change one data or optimization hypothesis and rerun.", decision: "Deliverable: a diagnostic record and a falsifiable next experiment.", boundary: "Acceptance: the evidence explains whether to continue, repair the data, change the metric, or stop.", sourceIds: ["hf-trl-sft-trainer", "openai-eval-best-practices"] },
        ]),
      ],
    ),
    section(
      "tuning-production",
      "ADAPTER SERVING AND REGRESSION",
      "A training win must survive the exact production combination",
      "Base weights, adapter, tokenizer, chat template, serving runtime, routing, and policy together form the effective model release.",
      [
        block("table", "Adapter deployment choices", [
          { id: "serving-dedicated-endpoint", title: "Dedicated endpoint", cells: ["One tuned model or adapter runs behind its own capacity, identity, scaling, and failure boundary.", "Use for strong isolation, high impact, or stable high load.", "Many low-volume customizations create idle capacity and version-operating cost."], sourceIds: ["lora-2021", "qlora-2023", "vllm-2023", "nist-genai-profile"] },
          { id: "serving-dynamic-adapters", title: "Shared base with dynamic adapters", cells: ["Requests share base weights and select or load an adapter at runtime.", "Use when many compatible customizations have dispersed traffic; test routing, hot loading, batching, caching, and tenant authorization.", "Utilization improves while the blast radius of misrouting, cache leakage, and base failure expands."], sourceIds: ["lora-2021", "qlora-2023", "vllm-2023", "nist-genai-profile"] },
          { id: "serving-merged-adapter", title: "Merged adapter", cells: ["The adapter update is merged into the base weights, creating a new complete model artifact.", "Use for a stable single task or a runtime without dynamic-adapter support; reassess and sign the merged result.", "Fast switching is lost; rollback requires the original base and adapter to remain available."], sourceIds: ["lora-2021", "qlora-2023"] },
          { id: "serving-managed-endpoint", title: "Managed fine-tuned endpoint", cells: ["A cloud service manages supported training artifacts, deployment, scaling, and part of version operation.", "Use for supported standard methods after checking region, base support, data handling, ownership, quotas, and exit.", "Convenience does not establish portability or a right to export the adapter."], sourceIds: ["nist-genai-profile"] },
        ], { columns: ["Runtime mechanism", "Good fit", "Primary risk"] }),
        block("cards", "Why an offline gain disappears in production", [
          { id: "regression-template-mismatch", title: "Template mismatch", body: "Training and serving assemble different roles, system instructions, tokenizers, stop conditions, or structured-output constraints.", decision: "Replay the frozen samples through the exact target endpoint and version the complete request assembly.", boundary: "An adapter hash alone does not make the result reproducible." },
          { id: "regression-narrow-task", title: "Narrow-task regression", body: "A narrow or repetitive dataset improves the target pattern while weakening retained capabilities and refusal boundaries.", decision: "Run target, retained-capability, and safety suites together; adjust data mix, training intensity, or method.", boundary: "A target gain cannot compensate for an unacceptable critical regression." },
          { id: "regression-base-compatibility", title: "Base-model compatibility drift", body: "The adapter was learned against particular base weights and layers; a changed base, tokenizer, or inference operator can invalidate the relationship.", decision: "Bind an immutable base identifier and treat an upgrade as a new candidate requiring retraining or full regression.", boundary: "A shared family name is not a compatibility guarantee." },
          { id: "regression-adapter-routing", title: "Adapter routing leak", body: "A defect in tenant identity, routing, cache keys, or batching applies another customization to the current request.", decision: "Propagate verified tenant identity, record model/adapter/policy versions in traces, and run cross-tenant negative tests.", boundary: "Even without readable customer data in the adapter, incorrect routing is an isolation and authorization incident." },
        ]),
      ],
    ),
    section(
      "tuning-cloud",
      "DELIVERY RESPONSIBILITIES",
      "Map the model change to data, training, artifact, and serving controls",
      "Cloud products provide building blocks; the customer still owns the customization objective, permitted data, release evidence, and operating boundary.",
      [
        block("table", "Four delivery stages", [
          { id: "cloud-data-governance", title: "Data governance", cells: ["Object storage, processing, annotation, deduplication, personal-data controls, and dataset versioning", "Turn historical data into lawful, reproducible training examples.", "Who owns rights, redaction, deletion, sample standards, and test isolation?"] },
          { id: "cloud-training-execution", title: "Training execution", cells: ["Managed fine-tuning APIs, on-demand accelerators, training jobs, checkpoints, and experiment tracking", "Choose operational convenience or deeper control according to the method and data boundary.", "Which base and method are required, and may the data enter a managed service?"] },
          { id: "cloud-adapter-governance", title: "Model and adapter governance", cells: ["Registry, artifact storage, signing, approval, lineage, and key management", "Bind the base, adapter, tokenizer, data, and evaluation so that the release can be audited and reversed.", "Who owns, migrates, and retires each customization, especially when a base is shared?"] },
          { id: "cloud-deployment-feedback", title: "Deployment and iteration", cells: ["Managed endpoints, multi-LoRA runtimes, canary, tracing, online evaluation, and adjudicated-failure intake", "Serve multiple customizations while continuously checking quality, isolation, and safety.", "Who owns traffic isolation, service objectives, rollback, retained-capability tests, and feedback decisions?"] },
        ], { columns: ["Service capabilities", "Value", "Discovery question"] }),
      ],
    ),
  ]),
  qa: Object.freeze([
    question("knowledge-supply-before-tuning", { q: "When should we repair knowledge supply instead of starting fine-tuning?", a: "Repair retrieval and knowledge delivery when the failure is missing, stale, attributable, or permission-sensitive external facts. Consider fine-tuning only after the evidence is correct and the output behavior remains persistently inconsistent.", depth: "Retrieval injects current, removable evidence at run time. Fine-tuning changes default behavior in weights or an adapter, making updates and causal tracing heavier. Diagnose the stage: if the fact was not found, repair retrieval; if correct evidence is present but the model repeatedly violates a stable task contract, test training.", ask: "Is the model missing the information, or failing to act correctly on information it already has? How often does the knowledge change, and must the answer cite evidence?", tag: "Intervention choice", basis: "Parameter-efficient adaptation plus evidence lifecycle", evidence: [{ sourceId: "lora-2021", supports: "Supports changing task behavior through low-rank adapters without updating the full parameter set." }, { sourceId: "nist-genai-profile", supports: "Supports continual risk assessment according to data provenance, context of use, and control effectiveness." }] }),
    question("lora-qlora-full-choice", { q: "How should we choose among LoRA, QLoRA, and full fine-tuning?", a: "For enterprise behavior customization, start with LoRA; evaluate QLoRA when training memory is constrained; consider full fine-tuning only when the parameter-efficient route misses a defined objective and the team can govern the larger regression and operating surface.", depth: "LoRA freezes the base and learns low-rank update matrices. QLoRA additionally uses a quantized frozen base to reduce training-memory demand. Full fine-tuning can change every weight but expands compute, artifact size, forgetting risk, and lifecycle cost. Compare all viable methods on the same base, data, and evaluation set, including task quality, retained capabilities, training resources, serving impact, and rollback.", ask: "Is the goal format, style, a narrow task, or deeper capability transfer? How many task variants must be operated, and which methods does the target runtime support?", tag: "Method selection", basis: "Original LoRA and QLoRA research", evidence: [{ sourceId: "lora-2021", supports: "Introduces low-rank trainable updates against frozen pretrained weights." }, { sourceId: "qlora-2023", supports: "Demonstrates training LoRA adapters against a quantized frozen base to reduce memory requirements." }] }),
    question("training-data-sufficiency", { q: "How much training data is enough, and is more always better?", a: "There is no universal count, and more is not automatically better. First prove a learning signal with a compact, high-quality set spanning normal, difficult, and refusal boundaries; then add data according to the observed error distribution.", depth: "Required volume depends on task complexity, base capability, output space, and error tolerance. Relevance, correctness, coverage, and consistency usually matter more than an unfiltered archive. Historical records can contain duplicates, contradictions, personal data, expired policy, incorrect answers, and test leakage. Define a sample contract, provenance, rights, deduplication, and isolated evaluation before expansion.", ask: "Who can adjudicate the ideal response? Do the examples cover difficult and refusal cases, and how are training and evaluation kept disjoint?", tag: "Data preparation", basis: "Supervised post-training plus data-risk governance", evidence: [{ sourceId: "instructgpt-2022", supports: "Shows that demonstrations and preference data, and therefore their collection and labeling quality, are central inputs to behavioral post-training." }, { sourceId: "nist-genai-profile", supports: "Supports governance of data provenance, privacy, quality, and lifecycle risk." }] }),
    question("prove-tuning-effectiveness", { q: "Training loss is falling. How do we prove the fine-tune is actually useful?", a: "Loss shows closer fit to the training objective. Prove value on frozen unseen tasks across business quality, safety, retained capabilities, and serving cost, then validate the exact target endpoint with shadow or controlled A/B traffic.", depth: "Interpret curves alongside task slices and fair baselines for the unchanged base, prompting, and retrieval. Guard against test leakage, template memorization, cherry-picked runs, judge bias, and proxy metrics. Report the baseline, slices that improved or regressed, uncertainty, and latency and cost impact. If loss improves while the task does not, diagnose the data and metric before adding epochs.", ask: "Which unseen tasks and business thresholds must improve, and which general or safety capabilities are not allowed to regress?", tag: "Acceptance", basis: "Continuous evaluation plus training diagnostics", evidence: [{ sourceId: "nist-genai-profile", supports: "Supports evaluation before and after deployment and risk-based go/no-go controls." }, { sourceId: "openai-eval-best-practices", supports: "Supports task-specific, continuous, and layered evaluation of system changes." }, { sourceId: "hf-trl-sft-trainer", supports: "Documents separate training and evaluation configuration for supervised fine-tuning." }] }),
    question("sft-dpo-reward-sequence", { q: "Must a program use SFT, DPO, and reinforcement-based fine-tuning?", a: "No. Use SFT for behavior that can be demonstrated. Add another stage only when the remaining gap is relative preference or a reliably verifiable outcome.", depth: "If an expert can write the desired answer, begin with SFT. If reviewers can consistently choose the better of two valid responses, DPO may fit. Consider reward-based training only when the result can be scored reliably and the scorer is resistant to gaming. Every additional stage increases data, evaluation, and regression complexity.", ask: "Can the desired behavior be demonstrated directly, only compared pairwise, or verified programmatically?", tag: "Post-training path", basis: "SFT/RLHF and DPO research", evidence: [{ sourceId: "instructgpt-2022", supports: "Separates supervised demonstrations from reinforcement learning based on human feedback." }, { sourceId: "dpo-2023", supports: "Introduces direct optimization from preference pairs." }] }),
    question("chat-template-mismatch", { q: "What happens if the wrong chat template is used during fine-tuning?", a: "The model can learn the wrong role boundaries, special-token semantics, or response start and stop positions, producing plausible offline training curves but materially different online behavior.", depth: "Conversational data must use roles and a template compatible with the target base. Training and serving also need the same tokenizer, stop conditions, and request assembly. Because a template changes the sequence the model actually observes, version it with the adapter and validate the complete serving path.", ask: "Do training and production use exactly the same template, tokenizer, system instruction, and stop conditions?", tag: "Data format", basis: "Conversation representation plus serving parity", evidence: [{ sourceId: "hf-trl-chat-templates", supports: "Documents how roles, chat templates, and special tokens turn conversations into model sequences." }, { sourceId: "hf-trl-data-formats", supports: "Distinguishes text, conversational, prompt-completion, and preference dataset structures." }] }),
    question("synthetic-data-boundary", { q: "Can synthetic data replace expert labeling?", a: "It can expand coverage and provide drafts, but it cannot automatically replace expert adjudication, provenance governance, or an independent evaluation set.", depth: "Synthetic examples can add phrasing variation and low-frequency cases, while also copying the teacher model's factual errors, preferences, and stylistic regularities. Record the generator and prompt, deduplicate, isolate from evaluation, and sample for expert review. Keep synthetic additions only when they improve target slices without degrading retained or safety behavior.", ask: "Which fields can be checked deterministically, which require a domain expert, and how will synthetic provenance and deduplication be tracked?", tag: "Synthetic data", basis: "Coverage expansion plus expert adjudication", evidence: [{ sourceId: "nist-genai-profile", supports: "Supports governance of training-data provenance, quality, bias, privacy, and lifecycle." }, { sourceId: "instructgpt-2022", supports: "Shows the importance of high-quality human demonstrations and preference judgments in shaping behavior." }] }),
    question("managed-self-hosted-training", { q: "How should we choose between managed fine-tuning and self-hosted training?", a: "Prefer a managed service when the supported model, method, region, and data boundary all fit. Evaluate self-hosting when open weights, a specialized training method, or deeper runtime control is essential.", depth: "Managed platforms reduce environment, scheduling, recovery, and serving work but constrain the base model, training method, observable details, and use of the resulting artifact. Self-hosting expands control and adds responsibility for accelerators, images, distributed execution, checkpoints, dependency security, inference compatibility, and long-term operation. Include team cost and exit capability in the comparison.", ask: "May the data enter the managed region? Must the customer export weights or an adapter, and who will operate training and inference?", tag: "Training platform", basis: "Control scope plus continuing operating cost", evidence: [{ sourceId: "nist-genai-profile", supports: "Supports explicit treatment of third-party, data, lifecycle, and organizational responsibilities." }, { sourceId: "lora-2021", supports: "Supports storing a parameter-efficient task update separately from the frozen base." }] }),
    question("dynamic-or-merged-adapter", { q: "Should an adapter be loaded dynamically or merged into the base model?", a: "Dynamic loading usually fits multiple tasks, multiple tenants, and fast rollback. Merging may fit a stable single task or a runtime that cannot select adapters safely.", depth: "Dynamic adapters share base weights and simplify version switching, but require validated routing, caching, batching, and tenant isolation. Merging simplifies the online path while creating a new full-weight artifact; provenance and rollback still depend on preserving the original base and adapter. Re-evaluate quality, memory, latency, and concurrency for either deployment form.", ask: "How many tuned variants must run concurrently, can the runtime route and hot-load them safely, and what rollback time is required?", tag: "Adapter deployment", basis: "Multi-version serving plus reversible artifacts", evidence: [{ sourceId: "hf-trl-peft", supports: "Documents integration of LoRA and related PEFT adapters into training workflows." }, { sourceId: "lora-2021", supports: "Supports preserving task updates separately from frozen base weights." }] }),
    question("adapter-after-base-upgrade", { q: "Can an existing adapter be reused unchanged after the base model is upgraded?", a: "Do not assume so. Changes in layer structure, tokenizer, template, or behavior can break compatibility and invalidate the previous evaluation.", depth: "An adapter is learned against specific base weights and target layers. Even within one model family, a new release can alter parameters, vocabulary, default template, or safety behavior. Bind every adapter to an immutable base identifier; for an upgrade, retrain or at minimum rerun target, retained-capability, safety, and serving-performance evaluation as a new candidate.", ask: "Which exact base and template is the adapter bound to, and can the team roll back base, adapter, and runtime configuration together?", tag: "Version compatibility", basis: "Artifact binding plus full regression", evidence: [{ sourceId: "lora-2021", supports: "LoRA updates target specific layers in a frozen base model." }, { sourceId: "nist-genai-profile", supports: "Supports renewed measurement of performance and risk after model or system changes." }] }),
    question("detect-catastrophic-forgetting", { q: "How do we detect catastrophic forgetting caused by fine-tuning?", a: "Compare against the base not only on the target task but also on unseen retained capabilities, safety behavior, and critical historical tasks that were not part of training.", depth: "Narrow data, excessive training, or unsuitable learning rates can raise the target score while weakening existing capability and refusal boundaries. Evaluate target, retention, high-risk, and service-performance suites and report gains and regressions by slice. If a critical capability falls, change the data mix or training intensity, or return to a lighter method.", ask: "Which original capabilities and safety behaviors are non-negotiable, what change is acceptable, and who approves it?", tag: "Capability retention", basis: "Target gain plus retained-capability regression", evidence: [{ sourceId: "nist-genai-profile", supports: "Supports measuring capability, safety, and use risk when models change." }, { sourceId: "openai-eval-best-practices", supports: "Supports continuing, task-sliced comparison of a candidate against the released system." }] }),
  ]),
  evidenceCards: Object.freeze([
    Object.freeze({ id: "lora-low-rank-update", metric: "Low-rank update", title: "LoRA trains the task-specific increment", finding: "LoRA freezes pretrained weights and introduces trainable low-rank update matrices in selected layers.", boundary: "Fewer trainable parameters do not guarantee equivalence to full fine-tuning; results depend on the task, data, and target modules.", sourceId: "lora-2021", accent: true }),
    Object.freeze({ id: "qlora-quantized-base", metric: "Quantized base + adapter", title: "QLoRA reduces the training-memory barrier", finding: "QLoRA trains LoRA adapters against a quantized frozen base, allowing large-model adaptation under lower memory budgets than conventional full-precision training.", boundary: "Resource requirements still depend on model, sequence length, batch, kernels, and implementation; the paper does not justify a universal accelerator count.", sourceId: "qlora-2023" }),
    Object.freeze({ id: "dpo-preference-pairs", metric: "Preference pairs", title: "DPO optimizes relative choice", finding: "DPO learns directly from chosen and rejected responses, fitting cases where reviewers can compare alternatives more reliably than write one canonical answer.", boundary: "Preference coverage and annotator bias still shape the result, and preference optimization does not replace factual or safety evaluation.", sourceId: "dpo-2023" }),
  ]),
  terms: Object.freeze({
    "fine-tuning": Object.freeze({ name: "Fine-tuning", definition: "Continuing training from an existing model to make a defined task, format, tone, or behavior more consistent, with the resulting weights or adapter governed as a release artifact." }),
    lora: Object.freeze({ name: "Low-Rank Adaptation", abbr: "LoRA", definition: "A parameter-efficient method that freezes the base weights and trains low-rank update matrices in selected layers." }),
    qlora: Object.freeze({ name: "Quantized Low-Rank Adaptation", abbr: "QLoRA", definition: "A parameter-efficient method that trains LoRA adapters against a quantized frozen base model to reduce training-memory demand." }),
    dpo: Object.freeze({ name: "Direct Preference Optimization", abbr: "DPO", definition: "A preference-optimization method that directly increases the relative likelihood of chosen responses over rejected responses without training a separate reward model." }),
    evaluation: Object.freeze({ name: "Evaluation", definition: "A controlled comparison using fixed tasks, samples, metrics, failure analysis, and acceptance thresholds to determine whether a model or system is releasable." }),
  }),
  sources: Object.freeze({
    "lora-2021": Object.freeze({ kind: "Peer-reviewed research paper", shortTitle: "LoRA", note: "Introduces low-rank adaptation against frozen pretrained weights. Its reported results are method evidence, not a guarantee for every base model, task, dataset, or serving runtime." }),
    "qlora-2023": Object.freeze({ kind: "Peer-reviewed research paper", shortTitle: "QLoRA", note: "Reports memory-efficient adapter training against quantized frozen models. Actual memory, speed, and quality depend on model size, sequence length, batch, hardware, and implementation." }),
    "vllm-2023": Object.freeze({ kind: "Peer-reviewed systems paper", shortTitle: "vLLM / PagedAttention", note: "Provides systems evidence about memory management and serving throughput. It does not by itself establish the isolation or quality of a particular multi-adapter deployment." }),
    "nist-genai-profile": Object.freeze({ kind: "Official risk-management framework", shortTitle: "NIST AI 600-1", note: "Organizes generative-AI risk management around Govern, Map, Measure, and Manage. It is a voluntary resource, not product certification, a universal compliance checklist, a model ranking, or a performance standard." }),
    "instructgpt-2022": Object.freeze({ kind: "Peer-reviewed research paper", shortTitle: "InstructGPT", note: "Separates supervised demonstrations, preference data, and reinforcement-learning stages in one model family. The study does not establish that every program needs all stages." }),
    "openai-eval-best-practices": Object.freeze({ kind: "Official engineering guidance", shortTitle: "OpenAI Evaluation Best Practices", note: "Recommends task-specific, continuing, and calibrated evaluation. It is provider guidance and must be combined with independent customer business, safety, and operational gates." }),
    "hf-trl-sft-trainer": Object.freeze({ kind: "Official framework documentation", shortTitle: "TRL SFT Trainer", note: "Documents current SFT configuration and training/evaluation workflows in TRL. Framework options can change and do not replace model- and task-specific validation." }),
    "dpo-2023": Object.freeze({ kind: "Peer-reviewed research paper", shortTitle: "DPO", note: "Introduces direct preference optimization from chosen and rejected pairs. Its assumptions and experimental results are not a universal guarantee of alignment or safety." }),
    "hf-trl-chat-templates": Object.freeze({ kind: "Official framework documentation", shortTitle: "TRL Chat Templates", note: "Documents how conversational roles and special tokens are rendered for training. Correctness still depends on the exact target model and production request assembly." }),
    "hf-trl-data-formats": Object.freeze({ kind: "Official framework documentation", shortTitle: "TRL Dataset Formats", note: "Documents supported dataset structures such as text, conversational, prompt-completion, and preference data. Support and defaults are version-sensitive." }),
    "hf-trl-peft": Object.freeze({ kind: "Official framework documentation", shortTitle: "TRL PEFT Integration", note: "Documents PEFT adapter integration in current TRL workflows. It does not guarantee compatibility across base-model, adapter, tokenizer, or runtime versions." }),
    "deepseek-r1-2025": Object.freeze({ kind: "Peer-reviewed journal paper", shortTitle: "DeepSeek-R1", note: "Reports reinforcement-learning and verifiable-reward methods for a particular model family. The results do not establish that reward training improves every open-ended task." }),
    "hf-trl-dpo-trainer": Object.freeze({ kind: "Official framework documentation", shortTitle: "TRL DPO Trainer", note: "Documents current DPO training interfaces and dataset expectations. Tool support is not evidence that the preference data or release result is valid." }),
    "openai-structured-outputs": Object.freeze({ kind: "Official API documentation", shortTitle: "Structured Outputs", note: "Documents provider-specific schema-constrained output behavior. Supported models and restrictions are time-sensitive; schema enforcement is a lighter control to test before weight adaptation." }),
  }),
});
