const freezeItems = (items) => Object.freeze(items.map((item) => Object.freeze(item)));
const block = (type, title, items, extra = {}) => Object.freeze({ type, title, ...extra, items: freezeItems(items) });
const section = (id, eyebrow, title, lead, blocks) => Object.freeze({ id, eyebrow, title, lead, blocks: Object.freeze(blocks) });
const question = (id, copy) => Object.freeze({ ...copy, id, evidence: freezeItems(copy.evidence) });

export const englishModule = Object.freeze({
  slug: "mcp",
  title: "Model Context Protocol",
  subtitle: "Standardize capability exchange while keeping trust and execution in authoritative systems",
  definition: "The Model Context Protocol (MCP) defines a common way for AI applications to discover, read, and invoke externally provided tools, resources, and prompt templates, reducing pairwise integration between clients and capability providers.",
  position: "This module sits in the protocol and interoperability layer. MCP connects hosts or agents to tools and context. It reuses rather than replaces business APIs, identity providers, authorization, gateways, transaction semantics, and security controls.",
  relatedSlugs: Object.freeze(["ai-agent", "a2a", "ai-gateway", "security", "ai-ops"]),
  sections: Object.freeze([
    section("mcp-protocol-model", "PROTOCOL MODEL", "The protocol standardizes interaction; the host still owns trust and execution", "As of July 29, 2026, MCP 2026-07-28 is the current final specification. It replaces the handshake-and-session lifecycle used by 2025-11-25; publication establishes the normative baseline, but each SDK, Client, Server, gateway, and extension still needs compatibility evidence.", [
      block("cards", "Five operating principles", [
        { id: "principle-host-client-server", title: "Host, Client, and Server", body: "The Host owns experience, policy, and connection aggregation. Under the current 2026-07-28 specification, a Client exchanges self-contained requests with a Server; protocol sessions apply only when supporting legacy revisions such as 2025-11-25.", decision: "Assign identity, consent, policy, execution, and audit to explicit components rather than the protocol name." },
        { id: "principle-tools-resources-prompts", title: "Tools, Resources, and Prompts", body: "Tools represent actions, Resources readable context, and Prompts reusable interaction templates. Their side effects and controlling actors differ.", decision: "Use Tools for actions, Resources for read-only context, and Prompts for user-selectable templates; authorize each according to its actual risk." },
        { id: "principle-versioned-lifecycle", title: "Versioned lifecycle and capability negotiation", body: "MCP 2026-07-28 uses stateless, self-contained requests carrying version and capability metadata, with server/discover available for up-front discovery. Revisions through 2025-11-25 use initialize/initialized and protocol sessions.", decision: "Pin the production baseline and maintain separate contract suites for modern and legacy protocol eras." },
        { id: "principle-transport-trust-boundary", title: "Transport changes the trust boundary", body: "stdio commonly connects a controlled local child process; Streamable HTTP supports remote services and introduces network, identity, tenant, gateway, and callback risks.", decision: "Repeat threat modeling, authentication, authorization, rate limiting, and audit when moving from local to remote." },
        { id: "principle-mcp-function-calling", title: "MCP complements function calling", body: "Function calling describes how a model proposes a tool and arguments. MCP standardizes how a host discovers and communicates with capability providers.", decision: "Use direct function calling for a few stable tools in one application; add MCP when reuse across clients or providers offsets protocol and governance cost." },
      ]),
      block("boundary", "Critical boundary", [{ id: "critical-mcp-boundary", title: "Interoperability does not create trust", body: "MCP standardizes discovery and invocation. It does not grant authority, establish a supplier's identity, validate business semantics, or make an action safe.", boundary: "Preserve the API gateway, identity, policy, transaction, validation, and audit controls that existed before MCP." }]),
    ]),
    section("mcp-curriculum", "COURSE MAP", "Learn the current contract and its legacy compatibility boundary", "Treat 2026-07-28 as the normative protocol and 2025-11-25 as a legacy migration contract. Every implementation claim must still identify both the protocol revision and the actual product support it describes.", [
      block("cards", "Nine course chapters", [
        { id: "curriculum-protocol-roles", title: "Host, Client, and Server roles", body: "The Host owns experience and security decisions, the Client speaks MCP to a Server, and the Server exposes capabilities. The current revision removes protocol-level sessions; legacy 2025-11-25 connections retain them without changing the three logical responsibilities.", decision: "Assign runtime, upgrade, authentication, and audit ownership to every role and protocol version.", boundary: "Protocol roles are not a deployment topology, and a stateless core does not remove application or business state.", sourceIds: ["mcp-architecture", "mcp-lifecycle-2025-11-25", "mcp-specification-2026-07-28"] },
        { id: "curriculum-server-primitives", title: "Tools, Resources, and Prompts", body: "Tools express callable actions, Resources readable context, and Prompts reusable interaction templates. Classification helps a host present controls but never bypasses downstream authorization.", decision: "Select the primitive according to side effect and user intent, not by wrapping every API as a Tool.", boundary: "A Resource can expose sensitive or malicious content, and a Prompt can still be untrusted.", sourceIds: ["mcp-architecture", "mcp-security"] },
        { id: "curriculum-version-discovery", title: "Versioned lifecycle and capability discovery", body: "The current 2026-07-28 revision declares protocol version, identity, and capabilities on every request and requires server/discover. Legacy revisions through 2025-11-25 negotiate through initialize/initialized and a session.", decision: "Manage protocol version separately from business-capability and Tool-schema versions; build independent contract suites.", boundary: "A published specification does not prove implementation support, and successful discovery does not prove business semantics or authorization.", sourceIds: ["mcp-lifecycle-2025-11-25", "mcp-specification-2026-07-28"] },
        { id: "curriculum-transport-deployment", title: "stdio and Streamable HTTP", body: "stdio usually binds a local child process to the operating-system user, while Streamable HTTP supports remote shared services. The current revision uses stateless requests; a legacy 2025-11-25 remote implementation may rely on a protocol session.", decision: "Pin the protocol version, draw the trust boundary, then select transport and state management.", boundary: "No protocol session does not mean no application state, and local-development assumptions cannot be copied into a remote service.", sourceIds: ["mcp-lifecycle-2025-11-25", "mcp-specification-2026-07-28", "mcp-authorization"] },
        { id: "curriculum-identity-authorization", title: "Identity, authorization, and consent", body: "Client identity, end-user identity, Server identity, resource audience, tenant, and scope can all differ. The 2026-07-28 specification adds issuer validation, client-type, and credential-binding requirements.", decision: "Make every high-impact call traceable to a subject, authorization basis, resource, parameters, and necessary confirmation.", boundary: "Normative requirements do not prove that every implementation supports them, and OAuth success does not establish business authorization inside a Tool.", sourceIds: ["mcp-authorization", "mcp-specification-2026-07-28", "nist-zero-trust"] },
        { id: "curriculum-elicitation", title: "Elicitation and sensitive interaction", body: "Legacy 2025-11-25 lets a Server initiate Form or URL Elicitation directly. The current revision carries required input in an input_required result and receives responses when the Client retries the original request under the Multi Round-Trip Requests pattern.", decision: "Select the flow by protocol version and sensitivity, and test rejection, cancellation, retry, and resumption.", boundary: "No elicitation flow replaces MCP authorization, third-party authorization, or business postconditions.", sourceIds: ["mcp-elicitation-2025-11-25", "mcp-specification-2026-07-28", "mcp-authorization"] },
        { id: "curriculum-durable-requests", title: "Long calls and Tasks", body: "MCP 2026-07-28 defines Tasks as an opt-in extension using durable handles, tasks/get, tasks/update, and tasks/cancel. The legacy 2025-11-25 contract placed experimental Tasks in the core protocol.", decision: "Use Tasks only after both sides advertise the correct version-specific capability and the business truly requires durable work.", boundary: "Do not mix the current extension with the legacy core experiment, and do not equate an MCP request Task with an A2A inter-agent Task.", sourceIds: ["mcp-tasks-2025-11-25", "mcp-specification-2026-07-28", "a2a-spec-1-0-0"] },
        { id: "curriculum-production-supply-chain", title: "Production engineering and supply chain", body: "Schema versioning, timeout, idempotency, rate limits, sandboxing, logging, revocation, key rotation, and Server provenance determine operability. A public Server is an executable supply-chain component.", decision: "Maintain an approved catalog, ownership, isolation, update, and emergency-disable process.", boundary: "Discovery and a successful call do not prove reversibility, correctness, or supplier trust.", sourceIds: ["mcp-security", "nist-zero-trust"] },
        { id: "curriculum-failure-observability", title: "Failure semantics and observability", body: "A Host must distinguish invalid arguments, denied authorization, temporary failure, timeout, partial result, and unknown business state and correlate the request, Tool, identity, Server version, and downstream operation.", decision: "Validate retry safety and auditability before shared reuse.", boundary: "A protocol error is not the business transaction state, and a timeout does not prove that an action did not occur.", sourceIds: ["mcp-architecture", "opentelemetry-genai-semconv"] },
      ]),
    ]),
    section("mcp-decisions", "PRESALES DECISIONS", "Adopt MCP only where the reuse and governance boundary are explicit", "The protocol should be a thin interoperability layer over authoritative business services, not a parallel source of policy and transaction truth.", [
      block("table", "Six recurring decisions", [
        { id: "decision-need-mcp", title: "Does the system actually need MCP?", cells: ["The same capability serves multiple AI clients or one client integrates many independent providers and repeats discovery and invocation adapters.", "Add a thin MCP adapter over existing APIs, starting with high-value, narrow, well-governed capabilities.", "For one application with a few fixed APIs, direct function calling may remain simpler."] },
        { id: "decision-stdio-http", title: "stdio or Streamable HTTP?", cells: ["The Server is either a controlled local tool or a shared multi-user, multi-host service.", "Prefer stdio for a controlled local process; use HTTP with enterprise identity, gateway, rate limits, and audit for remote sharing.", "stdio is not inherently safe and HTTP does not inherently authenticate; the full deployment boundary determines security."] },
        { id: "decision-evaluate-rc", title: "How should a 2025-11-25 deployment migrate to 2026-07-28?", cells: ["A team wants to switch immediately because the final specification now defines stateless requests, extensions, and authorization changes.", "Use 2026-07-28 as the protocol baseline, but validate each SDK, Client, Server, gateway, and private extension in an isolated compatibility track before rollout.", "Final-spec publication is not ecosystem compatibility; coexistence, canary, and rollback gates still apply."] },
        { id: "decision-primitive-choice", title: "Tool, Resource, or Prompt?", cells: ["The capability may change external state, return read-only context, or provide a reusable user-selectable template.", "Use a Tool for side effects with authorization, a Resource for readable context, and a Prompt for interaction templates.", "Mislabeling a write as a Resource or broad data access as a privileged Tool destroys the intended control boundary."] },
        { id: "decision-wrap-or-rewrite", title: "Wrap the existing API or rewrite the service?", cells: ["The existing API already has stable semantics, authorization, idempotency, and audit, but lacks MCP discovery.", "Add a thin adapter and keep the business API authoritative; refactor only when the underlying contract itself is defective.", "An MCP Server must not duplicate business rules or bypass the original authorization system."] },
        { id: "decision-remote-production", title: "How does a remote Server enter production?", cells: ["Service identity, user authorization, tenant isolation, Tool risk classes, quotas, versions, and audit are defined.", "Use a gateway for authentication, authorization, allowlists, rate limits, version control, logs, and incident isolation.", "Registry presence and successful connection are not enterprise security approval."] },
      ], { columns: ["Customer signal", "Recommended action", "Boundary"] }),
    ]),
    section("mcp-practice", "LEARN, PRACTICE, PROVE", "Build a production method that survives protocol and Tool changes", "Learning treats the 2026-07-28 final contract, legacy compatibility, trust, failure, and Server lifecycle as separate concerns.", [
      block("cards", "Learning outcomes", [
        { id: "outcome-mcp-roles-primitives", title: "Explain roles and primitives", body: "Separate Host, Client, and Server responsibilities and select among Tools, Resources, and Prompts." },
        { id: "outcome-current-versus-rc", title: "Separate the current revision from legacy behavior", body: "Describe 2026-07-28 as the normative protocol while naming any 2025-11-25 session or Tasks behavior retained for compatibility." },
        { id: "outcome-mcp-trust-boundary", title: "Select transport and trust boundary", body: "Distinguish local process risk from remote service identity, network, and tenant controls." },
        { id: "outcome-discovery-authorization", title: "Separate discovery from authorization", body: "Treat Server metadata as a candidate and authorize each resource and action independently." },
        { id: "outcome-mcp-release-gate", title: "Define a remote MCP release gate", body: "Prove identity, contract stability, failure semantics, observability, supply-chain ownership, and recovery." },
      ]),
      block("steps", "Recommended learning route", [
        { id: "route-protocol-objects-versions", title: "Understand protocol objects and versions", body: "Learn Tools, Resources, and Prompts and distinguish the current 2026-07-28 lifecycle from legacy 2025-11-25 behavior.", decision: "Checkpoint: every claim names the protocol version it describes." },
        { id: "route-map-trust-chain", title: "Map the invocation and trust chain", body: "Trace user, Host, Client, Server, authorization service, and downstream system identities and data.", decision: "Checkpoint: identify who authenticates, authorizes, validates, and audits each step." },
        { id: "route-production-controls", title: "Complete production controls", body: "Add schema versioning, timeout, idempotency, rate limits, revocation, isolation, and supply-chain governance.", decision: "Checkpoint: treat a remote Server as a privileged integration, not a harmless plugin." },
        { id: "route-failure-recovery", title: "Validate failure and recovery", body: "Define errors, timeouts, retries, cancellation, and business-state queries for read, write, and long-running Tools.", decision: "Checkpoint: the Host distinguishes retryable failure from unknown business outcome." },
        { id: "route-catalog-retirement", title: "Establish catalog and retirement ownership", body: "Register owner, version, provenance, compatibility, approval, update, vulnerability, and disable process.", decision: "Checkpoint: no Server becomes an ownerless executable dependency." },
      ]),
      block("cards", "Practice labs", [
        { id: "lab-wrap-order-api", title: "Wrap an existing read-only API", subtitle: "Multiple agent clients need one order-query capability", body: "Define Tool schema and errors, propagate caller identity and least privilege, and add timeout, audit, and sensitive-field filtering.", decision: "Deliverable: protocol contract, invocation sequence, and security checklist.", boundary: "Acceptance: discovery cannot bypass original API permissions, and failure and revocation paths are testable.", sourceIds: ["mcp-architecture", "mcp-authorization", "mcp-security"] },
        { id: "lab-local-remote-deployment", title: "Compare local and remote deployment", subtitle: "The same Server can run through stdio or Streamable HTTP", body: "Draw process, network, and credential boundaries; compare update, isolation, observability, and blast radius; choose for development, controlled desktop, and shared service.", decision: "Deliverable: deployment decision record and migration triggers.", boundary: "Acceptance: local assumptions are not copied into the remote service.", sourceIds: ["mcp-architecture", "mcp-security", "nist-zero-trust"] },
        { id: "lab-mcp-version-migration", title: "Review an MCP version migration", subtitle: "A 2025-11-25 implementation is moving to the current 2026-07-28 revision", body: "Freeze Client, Server, SDK, gateway, and extension inventory; compare initialize, sessions, Tasks, server/discover, and authorization; define isolated validation, ecosystem-support checks, coexistence, and rollback.", decision: "Deliverable: a version-separated impact matrix and validation plan.", boundary: "Acceptance: normative status and product compatibility are recorded separately, and every breaking change has an owner and gate.", sourceIds: ["mcp-lifecycle-2025-11-25", "mcp-tasks-2025-11-25", "mcp-specification-2026-07-28"] },
        { id: "lab-enterprise-server-review", title: "Review an enterprise MCP Server", subtitle: "A ticketing capability will be shared by multiple agent clients", body: "Review primitive boundaries, schema, read/write separation, identity chain, timeout, duplicate submission, incompatibility, and retirement.", decision: "Deliverable: an MCP Server release review package.", boundary: "Acceptance: the package proves who may invoke what, how failures recover, and who owns long-term maintenance.", sourceIds: ["mcp-architecture", "mcp-authorization", "mcp-security"] },
      ]),
    ]),
    section("mcp-trust-chain", "REMOTE MCP TRUST CHAIN", "Turn capability invocation into a verifiable authorization and execution chain", "The model may propose intent and arguments. Deterministic systems must still verify Server, version, caller, resource, action, and business outcome.", [
      block("steps", "Five trust boundaries in a remote Tool call", [
        { id: "trust-discover-verify-server", title: "Discover and verify the Server", body: "The Host obtains an endpoint and metadata and verifies publisher, domain, version, transport, artifact, and approved environment.", decision: "Use a managed private catalog, DNS, certificates, signed software, and admission workflow; treat third-party catalogs as leads.", boundary: "Resolving an endpoint or reading a Tool description does not make the service trusted.", sourceIds: ["mcp-architecture", "mcp-security"] },
        { id: "trust-pin-version-capability", title: "Pin version before capability", body: "The current revision declares version and capabilities on each self-contained request and supports server/discover; legacy revisions negotiate through initialize/initialized and a protocol session.", decision: "Maintain separate contract suites and log the exact protocol, Server, extension, and Tool-schema versions.", boundary: "A final specification is not proof of product support, and one earlier request cannot establish permanent capability.", sourceIds: ["mcp-lifecycle-2025-11-25", "mcp-specification-2026-07-28"] },
        { id: "trust-authorization-context", title: "Establish user or workload authorization", body: "Bind caller, resource audience, scope, tenant, and lifetime to the protected resource.", decision: "Use enterprise OAuth/OIDC or workload identity and short-lived credentials; the resource service validates access.", boundary: "The model's claim to represent a user and the Host's ability to connect are not authorization.", sourceIds: ["mcp-authorization", "nist-zero-trust"] },
        { id: "trust-policy-execution", title: "Apply policy before execution", body: "The model proposes Tool and arguments; the application enforces allowlist, schema, policy, confirmation, rate limit, and business validation.", decision: "Use gateway, policy engine, WAF, and authoritative API; preview high-impact changes before confirmation.", boundary: "A valid Tool schema proves shape, not authority or semantic correctness.", sourceIds: ["mcp-security", "nist-zero-trust"] },
        { id: "trust-result-audit", title: "Validate result and correlate audit", body: "A Tool result can contain errors, sensitive data, or prompt injection. Record execution outcome and filter before returning content to the model.", decision: "Correlate trace, Tool version, caller, policy decision, downstream state, and security events.", boundary: "HTTP success and valid JSON do not establish business success or trustworthy content.", sourceIds: ["mcp-security", "opentelemetry-genai-semconv"] },
      ]),
      block("table", "The same Server has different deployment risk", [
        { id: "deployment-local-tool", title: "Local developer tool", cells: ["A Host launches a controlled process over stdio; risks include files, command execution, and dependencies.", "Use sandboxing, directory allowlists, process isolation, minimal file rights, and pinned dependencies.", "Local execution does not automatically restrict what the process can read or execute."] },
        { id: "deployment-internal-service", title: "Internal shared service", cells: ["Multiple users and applications share identity, tenant, quota, and version control planes.", "Use private networking, gateway, enterprise identity, narrow scopes, rate limits, and centralized audit.", "Network location cannot replace per-request authorization."] },
        { id: "deployment-external-saas", title: "External SaaS Server", cells: ["An external provider controls descriptions, data handling, updates, and availability.", "Complete supplier review, data boundary, version pinning, egress control, and a minimum Tool allowlist.", "Protocol compatibility does not satisfy region, data, or incident requirements."] },
        { id: "deployment-high-impact-tool", title: "High-impact business Tool", cells: ["The Tool can pay, delete, publish, modify production, or access regulated data.", "Use strong identity, short-lived authorization, parameter constraints, approval, idempotency, compensation, and immutable audit.", "MCP must not lower the authorization standard of the underlying business system."] },
      ], { columns: ["Primary trust boundary", "Required controls", "Boundary"] }),
    ]),
    section("mcp-cloud", "DELIVERY RESPONSIBILITIES", "Map runtime, identity, adapters, and operations to explicit owners", "Managed services can host and govern the transport; business services remain the source of truth for permissions and outcomes.", [
      block("table", "Four delivery stages", [
        { id: "cloud-server-runtime", title: "Server runtime", cells: ["Serverless, containers, managed MCP runtimes, and service mesh", "Run Servers with isolation, scaling, version release, and health controls.", "Is the Server local, single-tenant, or remotely shared, and which protocol version and state assumptions apply?"] },
        { id: "cloud-identity-gateway", title: "Identity and gateway", cells: ["OAuth/OIDC, IAM, API gateway, WAF, keys, and certificates", "Centralize authentication, narrow authorization, rate limits, version control, network policy, and audit.", "Does execution use end-user or workload identity, and how are scope and tenant propagated?"] },
        { id: "cloud-api-data-adapters", title: "API and data adapters", cells: ["API management, databases, object storage, search, and enterprise SaaS connectors", "Reuse existing business APIs and data control planes instead of copying logic into the Server.", "Which existing interfaces already have stable schema, authorization, idempotency, and audit?"] },
        { id: "cloud-operations-security", title: "Operations and security", cells: ["Tracing, logs, SIEM, policy engine, vulnerability management, and private catalog", "Observe discovery and invocation, govern versions, detect abuse, and remove vulnerable dependencies.", "Who approves listing, update, revocation, vulnerability response, and disputed calls?"] },
      ], { columns: ["Service capabilities", "Value", "Discovery question"] }),
    ]),
  ]),
  qa: Object.freeze([
    question("mcp-versus-function-calling", { q: "If function calling already exists, why use MCP?", a: "Function calling defines how a model proposes a Tool and arguments. MCP defines how different hosts discover, describe, and invoke capabilities exposed by different Servers.", depth: "Direct function calling is sufficient for one application with a few fixed Tools. As clients, providers, and teams increase, MCP can reuse protocol adapters while underlying APIs, identity, and business policy remain. Adopt it according to duplicated integration cost, not market attention.", ask: "How many AI clients, Tool providers, and duplicate adapters exist, and must the capabilities be reused across teams?", tag: "Protocol boundary", basis: "MCP architecture plus function-calling mechanism", evidence: [{ sourceId: "mcp-architecture", supports: "Defines Host, Client, and Server roles and standardized capability discovery and context exchange." }, { sourceId: "openai-function-calling", supports: "Documents provider-specific function calling through Tool schemas and model-selected arguments." }] }),
    question("existing-user-permissions", { q: "Can an MCP Server directly reuse an existing user's permissions?", a: "Only through an explicit authorization chain. The Server must know the subject, resource audience, scope, tenant, and lifetime; a model's assertion that it represents a user is insufficient.", depth: "A remote MCP deployment should obtain short-lived, resource-bound credentials through mechanisms such as OAuth/OIDC and the protected resource should validate them again. The Host presents consent and high-impact confirmation; the Server enforces resource authorization. Long-lived credentials should not be exposed to the model.", ask: "How is user identity propagated to the Server, and how does the protected resource validate scope and tenant?", tag: "Identity and authorization", basis: "MCP authorization plus zero trust", evidence: [{ sourceId: "mcp-authorization", supports: "Defines authorization roles, protected-resource metadata, and OAuth-related flows for remote MCP." }, { sourceId: "nist-zero-trust", supports: "Supports subject- and resource-focused authorization without implicit trust." }] }),
    question("public-server-versus-saas", { q: "Is connecting to a public MCP Server equivalent to integrating an ordinary SaaS API?", a: "No. In addition to API risks, Tool descriptions can influence model selection, capabilities can change, returned content can inject instructions, and automation can expand side effects.", depth: "Verify publisher, source artifact, and deployment, pin versions and allowed Tools, monitor description changes, and constrain outputs before they enter privileged context. Preview or confirm high-impact actions. A public catalog is a discovery source, not approval.", ask: "Who approves external Servers, how are versions pinned, and how are Tool-description changes reviewed?", tag: "Supply-chain security", basis: "MCP threat model", evidence: [{ sourceId: "mcp-security", supports: "Documents Tool-description poisoning, confused-deputy, token, and related MCP security risks." }, { sourceId: "owasp-prompt-injection", supports: "Supports treating external Tool results as a possible indirect prompt-injection source." }] }),
    question("mcp-platform-lock-in", { q: "Can MCP create a new form of platform lock-in?", a: "It can reduce interface-layer lock-in while runtime, identity, gateway, extensions, and business data models remain platform-specific.", depth: "Separate the authoritative business API from the MCP adapter, prefer standard primitives and transports, limit unvalidated private extensions, and test a Server across more than one compatible client. Portability must include identity, operations, data, and exit—not only protocol messages.", ask: "Which capabilities are standard MCP and which depend on a particular managed platform or extension?", tag: "Portability", basis: "Interoperability boundary", evidence: [{ sourceId: "mcp-architecture", supports: "Defines interoperable Host, Client, Server, and message responsibilities." }] }),
    question("mcp-rc-production-switch", { q: "MCP 2026-07-28 is now final. Should production switch immediately?", a: "Not solely because the specification is final. The revision is now the normative baseline, but deployment depends on whether the chosen SDKs, Clients, Servers, gateways, and extensions pass compatibility testing.", depth: "Exercise the removal of initialize/initialized and protocol sessions, per-request version and capability metadata, server/discover, the Tasks extension, and authorization changes. Confirm every ecosystem component and private extension before setting coexistence, canary, and rollback gates. Protocol status and product compatibility are separate claims.", ask: "Which protocol revision is pinned today, and which SDKs, Servers, gateways, and private extensions are affected by the breaking changes?", tag: "Contract version", basis: "Current final revision plus legacy migration boundary", evidence: [{ sourceId: "mcp-lifecycle-2025-11-25", supports: "Documents the legacy initialization, protocol-version negotiation, and session behavior needed for migration comparison." }, { sourceId: "mcp-specification-2026-07-28", supports: "Establishes 2026-07-28 as the current final specification and defines stateless requests, per-request capabilities, and optional extensions; it does not prove product compatibility." }], addedAt: "2026-07-21" }),
    question("server-not-gateway-iam", { q: "Can an MCP Server replace the API gateway and IAM?", a: "No. MCP standardizes capability exchange. The underlying API still needs identity, authorization, rate limits, network policy, transaction controls, and audit.", depth: "The Host binds a real user or workload identity. The Server exposes the minimum capabilities and authoritative systems revalidate access on each call. Remote MCP also introduces credential delegation and tenant isolation. A uniform Tool schema never converts a model-proposed call into permission to execute.", ask: "Whose identity performs the final action, and is permission checked only at connection time or for every resource and operation?", tag: "Security boundary", basis: "MCP architecture plus zero trust", evidence: [{ sourceId: "mcp-architecture", supports: "Defines separation among MCP Host, Client, and Server responsibilities." }, { sourceId: "nist-zero-trust", supports: "Rejects implicit trust from network location or an existing connection and requires resource-focused decisions." }] }),
    question("enterprise-server-reuse", { q: "How do we determine whether an MCP Server is worth enterprise reuse?", a: "Evaluate contract stability, security boundary, failure semantics, observability, and accountable maintenance—not the number of Tools.", depth: "Review whether capabilities are narrow, inputs and outputs are validatable, reads and writes are separated, retries are safe, versions are compatible, and sensitive logs are controlled. Prove cross-client reuse with a few high-value Tools, then establish catalog, owner, approval, update, and retirement.", ask: "Who maintains the Server, and how do clients detect, degrade, and assign responsibility after incompatibility or Tool failure?", tag: "Platform governance", basis: "Protocol contract plus operating ownership", evidence: [{ sourceId: "mcp-architecture", supports: "Supports capability and lifecycle interaction between Host and Server." }, { sourceId: "opentelemetry-genai-semconv", supports: "Provides evolving telemetry semantics for generative-AI and agent operations." }] }),
    question("tool-success-business-failure", { q: "Why can the business action fail after the MCP Tool reports success?", a: "Protocol success proves message exchange, not the authoritative business outcome. A downstream system can deny authorization, reject validation, partially commit, or enter an unknown state after timeout.", depth: "Separate protocol errors from business results and return stable correlation identifiers and actionable error categories. For writes, use idempotency keys, authoritative status queries, and compensation. The Host must not interpret a success string as proof that an order, payment, or resource change completed.", ask: "Which system confirms final completion, and how is an unknown timeout queried, retried, or compensated?", tag: "Failure semantics", basis: "Protocol boundary plus business state", evidence: [{ sourceId: "mcp-architecture", supports: "Defines MCP protocol responsibilities while business semantics remain in the implemented capability." }, { sourceId: "opentelemetry-genai-semconv", supports: "Supports correlating agent, Tool, and model operations for cross-layer diagnosis." }] }),
    question("automatic-server-installation", { q: "Should enterprise clients install any discovered MCP Server automatically?", a: "No. A Server is executable capability and a data ingress/egress path; review provenance, software, permissions, versions, and operating responsibility before approval.", depth: "Use a managed catalog with publisher, artifact provenance, capabilities, required scopes, network egress, sensitive logging, update, and disable metadata. Test high-risk Servers in isolation, approve reads and writes separately, and prevent automatic discovery from bypassing enterprise installation and authorization policy.", ask: "Who approves a Server, how is an update re-reviewed, and how is a malicious or vulnerable version withdrawn?", tag: "Server supply chain", basis: "MCP security plus zero trust", evidence: [{ sourceId: "mcp-security", supports: "Supports assessment of authorization, token, and ecosystem threats in MCP deployments." }, { sourceId: "nist-zero-trust", supports: "Supports continuous validation and least-privilege access for subjects and resources." }] }),
    question("oauth-not-all-tools", { q: "After OAuth login, may an agent invoke every Tool on that Server?", a: "No. Authentication establishes a subject. Every resource, action, tenant, scope, and risk decision still requires authorization.", depth: "Separate user consent, client identity, Server scopes, and business-system permissions. Use narrow, current scopes and action-specific confirmation for high-impact writes. A Server must not turn one broad login into a permanent all-powerful token.", ask: "Who issues identity, and at which layer is resource-level permission checked for every Tool?", tag: "Authorization chain", basis: "Authentication plus resource authorization", evidence: [{ sourceId: "mcp-authorization", supports: "Defines MCP authorization flows and protected-resource boundaries." }, { sourceId: "nist-zero-trust", supports: "Supports evaluating each access by subject, resource, and context." }] }),
    question("tool-schema-update", { q: "Can clients adapt automatically when an MCP Tool schema changes?", a: "Do not assume so. Changes to fields, enums, defaults, constraints, outputs, or error semantics can change business behavior even when the protocol connection still succeeds.", depth: "Give every Tool semantic versions, compatibility ranges, deprecation windows, and contract tests. Before upgrade, replay frozen calls through argument generation, output parsing, and failure handling. Publish a new version in parallel for breaking changes rather than silently replacing the old contract.", ask: "How are consumers notified, and which schema changes must block automatic update?", tag: "Contract version", basis: "Schema compatibility plus release governance", evidence: [{ sourceId: "mcp-architecture", supports: "Supports interaction through explicit capability contracts among Host, Client, and Server." }, { sourceId: "opentelemetry-genai-semconv", supports: "Supports recording Tool and invocation attributes for before/after comparison." }] }),
    question("trust-server-capability-claim", { q: "May a Host trust a Server's capability description directly?", a: "No. Discovery metadata creates a candidate; it is neither a security proof nor business acceptance.", depth: "A managed catalog should verify publisher, software artifact, permissions, network egress, data processing, and downstream systems, then run contract and risk tests on representative Tools. Dynamic discovery is safe only inside an already approved trust domain.", ask: "Who signs and reviews capability metadata, and how does discovery map to the enterprise admission catalog?", tag: "Capability discovery", basis: "Discovery plus trust establishment", evidence: [{ sourceId: "mcp-architecture", supports: "Defines MCP capability discovery and negotiation." }, { sourceId: "mcp-security", supports: "Supports independent security assessment of ecosystem trust and attack surface." }] }),
    question("primitive-permission-separation", { q: "Should MCP Resources, Prompts, and Tools share one permission model?", a: "Not by default. Reading context, selecting a template, and executing an action have different data scopes, owners, and side effects.", depth: "Define Resource visibility, Prompt publication responsibility, and Tool-action permission separately. Read-only content may still contain sensitive data or hostile instructions; writes need stronger current authorization, confirmation, idempotency, and audit. The Host should expose source and risk according to capability type.", ask: "Which capabilities are read-only, which change business state, and who approves each primitive class?", tag: "Capability separation", basis: "Primitive type plus least privilege", evidence: [{ sourceId: "mcp-architecture", supports: "Defines Resources, Prompts, and Tools as distinct capability types." }, { sourceId: "nist-zero-trust", supports: "Supports fine-grained authorization by resource and operation." }] }),
    question("tool-result-untrusted-instruction", { q: "If Tool output comes from an enterprise system, may the model treat it as trusted instruction?", a: "No. It may be authoritative business data and still be untrusted as an instruction to the agent.", depth: "Separate instruction and data channels, mark provenance, validate type and length, and prevent returned text from changing system policy or future Tool authorization. High-impact decisions return to structured fields and the authoritative system.", ask: "Can Tool results contain user-controlled text, and can that text influence the next Tool selection or arguments?", tag: "Result injection", basis: "Data/instruction separation plus output validation", evidence: [{ sourceId: "owasp-prompt-injection", supports: "Supports treating external content as possible indirect prompt injection even when it arrives through a Tool." }, { sourceId: "mcp-security", supports: "Supports threat analysis for MCP Tools and content channels." }] }),
    question("long-running-mcp-call", { q: "Should an MCP call remain connected for minutes or hours?", a: "Usually not. Under MCP 2026-07-28, both parties can opt into the Tasks extension so a Server returns a durable handle and the Client can poll, supply input, and resume after disconnection.", depth: "Declare extension support in per-request capabilities and server/discover, then handle working, input_required, completed, failed, canceled, TTL, tasks/get, tasks/update, tasks/cancel, and recovery. Keep the legacy 2025-11-25 core experiment as a separate compatibility contract. An MCP Task wraps a client/server request; independent agent delegation and artifacts belong to an explicitly mapped A2A Task. The authoritative business system still owns the final outcome.", ask: "Which protocol version is pinned, which Task contract do both parties support, where is state recovered after disconnection, and how are protocol and business IDs mapped?", tag: "Long-running work", basis: "Versioned Tasks capability plus durable business state", evidence: [{ sourceId: "mcp-tasks-2025-11-25", supports: "Documents experimental Task status, polling, result, TTL, and cancellation in the legacy 2025-11-25 specification." }, { sourceId: "mcp-specification-2026-07-28", supports: "Defines Tasks as an optional extension in the current final revision, with durable handles, tasks/get, tasks/update, and tasks/cancel." }, { sourceId: "a2a-spec-1-0-0", supports: "Defines A2A Task semantics for independent agent collaboration, a different protocol boundary." }] }),
  ]),
  evidenceCards: Object.freeze([
    Object.freeze({ id: "mcp-role-separation", metric: "Host–Client–Server", title: "Three roles separate connection responsibility", finding: "MCP assigns experience and policy aggregation to the Host, protocol communication to the Client, and capability exposure to the Server.", boundary: "A product may combine these roles in one process, but their logical responsibilities remain distinct.", sourceId: "mcp-architecture", accent: true }),
    Object.freeze({ id: "mcp-primitive-control", metric: "Tool / Resource / Prompt", title: "Primitives carry different control meanings", finding: "Actions, readable context, and reusable templates use different MCP primitives so a Host can present and govern them differently.", boundary: "A primitive name does not replace business risk classification; every Tool still needs action-specific authorization.", sourceId: "mcp-architecture" }),
    Object.freeze({ id: "mcp-transport-threat-model", metric: "stdio ↔ HTTP", title: "A transport change changes the threat model", finding: "A local process and a remote shared service face different identity, network, tenant, callback, and operating risks.", boundary: "Every transport needs controls matched to the complete deployment boundary.", sourceId: "mcp-authorization" }),
    Object.freeze({ id: "mcp-interoperability-not-trust", metric: "Interoperable ≠ trusted", title: "A successful connection is not safe use", finding: "Tool descriptions, external content, credentials, and automatic execution can still cause poisoning, confused-deputy behavior, and unauthorized side effects.", boundary: "Gateway, identity, allowlist, approval, result validation, and audit remain outside protocol interoperability.", sourceId: "mcp-security" }),
    Object.freeze({ id: "mcp-final-versus-rc", metric: "2025-11-25 → 2026-07-28", title: "The final revision and the legacy compatibility path are different contracts", finding: "As of July 29, 2026, 2026-07-28 is the final specification. The initialize/session lifecycle and core experimental Tasks in 2025-11-25 now describe legacy implementations and migration comparison.", boundary: "Final publication does not establish ecosystem compatibility; validate each SDK, Client, Server, gateway, and private extension.", sourceId: "mcp-specification-2026-07-28" }),
  ]),
  terms: Object.freeze({
    mcp: Object.freeze({ name: "Model Context Protocol", abbr: "MCP", definition: "An open protocol for AI applications to discover and interact with external tools, resources, and prompt templates through a common capability contract." }),
    "tool-discovery": Object.freeze({ name: "Tool Discovery", definition: "Reading a Tool's name, description, arguments, outputs, and capability changes so a Host can decide whether to approve and use it." }),
    "identity-authorization": Object.freeze({ name: "Identity & Authorization", definition: "Verifying the real caller and target and deciding whether a subject may perform a specific action on a protected resource under the current context." }),
    "mcp-protocol-roles": Object.freeze({ name: "MCP Protocol Roles", definition: "The Host, Client, and Server responsibilities for user experience, connection management, capability aggregation, and capability exposure." }),
    "mcp-primitives": Object.freeze({ name: "MCP Server Primitives", definition: "Tools, Resources, and Prompts for expressing actions, readable context, and interaction templates with distinct control boundaries." }),
  }),
  sources: Object.freeze({
    "mcp-architecture": Object.freeze({ kind: "Official technical documentation", shortTitle: "MCP Architecture", note: "Defines MCP Host, Client, and Server responsibilities and server capabilities. It supports the A2A/MCP boundary but does not establish business authorization, agent-to-agent tasks, or Server trust." }),
    "mcp-lifecycle-2025-11-25": Object.freeze({ kind: "Official protocol specification", shortTitle: "MCP 2025-11-25 Lifecycle", note: "Documents the legacy initialization, version and capability negotiation, operation, and shutdown lifecycle. Since 2026-07-28 is now final, use this source only for pinned legacy implementations and migration comparison." }),
    "mcp-2026-07-28-rc": Object.freeze({ kind: "Official release-candidate announcement", shortTitle: "MCP 2026-07-28 RC", note: "Preserves the historical release-candidate announcement and proposed breaking changes. The milestone has been completed by the 2026-07-28 final specification, which is now the normative source." }),
    "mcp-authorization": Object.freeze({ kind: "Official protocol documentation", shortTitle: "MCP Authorization", note: "Defines MCP authorization roles and OAuth-related resource flows for remote Servers. It does not replace Tool-level business authorization or customer identity architecture." }),
    "mcp-security": Object.freeze({ kind: "Official security guidance", shortTitle: "MCP Security Best Practices", note: "Documents MCP-specific risks and mitigations. Guidance reduces risk but cannot prove that a particular Server, client, or deployment is secure." }),
    "nist-zero-trust": Object.freeze({ kind: "Official architecture guidance", shortTitle: "NIST SP 800-207", note: "Defines zero-trust principles for explicit, resource-focused access decisions without implicit trust. It does not provide an MCP/A2A implementation, AI quality evaluation, or business compensation design." }),
    "owasp-prompt-injection": Object.freeze({ kind: "Community security guidance", shortTitle: "OWASP Prompt Injection", note: "Describes direct and indirect prompt-injection threats and layered mitigations. Guidance can reduce risk but cannot prove that a particular deployment prevents every attack." }),
    "openai-function-calling": Object.freeze({ kind: "Official API documentation", shortTitle: "OpenAI Function Calling", note: "Documents provider-specific Tool schemas and model-proposed arguments. Supported interfaces are time-sensitive, and function calling does not itself authorize or execute a business action." }),
    "opentelemetry-genai-semconv": Object.freeze({ kind: "Open observability specification", shortTitle: "OpenTelemetry GenAI Conventions", note: "Defines evolving telemetry conventions for generative-AI clients, retrieval, agents, MCP, and Tool calls. Projects must pin the adopted version and add their own business outcomes, access controls, approvals, evidence coverage, and risk fields." }),
    "mcp-tasks-2025-11-25": Object.freeze({ kind: "Official protocol specification", shortTitle: "MCP 2025-11-25 Tasks", note: "Documents the experimental core Tasks contract in legacy 2025-11-25. The current 2026-07-28 revision uses a distinct opt-in extension, so the two contracts must not be conflated." }),
    "a2a-spec-1-0-0": Object.freeze({ kind: "Official protocol specification", shortTitle: "A2A 1.0.0", note: "Pins the A2A 1.0.0 contract for A2A-Version, AgentInterface, protocol bindings, optional Agent Card signatures, task behavior, authentication, and authorization responsibilities. Compatibility still requires per-binding tests and customer acceptance." }),
    "mcp-elicitation-2025-11-25": Object.freeze({ kind: "Official protocol specification", shortTitle: "MCP 2025-11-25 Elicitation", note: "Defines Form and URL Elicitation in legacy MCP 2025-11-25. The current revision uses the Multi Round-Trip Requests pattern, so implementations must pin the version." }),
    "mcp-specification-2026-07-28": Object.freeze({ kind: "Official protocol specification", shortTitle: "MCP 2026-07-28", note: "Defines the current final revision with stateless, self-contained requests, per-request version and capability metadata, server/discover, and optional extensions including Tasks. It does not prove that any particular SDK, Client, Server, gateway, or product supports the revision." }),
  }),
});
