const freezeItems = (items) => Object.freeze(items.map((item) => Object.freeze(item)));
const block = (type, title, items, extra = {}) => Object.freeze({ type, title, ...extra, items: freezeItems(items) });
const section = (id, eyebrow, title, lead, blocks) => Object.freeze({ id, eyebrow, title, lead, blocks: Object.freeze(blocks) });
const question = (id, copy) => Object.freeze({ ...copy, id, evidence: freezeItems(copy.evidence) });

export const englishModule = Object.freeze({
  slug: "multimodal",
  title: "Multimodal AI",
  subtitle: "Preserve evidence while systems perceive, align, reason, and generate across media",
  definition: "Multimodal AI enables a system to understand or generate images, documents, speech, audio, and video alongside text, combining evidence from multiple modalities for one business task. A production design must preserve how derived representations relate to the original media.",
  position: "This module sits in the application-pattern layer. It owns perception and media generation beyond plain text, supplies retrievable content to RAG, and gives agents perceptual and conversational channels without replacing source governance, authorization, or deterministic business controls.",
  relatedSlugs: Object.freeze(["rag", "ai-agent", "data-engineering", "llm-inference", "evaluation", "security", "ai-ops"]),
  sections: Object.freeze([
    section("multimodal-principles", "PERCEPTION AND GENERATION", "Select the task contract before choosing a native model or specialist pipeline", "Multimodal support is not one capability. Understanding, retrieval, generation, and real-time interaction have different inputs, metrics, failure modes, and release controls.", [
      block("cards", "Six operating principles", [
        { id: "principle-understanding-generation", title: "Separate understanding from generation", body: "Image question answering, document analysis, and speech recognition interpret an input; image, video, and speech synthesis create new media. Their models, metrics, economics, and risks differ.", decision: "Define separate input, output, acceptance, and governance contracts instead of accepting a generic 'multimodal' claim." },
        { id: "principle-visual-tokenization", title: "Visual tokenization has an information budget", body: "Vision Transformers divide an image into patches and encode them as a sequence. Resolution, crop, and patch strategy change visible detail, sequence size, latency, and cost.", decision: "Test small text, charts, dense pages, and local evidence at realistic resolutions and crops." },
        { id: "principle-cross-modal-alignment", title: "Alignment is not factual proof", body: "Contrastive approaches such as CLIP place images and text in a comparable representation space, enabling retrieval and open-vocabulary matching.", decision: "Evaluate retrieval relevance, fine-grained perception, factual reasoning, and generation as separate capabilities." },
        { id: "principle-native-pipeline-complement", title: "Native models and specialist pipelines are complementary", body: "Native multimodal models support open-ended interpretation. OCR, ASR, layout, detection, and structured extraction expose controllable intermediate results.", decision: "Use specialist pipelines for stable, auditable, cost-sensitive tasks and native models for ambiguity, open questions, or governed fallback." },
        { id: "principle-input-provenance", title: "Preserve the input contract and evidence coordinates", body: "Keep the original asset, transformations, encoding, page or region, time interval, speaker, and model output connected through stable identifiers.", decision: "Do not use an unlocatable output as decisive evidence in a high-impact workflow." },
        { id: "principle-realtime-loop", title: "Real-time interaction is a system loop", body: "Voice experience includes endpoint detection, turn taking, interruption, network transport, state synchronization, tool waits, speech synthesis, and failure recovery.", decision: "Evaluate end-to-end response, interruption success, and task completion rather than one model's first-packet speed." },
      ]),
      block("boundary", "Critical boundary", [{ id: "critical-multimodal-boundary", title: "One large model is not the complete media system", body: "Transcription is not understanding, semantic similarity is not factual correctness, and generation is not publication approval.", boundary: "Every high-impact output needs a defined evidence path, failure mode, and model-external authorization boundary." }]),
    ]),
    section("multimodal-curriculum", "COURSE MAP", "Trace information from acquisition through representation, alignment, reasoning, and publication", "The course map separates modality-specific loss from cross-modal inference so that a failure can be repaired at the layer that caused it.", [
      block("cards", "Nine course chapters", [
        { id: "curriculum-modality-contract", title: "Modality and task contract", body: "Images, documents, speech, and video have distinct sampling, resolution, time, speaker, layout, and provenance requirements. Understanding, retrieval, generation, and live conversation need different outputs and acceptance tests.", decision: "Define the media input and business output before selecting a model or pipeline.", boundary: "Accepting a file format does not prove reliable interpretation of every structure and business meaning it contains.", sourceIds: ["nist-genai-profile", "docling-report"] },
        { id: "curriculum-vision-transformer", title: "Vision Transformer and patches", body: "ViT maps image patches into a sequence and uses Transformer layers to combine relationships. Resolution, local detail, and position still determine what is visible and how much sequence budget is consumed.", decision: "Run dedicated resolution and crop tests for small print, dense tables, and local evidence.", boundary: "An encoder benchmark does not directly represent a customer's scans, languages, and layouts.", sourceIds: ["vit-2021", "colpali-2025"] },
        { id: "curriculum-contrastive-alignment", title: "Contrastive image-text alignment", body: "CLIP uses contrastive learning to align image and text representations, supporting open-vocabulary matching and retrieval. The shared space is useful for candidate discovery, not precise OCR or factual verification.", decision: "Use multimodal retrieval to find candidates and specialist parsing or reasoning to verify exact structure.", boundary: "High similarity means closeness in representation space, not that the image satisfies a business condition.", sourceIds: ["clip-2021"] },
        { id: "curriculum-native-vs-pipeline", title: "Native fusion and specialist pipelines", body: "A native model processes modalities in one context for open interpretation. OCR, ASR, layout, detection, and structured pipelines expose intermediate artifacts that can be inspected, replaced, and optimized.", decision: "Choose a hybrid according to traceability, latency, cost, and structural accuracy.", boundary: "No later model can recover pixels, audio, or structure already discarded during acquisition or parsing.", sourceIds: ["docling-report", "pp-ocr-2020", "colpali-2025"] },
        { id: "curriculum-understand-generate", title: "Understanding and generation", body: "Understanding covers recognition, description, question answering, retrieval, and temporal localization. Generation creates images, video, speech, or other media and introduces additional publication, copyright, identity, and content-safety concerns.", decision: "Maintain distinct gates for interpretation accuracy and publication readiness.", boundary: "Visual quality does not establish factual accuracy, rights, brand compliance, or approval to publish.", sourceIds: ["nist-genai-profile", "owasp-prompt-injection"] },
        { id: "curriculum-content-provenance", title: "Labels, watermarks, and content credentials", body: "A visible label informs a person; a watermark or soft binding helps reassociate an asset with metadata; a signed C2PA manifest records verifiable provenance and edit assertions. Publishing and receiving systems need explicit failure handling for each.", decision: "Test disclosure, reassociation, and cryptographic provenance as three different controls.", boundary: "A valid credential proves an assertion and asset binding, not that the content is true, licensed, or compliant; credentials can also be removed.", sourceIds: ["c2pa-2-4", "china-ai-content-labeling"] },
        { id: "curriculum-realtime-loop", title: "Real-time speech and video loop", body: "Capture, endpoint detection, recognition, inference, synthesis, network delivery, and interruption policy jointly determine experience. Average latency hides stalls, overlap, false endpoints, and repair turns.", decision: "Use end-to-end task success and stage-specific tail latency together.", boundary: "Model first-packet speed does not represent playback, network, tool, and interaction-policy delay at the user.", sourceIds: ["opentelemetry-semconv", "opentelemetry-genai-semconv", "nist-genai-profile"] },
        { id: "curriculum-trust-evidence", title: "Security, privacy, and evidence", body: "Images, audio, and documents can contain sensitive data, untrusted instructions, and subtle manipulations. Preserve source, page or region, timestamp, access policy, and original-asset version.", decision: "Treat multimodal material as auditable evidence, not an anonymous context blob.", boundary: "OCR does not make image text trustworthy and never grants permission to invoke a tool.", sourceIds: ["owasp-prompt-injection", "nist-zero-trust"] },
        { id: "curriculum-evidence-coordinates", title: "Evidence coordinates and layered evaluation", body: "Inspect acquisition, parsing, localization, cross-modal interpretation, and the final claim independently. Outputs should retain page, region, interval, or speaker coordinates from the original medium.", decision: "Use difficult modality slices and source replay to determine production readiness.", boundary: "A unified model interface does not restore missing layout, time, identity, or permission information.", sourceIds: ["docling-report", "nist-genai-profile"] },
      ]),
    ]),
    section("multimodal-decisions", "PRESALES DECISIONS", "Decide where multimodal capability changes the business outcome", "Choose the media path only after the missing information, audit requirement, latency, and publication boundary are explicit.", [
      block("table", "Five recurring decisions", [
        { id: "decision-need-multimodal", title: "Does the task truly need multimodal reasoning?", cells: ["Essential evidence exists only in layout, charts, imagery, acoustic features, or video sequence and is lost in plain transcription.", "Identify the exact information gap in the text-only baseline, then introduce the corresponding modality capability.", "An attachment or image upload alone does not justify a native multimodal model; stable OCR may be cheaper and more reliable."] },
        { id: "decision-native-or-parsing", title: "Native model or OCR/ASR pipeline?", cells: ["The task is either fixed extraction with audit requirements or open interpretation across regions and modalities.", "Use specialist parsing for stable extraction and a native model for open interpretation; often keep a pipeline backbone with governed native fallback.", "Being able to read a document does not prove reliable layout analysis, table extraction, or field validation."] },
        { id: "decision-managed-or-self-hosted-vlm", title: "Managed API or self-hosted vision-language model?", cells: ["Data sensitivity, scale, latency, customization, accelerator utilization, and the team's inference capability vary.", "Start validation with a managed API; consider self-hosting after stable load, data boundaries, or customization justify the operating burden.", "Model weights alone do not provide document parsing, elasticity, monitoring, or security controls."] },
        { id: "decision-cascade-or-native-speech", title: "Cascaded or end-to-end speech?", cells: ["The customer values auditability, replaceable stages, and terminology control, or instead prioritizes natural interruption and low conversational latency.", "Use ASR → LLM → TTS for stronger stage control; evaluate end-to-end speech for natural interaction, with structured confirmation before sensitive actions.", "A natural voice is not proof of task success; network, VAD, tools, and handoff all shape the experience."] },
        { id: "decision-video-production", title: "Can video generation replace content production?", cells: ["The customer accepts storyboarding, authorized references, review, editing, disclosure, and publication controls.", "Use generation to accelerate assets inside a generate-review-label-publish supply chain.", "Generated does not mean publishable; identity, likeness, brand, copyright, and synthetic-media obligations require separate review."] },
      ], { columns: ["Customer signal", "Recommended action", "Boundary"] }),
    ]),
    section("multimodal-practice", "LEARN, PRACTICE, PROVE", "Build an evidence-preserving multimodal method", "Practice separates perception quality, cross-modal interpretation, real-time behavior, and business outcome so that one score cannot conceal the failure layer.", [
      block("cards", "Learning outcomes", [
        { id: "outcome-understand-media-encoding", title: "Understand media encoding and alignment", body: "Explain how visual, speech, and text representations are formed and compared without treating them as interchangeable." },
        { id: "outcome-select-native-pipeline", title: "Select native or specialist processing", body: "Choose according to openness of the task, traceability, structure, latency, and cost." },
        { id: "outcome-build-evidence-chain", title: "Build a replayable evidence chain", body: "Return an answer to the source page, region, time interval, speaker, and original asset version." },
        { id: "outcome-layer-failure-metrics", title: "Diagnose failures by layer", body: "Separate acquisition, parsing, localization, alignment, inference, generation, and publication errors." },
      ]),
      block("steps", "Recommended learning route", [
        { id: "route-separate-understand-generate", title: "Separate understanding and generation", body: "Define contracts for recognition, parsing, question answering, synthesis, and live interaction.", decision: "Checkpoint: name the exact modality capability needed rather than saying only 'multimodal'." },
        { id: "route-trace-information-loss", title: "Trace where information is lost", body: "Follow acquisition, encoding, alignment, context assembly, and inference.", decision: "Checkpoint: locate a failure to a layer before changing the model." },
        { id: "route-design-evidence-operations", title: "Design evidence and operations", body: "Retain page, region, timestamp, speaker, transformation, and source version.", decision: "Checkpoint: every review and correction can return to the original evidence." },
        { id: "route-build-difficult-slices", title: "Build modality-specific difficult slices", body: "Separate scans, tables, low-resolution images, accents, noise, long video, and cross-modal reference.", decision: "Checkpoint: explain whether each error originates in acquisition, parsing, alignment, or inference." },
        { id: "route-validate-evidence-replay", title: "Validate source replay", body: "Require outputs to identify a page, region, interval, or speaker and specify human review.", decision: "Checkpoint: a high-impact claim does not rely on the model's self-explanation." },
      ]),
      block("cards", "Practice labs", [
        { id: "lab-native-vs-document-pipeline", title: "Compare a native model with a document pipeline", subtitle: "PDFs include text, tables, scans, and signatures", body: "Stratify by layout, language, and scan quality; compare native visual QA against OCR/layout parsing; retain page, region, and table-cell evidence.", decision: "Deliverable: a quality, cost, and traceability comparison.", boundary: "Acceptance: the hardest document types are included and every answer returns to the original page and region.", sourceIds: ["docling-report", "pp-ocr-2020", "colpali-2025"] },
        { id: "lab-realtime-voice-waterfall", title: "Decompose a real-time voice experience", subtitle: "Average latency looks acceptable while users interrupt and repeat themselves", body: "Measure endpoint detection, recognition, model, tool, synthesis, and network stages; include interruption, noise, accent, silence, and repair turns.", decision: "Deliverable: an end-to-end latency waterfall and failure inventory.", boundary: "Acceptance: ownership distinguishes model, pipeline, network, and interaction-policy failures.", sourceIds: ["nist-genai-profile", "opentelemetry-semconv", "opentelemetry-genai-semconv"] },
        { id: "lab-multimodal-error-report", title: "Create a layered multimodal error report", subtitle: "Contracts contain digital text, scans, tables, and image attachments", body: "Define source coordinates for each input type; label parsing, localization, interpretation, and answer failures; compare a unified model with specialist processing.", decision: "Deliverable: a failure matrix and route recommendation.", boundary: "Acceptance: every conclusion can replay the source evidence and states its non-generalization boundary.", sourceIds: ["docling-report", "pp-ocr-2020", "nist-genai-profile"] },
      ]),
    ]),
    section("multimodal-evidence-pipeline", "EVIDENCE-PRESERVING PIPELINE", "Turn media into business evidence without severing provenance", "Give each original asset a stable identity, select modality-specific processing, and keep every derived representation connected to the source coordinates.", [
      block("steps", "A replayable media pipeline", [
        { id: "pipeline-register-asset", title: "Register the original asset", body: "Record a stable identifier, hash, version, source, access policy, retention, and technical media metadata; every derivative points back to it.", decision: "Use controlled object storage, metadata, encryption keys, and access policy as the source of truth.", boundary: "A filename or public URL is not a durable provenance identifier.", sourceIds: ["docling-report", "nist-genai-profile"] },
        { id: "pipeline-route-modality", title: "Route by information form", body: "Continuous text, scanned text, tables, charts, natural images, speech, and video sequence require different parsing and sampling.", decision: "Combine document intelligence, OCR, ASR, keyframes, and visual models while preserving page, coordinate, time, and version.", boundary: "Flattening every asset to plain text discards layout, visual relationships, and acoustic cues.", sourceIds: ["docling-report", "pp-ocr-2020"] },
        { id: "pipeline-multiple-representations", title: "Create only useful representations", body: "One asset can have structured fields, transcription, image regions, captions, and multimodal embeddings for different query types.", decision: "Measure the incremental retrieval value of each representation before accepting its indexing and synchronization cost.", boundary: "Technical completeness is not a reason to enable every derivative." , sourceIds: ["colpali-2025", "clip-2021"] },
        { id: "pipeline-ground-generate", title: "Ground and generate", body: "Bind the response to a page region, table cell, audio interval, or video segment and preserve the transformation path.", decision: "For high-impact facts, present source media, the parsed representation, and uncertainty together.", boundary: "Whole-page understanding cannot replace field-, number-, or time-level verification.", sourceIds: ["docling-report", "nist-genai-profile"] },
        { id: "pipeline-feedback-reprocess", title: "Replay failures and reprocess selectively", body: "Connect a failure to asset, transformer, region, and model version; rerun only affected derivatives and their regression tests.", decision: "Use versioned pipelines, eventing, indexes, and traces so repair is reproducible.", boundary: "Calling the final model again cannot recover information lost when the source was first parsed.", sourceIds: ["opentelemetry-semconv", "opentelemetry-genai-semconv"] },
      ]),
      block("table", "Failure slices reveal the loss layer", [
        { id: "failure-small-text-tables", title: "Small text and table values are wrong", cells: ["Resolution, crop, OCR, reading order, or structure recovery lost characters or cell relationships.", "Compare the source crop with the parsed result; test specialist parsing, regional enlargement, and page-image retrieval.", "A larger general VLM cannot restore missing pixels or an incorrect table structure."] },
        { id: "failure-related-image-wrong-relation", title: "The image is relevant but the relationship is wrong", cells: ["The shared representation found a similar image without proving count, position, arrows, or causality.", "Separate retrieval relevance from visual fact verification and add count, spatial, chart, and process slices.", "Multimodal similarity is not factual accuracy."] },
        { id: "failure-voice-fast-but-stilted", title: "First response is fast but conversation still stalls", cells: ["Endpoint detection, network jitter, tool wait, speech queue, or failed interruption cancellation dominates experience.", "Trace VAD, ASR, model, tool, TTS, and transport, including cancellation and state continuation after interruption.", "A model first-packet metric does not represent a conversational turn."] },
        { id: "failure-correct-without-source", title: "The answer is correct but has no source", cells: ["A transcript, caption, or summary was detached from page, region, or timestamp.", "Persist source coordinates and original-asset references for every derived unit.", "An untraceable answer remains unsuitable as high-impact evidence."] },
      ], { columns: ["Likely loss layer", "Diagnostic action", "Boundary"] }),
    ]),
    section("multimodal-cloud", "DELIVERY RESPONSIBILITIES", "Map media ingestion, inference, real-time transport, governance, and operations", "Infrastructure can process and serve media, but the solution owner still defines what evidence must survive and what is safe to publish.", [
      block("table", "Five delivery stages", [
        { id: "cloud-media-ingestion", title: "Media ingestion and parsing", cells: ["Object storage, CDN, document AI, OCR, ASR, and transcoding", "Accept large assets reliably while preserving provenance between source and derivatives.", "Which formats, sizes, languages, update rates, and retention policies must be supported?"] },
        { id: "cloud-multimodal-inference", title: "Model understanding and generation", cells: ["Multimodal APIs, image/video generation, accelerators, inference services, and model gateways", "Route among managed and self-hosted models while controlling quota, region, and cost.", "What quality, P95, concurrency, private-network, region, and cost targets apply?"] },
        { id: "cloud-realtime-media", title: "Real-time media", cells: ["WebRTC, SIP, contact center, speech recognition/synthesis, and stream processing", "Support low-latency duplex speech, interruption, telephone networks, and session state.", "Must the service handle interruption, recording, human transfer, and regulatory notice?"] },
        { id: "cloud-content-governance", title: "Content governance", cells: ["Moderation, watermarking and credentials, DLP, encryption, access control, and audit storage", "Control sensitive data, impersonation, rights, injection, and erroneous publication.", "Who may upload and publish, and which content requires review or explicit labeling?"] },
        { id: "cloud-quality-operations", title: "Quality and operations", cells: ["Evaluation, tracing, logs, media-quality monitoring, and cost analysis", "Observe parsing, model, network, and business-task quality separately.", "Can every failure be located to page, region, interval, and exact processing version?"] },
      ], { columns: ["Service capabilities", "Value", "Discovery question"] }),
    ]),
  ]),
  qa: Object.freeze([
    question("native-model-replace-ocr", { q: "Can a multimodal model replace OCR and document parsing directly?", a: "Not universally. Native models fit open questions and complex visual interpretation; fixed extraction, strong audit requirements, and high-volume cost control often still require specialist parsing.", depth: "A reliable design can first recover text, structure, page, and region through parsing, then use a model for semantic interpretation, with a native multimodal route for ambiguous or failed cases. Both paths must return to the original page and region for review.", ask: "Is the task open interpretation or fixed fields? Which errors require human review, and which source coordinates must be retained?", tag: "Architecture choice", basis: "Visual representation plus production auditability", evidence: [{ sourceId: "vit-2021", supports: "Supports the basic mechanism by which image patches become a Transformer input sequence." }, { sourceId: "nist-genai-profile", supports: "Supports provenance, limitation measurement, and risk-proportionate human oversight." }] }),
    question("multimodal-cost-latency", { q: "Why are multimodal inputs often more expensive and slower?", a: "Images, documents, audio, and video require extra decoding, parsing, or large visual and temporal representations; long media also increases storage, network, and preprocessing work.", depth: "Optimize crop, resolution, keyframes, deduplication, caching, and specialist preprocessing before only switching models. Report media processing, inference, network, storage, and review costs separately so one price metric does not hide the pipeline.", ask: "What are the typical page count, image count, audio/video duration, concurrency, and processing deadline?", tag: "Cost and performance", basis: "Visual sequence size plus end-to-end economics", evidence: [{ sourceId: "vit-2021", supports: "Shows that images enter a Transformer through a patch sequence, linking input resolution and sequence scale." }, { sourceId: "opentelemetry-genai-semconv", supports: "Supports telemetry that distinguishes generative-AI operations within an end-to-end trace." }] }),
    question("realtime-voice-end-to-end", { q: "Why is model first-packet speed insufficient for evaluating real-time speech?", a: "User experience depends on endpoint detection, network, the model, tools, synthesis, interruption, playback, and state recovery together.", depth: "Measure from the end of the user's turn to audible response, and test whether interruption stops playback, cancels obsolete work, and preserves the correct context. When tools or transactions are involved, include execution and human handoff in task success.", ask: "Is the channel telephone or an app, and does it require interruption, transfer, recording, tools, and multiple languages?", tag: "Real-time interaction", basis: "End-to-end system evaluation", evidence: [{ sourceId: "opentelemetry-semconv", supports: "Supports distributed traces that correlate general processing stages." }, { sourceId: "opentelemetry-genai-semconv", supports: "Supports specialized attributes for model, agent, and tool operations." }, { sourceId: "nist-genai-profile", supports: "Supports measuring reliability and risk in the actual context of use." }] }),
    question("media-prompt-injection", { q: "Can text inside an image or document attack an agent?", a: "Yes. Indirect prompt injection can be embedded in web pages, documents, image text, email, or tool output.", depth: "Treat media as untrusted data, label its provenance, and separate it from system instructions and authorization. Seeing content must not grant execution rights. High-impact actions require independent policy, schema and parameter validation, current authorization, and confirmation.", ask: "Which external media can the model read, and which tools or data become reachable afterward?", tag: "Multimodal security", basis: "Indirect prompt injection plus least privilege", evidence: [{ sourceId: "owasp-prompt-injection", supports: "Describes indirect prompt injection through untrusted external content and layered mitigations." }, { sourceId: "nist-zero-trust", supports: "Supports explicit authorization before resource access rather than trust based on content origin." }] }),
    question("single-model-is-not-solution", { q: "If images, audio, and video all enter one model, is the multimodal solution complete?", a: "No. Sampling, temporal and layout coordinates, cross-modal alignment, evidence citation, economics, and human review still require system design.", depth: "Video needs synchronized frame, scene, audio, and subtitle handling. Documents need page, region, and reading order. Speech failures must distinguish transcription from semantic errors. A unified interface does not automatically create auditable source coordinates; high-impact results must return to a scene, interval, page, or region.", ask: "Which page, region, moment, or speaker must support the final conclusion, and what information may be lost?", tag: "Evidence chain", basis: "Media representation plus risk governance", evidence: [{ sourceId: "vit-2021", supports: "Supports the patch-to-sequence mechanism for visual input." }, { sourceId: "nist-genai-profile", supports: "Supports recording provenance and limitations and applying risk-proportionate oversight." }] }),
    question("evaluate-multimodal-system", { q: "How should a multimodal system be evaluated?", a: "Evaluate by modality, content difficulty, processing layer, and business consequence. One aggregate accuracy cannot reveal OCR, localization, interpretation, and generation failures.", depth: "Check whether the input was parsed, evidence coordinates are correct, cross-modal relationships were understood, and the final claim is supported. Maintain difficult slices for scans, dense tables, low-resolution images, accents, noise, and long video, together with latency, usage, media-processing cost, and review rate.", ask: "Which input-quality defects occur most often, and which missed or incorrect perception causes the largest business loss?", tag: "Evaluation design", basis: "Layered evaluation plus risk slices", evidence: [{ sourceId: "nist-genai-profile", supports: "Supports measurement in a defined context of use and according to affected parties and risk tolerance." }, { sourceId: "docling-report", supports: "Shows that document understanding requires layout, reading order, and table structure beyond plain-text extraction." }] }),
    question("ocr-accurate-table-wrong", { q: "Why can table question answering fail when OCR character accuracy is high?", a: "Correct characters do not establish correct layout, rows, columns, headers, units, reading order, or cross-page continuation.", depth: "Evaluate recognition, structure recovery, cell relationships, multi-page continuation, evidence coordinates, and any final computation separately. Slice merged cells, skewed scans, footnotes, and multi-level headers. High-impact numbers should be checked against the original region.", ask: "Which table structures are most complex, and what business consequence follows from assigning a value to the wrong row or column?", tag: "Structure recovery", basis: "Document parsing plus layered evaluation", evidence: [{ sourceId: "docling-report", supports: "Supports explicit recovery of document layout, reading order, and table structure." }, { sourceId: "pp-ocr-2020", supports: "Describes OCR as multiple stages such as detection, direction, and recognition, none of which alone establishes table semantics." }] }),
    question("native-or-specialist-pipeline", { q: "When should we use a native multimodal model, and when should we retain a specialist parsing pipeline?", a: "Prefer testing a native model for open interpretation and complex visual relationships; retain specialist or hybrid processing when stable extraction, source coordinates, batch economics, and auditability dominate.", depth: "Compare end-to-end and parsed-input routes on quality, failure localization, latency, cost, version stability, and review. Native processing reduces components but can hide intermediate loss; specialist pipelines expose structure but can discard visual relationships. Production systems often route by document type and failure mode.", ask: "Must every result return to source coordinates, are input types stable, and who repairs parsing failures?", tag: "Hybrid design", basis: "Multimodal representation plus auditability", evidence: [{ sourceId: "colpali-2025", supports: "Supports direct visual-language representations for visually rich document retrieval." }, { sourceId: "docling-report", supports: "Supports explicit recovery of document structure through parsing." }] }),
    question("resolution-frame-budget", { q: "Do higher image resolution and more video frames always improve results?", a: "No. More pixels and frames increase cost and latency and can add redundancy. The requirement is to preserve the evidence that changes the task outcome.", depth: "Design separate sampling for small text, charts, motion, and long video. Compare full input, crops, keyframes, and segments on evidence recall and interpretation. Record missed evidence, redundant sequence budget, first response, and human replay cost.", ask: "Does the task depend on fine text, spatial relationships, or temporal change, and what evidence must be retained at minimum?", tag: "Input budget", basis: "Evidence fidelity plus compute budget", evidence: [{ sourceId: "vit-2021", supports: "Shows that visual input is converted into a sequence whose scale affects computation." }, { sourceId: "nist-genai-profile", supports: "Supports measuring performance and risk under the actual operating conditions." }] }),
    question("long-video-segmentation", { q: "Can a long video be submitted as one input and queried directly?", a: "That can support exploration, but production usually needs scene, interval, audio, and subtitle indexing so that cost, omissions, and evidence localization can be controlled.", depth: "Separate sampling loss, cross-segment relationships, speaker identity, scene text, and inference errors. Build a timeline and evidence coordinates before asking whether the model retains necessary context around key events. High-impact claims should return an interval rather than only a summary.", ask: "Must the answer identify a particular moment or summarize the whole recording, and which brief events cannot be missed?", tag: "Temporal evidence", basis: "Temporal sampling plus replayable evidence", evidence: [{ sourceId: "clip-2021", supports: "Supports image-text alignment but does not establish long-video temporal continuity." }, { sourceId: "nist-genai-profile", supports: "Supports documenting limitations and retaining verification for high-impact outputs." }] }),
    question("accurate-asr-poor-experience", { q: "Why can a real-time voice agent feel poor even when transcription is accurate?", a: "Because experience also depends on endpoint detection, interruption, speaker handling, noise, first response, tool waits, playback, and recovery—not only word error rate.", depth: "Trace capture, end-of-turn detection, recognition, interpretation, tool execution, synthesis, and playback, reporting P50 and P95. Test overlapping speech, user interruption, accents, silence, and network jitter, and verify clarification and human transfer.", ask: "How long may a user wait, and how should the system behave during interruption or multiple speakers?", tag: "Voice interaction", basis: "End-to-end latency plus conversational control", evidence: [{ sourceId: "opentelemetry-semconv", supports: "Supports tracing general media, network, and playback stages." }, { sourceId: "opentelemetry-genai-semconv", supports: "Supports specialized attributes for generative-AI and tool operations." }, { sourceId: "nist-genai-profile", supports: "Supports reliability and human-oversight evaluation in real interaction contexts." }] }),
    question("embedding-does-not-desensitize", { q: "Does converting an image or voice recording into an embedding make it less sensitive?", a: "Do not assume so. Embeddings can retain identity, attributes, and similarity relationships and may inherit the original data's purpose and access restrictions.", depth: "For faces, identity documents, voices, or medical images, define lawful purpose, minimum scope, retention, and deletion propagation before collection. Vector stores require tenant isolation, current authorization, and audit. 'Not directly readable' is not a data classification.", ask: "Do the modalities contain biometric or identity data, who may retrieve them, and which derivatives must be deleted after withdrawal?", tag: "Modality privacy", basis: "Data classification plus derivative governance", evidence: [{ sourceId: "nist-genai-profile", supports: "Supports managing privacy and data-governance risks in multimodal generative-AI systems." }, { sourceId: "nist-zero-trust", supports: "Supports least-privilege decisions by subject and resource." }] }),
    question("unreadable-input-degradation", { q: "When the model cannot read the input reliably, should it guess or degrade automatically?", a: "A high-impact workflow should not guess silently. Detect unreadable, incomplete, low-confidence, or unsupported inputs and route to specialist processing, request a better source, or require human review.", depth: "Define processability gates and failure codes for every modality, separating 'evidence is absent' from 'the model did not find it.' A fallback must preserve source coordinates and authorization rather than widening access or discarding provenance during reprocessing.", ask: "Which input defects must block the workflow, what is the approved fallback order, and what human service level is required?", tag: "Degradation strategy", basis: "Processability detection plus safe failure", evidence: [{ sourceId: "docling-report", supports: "Supports explicit parsing and structure-recovery stages that need their own quality controls." }, { sourceId: "nist-genai-profile", supports: "Supports response, recovery, and human oversight for known system limitations." }] }),
  ]),
  evidenceCards: Object.freeze([
    Object.freeze({ id: "visual-patch-sequence", metric: "Patch → sequence", title: "Visual input consumes a representation budget", finding: "ViT converts image patches into a sequence, making resolution and partitioning relevant to detail, latency, and compute.", boundary: "This is a representation mechanism, not proof that every commercial service uses the same token accounting or pricing.", sourceId: "vit-2021", accent: true }),
    Object.freeze({ id: "clip-image-text-alignment", metric: "Image ↔ text", title: "A shared space enables cross-modal retrieval", finding: "CLIP uses contrastive learning to align image and text representations for retrieval and open-vocabulary transfer.", boundary: "Alignment does not prove correct judgment of facts, counts, spatial relations, or business conditions in an image.", sourceId: "clip-2021" }),
    Object.freeze({ id: "hybrid-multimodal-operations", metric: "Pipeline + native", title: "Hybrid designs often expose a more operable evidence path", finding: "A specialist backbone can preserve structure while a native model handles open interpretation and exceptions.", boundary: "The NIST profile supports risk-based system design, not one mandatory hybrid architecture; the combination must be validated on customer data.", sourceId: "nist-genai-profile" }),
    Object.freeze({ id: "media-indirect-injection", metric: "Media is input", title: "Multimodal content can carry hostile instructions", finding: "Text in web pages, documents, and images can form an indirect prompt-injection path when it is consumed as model context.", boundary: "Input inspection alone is insufficient; authorization and action controls must remain outside the model.", sourceId: "owasp-prompt-injection" }),
  ]),
  terms: Object.freeze({
    multimodal: Object.freeze({ name: "Multimodal AI", definition: "AI that processes or generates more than one modality while preserving the relationships among text, images, documents, audio, or video for a defined task." }),
    "vision-transformer": Object.freeze({ name: "Vision Transformer", abbr: "ViT", definition: "A Transformer-based vision architecture that maps image patches into a sequence representation before combining their relationships." }),
    ocr: Object.freeze({ name: "Optical Character Recognition", abbr: "OCR", definition: "Recovering text and location from images or scans; the output still requires layout, structure, and source-coordinate validation." }),
    asr: Object.freeze({ name: "Automatic Speech Recognition", abbr: "ASR", definition: "Converting speech into time-related text; recognition errors and speaker or timing loss propagate into downstream interpretation." }),
    "document-intelligence": Object.freeze({ name: "Document Intelligence", definition: "Recovering text, layout, tables, reading order, and evidence coordinates from complex documents for retrieval, extraction, and review." }),
  }),
  sources: Object.freeze({
    "docling-report": Object.freeze({ kind: "Primary technical report", shortTitle: "Docling Technical Report", note: "Describes a document-conversion system that recovers layout, reading order, tables, and structured output. System results do not guarantee equal performance on every language, scan, or customer layout." }),
    "pp-ocr-2020": Object.freeze({ kind: "Primary research paper", shortTitle: "PP-OCR", note: "Describes an OCR pipeline with distinct detection, direction, and recognition components. Character recognition alone does not establish document structure or table semantics." }),
    "colpali-2025": Object.freeze({ kind: "Peer-reviewed research paper", shortTitle: "ColPali", note: "Evaluates visual-language representations for document retrieval. Results are retrieval evidence for tested datasets and models, not proof of downstream answer correctness." }),
    "nist-genai-profile": Object.freeze({ kind: "Official risk-management framework", shortTitle: "NIST AI 600-1", note: "Organizes generative-AI risk management around Govern, Map, Measure, and Manage. It is a voluntary resource, not product certification, a universal compliance checklist, a model ranking, or a performance standard." }),
    "vit-2021": Object.freeze({ kind: "Peer-reviewed research paper", shortTitle: "Vision Transformer", note: "Introduces image-patch sequences for Transformer-based image recognition. The study does not define the tokenization or billing behavior of every multimodal product." }),
    "clip-2021": Object.freeze({ kind: "Peer-reviewed research paper", shortTitle: "CLIP", note: "Introduces contrastive image-text representation learning and transfer. Semantic alignment does not by itself establish OCR, spatial reasoning, or factual verification." }),
    "opentelemetry-semconv": Object.freeze({ kind: "Open observability specification", shortTitle: "OpenTelemetry Semantic Conventions", note: "Defines evolving common telemetry semantics and trace context. Adopted versions must be pinned, while business outcomes, media- or agent-specific evidence, and project policy fields remain application responsibilities." }),
    "opentelemetry-genai-semconv": Object.freeze({ kind: "Open observability specification", shortTitle: "OpenTelemetry GenAI Conventions", note: "Defines evolving telemetry conventions for generative-AI clients, retrieval, agents, MCP, and Tool calls. Projects must pin the adopted version and add their own business outcomes, access controls, approvals, evidence coverage, and risk fields." }),
    "owasp-prompt-injection": Object.freeze({ kind: "Community security guidance", shortTitle: "OWASP Prompt Injection", note: "Describes direct and indirect prompt-injection threats and layered mitigations. Guidance can reduce risk but cannot prove that a particular deployment prevents every attack." }),
    "nist-zero-trust": Object.freeze({ kind: "Official architecture guidance", shortTitle: "NIST SP 800-207", note: "Defines zero-trust principles for explicit, resource-focused access decisions without implicit trust. It does not provide an MCP/A2A implementation, AI quality evaluation, or business compensation design." }),
    "c2pa-2-4": Object.freeze({ kind: "Open technical standard", shortTitle: "C2PA 2.4", note: "Defines signed content-provenance manifests and asset binding. A valid manifest verifies recorded assertions and integrity, not truth, ownership, or legal compliance." }),
    "china-ai-content-labeling": Object.freeze({ kind: "Official regulatory instrument", shortTitle: "China AI Content Labeling Measures", note: "Provides jurisdiction-specific requirements for labeling AI-generated or synthetic content. Qualified counsel must determine applicability to a particular actor, channel, and use." }),
  }),
});
