const freeze = Object.freeze;
const items = (values) => freeze(values.map((value) => freeze(value)));

export const englishModule = freeze({
  slug: "security",
  title: "AI Security",
  subtitle: "Keep untrusted content, probabilistic decisions, and autonomous actions within deterministic controls",
  definition: "AI security protects models, data, applications, agents, tools, and the supply chain so that systems retain least privilege, bounded impact, and auditable accountability when they process untrusted input, generate dynamic output, or take action.",
  position: "This discipline spans data ingestion, model calls, tool execution, output delivery, and continuous operations in the engineering-assurance layer. Security controls and evaluation reinforce each other, but a strong evaluation score cannot substitute for authorization, isolation, or incident response.",
  relatedSlugs: freeze(["rag", "ai-agent", "multimodal", "mcp", "a2a", "data-engineering", "ai-gateway", "evaluation", "ai-ops"]),
  sections: items([
    { id: "threat-path", eyebrow: "UNTRUSTED CONTENT TO ACTION", title: "Let the model see content without giving that content authority", lead: "Treat user input, retrieved documents, websites, email, images, and tool results as data from distinct principals. The model may propose an action; deterministic policy decides whether it may run.", blocks: items([
      { type: "steps", title: "Five control points", items: items([
        { id: "security-source-classification", title: "Classify source and trust", body: "Record origin, tenant, version, integrity, sensitivity, and authorization context at ingestion. Apply admission scanning, data classification, and data-loss prevention.", decision: "Authenticated input can still be malicious or copied from an untrusted source." },
        { id: "security-context-isolation", title: "Separate instruction from evidence", body: "Structure system policy, user intent, and external evidence; minimize context and enforce retrieval access controls before content reaches the model.", decision: "Delimiters and injection detectors reduce confusion but cannot guarantee obedience to policy." },
        { id: "security-proposed-action", title: "Keep model output as a proposal", body: "The model emits a tool and arguments but holds no long-lived credential and has no direct path to high-value resources.", decision: "Validate schema, parameter provenance, resource scope, and action risk outside the model." },
        { id: "security-policy-enforcement", title: "Authorize deterministically", body: "Use the real user or workload identity, tenant, resource, action, and current context to allow, require confirmation, or deny.", decision: "A model statement that the user is authorized is not authorization." },
        { id: "security-execute-observe", title: "Execute, verify, and observe", body: "A controlled executor invokes downstream systems, validates the business end state, and records identity, policy, arguments, result, and compensation status.", decision: "A successful tool response is still untrusted input and may not prove the intended outcome." },
      ]) },
      { type: "boundary", title: "Critical boundary", items: items([{ id: "security-deterministic-boundary", title: "Safety-aligned model does not mean secure application", body: "Identity, authorization, credentials, data access, and irreversible actions must be enforced by deterministic controls outside the model.", boundary: "A system prompt is not a security policy, and vectorization is not anonymization." }]) },
    ]) },
    { id: "security-decisions", eyebrow: "PRESALES DECISIONS", title: "Choose controls from the reachable authority and business consequence", lead: "Start with the source an attacker can influence, the sensitive asset or action that source can reach, and the cost of a failed control. The recommendation should narrow authority and preserve recovery rather than promise that one detector removes the risk.", blocks: items([
      { type: "table", title: "Five security decisions that change the architecture", intro: "Use the customer signal to select an enforceable control, then state what that control still cannot prove.", columns: freeze(["Customer signal", "Recommended action", "Boundary"]), items: items([
        { id: "security-decision-injection-path", title: "Which prompt-injection paths does the system face?", cells: freeze([
          "The model reads websites, documents, email, retrieval results, screens, or tool output and may use that content when selecting an action.",
          "Test direct and indirect injection, label and isolate untrusted sources, and independently authorize every sensitive sink with least privilege.",
          "A longer system prompt, keyword filter, or single detection model cannot eliminate prompt injection.",
        ]) },
        { id: "security-decision-rag-or-training", title: "Should sensitive enterprise knowledge use retrieval or training?", cells: freeze([
          "The knowledge changes frequently or requires per-user authorization, citation, correction, revocation, deletion, and audit.",
          "Prefer retrieval for dynamic sensitive knowledge; reserve training for stable behavior or capability changes and apply data governance to both paths.",
          "Retrieval improves revocation and access control options, but the corpus, vector store, caches, and retrieval chain remain security-sensitive.",
        ]) },
        { id: "security-decision-agent-authority", title: "How much authority should an agent receive?", cells: freeze([
          "The action may be read-only, reversible, financial, production-changing, destructive, externally visible, or applied to regulated data.",
          "Tier tools by consequence; use short-lived, resource-scoped credentials bound to the real user or workload, and require preview and approval for high-impact actions.",
          "Giving the model a credential or a shared service account breaks identity, authorization, and audit chains.",
        ]) },
        { id: "security-decision-component-admission", title: "How should an external model or plugin enter production?", cells: freeze([
          "Origin, license, digest, format, dependencies, vulnerabilities, model or data documentation, and affected consumers can be identified and tested in isolation.",
          "Scan, sign, sandbox, and approve the component before it enters a private registry; bind each release to an inventory, evidence package, and rollback version.",
          "Downloadability, successful loading, or popularity in a public catalog is not supply-chain assurance.",
        ]) },
        { id: "security-decision-guardrail-coverage", title: "Is one guardrail service sufficient?", cells: freeze([
          "The exposure includes not only known content categories but also identity, private data, tools, external dependencies, and business side effects.",
          "Layer content controls with IAM, DLP, policy enforcement, sandboxing, audit, human approval, incident response, and recurring red-team tests.",
          "A guardrail can reduce measured risk; it cannot remove model uncertainty or replace conventional security controls.",
        ]) },
      ]) },
    ]) },
    { id: "security-curriculum", eyebrow: "COURSE MAP", title: "Build defense in depth across the complete AI system", lead: "Start with assets and trust boundaries, then trace untrusted sources to high-impact sinks and test the controls that limit blast radius.", blocks: items([
      { type: "cards", items: items([
        { id: "security-chapter-threat-model", title: "Layered threat modeling", body: "Map assets, attackers, trust boundaries, and consequences across data, model, application, agent, identity, tools, output, and external dependencies.", decision: "Use general risk catalogs to prevent omissions, then build system-specific attack paths.", boundary: "A checklist cannot replace the system data-flow and loss analysis.", sourceIds: freeze(["owasp-llm-top-ten", "nist-genai-profile"]) },
        { id: "security-chapter-injection", title: "Direct and indirect prompt injection", body: "Injection can arrive from a user or hide in a webpage, document, email, image, retrieval result, or tool response because the model processes instructions and untrusted data together.", decision: "Control the source-to-sink path and the authority available at every sink.", boundary: "System prompts, retrieval, fine-tuning, and input detection cannot independently eliminate injection.", sourceIds: freeze(["owasp-prompt-injection", "mcp-security"]) },
        { id: "security-chapter-data-vector", title: "Data, vector, and deletion security", body: "Track source documents into chunks, embeddings, indexes, caches, logs, and evaluation assets. Enforce tenant isolation, retrieval-time ACLs, write admission, retention, and deletion propagation.", decision: "Prove revocation and deletion across every read path within a stated time.", boundary: "Embeddings can remain sensitive, and deleting the source does not remove derived copies.", sourceIds: freeze(["owasp-vector-weaknesses", "nist-zero-trust"]) },
        { id: "security-chapter-identity", title: "Identity, authorization, and credentials", body: "Distinguish the initiating user, application, agent, tool, and downstream principal. Use scoped short-lived credentials and resource-side enforcement.", decision: "Grade actions as advice, read, reversible write, or high-impact execution.", boundary: "Authentication does not grant every requested action, and shared service accounts break attribution.", sourceIds: freeze(["nist-zero-trust", "mcp-authorization", "mcp-security"]) },
        { id: "security-chapter-agent", title: "Agentic blast radius", body: "Permissions, action irreversibility, speed, memory, and autonomous loops compound probabilistic errors. Put schema validation, limits, sandboxing, approval, and compensation outside the model.", decision: "Increase autonomy only where measured benefit justifies the additional control surface.", boundary: "Tool-calling capability is not tool authorization.", sourceIds: freeze(["nist-zero-trust", "mcp-security"]) },
        { id: "security-chapter-supply-chain", title: "AI supply chain", body: "Models, datasets, containers, plugins, MCP servers, evaluators, and hosted APIs require provenance, version, license, vulnerability, integrity, isolation, inventory, and replacement paths.", decision: "Manage executable AI components at least as strictly as code dependencies.", boundary: "Open weights are not automatically trustworthy, and managed hosting does not transfer customer-use responsibility.", sourceIds: freeze(["nist-genai-profile", "mcp-security"]) },
        { id: "security-chapter-guardrails", title: "Input, action, output, and monitoring gates", body: "Combine content controls with IAM, policy, DLP, sandboxing, audit, human approval, detection, and response so that one failed control does not expose the full system.", decision: "Test bypasses and residual impact rather than reporting only guardrail hit rates.", boundary: "A guardrail is one control component, not a security architecture.", sourceIds: freeze(["nist-genai-profile", "owasp-llm-top-ten"]) },
        { id: "security-chapter-red-team", title: "Red teaming and control assurance", body: "Test realistic direct, indirect, multimodal, tool, retrieval, and long-conversation attack paths. Record false positives, bypasses, and the effect after a control fails.", decision: "Promote confirmed attacks into regression while continuing adaptive testing.", boundary: "Passing a fixed attack set cannot establish absence of unknown threats.", sourceIds: freeze(["nist-aml-100-2e2025", "nist-genai-profile"]) },
        { id: "security-chapter-regulation", title: "Jurisdiction and use-case applicability", body: "Record user region, industry, use, data, distribution mode, product role, legal owner, verification date, and pending questions for dynamic regulation.", decision: "Separate legal applicability from the technical controls used to implement it.", boundary: "This fieldbook identifies verification needs and cannot provide jurisdiction-specific legal advice.", sourceIds: freeze(["china-ai-content-labeling", "gb-45438-2025", "eu-ai-act"]) },
        { id: "security-chapter-incident", title: "Incident containment and recovery", body: "Stop propagation, revoke credentials, pause queues and high-impact writes, retain evidence, determine affected users and state, compensate, and recover on a known-safe version.", decision: "Exercise containment without assuming the original provider remains available.", boundary: "Restoring an endpoint does not repair business actions already executed.", sourceIds: freeze(["nist-genai-profile", "nist-zero-trust"]) },
        { id: "security-chapter-logging", title: "Privacy-aware security telemetry", body: "Prefer identifiers, versions, usage, policy decisions, tools, and derived signals; capture content only when necessary, lawful, protected, and time-limited.", decision: "Design observability and data minimization together.", boundary: "Complete prompt retention is neither required nor safe by default.", sourceIds: freeze(["opentelemetry-genai-semconv", "nist-genai-profile"]) },
      ]) },
    ]) },
    { id: "security-study-guide", eyebrow: "LEARN, PRACTICE, PROVE", title: "Turn a threat catalog into tested controls and recovery evidence", lead: "The learner should be able to trace a malicious source to a valuable sink, identify the deterministic control, and explain the residual risk.", blocks: items([
      { type: "cards", title: "Learning outcomes", items: items([
        { id: "security-outcome-model", title: "Build a layered threat model", body: "Cover model, application, agent, data, tool, identity, and supply-chain risks." },
        { id: "security-outcome-injection", title: "Explain prompt injection", body: "Distinguish direct and indirect injection and why model-only defenses are insufficient." },
        { id: "security-outcome-autonomy", title: "Bound autonomous action", body: "Use external identity, policy, validation, limits, approvals, and compensation." },
        { id: "security-outcome-operation", title: "Operate security continuously", body: "Connect red teaming, monitoring, incident response, regulation review, and regression." },
      ]) },
      { type: "steps", title: "Recommended route", items: items([
        { id: "security-route-catalog", title: "Use a catalog to find blind spots", body: "Map common risks to actual assets and losses.", decision: "Checkpoint: name the business consequence, not only the vulnerability label." },
        { id: "security-route-boundaries", title: "Trace trust boundaries", body: "Mark untrusted sources, sensitive data, executable tools, derived assets, and external dependencies.", decision: "Checkpoint: show which boundary an attacker crosses and what authority becomes reachable." },
        { id: "security-route-identity", title: "Separate identities and credentials", body: "Trace the user, app, agent, tool, and downstream resource principal.", decision: "Checkpoint: every high-impact action has resource-side authorization." },
        { id: "security-route-controls", title: "Layer controls and red-team them", body: "Combine isolation, validation, approval, sandbox, monitoring, stop controls, and recovery.", decision: "Checkpoint: a second layer limits impact when one guardrail fails." },
        { id: "security-route-regulation", title: "Convert governance into release evidence", body: "Connect jurisdiction and use to inventory, controls, owners, legal review, and freshness.", decision: "Checkpoint: dynamic claims have a responsible reviewer and deadline." },
        { id: "security-route-recovery", title: "Exercise incident recovery", body: "Contain, preserve evidence, revoke, compensate, validate recovery, and add regression cases.", decision: "Checkpoint: prove control effectiveness, not merely product enablement." },
      ]) },
      { type: "cards", title: "Practice labs", items: items([
        { id: "security-lab-rag-agent", title: "Threat-model a tool-using RAG agent", body: "Trace instructions, data, retrieval, and tools; enumerate injection, escalation, and exfiltration; place authorization and human gates at high-impact sinks.", decision: "Deliverable: threat model, control map, and residual-risk register.", boundary: "Acceptance: an untrusted document cannot obtain authority or change business rules through text alone.", sourceIds: freeze(["owasp-prompt-injection", "nist-zero-trust", "mcp-security"]) },
        { id: "security-lab-supply-chain", title: "Run a supply-chain incident", body: "Inventory version, origin, deployment, and consumers; isolate the affected component and activate an approved replacement.", decision: "Deliverable: incident timeline and recovery threshold.", boundary: "Acceptance: impact can be found and contained without relying on the affected vendor.", sourceIds: freeze(["nist-genai-profile", "nist-zero-trust"]) },
        { id: "security-lab-deletion", title: "Verify vector-store revocation and deletion", body: "Trace source, chunks, embeddings, index, cache, logs, and evaluation samples; test search and generation under changed identities.", decision: "Deliverable: derived-data inventory and completion evidence.", boundary: "Acceptance: every read path stops returning the content within the promised interval.", sourceIds: freeze(["owasp-vector-weaknesses", "nist-zero-trust"]) },
        { id: "security-lab-regulation", title: "Assess regional and use-case applicability", body: "Document region, role, users, content, data, distribution, official requirements, technical controls, review owner, and unresolved legal questions.", decision: "Deliverable: applicability worksheet and control mapping.", boundary: "Acceptance: unverified legal conclusions are not presented as facts or a permanent compliant label.", sourceIds: freeze(["china-ai-content-labeling", "gb-45438-2025", "eu-ai-act"]) },
      ]) },
    ]) },
    { id: "security-deep-dive", eyebrow: "INCIDENT DIAGNOSIS", title: "Trace an AI incident from symptom to failed control and recoverable state", lead: "AI incident response needs both conventional security evidence and model-context evidence. Stop further impact first, then reconstruct the source, retrieved content, model and policy versions, represented identity, tool arguments, downstream result, and compensation state.", blocks: items([
      { type: "table", title: "Five incident paths that require different containment", intro: "A visible bad answer may originate in data access, authorization, tool execution, the supply chain, or missing telemetry. Diagnose the failed boundary before changing prompts or thresholds.", columns: freeze(["Likely failure path", "Containment and recovery", "Do not assume"]), items: items([
        { id: "security-incident-unauthorized-knowledge", title: "A user sees knowledge they were not authorized to access", cells: freeze([
          "Retrieval ACLs, tenant mapping, cache keys, log redaction, or deletion propagation allowed sensitive content into context or output.",
          "Disable the affected index and cache paths; reconstruct identity, query filters, source documents, and ACL versions; then run negative tests across tenants and every read path.",
          "Deleting the final response does not prove that chunks, embeddings, caches, logs, or evaluation copies are gone.",
        ]), sourceIds: freeze(["owasp-vector-weaknesses", "nist-zero-trust"]) },
        { id: "security-incident-unexpected-agent-action", title: "An agent executes an unexpected action", cells: freeze([
          "Prompt injection, incorrect tool selection, unvalidated arguments, excessive credentials, or an approval bypass converted a probabilistic error into changed business state.",
          "Pause the high-impact tool, revoke credentials, preserve the model input and policy decision, verify the authoritative business state, and execute compensation where possible.",
          "Changing the prompt cannot repair overbroad permissions or missing authorization at the resource.",
        ]), sourceIds: freeze(["owasp-prompt-injection", "nist-zero-trust", "mcp-security"]) },
        { id: "security-incident-poisoned-knowledge", title: "The knowledge system begins producing the same wrong claim", cells: freeze([
          "A trusted write path was poisoned, a source version was replaced, a malicious document ranked highly, or an embedding or index update changed retrieval behavior.",
          "Freeze writes, isolate the source batch, verify hashes and lineage, rebuild from approved inputs, and rerun historical failures plus poisoning cases.",
          "Vector similarity and reranker scores do not establish source authenticity or factual authority.",
        ]), sourceIds: freeze(["owasp-vector-weaknesses", "nist-genai-profile"]) },
        { id: "security-incident-supplier-change", title: "An external model or tool server changes behavior", cells: freeze([
          "A model version, server capability, dependency, weight file, or supplier policy changed outside the scope of the approved release.",
          "Route to an approved version, verify registry identity, digests, inventory, release records, and supplier notices, then repeat security and task regression.",
          "Continued availability does not mean behavior, data handling, or permissions still match the approved state.",
        ]), sourceIds: freeze(["nist-genai-profile", "mcp-security"]) },
        { id: "security-incident-silent-control-gap", title: "Guardrail metrics look normal while harm still occurs", cells: freeze([
          "The detector covers known content patterns, while the real failure occurs in authorization, tools, encoding, multimodal input, supply-chain behavior, or a human workflow.",
          "Reconstruct the complete source-to-sink path, test input, action, output, and monitoring gates, and add deterministic policy or adaptive red-team coverage at the failed boundary.",
          "No alert does not establish no incident; missing or uncorrelated telemetry is itself a control gap.",
        ]), sourceIds: freeze(["owasp-prompt-injection", "owasp-llm-top-ten", "nist-genai-profile"]) },
      ]) },
    ]) },
    { id: "security-cloud-connections", eyebrow: "CLOUD SERVICE CONNECTIONS", title: "Place cloud controls at identity, execution, data, and response boundaries", lead: "Cloud services can enforce identity, network, data, policy, and evidence controls around an AI workload. They do not decide the acceptable business risk, repair an unsafe authority model, or make a model-generated decision trustworthy by themselves.", blocks: items([
      { type: "cards", title: "Five capability areas for a cloud security design", items: items([
        { id: "security-cloud-identity", title: "Identity and credentials", subtitle: "IAM, OAuth/OIDC, workload identity, KMS, secrets management, and privileged access management", body: "Issue short-lived, resource-scoped, revocable identity to the application or executor so credentials do not enter prompts or model context.", decision: "Discovery question: whose authority does each call represent, and where are tenant, audience, scope, and lifetime enforced?", boundary: "Authentication establishes a principal; it does not authorize every tool, resource, or business action.", sourceIds: freeze(["nist-zero-trust", "mcp-authorization"]) },
        { id: "security-cloud-runtime", title: "Network and runtime isolation", subtitle: "Private networking, WAF, API gateway, container sandbox, virtual desktop, and service mesh", body: "Limit communication and execution paths among models, agents, tools, external content, and high-value systems; isolate code execution and outbound access by task.", decision: "Discovery question: which workload may reach the internet, execute code, or write to production, and can that environment be destroyed after the task?", boundary: "A private network does not make content or a workload trustworthy, and an API gateway does not replace resource-side authorization.", sourceIds: freeze(["nist-zero-trust", "mcp-security"]) },
        { id: "security-cloud-data", title: "Data protection", subtitle: "DLP, classification, encryption, access control, vector databases, and audit storage", body: "Protect prompts, logs, knowledge, embeddings, and outputs through admission rules, tenant isolation, retrieval-time authorization, retention, and deletion propagation.", decision: "Discovery question: which data may enter the model, vector store, cache, or log, and how is revocation proved across every derived copy?", boundary: "Encryption at rest does not establish lawful use, correct retrieval authorization, or deletion completion.", sourceIds: freeze(["owasp-vector-weaknesses", "nist-zero-trust", "nist-genai-profile"]) },
        { id: "security-cloud-guardrails", title: "AI guardrails and action policy", subtitle: "Content safety, prompt protection, policy engines, model filters, and approval workflows", body: "Detect and constrain risky input, proposed actions, and output while deterministic policy decides whether sensitive execution is allowed, confirmed, or denied.", decision: "Discovery question: which content and actions are prohibited, which require confirmation, and who approves policy and exception changes?", boundary: "A guardrail reduces a measured risk; it cannot guarantee prompt-injection resistance or replace identity, authorization, and recovery.", sourceIds: freeze(["owasp-prompt-injection", "nist-genai-profile"]) },
        { id: "security-cloud-secops", title: "Security operations and assurance", subtitle: "SIEM, tracing, threat detection, red-team platforms, vulnerability management, asset inventory, and bills of materials", body: "Correlate source, model, policy, identity, tool, result, supplier version, and incident evidence so teams can detect change, contain impact, and prove recovery.", decision: "Discovery question: who owns each AI asset and alert, and how quickly can the organization find affected consumers, revoke access, and restore a known-safe version?", boundary: "More telemetry does not create assurance unless it is scoped, privacy-aware, retained long enough for the incident, and tied to an accountable response.", sourceIds: freeze(["opentelemetry-genai-semconv", "nist-genai-profile", "mcp-security"]) },
      ]) },
    ]) },
  ]),
  qa: items([
    { id: "aligned-model-application-security", q: "If the model has undergone safety alignment, what security work remains for the application?", a: "Both conventional and AI-specific security remain necessary. Model alignment affects generated behavior; it does not implement identity, authorization, data isolation, tool approval, or incident response.", depth: "The application owns input provenance, knowledge permissions, credentials, tool execution, output handling, and logs. Agents can change external state, so they also require short-lived identity, action tiers, idempotency, approval, and compensation.", ask: "Which data and tools can the model reach, and what real state could the worst error change?", tag: "Shared responsibility", basis: "Generative-AI risk management plus zero trust", evidence: items([{ sourceId: "nist-genai-profile", supports: "Supports identifying, measuring, and managing system-level generative-AI risk throughout the lifecycle." }, { sourceId: "nist-zero-trust", supports: "Requires explicit identity and authorization before resource access rather than implicit trust." }]) },
    { id: "system-prompt-injection-defense", q: "Can a stronger system prompt solve prompt injection?", a: "It cannot guarantee security. Prompts may reduce some failures, but the model can still confuse untrusted content with instructions, so authority and impact must be constrained outside the model.", depth: "Direct injection arrives from the user; indirect injection can hide in websites, email, documents, images, retrieval, or tool results. Separate instruction and data, minimize context, detect suspicious content, and independently authorize and validate sensitive access and actions.", ask: "Which external content can the model read, and what is the highest-impact sink that content can influence?", tag: "Prompt injection", basis: "OWASP threat definition plus external enforcement", evidence: items([{ sourceId: "owasp-prompt-injection", supports: "Documents direct and indirect prompt injection and the limits of model-internal instructions as a sole defense." }]) },
    { id: "embedding-vector-data-risk", q: "Does storing an embedding in a vector database materially remove the data risk?", a: "Do not assume so. Vectorization is not anonymization; embeddings, metadata, source text, and retrieval results may remain sensitive, and deleting the source does not remove derived copies.", depth: "Track chunks, embeddings, indexes, caches, logs, and evaluation samples. Enforce tenant isolation, retrieval-time ACLs, write admission, and a deletion-propagation deadline with retries and completion evidence. Poisoning and weak access control can also expose or distort information.", ask: "Where is each document copied, how fast must revocation propagate, and how is completion proved?", tag: "RAG security", basis: "Vector and embedding risk", evidence: items([{ sourceId: "owasp-vector-weaknesses", supports: "Covers access-control, poisoning, cross-tenant, and information-disclosure risks in vector and embedding systems." }]) },
    { id: "prevent-agent-overreach", q: "How do we prevent an agent from exceeding authority or causing irreversible loss?", a: "Let the model propose an action, then authorize, validate, and execute it under the real identity. Choose automatic, confirmed, or prohibited execution according to consequence.", depth: "Authentication does not authorize every resource and action. Separate initiator, represented principal, permitted operation, and token audience. Automate low-risk reads, preview reversible writes, and retain human approval for money, production, deletion, or external communication.", ask: "Whose identity executes the call, who grants final authority, and how is a failed action reversed or compensated?", tag: "Agent security", basis: "Least privilege plus action control", evidence: items([{ sourceId: "nist-zero-trust", supports: "Requires identity and authorization to be verified and access scope to remain limited." }, { sourceId: "mcp-security", supports: "Documents confused-deputy, token, and permission risks in tool-connected systems." }]) },
    { id: "guardrail-red-team-retesting", q: "After deploying guardrails and passing one red team, can later security testing be reduced?", a: "No. A guardrail is one component and a red team is limited evidence for one version. Models, prompts, knowledge, tools, and attacks all change.", depth: "Test direct, retrieved, tool-returned, multimodal, and long-conversation input, plus high-impact actions and residual impact after a control fails. Version findings, false positives, bypasses, and uncovered areas; rerun material changes and promote adjudicated production risks into regression.", ask: "What changes trigger retesting, and what is the blast radius after the guardrail is bypassed?", tag: "Security validation", basis: "Continuous risk measurement", evidence: items([{ sourceId: "nist-genai-profile", supports: "Supports ongoing measurement, red teaming, and control-effectiveness review before and after deployment." }, { sourceId: "owasp-prompt-injection", supports: "Supports layered mitigation rather than relying on one detector or prompt." }, { sourceId: "owasp-llm-top-ten", supports: "Broadens test coverage beyond content filtering to multiple application-level risks." }]) },
    { id: "owasp-checklist-boundary", q: "Can the OWASP Top 10 for LLM Applications serve directly as the security acceptance checklist?", a: "Use it to reduce omissions, but not as a replacement for the system threat model and control tests.", depth: "The catalog covers common risks such as injection, sensitive information, supply chain, poisoning, output handling, excessive agency, and vector weaknesses. The project must still identify its assets, attackers, trust boundaries, data flows, high-impact actions, and acceptable residual risk.", ask: "What are the three losses this system cannot tolerate, and which actual path could trigger each one?", tag: "Risk inventory", basis: "Common catalog plus system threat model", evidence: items([{ sourceId: "owasp-llm-top-ten", supports: "Provides common generative-AI application risk categories for initial coverage checks." }, { sourceId: "nist-genai-profile", supports: "Requires risk to be identified and managed in the actual context of use." }]) },
    { id: "third-party-component-admission", q: "What should be checked before a third-party model, dataset, or plugin reaches production?", a: "At minimum, verify origin, version, license, format, dependencies, vulnerabilities, integrity, runtime permissions, and an exit path.", depth: "Weights and plugins may execute code or reach valuable resources; datasets can contain poisoning, privacy, and licensing risk. Load in isolation, prefer safe formats, retain hashes, signatures, model and data documentation, and deployment inventory, and prove that affected consumers can be found and rolled back.", ask: "Who approves external components, and can impact be located and reversed without the original supplier?", tag: "Supply chain", basis: "Component admission plus recoverable release", evidence: items([{ sourceId: "nist-genai-profile", supports: "Supports managing generative-AI model, data, and third-party supply-chain risks." }, { sourceId: "mcp-security", supports: "Supports provenance review, least privilege, and isolation for external tool servers." }]) },
    { id: "multi-jurisdiction-regulatory-review", q: "What regulatory questions should security teams confirm before launching in multiple countries?", a: "First identify user regions, industry, use, data types, distribution mode, and the product's role, then evaluate applicable requirements from current official text.", depth: "The same feature can carry different obligations as internal assistance, public content, or a high-impact service. China's synthetic-content labeling measures and mandatory national standard took effect on September 1, 2025; the EU AI Act follows a phased implementation. Record legal owners, unresolved questions, and review dates instead of a blanket compliance claim.", ask: "Who uses the service, where, whether content is distributed externally, and who approves the legal conclusion?", tag: "Regulatory applicability", basis: "Jurisdiction and use plus scheduled review", evidence: items([{ sourceId: "china-ai-content-labeling", supports: "Supports explicit and implicit labeling duties for synthetic content and the roles covered by the Chinese measures." }, { sourceId: "eu-ai-act", supports: "Supports the EU AI Act's risk-based requirements and phased implementation information." }]) },
    { id: "incident-first-response", q: "What is the first response to data exposure or an agent authorization incident?", a: "Stop propagation: isolate affected models or components, revoke credentials, pause queues and high-impact writes, and preserve evidence.", depth: "Then identify affected data, users, actions, and business state; perform required compensation and notification; validate recovery on a known-safe version. Disabling a model endpoint may not stop queued work, and restoring the interface does not repair completed actions.", ask: "Who can stop each component immediately, revoke credentials, handle queued work, and prove business-state recovery?", tag: "Incident response", basis: "Containment plus evidence and compensation", evidence: items([{ sourceId: "nist-genai-profile", supports: "Supports generative-AI incident management, response, and continuous improvement." }, { sourceId: "nist-zero-trust", supports: "Supports rapid revocation and renewed validation of subject and resource state." }]) },
    { id: "prompt-log-retention", q: "Should AI application logs retain complete prompts and responses?", a: "Not by default. Observability must be designed with privacy, confidentiality, retention, and minimization.", depth: "Begin with request IDs, versions, token use, latency, errors, tools, policy decisions, and evaluation results. Capture content only when lawful and necessary, with sampling, field-level redaction, encryption, access audit, and time-bound deletion. High-sensitivity uses can separate a controlled evaluation store from operating telemetry.", ask: "Which content is personal, commercial, or regulated; who may view it; how long is it kept; and how is deletion proved?", tag: "Logging governance", basis: "Observability plus data minimization", evidence: items([{ sourceId: "opentelemetry-genai-semconv", supports: "Provides generative-AI call attributes while leaving sensitive-content capture under implementation policy." }, { sourceId: "nist-genai-profile", supports: "Supports governing privacy, transparency, and lifecycle risks for generative-AI data." }]) },
  ]),
  evidenceCards: items([
    { id: "complete-system-security", metric: "Model + application + agent", title: "Security risk exists across the complete system", finding: "Model output, application data flow, and agent tool execution create distinct attack surfaces that require layered controls.", boundary: "Passing model safety tests does not establish that data, identities, tools, or the supply chain are secure.", sourceId: "nist-genai-profile", accent: true },
    { id: "indirect-prompt-injection", metric: "Direct + indirect", title: "External content can carry prompt injection", finding: "Websites, documents, email, retrieval, and tool results can introduce malicious instructions into model context.", boundary: "Detection reduces risk but cannot provide absolute prevention; executable authority must remain bounded.", sourceId: "owasp-prompt-injection" },
    { id: "embedding-governance", metric: "Vectorization ≠ anonymization", title: "Embeddings still require data governance", finding: "Vector systems can be poisoned, leak across tenants, retrieve without authorization, or enable sensitive-information inference.", boundary: "Encryption at rest does not replace retrieval-time ACLs, tenant isolation, and source governance.", sourceId: "owasp-vector-weaknesses" },
    { id: "four-control-gates", metric: "Input / action / output / monitoring", title: "Four control gates reduce single-point failure", finding: "Detection, identity, policy, DLP, approval, and audit can be placed at different stages of the path.", boundary: "The combination must be tested for the specific use and cannot promise removal of all generative-AI risk.", sourceId: "nist-genai-profile" },
    { id: "top-ten-threat-coverage", metric: "10 common risks", title: "A risk catalog helps prevent threat-model omissions", finding: "Injection, sensitive information, supply chain, poisoning, output handling, excessive agency, and vector weaknesses require cross-layer review.", boundary: "The catalog supplies common language, not the system's data flow, loss analysis, or control evidence.", sourceId: "owasp-llm-top-ten" },
    { id: "china-labeling-effective-date", metric: "2025-09-01", title: "Synthetic-content labeling requirements are in effect", finding: "China's relevant measures and mandatory national standard took effect on September 1, 2025, so content services need an applicability assessment.", boundary: "Applicability and implementation depend on product role, content, and distribution and require review of official text by qualified legal and security owners.", sourceId: "china-ai-content-labeling" },
  ]),
  terms: freeze({
    "prompt-injection": freeze({ name: "Prompt Injection", definition: "An attack in which untrusted input attempts to alter model instructions, disclose information, or trigger unauthorized action." }),
    "data-lineage": freeze({ name: "Data Lineage", definition: "A trace of data from its source through parsing, chunks, embeddings, indexes, caches, and evaluation assets." }),
    "deletion-propagation": freeze({ name: "Deletion Propagation", definition: "Applying deletion or revocation across derived data and caches with retries and completion evidence." }),
    "ai-risk-tiering": freeze({ name: "AI Risk Tiering", definition: "Assigning controls in proportion to a specific use's affected parties, autonomy, reversibility, scale, and consequence." }),
    security: freeze({ name: "AI Security", definition: "Controls that limit leakage, unauthorized action, and business harm across untrusted content, data, models, tools, and outputs." }),
    guardrails: freeze({ name: "Guardrails", definition: "Detection, constraints, or blocking around input, context, output, and action; they do not replace identity or business authorization." }),
    "identity-authorization": freeze({ name: "Identity & Authorization", definition: "Establishing the real principal and deciding whether it may access a resource or perform an action in the current context." }),
    iam: freeze({ name: "Identity and Access Management", abbr: "IAM", definition: "The systems and practices that manage who may access which resources under which identity and conditions." }),
    acl: freeze({ name: "Access Control List", abbr: "ACL", definition: "An explicit mapping of identities to permitted resources and operations." }),
    dlp: freeze({ name: "Data Loss Prevention", abbr: "DLP", definition: "Detection and control of sensitive data moving through input, output, logs, files, or other channels." }),
    hitl: freeze({ name: "Human in the Loop", abbr: "HITL", definition: "Accountable human approval, correction, or takeover at ambiguous, high-impact, or irreversible steps." }),
  }),
  sources: freeze({
    "owasp-prompt-injection": freeze({ kind: "Community security guide", shortTitle: "OWASP LLM01:2025 Prompt Injection", note: "Defines direct and indirect prompt injection and states that retrieval, fine-tuning, and system prompts cannot eliminate it alone. Community guidance must be mapped to the actual system threat model." }),
    "nist-zero-trust": freeze({ kind: "Official architecture publication", shortTitle: "NIST SP 800-207", note: "Defines zero-trust architecture around explicit subject and resource authentication and authorization rather than network-location trust. AI-specific control design remains the adopter's responsibility." }),
    "mcp-security": freeze({ kind: "Official protocol security guidance", shortTitle: "MCP Security Best Practices", note: "Documents security considerations for MCP deployments, including tokens, confused-deputy risks, and tool-server trust. Guidance evolves with the protocol and does not replace resource-side business authorization." }),
    "nist-genai-profile": freeze({ kind: "Official risk-management framework", shortTitle: "NIST AI 600-1", note: "Organizes generative-AI risk around Govern, Map, Measure, and Manage. It is voluntary guidance, not a product certification or a guarantee of security." }),
    "owasp-vector-weaknesses": freeze({ kind: "Community security guide", shortTitle: "OWASP LLM08:2025", note: "Covers vector and embedding risks including cross-context leakage, access control, isolation, provenance, and retrieval logging. It is a risk catalog rather than a complete data-governance program." }),
    "owasp-llm-top-ten": freeze({ kind: "Community security risk catalog", shortTitle: "OWASP Top 10 for LLM Applications 2025", note: "Provides common risk categories for generative-AI applications. It helps coverage but cannot substitute for system-specific threat modeling or control tests." }),
    "china-ai-content-labeling": freeze({ kind: "Official regulation", shortTitle: "China AI-Generated Content Labeling Measures", note: "The measures took effect September 1, 2025 and cover explicit and implicit labels and relevant service roles. Applicability requires current official-text and product-role review." }),
    "eu-ai-act": freeze({ kind: "Official regulation portal", shortTitle: "EU AI Act", note: "Provides the European Union's risk-based legal framework and implementation information. Duties and dates depend on role, system, use, and phased application and require qualified legal review." }),
    "opentelemetry-genai-semconv": freeze({ kind: "Open observability specification", shortTitle: "OTel GenAI SemConv", note: "Provides evolving generative-AI telemetry conventions. Pin the version, minimize sensitive content, and add business, policy, and incident fields required by the deployment." }),
    "nist-aml-100-2e2025": freeze({ kind: "Official adversarial machine-learning publication", shortTitle: "NIST AI 100-2e2025", note: "Provides a taxonomy and terminology for adversarial machine learning. It supports threat analysis but does not define universal acceptance thresholds for an application." }),
    "mcp-authorization": freeze({ kind: "Official protocol specification", shortTitle: "MCP Authorization", note: "Separates client, authorization-server, and resource-server responsibilities and uses resource-bound access tokens. Tool-internal business authorization and transaction controls remain necessary." }),
    "gb-45438-2025": freeze({ kind: "Mandatory national standard", shortTitle: "GB 45438-2025", note: "Specifies labeling requirements for AI-generated synthetic content in China and took effect September 1, 2025. Apply only after verifying scope, product role, and current official text." }),
  }),
});
