const freeze = Object.freeze;
const items = (values) => freeze(values.map((value) => freeze(value)));

export const englishModule = freeze({
  slug: "security",
  title: "AI Security",
  subtitle: "Keep a malicious resume from becoming authority over applicant data or the ATS",
  definition: "AI security uses threat modeling, trust boundaries, deterministic authorization, control assurance, and incident recovery to protect models, data, applications, agents, tools, and suppliers. Even when untrusted content influences a model, it must not expand authority, cross data boundaries, or directly change high-impact business state.",
  position: "Security owns attack paths, technical controls, adversarial assurance, containment, and forensics. AI Governance defines use gates, evidence, exceptions, and residual-risk decision rights; the authorized recruiting owner decides the use and any high-impact applicant state. Evaluation owns measurement evidence, and AI Ops owns release, stop, rollback, and recovery execution. The ATS enforces scoped permission and stores authoritative state; it does not accept business risk.",
  relatedSlugs: freeze(["rag", "ai-agent", "multimodal", "mcp", "a2a", "data-engineering", "ai-gateway", "evaluation", "ai-ops", "ai-governance"]),
  sections: items([
    {
      id: "security-study-guide",
      eyebrow: "LEARN, PRACTICE, PROVE",
      title: "Learn security by tracing one hostile document to a protected business state",
      lead: "The learner should be able to name the unacceptable loss, draw the source-to-sink path, identify the deterministic control at each boundary, and show how the organization contains and repairs an incident.",
      blocks: items([
        {
          type: "cards",
          title: "Learning outcomes",
          items: items([
            { id: "security-outcome-loss-path", title: "Threat-model from loss", body: "Protect applicant privacy, job boundaries, ATS integrity, hiring decisions, and accountability before selecting controls." },
            { id: "security-outcome-untrusted-resume", title: "Treat the resume as untrusted evidence", body: "Trace hidden instructions through parsing, retrieval, model context, tool arguments, and downstream actions." },
            { id: "security-outcome-ats-authority", title: "Keep ATS authority deterministic", body: "Bind execution to a real principal, approved fields, current resource state, business policy, and explicit approval." },
            { id: "security-outcome-recovery", title: "Prove containment and recovery", body: "Exercise credential revocation, queue stop, evidence preservation, state repair, and regression." },
          ]),
        },
        {
          type: "steps",
          title: "Recommended route",
          items: items([
            { id: "security-route-loss", title: "Define protected assets and unacceptable loss", body: "Identify who can control a resume, which data and decisions are valuable, and which business outcomes cannot be tolerated.", decision: "Checkpoint: every risk category maps to a concrete source, sink, and consequence." },
            { id: "security-route-boundaries", title: "Break the path into trust boundaries", body: "Separate file admission, parsing, retrieval, model proposal, policy enforcement, and ATS execution.", decision: "Checkpoint: untrusted content never inherits the authority of the component reading it." },
            { id: "security-route-control-test", title: "Test the controls, not only the detector", body: "Inject hidden text, cross-applicant retrieval, argument tampering, approval bypass, and unknown-result failures.", decision: "Checkpoint: another layer bounds impact when one control fails." },
            { id: "security-route-incident", title: "Exercise incident recovery", body: "Pause high-impact writes, revoke credentials, preserve evidence, query authoritative state, compensate, and validate recovery.", decision: "Checkpoint: the team can prove business-state repair, not merely endpoint availability." },
          ]),
        },
        {
          type: "cards",
          title: "Practice labs",
          items: items([
            { id: "security-lab-resume-to-ats", title: "Threat-model a malicious resume reaching the ATS", body: "Map resume, parser, retrieval, proposal, policy, and ATS paths; enumerate hidden injection, cross-applicant access, argument tampering, and approval bypass.", decision: "Deliverable: threat model, control map, and residual technical-risk register.", boundary: "Completion criterion: a hostile resume cannot obtain other applicants' data or directly change a high-impact ATS state.", sourceIds: freeze(["owasp-prompt-injection", "owasp-vector-weaknesses", "nist-zero-trust"]) },
            { id: "security-lab-vector-boundary", title: "Verify applicant-data isolation and deletion", body: "Have Data Engineering trace source files into chunks, embeddings, indexes, caches, logs, and evaluation assets; test positive and negative access by recruiter, requisition, and applicant.", decision: "Deliverable: derived-data inventory, authorization matrix, and negative-access evidence under customer-defined revocation and deletion SLOs.", boundary: "Completion criterion: every read path stops returning revoked material within the customer's promised interval. OWASP identifies vector risks but does not prescribe that interval.", sourceIds: freeze(["owasp-vector-weaknesses", "nist-zero-trust"]) },
            { id: "security-lab-unknown-result", title: "Exercise an ATS authorization incident", body: "Pause writes, revoke credentials, stop queues, reconstruct identity and policy evidence, query authoritative state, compensate, and create regression cases.", decision: "Deliverable: incident timeline, impact list, repair record, and recovery sign-off.", boundary: "Completion criterion: the team does not blindly retry and can prove which applicant states were restored or routed to human repair.", sourceIds: freeze(["nist-sp-800-61r3", "nist-genai-profile", "nist-zero-trust"]) },
            { id: "security-lab-content-delivery", title: "Review a high-risk content release", body: "A customer plans to publish an assistant that generates text and images, but ownership of labeling, review, takedown, and appeal is unclear. Design controls for generation, review, labeling, publication, takedown, correction, appeal, and incident response; keep technical generation, review approval, labeling and distribution, business authorization, and ongoing responsibility as separate states.", decision: "Deliverable: a content-delivery control matrix, evidence checklist, and open-issues log.", boundary: "Completion criterion: every release action has an accountable owner and evidence. Do not treat a label as proof of compliance.", sourceIds: freeze(["china-ai-content-labeling-2026-08-05", "gb-45438-2025", "nist-genai-profile"]) },
          ]),
        },
      ]),
    },
    {
      id: "security-curriculum",
      eyebrow: "COURSE MAP",
      title: "Build a defensible path from hostile content to recoverable execution",
      lead: "The course starts with business loss and trust boundaries, then adds data isolation, resource-side authorization, supplier admission, control testing, and incident recovery.",
      blocks: items([
        {
          type: "cards",
          items: items([
            { id: "security-chapter-threat-model", title: "Threat modeling from unacceptable loss", body: "Map applicant privacy, requisition scope, ATS integrity, hiring decisions, attackers, trust boundaries, and reachable sinks.", decision: "Organize the threat model around loss and authority.", boundary: "The OWASP catalog prevents omissions; it is not a system acceptance test.", sourceIds: freeze(["owasp-llm-top-ten", "nist-genai-profile"]) },
            { id: "security-chapter-malicious-resume", title: "Malicious resumes and indirect injection", body: "PDF text, hidden content, images, OCR, and parser output can carry instructions into model context.", decision: "Isolate parsing, preserve provenance, and constrain every reachable sink.", boundary: "Prompts, delimiters, retrieval, fine-tuning, and detection cannot independently eliminate injection.", sourceIds: freeze(["owasp-prompt-injection"]) },
            { id: "security-chapter-candidate-data", title: "Applicant data, vectors, and deletion", body: "Source files, chunks, embeddings, indexes, caches, logs, and evaluation samples remain sensitive. Data Engineering implements copy inventory and revocation or deletion propagation; Security tests access by recruiter, requisition, applicant, and purpose.", decision: "Use customer-defined SLOs and negative probes to verify admission, retrieval-time ACLs, isolation, and revocation.", boundary: "OWASP supports vector-access, poisoning, and disclosure risk; it does not prescribe a universal deletion SLA. An embedding is not anonymized data.", sourceIds: freeze(["owasp-vector-weaknesses", "nist-zero-trust"]) },
            { id: "security-chapter-proposal-authorization", title: "Model proposal versus ATS authorization", body: "The model may propose an applicant, job, allowed field, evidence, and uncertainty; the application authorizes under the real principal, current resource state, and business rule.", decision: "Automate drafts; retain business authorization for high-impact state changes.", boundary: "Tool calling, MCP, valid JSON, or a shared service account is not ATS authorization.", sourceIds: freeze(["nist-zero-trust", "mcp-authorization"]) },
            { id: "security-chapter-execution", title: "Least privilege and authoritative end state", body: "Use short-lived scoped credentials, allowed fields, current versions, idempotency, and post-execution reads. Query state before retrying an unknown result.", decision: "Record initiator, on-behalf-of identity, policy basis, arguments, result, and compensation.", boundary: "A successful API response does not prove a correct applicant state.", sourceIds: freeze(["nist-zero-trust", "mcp-security"]) },
            { id: "security-chapter-supply-chain", title: "Supplier and component admission", body: "Parsers, models, datasets, plugins, connectors, and hosted APIs need origin, version, license, vulnerability, integrity, permission, inventory, and replacement evidence.", decision: "Test in isolation and bind the approved version to the release.", boundary: "Managed hosting, open weights, or a supplier certificate does not prove the customer's integration is secure; MCP guidance applies only when that protocol is used.", sourceIds: freeze(["nist-genai-profile", "nist-sp-800-218a"]) },
            { id: "security-chapter-control-assurance", title: "Control assurance and adversarial testing", body: "Test ordinary and hostile resumes, hidden text, cross-applicant retrieval, argument tampering, approval bypass, supplier change, and residual impact after a failed control.", decision: "Measure whether each layer bounds consequence and promote adjudicated incidents into regression.", boundary: "A guardrail hit rate or one red-team pass cannot establish absence of unknown attacks.", sourceIds: freeze(["nist-aml-100-2e2025", "owasp-prompt-injection", "nist-genai-profile"]) },
            { id: "security-chapter-incident-response", title: "Incident evidence, containment, and recovery", body: "Pause high-impact writes, revoke credentials, stop queues, preserve source and context evidence, verify ATS state, compensate, and sign off recovery.", decision: "Preassign stop authority, evidence fields, repair ownership, and recovery tests.", boundary: "NIST provides a response discipline, not universal AI alert thresholds or recovery times.", sourceIds: freeze(["nist-sp-800-61r3", "nist-genai-profile", "nist-zero-trust"]) },
            { id: "security-chapter-content-labeling", title: "Content labeling and scope boundary", body: "China's Measures for the Labeling of AI-Generated and Synthetic Content and GB 45438-2025 are in force. Treat explicit labels, metadata-based implicit labels, distribution roles, and scope conditions as items to verify in engineering design.", decision: "Have Engineering, Content, Security, and Legal confirm the service role, output type, and distribution channel before designing labels, logs, and takedown.", boundary: "The Measures and national standard define an obligation framework; they do not determine whether a particular system falls within the relevant entity, territorial, content-classification, or other legal scope.", sourceIds: freeze(["china-ai-content-labeling-2026-08-05", "gb-45438-2025", "nist-genai-profile"]) },
          ]),
        },
      ]),
    },
    {
      id: "threat-path",
      eyebrow: "MALICIOUS RESUME TO ATS",
      title: "Allow the model to inspect a resume without letting the resume acquire authority",
      lead: "The security objective is not to prove that a model can never be influenced. It is to prove that influenced model output remains a bounded proposal until deterministic controls authorize a permitted business action.",
      blocks: items([
        {
          type: "steps",
          title: "Five control points",
          items: items([
            { id: "security-path-loss", title: "Define assets and unacceptable loss", body: "Identify applicant records, recruiting policy, requisition scope, ATS integrity, decision authority, and the consequences of disclosure or unauthorized state change.", decision: "A generic risk label is not a threat model." },
            { id: "security-path-admission", title: "Admit the resume as untrusted evidence", body: "Parse in isolation and retain source file, page, version, integrity, and trust labels across hidden text, images, and extracted content.", decision: "Authentication of the uploader does not make the content trusted." },
            { id: "security-path-retrieval", title: "Retrieve under the current identity", body: "Enforce recruiter, job, applicant, region, and purpose constraints in retrieval, cache keys, and deletion propagation.", decision: "Relevance and similarity do not establish authorization." },
            { id: "security-path-proposal", title: "Produce an evidence-bound proposal", body: "Restrict output to allowed applicant and job identifiers, permitted fields, citations, uncertainty, and escalation; keep ATS credentials outside model context.", decision: "Fluent rationale and valid structure do not grant execution authority." },
            { id: "security-path-authorize", title: "Authorize, execute, verify, and recover", body: "Check the real principal, requisition scope, allowed fields, resource version, and approval; then read authoritative ATS state and record compensation.", decision: "The ATS enforces scoped permission and stores state; the authorized recruiting owner approves any high-impact applicant decision." },
          ]),
        },
        {
          type: "boundary",
          title: "Critical boundary",
          items: items([
            { id: "security-owner-boundary", title: "Security limits attack paths; it does not approve the use", body: "Security proves that technical controls bound authority and that incidents can be contained and reconstructed.", boundary: "Governance owns use conditions and residual-risk acceptance, Evaluation owns measurement, AI Ops owns release and recovery execution, and qualified professionals own legal applicability." },
          ]),
        },
      ]),
    },
    {
      id: "security-decisions",
      eyebrow: "PRESALES DECISIONS",
      title: "Choose controls from reachable authority and consequence",
      lead: "Each decision starts with what an attacker can influence, what data or action becomes reachable, and which deterministic boundary changes the outcome.",
      blocks: items([
        {
          type: "table",
          title: "Five decisions that change the recruitment architecture",
          columns: freeze(["Customer signal", "Recommended action", "Boundary"]),
          items: items([
            { id: "security-decision-loss", title: "What must not be lost?", cells: freeze(["The system reads applicant material, recruiting policy, other applicant records, or ATS fields.", "Name protected assets, unacceptable business outcomes, attacker-controlled sources, and reachable sinks.", "A common risk catalog cannot choose the customer's loss tolerance."]) },
            { id: "security-decision-injection", title: "How far can a hostile resume reach?", cells: freeze(["Resume text flows through parsing, retrieval, model context, arguments, and ATS actions.", "Label and isolate untrusted content; independently authorize every sensitive read and write.", "A stronger system prompt or one detector cannot establish an authority boundary."]) },
            { id: "security-decision-data", title: "How is cross-applicant access prevented?", cells: freeze(["Vectors, caches, and indexes mix jobs, regions, or applicants while permissions change over time.", "Enforce admission, recruiter/job/applicant ACLs, isolated cache keys, and tested revocation and deletion.", "Vectorization, ranking scores, and encryption at rest do not replace access control."]) },
            { id: "security-decision-ats", title: "Which ATS actions may run automatically?", cells: freeze(["The output ranges from a recruiter draft to ranking publication, rejection, status change, or external communication.", "Grade actions by consequence and bind execution to the real principal, allowed fields, current state, and approval.", "Valid JSON, a callable tool, or a service credential is not business authorization."]) },
            { id: "security-decision-recovery", title: "Can the team contain and repair a failed control?", cells: freeze(["Models, parsers, prompts, indexes, permissions, and connectors change after a guardrail or red-team pass.", "Inject control failures and verify stop authority, evidence, queue handling, compensation, and recovery thresholds.", "A restored endpoint or revised prompt does not prove repaired applicant state."]) },
          ]),
        },
      ]),
    },
    {
      id: "security-deep-dive",
      eyebrow: "INCIDENT DIAGNOSIS",
      title: "Reconstruct a recruitment-agent incident from source to business state",
      lead: "Contain high-impact ATS writes first. Then reconstruct the resume source, parser output, retrieved material, model and prompt versions, represented identity, policy result, tool arguments, ATS state, and compensation.",
      blocks: items([
        {
          type: "table",
          title: "Five symptoms, five failed boundaries",
          columns: freeze(["Likely failure", "Containment and recovery", "Do not assume"]),
          items: items([
            { id: "security-incident-cross-applicant", title: "A recruiter sees another job's applicant data", cells: freeze(["Retrieval ACLs, tenant or job mapping, cache keys, or deletion propagation failed.", "Disable affected index and cache paths; reconstruct identity, filters, source versions, and ACLs; run negative tests.", "Deleting the response proves nothing about chunks, embeddings, caches, logs, or evaluation copies."]), sourceIds: freeze(["owasp-vector-weaknesses", "nist-zero-trust"]) },
            { id: "security-incident-ats-action", title: "The agent changes an unauthorized applicant state", cells: freeze(["Injection, bad tool selection, unvalidated arguments, excessive credentials, or approval bypass reached the ATS.", "Pause writes, revoke credentials, inspect policy and ATS audit, query authoritative state, and compensate.", "Editing the prompt cannot repair excessive authority or a completed business action."]), sourceIds: freeze(["owasp-prompt-injection", "nist-zero-trust", "nist-sp-800-61r3"]) },
            { id: "security-incident-poisoning", title: "Hostile resumes consistently influence screening", cells: freeze(["A trusted write path was poisoned, provenance changed, or ranking repeatedly elevated attacker-controlled content.", "Freeze ingestion, quarantine the batch, verify lineage and digests, rebuild a clean index, and rerun attack cases.", "A high reranker score does not establish truth or trust."]), sourceIds: freeze(["owasp-vector-weaknesses", "nist-genai-profile"]) },
            { id: "security-incident-supplier", title: "A parser, model, or connector changes behavior", cells: freeze(["An unapproved version, dependency, description, or supplier policy bypassed the evaluated scope.", "Return to an approved version; verify inventory, digests, release evidence, and affected recruiting workflows.", "Availability does not mean behavior and data terms remain approved."]), sourceIds: freeze(["nist-genai-profile", "nist-sp-800-218a"]) },
            { id: "security-incident-missing-signal", title: "Detection looks normal while wrongful exclusion occurs", cells: freeze(["The detector covers known content patterns while the failed boundary is authorization, data access, business workflow, or missing telemetry.", "Security reconstructs the technical path and evidence; HR, Governance, and Legal own impact, appeal, remedy, and notification decisions.", "No alert is not evidence of no harm; missing evidence is itself a control gap."]), sourceIds: freeze(["nist-sp-800-61r3", "nist-genai-profile"]) },
          ]),
        },
      ]),
    },
    {
      id: "security-cloud",
      eyebrow: "CLOUD CONNECTIONS",
      title: "Map each control point to an accountable platform capability",
      lead: "Cloud products provide enforcement and evidence only when they are bound to the recruiting threat model, real identity, approved data boundary, and incident owner.",
      blocks: items([
        {
          type: "cards",
          items: items([
            { id: "security-cloud-identity", title: "Identity and credentials", body: "IAM, OIDC, workload identity, secret management, and privileged access provide short-lived, scoped, revocable authority.", decision: "Ask which principal reaches the ATS and which applicant, job, field, and duration the credential permits.", boundary: "A platform identity does not define recruiting authorization.", sourceIds: freeze(["nist-zero-trust"]) },
            { id: "security-cloud-data", title: "Data and retrieval protection", body: "Classification, DLP, encryption, access control, vector storage, and audit protect applicant source and derived data.", decision: "Ask where every copy lives and how recruiter/job/applicant revocation reaches it.", boundary: "Storage encryption cannot replace retrieval-time authorization.", sourceIds: freeze(["owasp-vector-weaknesses", "nist-zero-trust"]) },
            { id: "security-cloud-runtime", title: "Isolation and action enforcement", body: "Sandboxes, private networking, API gateways, policy engines, schema validation, and approval workflows limit content and tool reach.", decision: "Ask which ATS actions are read-only, reversible, or high impact and where each is denied or approved.", boundary: "A gateway or guardrail does not own downstream business permission.", sourceIds: freeze(["owasp-prompt-injection", "mcp-security"]) },
            { id: "security-cloud-response", title: "Security operations and recovery", body: "Tracing, SIEM, detection, asset inventory, ticketing, and response automation correlate source, identity, policy, action, business state, and repair.", decision: "Ask who can pause writes, revoke authority, locate affected applicants, and sign off recovery.", boundary: "Telemetry volume is not assurance unless evidence is privacy-aware and tied to a response.", sourceIds: freeze(["nist-sp-800-61r3", "nist-genai-profile"]) },
          ]),
        },
      ]),
    },
  ]),
  qa: items([
    { id: "aligned-model-application-security", q: "If the model has been safety-aligned, what security work remains in an AI-assisted recruiting system?", a: "Both conventional and AI-specific security remain necessary. Alignment can influence generated behavior; it does not implement applicant-data isolation, ATS authorization, tool approval, or incident recovery.", depth: "The application team owns resume provenance, recruiter/requisition/applicant permissions, policy retrieval, ATS credentials, allowed fields, human authorization, and authoritative-state integration. The goal is not to promise that the model never follows a malicious resume; it is to prevent that influence from expanding authority or directly rejecting an applicant.", ask: "How far can a hostile resume reach, and which real applicant state could the worst failure change?", tag: "Shared responsibility", basis: "Generative-AI risk management plus zero trust", evidence: items([{ sourceId: "nist-genai-profile", supports: "Supports lifecycle management of system-level generative-AI risk." }, { sourceId: "nist-zero-trust", supports: "Requires explicit identity and authorization before access to a resource." }]) },
    { id: "system-prompt-injection-defense", q: "Can a stronger system prompt neutralize malicious instructions hidden in a resume?", a: "It cannot guarantee security. The resume remains untrusted data, and model influence must be prevented from becoming data access or ATS authority.", depth: "OWASP explicitly describes indirect injection in resume screening. Preserve provenance, isolate parsing, minimize context, and detect suspicious content, but place the decisive controls at cross-applicant reads, argument validation, and high-impact ATS writes. Those controls must evaluate the real principal and current business policy.", ask: "Which trust boundaries does a resume cross before it can influence retrieval, model output, or an ATS action?", tag: "Prompt injection", basis: "OWASP threat definition plus external enforcement", evidence: items([{ sourceId: "owasp-prompt-injection", supports: "Documents direct and indirect injection, including a malicious-resume scenario, and the limits of model-only defenses." }]) },
    { id: "embedding-vector-data-risk", q: "Does placing applicant material in a vector database reduce its security risk?", a: "Do not assume so. Vectorization is not anonymization; embeddings, metadata, source files, and retrieval results may remain sensitive.", depth: "A resume can create chunks, embeddings, indexes, caches, logs, and evaluation samples. Bind access to recruiter, requisition, applicant, and purpose, with write admission and retrieval-time ACLs. Data Engineering owns copy inventory and revocation or deletion propagation; Security requires customer-defined deadlines, failure handling, and negative-access probes as acceptance evidence. OWASP supports vector-access, poisoning, and disclosure risk, not a universal deletion SLA.", ask: "Where is a resume copied, who can read it across requisitions, and how is revocation or deletion proved against the customer's SLO?", tag: "RAG security", basis: "Vector risk plus system-defined lifecycle control", evidence: items([{ sourceId: "owasp-vector-weaknesses", supports: "Covers access control, isolation, poisoning, provenance, and disclosure risks in vector systems; it does not define deletion deadlines." }]) },
    { id: "prevent-agent-overreach", q: "How do we prevent a recruiting agent from changing an unauthorized ATS field or rejecting an applicant?", a: "Keep the model at the proposal layer, then authorize, validate, and execute under the real principal and current business rule.", depth: "A signed-in recruiter is not automatically authorized for every requisition, applicant, or ATS field. Distinguish the initiator, on-behalf-of identity, requisition scope, allowed fields, credential audience, resource version, and approval. Drafts may be automated; ranking publication, rejection, status changes, and external communication should require an authorized recruiting decision. The ATS enforces the permitted transaction and stores authoritative state; it does not accept the business consequence.", ask: "Whose identity performs the call, which fields may change, which recruiting owner authorizes applicant state, and how is failure compensated?", tag: "Agent security", basis: "Least privilege plus action control", evidence: items([{ sourceId: "nist-zero-trust", supports: "Requires explicit authorization and limited resource access." }, { sourceId: "mcp-security", supports: "Documents token, confused-deputy, and tool-server trust risks; the protocol does not replace business authorization." }]) },
    { id: "guardrail-red-team-retesting", q: "After guardrails and one successful red team, can later recruitment-security testing be reduced?", a: "No. A guardrail is one control, and a red team is limited evidence for one version of the complete system.", depth: "Test ordinary and hostile resumes, hidden text, cross-applicant retrieval, ATS argument tampering, approval bypass, unknown results, and supplier changes. A material model, parser, prompt, index, permission, or connector change should trigger reruns. Measure whether a second layer bounds harm after the first control fails, and promote adjudicated incidents into regression.", ask: "Which changes trigger retesting, and what ATS effect remains possible after the guardrail is bypassed?", tag: "Security validation", basis: "Continuous control assurance", evidence: items([{ sourceId: "nist-genai-profile", supports: "Supports recurring measurement, red teaming, and control review." }, { sourceId: "owasp-prompt-injection", supports: "Supports layered mitigation rather than one prompt or detector." }, { sourceId: "owasp-llm-top-ten", supports: "Broadens coverage beyond content filtering to system risks." }]) },
    { id: "owasp-checklist-boundary", q: "Can the OWASP Top 10 for LLM Applications serve as the recruitment system's acceptance checklist?", a: "Use it to reduce omissions, but not as a substitute for the system threat model and control tests.", depth: "The catalog covers common risks such as injection, sensitive information, suppliers, poisoning, output handling, excessive agency, and vector weaknesses. The recruitment project must still name protected applicant and ATS assets, attacker-controlled resumes, trust boundaries, high-impact sinks, and acceptable residual technical risk.", ask: "What are the three losses this recruitment system cannot tolerate, and which source-to-sink path could cause each?", tag: "Risk inventory", basis: "Risk catalog plus system threat model", evidence: items([{ sourceId: "owasp-llm-top-ten", supports: "Provides common generative-AI application risk categories for coverage." }, { sourceId: "nist-genai-profile", supports: "Requires risk management in the actual context of use." }]) },
    { id: "third-party-component-admission", q: "What should be checked before a parser, model, dataset, or ATS connector reaches production?", a: "Verify origin, version, license, format, dependencies, vulnerabilities, integrity, runtime permissions, affected workflows, and an exit path.", depth: "AI-assisted recruiting components may execute code, process applicant records, or connect to high-value systems. Load in isolation, prefer safe formats, retain digests, signatures, model and data documentation, permission evidence, and deployment inventory, and prove that affected requisitions and applicants can be located and rolled back.", ask: "Who approves the component, and can affected recruiting workflows be found and recovered without the original supplier?", tag: "Supply chain", basis: "Component admission plus recoverable release", evidence: items([{ sourceId: "nist-genai-profile", supports: "Supports management of model, data, and third-party supply-chain risk." }, { sourceId: "nist-sp-800-218a", supports: "Adds secure-development and acquisition practices for AI model producers, AI system producers, and acquirers across the software lifecycle." }]) },
    { id: "incident-first-response", q: "What is the first response to applicant-data exposure or unauthorized ATS action?", a: "Stop propagation: pause high-impact ATS writes, isolate affected components, revoke credentials, stop queues, and preserve evidence.", depth: "Then identify affected applicants, requisitions, data, actions, and ATS state; perform compensation and human repair; and give HR, Governance, and Legal the technical facts and impact evidence needed to decide appeal, remedy, and notification duties. Validate recovery on a known-safe version. Disabling a model endpoint may not stop queued work, and restoring an interface does not repair wrongful exclusion or completed field changes.", ask: "Who can pause each ATS action, handle unknown-result requests, and prove applicant-state recovery?", tag: "Incident response", basis: "Containment, evidence, and compensation", evidence: items([{ sourceId: "nist-sp-800-61r3", supports: "Integrates preparation, detection, response, recovery, and improvement into cybersecurity risk management." }, { sourceId: "nist-genai-profile", supports: "Supports generative-AI incident management and continuous improvement." }]) },
    { id: "content-labeling-log-controls", q: "What technical controls correspond to content-labeling and log-retention requirements?", a: "They can become testable controls, but that mapping does not establish legal compliance.", depth: "Under the Measures, explicit labels map to prominent notices in generation and publishing flows; implicit labels map to file-metadata writes; platform duties map to metadata verification, notice logic, and identification of suspected synthetic content. In the specific Article 9 scenario in which a user requests content without an explicit label, the provider may supply it only after the user agreement clearly specifies the user's labeling duties and responsibility for use, and must retain recipient information and related logs for at least six months in accordance with law. Implement label generation, metadata verification, retention, integrity protection, and searchability. Bind each control to its trigger, evidence, and accountable owner; qualified reviewers decide whether the entity and scenario are in scope.", ask: "Who generates and verifies labels, how long must records be retained, and how are deletion or tampering detected?", tag: "Regulatory controls", basis: "Content Labeling Measures plus engineering control mapping", evidence: items([{ sourceId: "china-ai-content-labeling-2026-08-05", supports: "Articles 4–6 define explicit and metadata-based labels and platform duties; Article 9 specifies the defined no-explicit-label scenario and six-month log-retention requirement." }]), addedAt: "2026-08-05" },
    { id: "multimodal-content-incident-forensics", q: "How should a team investigate and limit harm when multimodal content is altered, misattributed, or published improperly?", a: "Use an incident evidence chain: preserve the source asset, generated and reviewed versions, labels, publication records, and takedown actions. Stop distribution and withdraw the content first; then verify versions and hashes, trace the alteration path, assess impact, and recover.", depth: "The publisher must be able to show which version was released, when, by whom, and whether labeling was completed. Fingerprints, hashes, and Content Credentials can support provenance and integrity checks. C2PA verification covers recorded assertions and asset integrity; it does not independently establish the truth of assertions, a signer's real-world identity or authority, ownership or copyright, legal sufficiency, or deletion of all replicas. Removing the final file does not prove that copies, caches, or distribution channels are clear; qualified professionals determine forensic and accountability conclusions.", ask: "Which version was released, who approved it, which copies and caches exist, and how is removal verified after takedown?", tag: "Incident forensics", basis: "Incident response plus Content Credentials", evidence: items([{ sourceId: "nist-sp-800-61r3", supports: "Provides an incident-response discipline within cybersecurity risk management; it does not define AI-specific forensic or recovery criteria." }, { sourceId: "c2pa-2-4", supports: "Supports verification of recorded assertions and their binding to an asset when a valid manifest is present; it does not independently establish the truth of assertions, a signer's real-world identity or authority, ownership or copyright, legal sufficiency, or deletion of all replicas." }]), addedAt: "2026-08-05" },
    { id: "claims-material-indirect-injection", q: "Can scanned claim documents and images carry an attack?", a: "Yes. Text and tables in PDFs and images can carry indirect prompt injection, which can gain reach through parsing, retrieval, and tool calls.", depth: "Treat claim material as untrusted content: parse it in isolation, retain provenance and trust labels, and minimize context. Enforce case- and role-based ACLs on retrieval; execute tool calls with a real identity and deterministic authorization. AI may produce evidence-bound recommendations, but untrusted content must not grant the system cross-customer read access or authority to write claim-payment state.", ask: "Which parsing, retrieval, and tool paths can the material reach, and what business state could the worst case affect?", tag: "Sector security", basis: "Prompt injection plus least privilege", evidence: items([{ sourceId: "owasp-prompt-injection", supports: "Describes direct and indirect prompt injection and the need for layered mitigation beyond model-only controls." }, { sourceId: "nist-zero-trust", supports: "Supports resource access decisions based on explicit identity and authorization." }]), addedAt: "2026-08-05" },
  ]),
  evidenceCards: items([
    { id: "complete-system-security", metric: "Model + application + agent", title: "Security belongs to the complete system", finding: "Resume ingestion, applicant-data retrieval, model proposals, ATS execution, and supplier change create distinct attack surfaces.", boundary: "A model safety test cannot establish secure identities, data boundaries, tools, or recovery.", sourceId: "nist-genai-profile", accent: true },
    { id: "malicious-resume-injection", metric: "Direct + indirect", title: "A resume can carry indirect prompt injection", finding: "OWASP explicitly describes hidden malicious instructions in a resume influencing screening behavior.", boundary: "Detection reduces risk; the resume still must not obtain cross-applicant access or ATS authority.", sourceId: "owasp-prompt-injection" },
    { id: "embedding-governance", metric: "Vectorization is not anonymization", title: "Applicant embeddings still need authorization", finding: "Vector systems can be poisoned, leak across contexts, retrieve without authorization, or expose sensitive information.", boundary: "Encryption at rest cannot replace recruiter/job/applicant ACLs, isolation, and provenance.", sourceId: "owasp-vector-weaknesses" },
    { id: "layered-control-assurance", metric: "Input / data / action / recovery", title: "Layered controls bound a failed detector", finding: "Admission, retrieval authorization, proposal validation, ATS policy, business approval, and recovery operate at different boundaries.", boundary: "The combination must be tested for the recruitment use and cannot promise zero risk.", sourceId: "nist-genai-profile" },
    { id: "catalog-coverage", metric: "10 common risks", title: "A catalog prevents threat-model omissions", finding: "Injection, sensitive information, suppliers, poisoning, output handling, excessive agency, and vector weaknesses require cross-layer review.", boundary: "The catalog does not provide the system's loss analysis, data flow, or control evidence.", sourceId: "owasp-llm-top-ten" },
    { id: "incident-risk-management", metric: "Prepare / detect / respond / recover", title: "Incident response is part of risk management", finding: "NIST SP 800-61 Rev. 3 integrates incident response with CSF 2.0 risk management and continuous improvement.", boundary: "It does not prescribe universal AI alert thresholds, forensic fields, or recovery times.", sourceId: "nist-sp-800-61r3" },
    { id: "content-labeling-controls", metric: "Label + metadata + logs", title: "Labeling duties become testable controls", finding: "The Measures connect explicit labels, metadata-based implicit labels, distribution-platform verification and notice, and specified log retention into a testable chain: generate, write, verify, display, and retain evidence.", boundary: "A control's presence does not prove that every legal duty is met; qualified reviewers must determine whether the entity and scenario are in scope.", sourceId: "china-ai-content-labeling-2026-08-05" },
  ]),
  terms: freeze({
    security: freeze({ name: "AI Security", definition: "Technical controls and response practices that constrain leakage, unauthorized action, and business harm across untrusted content, data, models, tools, and suppliers." }),
    guardrails: freeze({ name: "Guardrails", definition: "Detection, constraints, or blocking around input, context, output, and action; guardrails do not replace identity, authorization, or recovery." }),
    "identity-authorization": freeze({ name: "Identity & Authorization", definition: "Establishing the real principal and determining whether it may access a resource or perform an action in the current context." }),
    iam: freeze({ name: "Identity and Access Management", abbr: "IAM", definition: "Managing which identities may access which resources and operations, with authorization and audit kept outside model discretion." }),
    "prompt-injection": freeze({ name: "Prompt Injection", definition: "An attack in which untrusted input attempts to alter model behavior, disclose information, or trigger unauthorized action." }),
    acl: freeze({ name: "Access Control List", abbr: "ACL", definition: "An explicit mapping of identities to permitted resources and operations." }),
    dlp: freeze({ name: "Data Loss Prevention", abbr: "DLP", definition: "Detection and control of sensitive data moving through files, input, output, logs, or other channels." }),
  }),
  sources: freeze({
    "nist-genai-profile": freeze({ kind: "Official risk-management framework", shortTitle: "NIST AI 600-1", note: "Organizes generative-AI risk around Govern, Map, Measure, and Manage. It is voluntary guidance, not a security certification or a universal control threshold." }),
    "nist-zero-trust": freeze({ kind: "Official architecture publication", shortTitle: "NIST SP 800-207", note: "Defines explicit subject and resource authentication and authorization rather than implicit trust. Recruitment-specific policy and ATS controls remain the adopter's responsibility." }),
    "nist-sp-800-61r3": freeze({ kind: "Official incident-response guidance", shortTitle: "NIST SP 800-61 Rev. 3", note: "Integrates incident response with CSF 2.0 risk management across preparation, detection, response, recovery, and improvement. It is not an AI-specific alert or recovery specification." }),
    "nist-sp-800-218a": freeze({ kind: "Official secure-development guidance", shortTitle: "NIST SP 800-218A", note: "Adds secure-development and acquisition practices for AI model producers, AI system producers, and acquirers. It does not prove that a particular parser, model, dataset, or connector has passed customer admission." }),
    "nist-aml-100-2e2025": freeze({ kind: "Official adversarial-machine-learning publication", shortTitle: "NIST AI 100-2e2025", note: "Provides an adversarial-machine-learning taxonomy. It supports threat analysis but does not define universal application acceptance thresholds." }),
    "owasp-prompt-injection": freeze({ kind: "Community security guide", shortTitle: "OWASP LLM01:2025 Prompt Injection", note: "Defines direct and indirect injection, includes a malicious-resume example, and explains why model-only controls cannot eliminate the risk." }),
    "owasp-vector-weaknesses": freeze({ kind: "Community security guide", shortTitle: "OWASP LLM08:2025", note: "Covers vector-system access control, isolation, poisoning, provenance, and disclosure risks. It is a risk guide rather than a complete data-governance program." }),
    "owasp-llm-top-ten": freeze({ kind: "Community security risk catalog", shortTitle: "OWASP Top 10 for LLM Applications 2025", note: "Provides common generative-AI application risk categories. It supports coverage but does not replace system-specific loss analysis and control tests." }),
    "mcp-security": freeze({ kind: "Official protocol security guidance", shortTitle: "MCP Security Best Practices", note: "The 2026-07-28 guidance documents MCP-specific token, confused-deputy, local-server, and tool-server risks. It does not establish general AI supply-chain admission or ATS business authorization." }),
    "mcp-authorization": freeze({ kind: "Official protocol specification", shortTitle: "MCP Authorization", note: "The 2026-07-28 specification defines an optional HTTP-transport authorization flow with client, authorization-server, resource-server, issuer, resource, scope, and step-up boundaries. Tool-internal business permission remains necessary." }),
    "china-ai-content-labeling-2026-08-05": freeze({ kind: "Official regulatory instrument", shortTitle: "China AI Content Labeling Measures", note: "Sets China-specific requirements for explicit and metadata-based implicit labels, and duties for relevant service and dissemination roles. In the defined Article 9 scenario where a user requests content without an explicit label, it also requires specified agreement terms and retention of relevant recipient information and logs for at least six months in accordance with law. Applicability depends on the entity, service role, content, distribution path, and scenario and requires qualified review." }),
    "gb-45438-2025": freeze({ kind: "Mandatory Chinese national standard", shortTitle: "GB 45438-2025", note: "Specifies methods for labeling AI-generated or synthetic content in China. Engineering applicability still depends on the formal text, product role, content, and distribution path." }),
    "c2pa-2-4": freeze({ kind: "Open technical standard", shortTitle: "C2PA 2.4", note: "Defines signed provenance manifests, asset bindings, provenance assertions, and validation status. A validation result concerns the recorded assertions and the integrity of their binding to an asset in the applicable validation context; it does not independently establish that content is true, a signer's real-world identity or authority is correct, rights or ownership are held, consent exists, legal requirements are met, publication is authorized, or all copies have been deleted. A manifest can be removed." }),
  }),
});
